### ISSUE TITLE
VSCode extension no with-deps checkbox available on angular build tasks

### ISSUE THREAD

**Issue by va4ok** [nrwl/nx-console#1004]
**Steps to reproduce:**
Install or update VSCode extension version 16 on windows os.
Generate angular workspace
Generate angular library
Import library method into generated app
Open Nx Console - Build - <generated_app_name>
Navigate to section With-deps
**Expected result:**
Checkbox and description appear
**Actual result**
Only section names available

Extension version: 16.0.0+

VSCode info:
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.15063

PS workaround is console command npx nx build --with-deps

**Comment by labeled** [comment]
I believe we are also experiencing this issue at our organization. See the image, no boxes to check in the UI for nx console commands.
![image](https://user-images.githubusercontent.com/17855377/106649786-aa615e00-6557-11eb-85e7-c07375900265.png)
