### ISSUE TITLE
Split nxConsole.revealWebViewPanel into two commands

### ISSUE THREAD

**Issue by srleecode** [nrwl/nx-console#1005]
I believe nxConsole.revealWebViewPanel should be split into two commands because:

- Schematics by default have no awareness of context which means you have often have to fill in the same values when using the same schematic multiple times. If nxConsole allowed opening the webViewPanel, e.g. schematic runner, directly as well as some method to transform the schema, then other plugins can look at the context to prefill schematic values and set them as the default in the schema. See https://github.com/srlee309/vscode-domain-schematics-extension for some examples that do this prefilling.
- To generate the quick pick list of what can be called it reads the schematics information and normalizes the schema. It would be more performant if this schema normalization only happened when you have selected a schematic to open.

Do you think something like this would work:

The first command shows the window quick pick, but with simplified tree items. For example:
```
{
  description: "Create an app shell.",
  label: "@schematics/angular - app-shell",
  collectionName: "@schematics/angular",
}
```

Once a selection has been made a second command is run that reads the schematic, normalizes the schema, does some transformation based on options passed in the command and opens the webViewPanel as it currently does.

Other extensions can call this second command to open the schematic runner directly.

**Comment by MaxKless** [comment]
Hey! We're looking to drop Angular CLI support in the not-too-far future, so I'm closing this issue. 
Unlike for angular schematics, I think that there aren't really any other Nx VSCode plugins that would need to integrate with the commands here. 
So for, now we won't split the command into two. 
**However** if you are or know of a plugin author that is building things for Nx, definitely feel free to reach out. I'd be glad to work with them and make sure N Console plays nice.

On the performance side of things, you probably have a point. So far, it hasn't been an issue. 
Once we restructure things regarding angular CLI, we will reconsider `normalizeSchema` and its uses.
