### ISSUE TITLE
Feature: Move the 'Execute Task' button in the NX CONSOLE projects section.

### ISSUE THREAD

**Issue by labeled** [nrwl/nx-console#1007]
Currently the really awesome shortcut to build, lint, test different projects and libraries has an 'Execute Task' (play icon) button that is floated to the right of the screen. This is great at first, but as we added more nested libraries the button begins to hide. There is a horizontal scroll, and the ability to make it wider, but it would be nicer to have the play button either on the left, or not floated to the right.
Here you can see I can't find the play button.
![image](https://user-images.githubusercontent.com/17855377/106650322-6589f700-6558-11eb-8d2d-79b3ac62577b.png)
Here you can see how far I need to move the width to see it properly.
![image](https://user-images.githubusercontent.com/17855377/106650428-82bec580-6558-11eb-95f6-e2d15247129f.png)

**Comment by sandikbarr** [comment]
I'm not sure what might be causing this issue for you. Is this the standard dark theme? with a File Icon Theme enabled? Are you using a specific font? Even with long configuration names and icons enabled with a scrollbar in the Projects view, I'm always seeing the button even in a narrow panel.
![Screen Shot 2021-03-19 at 2 30 06 PM](https://user-images.githubusercontent.com/2250413/111833342-0b52b480-88c0-11eb-8426-90088b77e3cf.png)
![Screen Shot 2021-03-19 at 2 31 03 PM](https://user-images.githubusercontent.com/2250413/111833352-0ee63b80-88c0-11eb-9129-1ee95826e3a7.png)

We have those View Actions [configured as `"group": "inline"`](https://github.com/nrwl/nx-console/blob/master/apps/vscode/src/package.json#L74) according to the extension [docs](https://code.visualstudio.com/api/extension-guides/tree-view#view-actions) and don't have any more control of layout there unfortunately.

**Comment by labeled** [comment]
You know what, I feel silly. I have this setting enabled in vs code  
"workbench.list.horizontalScrolling": true, 
And that changes the behavior. So sorry if I wasted much of your time! <3

**Comment by sandikbarr** [comment]
No worries! Glad you could figure out what was interfering.
