### ISSUE TITLE
Generate Angular component/service/etc. no longer autocompleting project name in v16

### ISSUE THREAD

**Issue by luejerry** [nrwl/nx-console#1009]
Possible regression: on the form for generating components from Angular schematics (as well as service, directive, pipe, etc), the autocomplete functionality for filling out the project name is no longer working for me as of extension v16.

**Steps to reproduce**:
* Install extension v16.0 or greater in VSCode
* Generate `@schematics/angular - component`
* Start typing the name of a project into the project field
* Autocomplete suggestions do not appear

**Expected behavior**:
Autocomplete should offer suggestions matching available projects. I rolled back the extension to v15 and autocomplete worked again:

![Screen Shot 2021-02-08 at 6 25 12 AM](https://user-images.githubusercontent.com/5891296/107233185-25eb6100-69d7-11eb-9244-298d832d34b7.png)

**Comment by sandikbarr** [comment]
This is a recent regression unfortunately. I have a fix for this issue in #1008

**Comment by Cammisuli** [comment]
Fixed with https://github.com/nrwl/nx-console/pull/1008
