### ISSUE TITLE
Running lint via Nx Console doesn't populate problems pane in vscode

### ISSUE THREAD

**Issue by jaytavares** [nrwl/nx-console#1012]
I'm guessing that the problem matchers need to be set for the terminal window that is created to run commands from Nx Console.

**Comment by Cammisuli** [comment]
I'm marking this as an enhancement because it was something that was never in scope.

**Comment by work933k** [comment]
I think this would benefit many VSCode developers.

**Comment by work933k** [comment]
https://github.com/nrwl/nx-console/pull/2027
