### ISSUE TITLE
Refactoring File-Names in VSCode Fails

### ISSUE THREAD

**Issue by thestillheron** [nrwl/nx-console#1027]
## Current Behavior

Using VSCode's "rename" feature for files does not update any typescript references to that file within the same project. References must be manually searched for, and manually renamed.

This is true either by using F2 when the file is selected in File Explorer, or by using F2 with your caret on the file import on a typescript file.

These failures do not occur for non-NX projects.

## Expected Behavior

Using VSCode's rename feature on a file should search for and update all typescript references to that file within other files of the same project.

## Steps to Reproduce

1. Clone https://github.com/nrwl/nx-examples
1. Rename `./libs/cart/cart-page/src/lib/cart-cart-page/cart-cart-page.tsx` to `CartCartPage.tsx`
1. Note that the corresponding import in `./libs/cart/cart-page/src/index.ts` is not updated
1. Revert your change so the project once again compiles
1. Right-click on the filename of the import on line 1 of `./libs/cart/cart-page/src/index.ts` and select "rename"
1. Rename the file import to `CartCartPage.tsx`
1. Note that vscode fails the refactor, and generates an error (see Failure Logs)

### Failure Logs

Error generated when attempting to rename file via right-click import refactor:

```
<semantic> TypeScript Server Error (3.9.7) Debug Failure. Error: Debug Failure. at 
 
/private/var/folders/n0/pr4ql4lx3m3f3dkgnsvysw040000gn/T/AppTranslocation/AB2B43A6-0FD2-4CDB-9F2F-B9F2E493ACB1/d/Visual Studio 
 
Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:117897:61 at forEachProperty (/private/var/folders/n0/pr4ql4lx3m3f3dkgnsvysw040000gn/T/AppTranslocation/AB2B43A6-0FD2-4CDB-9F2F-B9F2E493ACB1/d/Visual Studio 
 
Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118061:17) at updateTsconfigFiles (/private/var/folders/n0/pr4ql4lx3m3f3dkgnsvysw040000gn/T/AppTranslocation/AB2B43A6-0FD2-4CDB-9F2F-B9F2E493ACB1/d/Visual Studio 
 
Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:117887:9) at /private/var/folders/n0/pr4ql4lx3m3f3dkgnsvysw040000gn/T/AppTranslocation/AB2B43A6-0FD2-4CDB-9F2F-B9F2E493ACB1/d/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript...
```

### Environment

```
>  NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : 10.2.0
  @nrwl/cli : 10.2.0
  @nrwl/cypress : 10.2.0
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 10.2.0
  @nrwl/linter : 10.2.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 10.2.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.2.0
  @nrwl/web : 10.2.0
  @nrwl/workspace : 10.2.0
  typescript : 3.9.7
```

**Comment by Areen3** [comment]
I solved this problem as follows:
I switched to webstorm
of course, this is not a solution, but the only one I knew to be sure that the environment changes each use of a given variable, function, class

**Comment by iguissouma** [comment]
Hi @Areen3 ,
Do you use the [Nx Console Idea](https://plugins.jetbrains.com/plugin/15101-nx-console-idea) plugin?. it has similar features with Nx Console for vscode.

**Comment by Areen3** [comment]
Hi
Main feature in this soluction is run task, 
I was try it, but I left it.
In my monorepo I have about 150 projects, it is hard to find project when I have list without filter 

great feature will be:
when I write project name list of project will be filtered, it is useful to locate project 
second: some group view  to better managment
for example i have:
![image](https://user-images.githubusercontent.com/34617740/109398792-3f7d2a00-793f-11eb-92b5-92e543c32707.png)
changing view beetwen tree and list will be usefull (group by directory/name)

I thing that main idea of this plugin is locate project and run task
maybe try make better posibility of  localization project :)
I didn't see that view in any solution

**Comment by iguissouma** [comment]
Hello, thanks for this feedback.
You have a filter support in many places, if the tree is not perfect for your use case you can try the `Run Anything` feature, or `Running Actions`.
Here some views with filters:
<img width="638" alt="Screenshot 2021-02-28 at 11 32 24" src="https://user-images.githubusercontent.com/9085108/109415421-ee118100-79b8-11eb-8efe-936ef80c1d31.png">
<img width="670" alt="Screenshot 2021-02-28 at 11 25 26" src="https://user-images.githubusercontent.com/9085108/109415438-04b7d800-79b9-11eb-88cf-8d11dbf90a8e.png">
<img width="237" alt="Screenshot 2021-02-28 at 11 28 08" src="https://user-images.githubusercontent.com/9085108/109415440-06819b80-79b9-11eb-9e01-3e1a002a238b.png">
<img width="671" alt="Screenshot 2021-02-28 at 11 36 10" src="https://user-images.githubusercontent.com/9085108/109415476-3b8dee00-79b9-11eb-839f-cc789ea460a5.png">

The tree should support filter natively too(but seems broken), should behave like `npm` window.
<img width="396" alt="Screenshot 2021-02-28 at 11 40 58" src="https://user-images.githubusercontent.com/9085108/109415597-e0103000-79b9-11eb-9e13-7223054012ff.png">

**Comment by Cammisuli** [comment]
On topic of what's being discussed in the OP, that's unfortunately an issue with TypeScript and how the multiple projects are set up with Nx. Before TypeScript used to scan the whole project tree and add all reference points to the TypeScript server in the background. Recently this changed where TypeScript will only start a scan when a file is opened in the editor. 

WebStorm uses a different mechanism (which I agree is a little nicer).

In the end, I'm not sure how we can make it better with this extension. I feel like we could probably plug into the TypeScript server and start adding things in the background? I'm not sure.. But I can look into it eventually.

**Comment by Cammisuli** [comment]
There’s no way for us to improve this. We’ll have to wait for newer versions of TypeScript to fix this. I suggest opening or reading through the VSCode/TypeScript issues to see where they’re heading with this. 

As of today, we can’t do anything about this. ☹️ 

Because of that, I’m going to close this issue.
