### ISSUE TITLE
Filter projects view 

### ISSUE THREAD

**Issue by mackelito** [nrwl/nx-console#1043]
We have 100+ projects and it's some time a hassle to scroll thru the projects list to find anything.. 
a search bar could make my life easier :)

**Comment by Cammisuli** [comment]
Definitely! I actually was going to create the same issue to track this 😄

**Comment by mackelito** [comment]
I was remembering this request and wanted to take a look at the status and see now that is has been closed.. but lookgin at #1050 I'm not sure that you understood what I meant.. 

#1050 is adding a button to open the project config.. What I was requesting was a simple search input to filter out projects we see in the sidebar :)

**Comment by mackelito** [comment]
Oh will you look at that.. you jus needed to click on any project and start typing!.. 👍
Thx for the tip!
