### ISSUE TITLE
Display customized command in VSCode plugin

### ISSUE THREAD

**Issue by Kunjinkao0** [nrwl/nx-console#1048]
We've just created several own schematics in our project, and everytime team members need to use **nx workspace-schematic xxx** in bash to execute these command, is it possible to show all the customized schematic command in the VSCode plugin panel(configurable ui should be better)? That will be much convenient when developers run.

**Comment by MaxKless** [comment]
Nowadays, the `Generate & Run Target` view contains all targets from the workspace and isn't hardcoded anymore! 
Also, you can configure the `Common Nx Commands` view with arbitrary commands of your liking :)
