### ISSUE TITLE
Generating @nrwl/angular:library with v17.0.1 and higher throws 'Project name is not valid'

### ISSUE THREAD

**Issue by arndwestermann** [nrwl/nx-console#1049]
Hello folks, i have the issue with the nx console extension v17.0.1 or higher for VS Code that i'm getting the error:

`Project name is not valid. New project names must start with a letter, and must contain only alphanumeric characters or dashes. When adding a dash the segment after the dash must also start with a letter.`

I can create components, services, etc but no libraries.
Downgraded to 17.0.0 and it works like a charm.

Nrwl Angular Version
"@nrwl/angular": "11.3.0"

Nrwl Cli Version
"@nrwl/cli": "11.3.0"

VS Code Version:
Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T11:57:12.728Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 18.7.0

**Comment by pacoita** [comment]
I had the same issue. The problem in my case was related to the directory path (eg: /libs/booking). If you remove the leading slash `/` it works.

I also created a [SO question](https://stackoverflow.com/questions/66765843/schematicsexception-when-creating-an-angular-library-with-nx-commands/66775925#66775925) with the details.

**Comment by Cammisuli** [comment]
This is something I noticed too when creating libraries. 

We can message the path/directory a bit, especially with generating libraries. If you notice, if you have libs in the directory argument, you'll get a double nested libs/libs. We should be able to check to see if a path starts with one of the defined apps or libs properties in nx.json.
