### ISSUE TITLE
Any chance for you to publish the libs to npm as packages?

### ISSUE THREAD

**Issue by ntziolis** [nrwl/nx-console#1073]
There is a lot of very helpful code in these libs especially around parsing schematics / options etc. 

Our use case:
We are currently building tooling to expose schematics as part of a customized application component generator interface. Hence we need to make schematics + args available via a api which is where leveraging the libs in the project come in.

In case you are wondering why we are not just using plain schematics / generators:
- The generator application lets the user connect to a graphql endpoint
- We then use graphql schema introspection to provide analyze the possible components that can be generated (grids / forms etc)
- The devthen picks the resolver / fields he would like to generate 
  - for example a grid component for resolver customers
  - with fields id name, users
  - for lookup fields (like users) the dev is provided with an overridable default lookup data source that can be customized via the ui
- The user can then further configure each field (filterable / sortable / editable etc.)
- And then issues a web request to the app server with the collected input as params 
- The server that simply triggers a nx generator
- The generator then creates a customized component based on the collected input

While we can create our own wrapper to expose the available generators and params your lib already provides exactly what is necessary todo this. While we could C&P the code snippets required we feel others might have use for it as well hence we created this issue.

Most of our work is building data driven angular apps for enterprises with lots of related data (lookups) and in our initial trials we were able to reduce development time by 10x+ as well as improve consistency across the application.

**Comment by Cammisuli** [comment]
What parts are you looking at? There's a few places where we try to leverage the angular cli to read the schematics. 

We actually are planning on using the newer Nx CLI (which is called tao) to get the required information we need than to write custom schematic parsers here. 

One of the goals is to fully utilize Nx (which can be imported via npm) and rely on it more. 

Anyway, let me know what parts you're looking at and we can probably expose utilities from `@nrwl/tao` to do the same thing.

**Comment by ntziolis** [comment]
We are especially interested in the functions that analyze the current workspace and expose all available schematics + generators as well as their respective arguments and potential values. Will def have a look in `@nrwl/tao` to get a better understanding if some if not all is already available through that

**Comment by Cammisuli** [comment]
We'll be working on moving from our own custom lookup to use the one provided by nx in the coming weeks.

**Comment by MaxKless** [comment]
Furthermore, there's the nx language server which is available as a standalone package. So if you want to build some nx functionality around that, you can. In general, we try not to (re-)implement stuff in Nx Console but always redirect to the underlying nx installation.
Combined with `@nrwl/devkit` I think there's a lot of functionality available.
