### ISSUE TITLE
nx console vs code extension doesn't take nx.json options

### ISSUE THREAD

**Issue by maxisam** [nrwl/nx-console#1079]
if I change nx.json to

```json
"tasksRunnerOptions": {
      "default": {
         "runner": "@nrwl/nx-cloud",
         "options": {
            "cacheableOperations": ["build", "lint", "test", "e2e", "stylelint", "server"],
            "accessToken": "",
            "canTrackAnalytics": false,
            "showUsageWarnings": true,
            "parallel": true,
            "maxParallel": 5
         }
      }
   },

```

nx console extension doesn't check parallel and change maxParallel from 3 to 5

**Comment by Cammisuli** [comment]
Those additional options you provided in the nx.json won't work as you expect. 

The

**Comment by maxisam** [comment]
Thanks for clarifying this. Where should I set in the angular.json?

**Comment by Cammisuli** [comment]
It depends on the executor/builder being run. For example, the only package that I could find that has the parallel, and maxParallel options is the web:file-server one (https://nx.dev/latest/node/web/file-server#maxparallel).

So options for that will look like this:
```
{
  "projects": {
    "products": {
      "architect": {
        "build": {
          "builder": "@nrwl/web:file-server",
          "options": {
           "maxParallel": 3,
           "parallel": true
          }
        }
      }
    }
  }
}

```

**Comment by maxisam** [comment]
But I want to use it for build. Those options are for build actually.

![image](https://user-images.githubusercontent.com/456807/121096709-580ba480-c7b8-11eb-9ce3-08bbc4e3b43a.png)

**Comment by Cammisuli** [comment]
Oh interesting... Those look like they're hard coded in the extension, and seem to be related to nx cloud..

Are you looking to set those options for Nx Cloud only then?

**Comment by maxisam** [comment]
Well, I do use nx cloud but I would like to use it in all situation. I don't know why it is not default anyway.

**Comment by MaxKless** [comment]
Hey! We're planning to get rid of the `run` UI and support to move only generating via the form. It's adding a lot of abstraction overhead to the form application but is rarely used.
Closing this issue.
