### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by houssam-eldeen** [nrwl/nx-console#1104]
- Issue Type: `Performance`
- Extension Name: `angular-console`
- Extension Version: `17.6.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.57.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\hfadel\AppData\Local\Temp\nrwl.angular-console-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Cammisuli** [comment]
Can you please attach the cpu profile?

**Comment by OysteinAmundsen** [comment]
Had the same problem. This is my cpu profile:

[nrwl.angular-console-unresponsive.cpuprofile.txt](https://github.com/nrwl/nx-console/files/6890816/nrwl.angular-console-unresponsive.cpuprofile.txt)

**Comment by Cammisuli** [comment]
Thanks for your cpuprofile @OysteinAmundsen, but unfortunately I can't see anything related to Nx console in there. I did notice that your instance is loading things from the C:/ drive and the D:/ drive. 

I still have to do a whole suite of performance fixes for Windows (I finally have a copy of Windows via parallels 😅 )

**Comment by jeroenvheel** [comment]
Also got the same error in vscode this is my cpu profile.

Issue Type: Performance
Extension Name: angular-console
Extension Version: 17.9.0
OS Version: Windows_NT x64 10.0.19043
VS Code version: 1.59.1

[nrwl.angular-console-unresponsive.cpuprofile.txt](https://github.com/nrwl/nx-console/files/7091212/nrwl.angular-console-unresponsive.cpuprofile.txt)

**Comment by Cammisuli** [comment]
sorry @jeroenvheel I can't seem to open that cpuprofile ☹️ vscode says it's a malformed json, and chrome reveals a blank panel.

**Comment by Cammisuli** [comment]
@jeroenvheel this looks like an issue with `@nrwl/workspace/src/core/hasher/git-hasher.js`. What version of nx are you using?
