### ISSUE TITLE
Projects not loading when using standalone config with empty workspace starter

### ISSUE THREAD

**Issue by Unbuttun** [nrwl/nx-console#1109]
Whenever I move a project to it's standalone config move, the extension stops listing projects, running their command and various things.

1. Right after you move a project to it's standalone config or create a new one, the project stops listing all projects. 
`The "path" argument must be of type string. Received undefined`
2. Clicking Run-many/affected results in this error - 
`None of your workspace projects have an architect command`

>  NX  Report complete - copy this into the issue template

  Node : 16.4.0
  OS   : linux x64
  pnpm : 6.9.1
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.5.7
  @nrwl/cypress : 12.5.7
  @nrwl/devkit : 12.5.7
  @nrwl/eslint-plugin-nx : 12.5.7
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.7
  @nrwl/linter : 12.5.7
  @nrwl/nest : Not Found
  @nrwl/next : 12.5.7
  @nrwl/node : 12.5.7
  @nrwl/react : 12.5.7
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.7
  @nrwl/web : 12.5.7
  @nrwl/workspace : 12.5.7
  @nrwl/storybook : 12.5.7
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by sandikbarr** [comment]
Is your workspace using angular.json or workspace.json for the main config? Initially, we only added support in Nx Console for the standalone project config with workspace.json. A [PR](https://github.com/nrwl/nx-console/pull/1105) has been merged to support this with angular.json as well, but it has not yet been released.

**Comment by Unbuttun** [comment]
It's using workspace.json, i've tested it newly created workspace and selecting empty as the target when it asks, then installing @nrwl/node library to generate application  and select standalone config there while generating it.

**Comment by sandikbarr** [comment]
Hmm... Nx is [requiring '@angular-devkit/schematics'](https://github.com/nrwl/nx/blob/master/packages/workspace/src/utils/project-type.ts#L1) to read the standalone configuration workspace.

```
Error: Cannot find module '@angular-devkit/schematics'
Require stack:
- /Users/sandikbarr/code/nrwl/test/split-config/node_modules/@nrwl/workspace/src/utils/ast-utils.js
- /Users/sandikbarr/code/nrwl/test/split-config/node_modules/@nrwl/workspace/src/utils/project-type.js
- /Users/sandikbarr/code/nrwl/test/split-config/node_modules/@nrwl/workspace/index.js
- /Users/sandikbarr/code/nrwl/nx-console/dist/apps/vscode/main.js
```

Dang. Using the standalone config shouldn't have a dependency on angular-devkit. We'll look at this further and get it addressed. Appreciate the report, thanks.
