### ISSUE TITLE
List Projects in the Projects View in Alphabetical Order.

### ISSUE THREAD

**Issue by gmattie** [nrwl/nx-console#1111]
While there is now a way to **[filter projects in the project view](https://github.com/nrwl/nx-console/pull/1050)**, I think a lot of the pain of searching through the project view, particularly in large monorepos, could be alleviated by simply listing the projects in alphabetical order.

**Comment by Cammisuli** [comment]
I'm open to it. Any one can add a PR to get this in if they'd like 😄

**Comment by sandikbarr** [comment]
Yeah, I like it. I was thinking it could be a sort button on the Projects TreeView (near the refresh.)

A lot of folks like to keep the workspace configuration file sorted, which probably makes a large workspace easier to navigate in that view as well.
