### ISSUE TITLE
Extension issue: NxConsole is unresponsive

### ISSUE THREAD

**Issue by omostan** [nrwl/nx-console#1127]
- Issue Type: `Bug`
- Extension Name: `angular-console`
- Extension Version: `17.9.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.59.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 373,
		"activateCallTime": 9669,
		"activateResolvedTime": 299,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "nrwl.angular-console",
				"_lower": "nrwl.angular-console"
			},
			"activationEvent": "onStartupFinished"
		}
	},
	"runtimeErrors": []
}
```

**Comment by Cammisuli** [comment]
I can't really go off anything in this issue.. It just appears that the start up is a bit slow?
