### ISSUE TITLE
Style option "none" is missing from console

### ISSUE THREAD

**Issue by emaildano** [nrwl/nx-console#1133]
When using the nx cli, the flag `--style=none` is available but missing from nx console. What I often do is copy/paste the cli command that the console generates and add the flag to it. I assumed that leaving it off would produce the same result, but the default is CSS modules.

In my case, I'm using `@nrwl/next:component`

```
nx generate @nrwl/next:component --name=foo --project=ui --export --style=none
```

![Screen Shot 2021-09-11 at 14 49 34](https://user-images.githubusercontent.com/1872327/132958312-7155befc-380d-471e-b603-8dfa1fb09e44.png)

**Comment by Cammisuli** [comment]
This doesn't actually look like it's an issue with Nx Console. We read the schema.json file that comes with the generator and "none" is not in the items listed.

https://github.com/nrwl/nx/blob/295b8d737c687e21e709fa5fa8397e49e12987d3/packages/next/src/generators/component/schema.json#L41-L71

I suggest opening a PR to add this option in the actual schema.json.
