### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by waguirre** [nrwl/nx-console#1140]
- Issue Type: `Performance`
- Extension Name: `angular-console`
- Extension Version: `17.10.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.61.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\waguirre\AppData\Local\Temp\nrwl.angular-console-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Cammisuli** [comment]
Should be fixed with #1131
