### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Zamachi** [nrwl/nx-console#1142]
- Issue Type: `Performance`
- Extension Name: `angular-console`
- Extension Version: `17.10.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.60.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Zamachi\AppData\Local\Temp\nrwl.angular-console-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Cammisuli** [comment]
A fix should be coming in the next release that hopefully was fixed with #1131
