### ISSUE TITLE
The "path" argument must be of type string. Received undefined after upgrade to 17.11.0

### ISSUE THREAD

**Issue by labeled** [nrwl/nx-console#1146]
After upgrading to version 17.11.0 (and 17.11.1) we receive an error as mentioned in the title.
![image](https://user-images.githubusercontent.com/17855377/134943324-e4020f6b-24f3-4a31-95f1-0e37da900eb0.png)
We are using Nx with a workspace.json and the Standalone Config if that helps.

Workspace.json
{
  "cli": {
    "analytics": false,
    "defaultCollection": "@nrwl/angular"
  },
  "defaultProject": "voyager",
  "generators": {
    "@nrwl/angular:application": {
      "style": "scss",
      "linter": "eslint",
      "unitTestRunner": "karma",
      "e2eTestRunner": "cypress",
      "routing": true,
      "skipFormat": true,
      "standaloneConfig": true,
      "strict": true
    },
    "@nrwl/angular:component": {
      "style": "scss"
    },
    "@nrwl/angular:library": {
      "style": "SCSS",
      "linter": "eslint",
      "unitTestRunner": "karma",
      "buildable": true,
      "enableIvy": true,
      "skipFormat": true,
      "skipPackageJson": true,
      "standaloneConfig": true,
      "strict": true
    },
    "@nrwl/cypress": {
      "cypress-project": {
        "linter": "eslint",
        "skipFormat": true
      }
    },
    "@nrwl/express": {
      "application": {
        "linter": "eslint",
        "skipFormat": true
      },
      "library": {
        "linter": "eslint",
        "skipFormat": true
      }
    },
    "@nrwl/nest": {
      "application": {
        "linter": "eslint",
        "skipFormat": true
      },
      "library": {
        "linter": "eslint",
        "skipFormat": true
      }
    },
    "@nrwl/node": {
      "application": {
        "linter": "eslint",
        "skipFormat": true
      },
      "library": {
        "linter": "eslint",
        "skipFormat": true
      }
    },
    "@nrwl/workspace": {
      "library": {
        "linter": "eslint",
        "skipFormat": true
      }
    },
    "@nrwl/workspace:remove": {
      "skipFormat": true
    }
  },
  "projects": {
    "audit-common-data-access": "libs/audit/common/data-access",
    "audit-data-access": "libs/audit/data-access",
    "audit-shared-audit-hits-data-access": "libs/audit/shared/audit-hits/data-access",
    "audit-shared-audit-hits-feature": "libs/audit/shared/audit-hits/feature",
    "challenges-qa-holds-entry-form-data-access": "libs/challenges/qa-holds/entry-form/data-access",
    "challenges-qa-holds-entry-form-feature": "libs/challenges/qa-holds/entry-form/feature",
    "challenges-qa-holds-holds-manager-data-access": "libs/challenges/qa-holds/holds-manager/data-access",
    "challenges-qa-holds-holds-manager-feature": "libs/challenges/qa-holds/holds-manager/feature",
    "chassis-tracker": "apps/chassis-tracker",
    "chassis-tracker-data-access": "libs/chassis-tracker/data-access",
    "chassis-tracker-e2e": "apps/chassis-tracker-e2e",
    "chassis-tracker-main-mobile-page-feature": "libs/chassis-tracker/main-mobile-page/feature",
    "chassis-tracker-main-mobile-page-pin-details-drawer-feature": "libs/chassis-tracker/main-mobile-page/pin-details-drawer/feature",
    "chassis-tracker-main-page-feature": "libs/chassis-tracker/main-page/feature",
    "chassis-tracker-shared-chassis-not-found-snack-bar-ui": "libs/chassis-tracker/shared/chassis-not-found-snack-bar/ui",
    "chassis-tracker-shared-chassis-typeahead-feature": "libs/chassis-tracker/shared/chassis-typeahead/feature",
    "chassis-tracker-shared-location-history-navigator-feature": "libs/chassis-tracker/shared/location-history-navigator/feature",
    "chassis-tracker-shared-maps-util": "libs/chassis-tracker/shared/maps/util",
    "chassis-tracker-shared-pin-info-ui": "libs/chassis-tracker/shared/pin-info/ui",
    "chassis-tracker-shared-tracker-assignment-feature": "libs/chassis-tracker/shared/tracker-assignment/feature",
    "chassis-tracker-shared-tracker-typeahead-feature": "libs/chassis-tracker/shared/tracker-typeahead/feature",
    "chassis-tracker-zone-page-feature": "libs/chassis-tracker/zone-page/feature",
    "checksheet-shared-common-data-access": "libs/checksheet/shared/common/data-access",
    "checksheet-shared-current-checksheet-data-access": "libs/checksheet/shared/current-checksheet/data-access",
    "checksheet-shared-current-checksheet-feature": "libs/checksheet/shared/current-checksheet/feature",
    "clear-to-build": "apps/clear-to-build",
    "clear-to-build-data-access": "libs/clear-to-build/data-access",
    "clear-to-build-e2e": "apps/clear-to-build-e2e",
    "clear-to-build-feature": "libs/clear-to-build/feature",
    "clear-to-build-models": "libs/clear-to-build/models",
    "custom-color-data-access": "libs/custom-color/data-access",
    "custom-color-released-paint-item": "libs/custom-color/released-paint-item",
    "dashboard": "apps/dashboard",
    "dashboard-e2e": "apps/dashboard-e2e",
    "example": "apps/_example",
    "fab-manager-shared-dj-column-display-ui": "libs/fab-manager/shared/dj-column-display/ui",
    "fab-manager-shared-parts-view-time-ui": "libs/fab-manager/shared/parts-view-time/ui",
    "materials": "apps/materials",
    "materials-buyer-console": "libs/materials/buyer-console",
    "materials-e2e": "apps/materials-e2e",
    "materials-main-page": "libs/materials/main-page",
    "materials-shared-bulk-actions": "libs/materials/shared/bulk-actions",
    "materials-view-requests": "libs/materials/view-requests",
    "part-transfer-types": "libs/part-transfer/types",
    "pit-studio": "libs/pit-studio",
    "pit-studio-admin-admin": "libs/pit-studio-admin/admin",
    "pit-studio-admin-alerts": "libs/pit-studio-admin/alerts",
    "pit-studio-admin-app-subscription-feature": "libs/pit-studio-admin/app-subscription/feature",
    "pit-studio-admin-data-access": "libs/pit-studio-admin/data-access",
    "pit-studio-admin-ui": "libs/pit-studio-admin/ui",
    "production-manager-freeze-data-access": "libs/production-manager/freeze/data-access",
    "production-manager-freeze-data-shift-scheduling-recent-date-shifts": "libs/production-manager/freeze/data-shift-scheduling/recent-date-shifts",
    "production-manager-freeze-effect": "libs/production-manager/freeze/effect",
    "production-manager-freeze-missing-item-demand-dialog": "libs/production-manager/freeze/missing-item-demand-dialog",
    "production-manager-freeze-ui-data-shift-scheduling": "libs/production-manager/freeze/ui/data-shift-scheduling",
    "production-manager-freeze-ui-freeze-list": "libs/production-manager/freeze/ui/freeze-list",
    "production-manager-freeze-ui-missing-item-demand": "libs/production-manager/freeze/ui/missing-item-demand",
    "production-manager-freeze-ui-reschedule-start-week-processing-request": "libs/production-manager/freeze/ui/reschedule-start-week/processing-request",
    "production-manager-freeze-ui-reschedule-start-week-reschedule-job-list": "libs/production-manager/freeze/ui/reschedule-start-week/reschedule-job-list",
    "production-manager-freeze-ui-scheduling-actions": "libs/production-manager/freeze/ui/scheduling-actions",
    "production-manager-freeze-ui-unfreeze-confirm": "libs/production-manager/freeze/ui/unfreeze-confirm",
    "production-manager-freeze-ui-week-picker": "libs/production-manager/freeze/ui/week-picker",
    "production-manager-glance-board-data-access": "libs/production-manager/glance-board/data-access",
    "production-manager-glance-board-effect": "libs/production-manager/glance-board/effect",
    "production-manager-glance-board-types": "libs/production-manager/glance-board/types",
    "production-manager-glance-board-ui-department-group-configuration": "libs/production-manager/glance-board/ui/department-group-configuration",
    "production-manager-glance-board-ui-department-group-viewer": "libs/production-manager/glance-board/ui/department-group-viewer",
    "production-manager-menu": "libs/production-manager/menu",
    "production-manager-settings-data-access": "libs/production-manager/settings/data-access",
    "production-manager-settings-department-item-types": "libs/production-manager/settings/department-item-types",
    "production-manager-settings-org-item-types": "libs/production-manager/settings/org/org-item-types",
    "production-manager-settings-types": "libs/production-manager/settings/types",
    "production-manager-settings-ui-item-types": "libs/production-manager/settings/ui/item-types",
    "production-manager-settings-ui-production-line": "libs/production-manager/settings/ui/production-line",
    "production-manager-shared-associate-dialog": "libs/production-manager/shared/associate-dialog",
    "production-manager-shared-custom-color-badge": "libs/production-manager/shared/custom-color-badge",
    "production-manager-shared-data-access": "libs/production-manager/shared/data-access",
    "production-manager-shared-job-number-typeahead": "libs/production-manager/shared/job-number-typeahead",
    "production-manager-shared-subjob-display": "libs/production-manager/shared/subjob-display",
    "production-manager-shared-types": "libs/production-manager/shared/types",
    "production-manager-shared-ui": "libs/production-manager/shared/ui",
    "production-manager-shared-util": "libs/production-manager/shared/util",
    "production-manager-signoff-data-access": "libs/production-manager/signoff/data-access",
    "production-manager-signoff-effect": "libs/production-manager/signoff/effect",
    "production-manager-signoff-excess-part-dialog": "libs/production-manager/signoff/excess-part-dialog",
    "production-manager-signoff-paint-part-demand-selection": "libs/production-manager/signoff/paint/part-demand-selection",
    "production-manager-signoff-paint-part-demand-staging": "libs/production-manager/signoff/paint/part-demand-staging",
    "production-manager-signoff-shortage-confirm-dialog": "libs/production-manager/signoff/shortage-confirm-dialog",
    "production-manager-signoff-signoff-associate-dialog": "libs/production-manager/signoff/signoff-associate-dialog",
    "production-manager-signoff-signoff-review-list": "libs/production-manager/signoff/signoff-review-list",
    "production-manager-signoff-signoff-review-search": "libs/production-manager/signoff/signoff-review/signoff-review-search",
    "production-manager-signoff-signoff-review-signoff-review-list-item": "libs/production-manager/signoff/signoff-review/signoff-review-list-item",
    "production-manager-signoff-subjob-department-items": "libs/production-manager/signoff/subjob-department-items",
    "production-manager-signoff-ui-multi-category-search": "libs/production-manager/signoff/ui/multi-category-search",
    "production-manager-signoff-ui-part-signoff-button": "libs/production-manager/signoff/ui/part-signoff-button",
    "production-manager-signoff-ui-progress-box": "libs/production-manager/signoff/ui/progress-box",
    "production-manager-signoff-ui-shortages-confirm": "libs/production-manager/signoff/ui/shortages-confirm",
    "run-manager": "apps/run-manager",
    "run-manager-e2e": "apps/run-manager-e2e",
    "run-manager-main-page-feature": "libs/run-manager/main-page/feature",
    "shared-active-item-typeahead-data-access": "libs/shared/active-item-typeahead/data-access",
    "shared-active-item-typeahead-feature": "libs/shared/active-item-typeahead/feature",
    "shared-adam-image-feature": "libs/shared/adam-image/feature",
    "shared-adam-image-ui": "libs/shared/adam-image/ui",
    "shared-applications-menu-data-access": "libs/shared/applications-menu/data-access",
    "shared-applications-menu-feature": "libs/shared/applications-menu/feature",
    "shared-customer-typeahead-data-access": "libs/shared/customer-typeahead/data-access",
    "shared-customer-typeahead-feature": "libs/shared/customer-typeahead/feature",
    "shared-data-access-division": "libs/shared/data-access/division",
    "shared-data-access-init-configuration": "libs/shared/data-access/init-configuration",
    "shared-data-access-models": "libs/shared/data-access/models",
    "shared-data-access-org": "libs/shared/data-access/org",
    "shared-data-access-quick-finder": "libs/shared/data-access/quick-finder",
    "shared-data-access-services": "libs/shared/data-access/services",
    "shared-data-access-signalr": "libs/shared/data-access/signalr",
    "shared-data-access-user": "libs/shared/data-access/user",
    "shared-directives-debounce-click": "libs/shared/directives/debounce-click",
    "shared-directives-open-job-details": "libs/shared/directives/open-job-details",
    "shared-directives-open-print": "libs/shared/directives/open-print",
    "shared-directives-part-image-thumb": "libs/shared/directives/part-image-thumb",
    "shared-discrete-job-typeahead-data-access": "libs/shared/discrete-job-typeahead/data-access",
    "shared-discrete-job-typeahead-feature": "libs/shared/discrete-job-typeahead/feature",
    "shared-feature-badge-number-lookup": "libs/shared/feature/badge-number-lookup",
    "shared-feature-login": "libs/shared/feature/login",
    "shared-feature-material-notification-snack-bar": "libs/shared/feature/material-notification-snack-bar",
    "shared-feature-navbar-notification": "libs/shared/feature/navbar-notification",
    "shared-feature-navigation-links": "libs/shared/feature/navigation-links",
    "shared-feature-user-typeahead": "libs/shared/feature/user-typeahead",
    "shared-item-compliance-feature": "libs/shared/item-compliance/feature",
    "shared-kendo-custom-grid-filters-ui": "libs/shared/kendo/custom-grid-filters/ui",
    "shared-kendo-grid-directives-feature": "libs/shared/kendo/grid-directives/feature",
    "shared-kendo-toggle-filter-feature": "libs/shared/kendo/toggle-filter/feature",
    "shared-loading-indicator": "libs/shared/loading-indicator",
    "shared-mat-associate-dialog-feature": "libs/shared/mat-associate-dialog/feature",
    "shared-materials-request-feature": "libs/shared/materials/request/feature",
    "shared-model-name-typeahead-data-access": "libs/shared/model-name-typeahead/data-access",
    "shared-model-name-typeahead-feature": "libs/shared/model-name-typeahead/feature",
    "shared-navbar-custom-search-feature": "libs/shared/navbar/custom-search/feature",
    "shared-navbar-data-access": "libs/shared/navbar/data-access",
    "shared-navbar-help-menu": "libs/shared/navbar/help-menu",
    "shared-navbar-options-menu-feature": "libs/shared/navbar/options-menu/feature",
    "shared-part-more-items": "libs/shared/part-more-items",
    "shared-router-data-access": "libs/shared/router/data-access",
    "shared-ui-alert-dialog": "libs/shared/ui/alert-dialog",
    "shared-ui-mat-confirm-dialog": "libs/shared/ui/mat-confirm-dialog",
    "shared-ui-mat-revision-mismatch-badge": "libs/shared/ui/mat-revision-mismatch-badge",
    "shared-ui-mat-submit-multi-select": "libs/shared/ui/mat-submit-multi-select",
    "shared-ui-material-async-typeahead": "libs/shared/ui/material-async-typeahead",
    "shared-util-cookie": "libs/shared/util/cookie",
    "shared-util-dates": "libs/shared/util/dates",
    "shared-util-guid": "libs/shared/util/guid",
    "shared-util-interceptors-loading-indicator": "libs/shared/util/interceptors/loading-indicator",
    "shared-util-ngrx-spinner": "libs/shared/util/ngrx-spinner",
    "shared-util-operators": "libs/shared/util/operators",
    "shared-util-pipes": "libs/shared/util/pipes",
    "shared-util-testing": "libs/shared/util/testing",
    "shared-util-validators": "libs/shared/util/validators",
    "shared-vendor-typeahead": "libs/shared/vendor-typeahead",
    "shared-vin-number-typeahead-data-access": "libs/shared/vin-number-typeahead/data-access",
    "shared-vin-number-typeahead-feature": "libs/shared/vin-number-typeahead/feature",
    "voyager": "apps/voyager"
  },
  "version": 2
}

**Comment by Cammisuli** [comment]
I'm going to close this because I reopened the original issue #1146
