### ISSUE TITLE
i get same error and roll back helps.  This is the only error i see:

### ISSUE THREAD

**Issue by alkgreer** [nrwl/nx-console#1148]
i get same error and roll back helps.  This is the only error i see:

![image](https://user-images.githubusercontent.com/1134683/134789885-b37809e6-0e82-400c-b7e4-24aad29f6d79.png)

_Originally posted by @chrismcleod in https://github.com/nrwl/nx-console/issues/1144#issuecomment-927208069_

Still getting this in 17.11.1

**Comment by Cammisuli** [comment]
I'm going to close this and reopen #1144
