### ISSUE TITLE
can't use option to generate in 17.11.2

### ISSUE THREAD

**Issue by maxisam** [nrwl/nx-console#1150]
![image](https://user-images.githubusercontent.com/456807/135024690-bf464610-0ef4-4c03-89c9-ca2b684fe808.png)

It work fine with 17.10.0

**Comment by Cammisuli** [comment]
Now this is interesting... I can't seem to reproduce this on macOS or Windows. 
<img width="766" alt="image" src="https://user-images.githubusercontent.com/4332460/135093301-a1491095-3e9e-4d9f-b5b4-0e42c75da2fe.png">

<img width="727" alt="image" src="https://user-images.githubusercontent.com/4332460/135093215-990dcf20-0861-4721-a67d-0a36fd5f4692.png">

What's the version of all the libraries you're using?

**Comment by maxisam** [comment]
somehow it is working now after I reinstall the latest version again. Weird thing in late night.
