### ISSUE TITLE
feat(settings): Configure the path to nx workspace file 

### ISSUE THREAD

**Issue by vymarkov** [nrwl/nx-console#1151]
What?
I want to be able to configure the path to workspace.json within vscode workspace settings.

Why?

During migration to nx we decided to create a separate folder with workspace configuration, in case of usage of Gitpod as Cloud IDE where each workspace is being built each time for each pull request I have to setup nx extensions again and again.

**Comment by MaxKless** [comment]
With `workspace.json` not recommended anymore, I'm closing this feature request.
