### ISSUE TITLE
nx console - Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by guiseek** [nrwl/nx-console#1155]
## Current Behavior

I can't use the generator more than 1 time, the message "Extension host terminated unexpectedly." happens all the time

## Expected Behavior

I believe you already know how you should behave

## Steps to Reproduce

Just use nx console

#### VSCode
Version: 1.60.2
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T11:59:27.195Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.5.0

#### NX Report
  Node : 12.18.2
  OS   : darwin x64
  npm  : 6.14.5
  
  nx : Not Found
  @nrwl/angular : 12.5.7
  @nrwl/cli : 12.5.7
  @nrwl/cypress : 12.5.7
  @nrwl/devkit : 12.5.8
  @nrwl/eslint-plugin-nx : 12.5.7
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.7
  @nrwl/linter : 12.5.7
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.5.7
  @nrwl/react : 12.9.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.7
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.5.7
  @nrwl/storybook : 12.5.7
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by Cammisuli** [comment]
@guiseek I seen some folks mention that this was happening to them, but I never was able to reproduce this. Is it still happening to you with the latest version of VS Code? (which would be 1.61 today)

**Comment by guiseek** [comment]
> @guiseek I seen some folks mention that this was happening to them, but I never was able to reproduce this. Is it still happening to you with the latest version of VS Code? (which would be 1.61 today)

@Cammisuli  yes it's still happening

version:
Version: 1.61.0
Confirm: ee8c7def80afc00dd6e593ef12f37756d8f504ea
Date: 2021-10-07T18:11:58.853Z (1 day ago)

**Comment by Micha-Richter** [comment]
I can provoke the exception by first saving an (even unchanged) angular.json and then typing any key (e.g. space bar).
Only enabled extension is Nx Console. Behavior is reproducible after restarting the extension host.

Hope it helps.

**Comment by dennisschneider** [comment]
Same for me ... Version: 1.61.0 ... let me know if you need further information to investigate this issue

**Comment by Micha-Richter** [comment]
I've tried to reproduce the exceptions in an extension development host version of VSCode, but to no avail :(

**Comment by jaruesink** [comment]
following, having this issue also

**Comment by aboqasem** [comment]
Similar problem here when opening `workspace.json`.

### Failure Logs

![Screenshot 2021-10-21 at 12 49 00 PM](https://user-images.githubusercontent.com/62098043/138213544-94b0d530-3159-4828-9c53-af4ca483baf5.png)
