### ISSUE TITLE
Nx console generate for VS Code isn't working with yarn 2

### ISSUE THREAD

**Issue by danielchikaka** [nrwl/nx-console#1159]
I can't run Nx console's generate on my visual studio code. I have tried to downgrade the plugin package and got the same results with this error "Could not execute task since node_modules directory is missing..." but the node_modules folder is there.

**Comment by awidjaja** [comment]
I have the same error message for my workspace. I use yarn version 2 (berry) for my package manager. Yarn is configured to use plug and play and zero install mode and thus is not using node_modules but .yarn/cache to store the insalled packages. yarn nx -version is showing the right nx version from my workspace, and the **nx cli works from terminal** but the nx console extension is looking for `node_modules` folder.  The current workspace listed in Nx console `change wrkspace item`. 

To replicate this issue,  you can install a new nx workspace using `yarn create nx-workspace --preset=npm` command and then do `yarn set version berry`, add `nodeLinker: pnp` in .yarnrc.yml and do `yarn install`. It will install yarn 2 locally and migrate all packages and scripts in node_modules into `.yarn/cache` folder.

Considering this is the future of yarn and the NX cli already works, NX console should be updated to support this.
