### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ronaldofas** [nrwl/nx-console#1166]
- Issue Type: `Performance`
- Extension Name: `angular-console`
- Extension Version: `17.11.2`
- OS Version: `Linux x64 5.14.12-200.fc34.x86_64`
- VS Code version: `1.61.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/nrwl.angular-console-unresponsive.cpuprofile.txt` -> [file](http://www.filedropper.com/nrwlangular-console-unresponsivecpuprofile)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Cammisuli** [comment]
I'm going to close this in the meantime because I haven't seen any issues in the last couple weeks.  Reopen this if there's still an issue.
