### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Vorakor** [nrwl/nx-console#1170]
- Issue Type: `Performance`
- Extension Name: `angular-console`
- Extension Version: `17.12.2`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.61.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\sberube\AppData\Local\Temp\nrwl.angular-console-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Vorakor** [comment]
Attaching file.
[nrwl.angular-console-unresponsive.cpuprofile.txt](https://github.com/nrwl/nx-console/files/7516090/nrwl.angular-console-unresponsive.cpuprofile.txt)

**Comment by Cammisuli** [comment]
Try and give this another go. All the functions in Nx Console are now async, and shouldn't hang anything anymore. Please request to reopen if this is still happening.
