### ISSUE TITLE
Using "ng generate ..." on contextual menu in Angular repositories does not use angular.json default config

### ISSUE THREAD

**Issue by Maryannah** [nrwl/nx-console#1173]
Following #1168 

- Create an Agular project
- Edit the angular.json configuration file to add custom schematics properties : 

![image](https://user-images.githubusercontent.com/46892394/141647771-d6c25d43-e48c-4908-b6ca-942ffb2d6558.png)

- Use "ng generate ..." with the conextual menu on a folder

The fields are not populated with the correct information : 

![image](https://user-images.githubusercontent.com/46892394/141647824-f0a52cc7-99f1-43fd-8174-78abd42f661e.png)

I do not know if this is by design or not, so I am raising it as an issue, feel free to close it if it's made to work this way :) 

PS : thank you for the work and the reactivity on #1168 !

**Comment by Cammisuli** [comment]
oh, I didn't realize we could put schematic defaults within a project like that.. We can probably support it, but let me try some things out.

**Comment by Maryannah** [comment]
Hi @Cammisuli any news on that matter ? 

(Not pressuring you or anything, just checking in every month or so as I usually do !)

**Comment by Cammisuli** [comment]
No, sorry! It's on the list of things to do 😅

**Comment by sir-captainmorgan21** [comment]
@Cammisuli this same issue exists when defining defaults in the nx.json as well... It populates the UI, but the resulting output of the dryrun doesn't seem to honor it

**Comment by Cammisuli** [comment]
@sir-captainmorgan21 Are you using an angular.json based workspace, and on the latest version of Nx Console?

**Comment by MaxKless** [comment]
Hey! We're looking to drop Angular CLI support in the not-too-far future, so I'm closing this issue. 
You can use `nx generate @nrwl/angular:component` instead of `@schematics/angular` and default configs will be honored just fine :)
