### ISSUE TITLE
Custom executor does not start on project.json or `run` panel

### ISSUE THREAD

**Issue by zanettin** [nrwl/nx-console#1180]
sorry @Cammisuli to chime in here as well 🙈  have the same issue as mentioned by @xiejay97 on #1125:

- clicking on the link within the `project.json` does nothing
- click on the `run` cmd does also nothing
- only clicking on the `projects` actions does trigger my custom action. 

any ideas what could be the cause of it? thanks a lot in advance 🙏 

https://user-images.githubusercontent.com/3241476/143937339-723f88cc-4da7-4e10-9162-91fe21bd9742.mp4

### computer specs
mac book pro 2021
osx monterey
vs code insiders `1.63.0-insider`
nx console `17.12.4`
iterm2 terminal with oh-my-zsh installed

if you need any further info just let me know. thanks again

**Comment by Cammisuli** [comment]
hmm interesting.. all those execution actions call the same command. Do you mind setting up a repo that has an internal executor like you have set up?

That will save me some time and get this fixed quicker. Thank you!

**Comment by zanettin** [comment]
Hi @Cammisuli 
And thx a lot for your quick reply and help on this 🙏 
i've created to most basic example i could over here > https://github.com/zanettin/nx-trigger-issue-repro
action is called `baz` on project `foobar`.
if you need any further info please let me know and thanks again for having a look at it!
bw
