### ISSUE TITLE
Generate commands should be executed with `nx` rather than `ng`

### ISSUE THREAD

**Issue by rene-leanix** [nrwl/nx-console#1188]
After moving to `angular.json` version 2 (in order to use separate `project.json`-files as documented [here](https://nx.dev/l/a/core-concepts/configuration)), we are unable to execute Angular schematics via the nx console. 

The problem is, that the generated command uses `ng` rather than `nx`, which then fails with: `Invalid format version detected - Expected:[ 1 ] Found: [ 2 ]`. Using `nx` throughout should fix this issue and be completely downwards compatible.

**Comment by Cammisuli** [comment]
The logic of this check is here:
https://github.com/nrwl/nx-console/blob/fc4caeaf3c17c95f1f305d13f6dd062acff5f47c/libs/vscode/tasks/src/lib/cli-task.ts#L18-L22

This means that you should also rename angular.json to workspace.json. Pure Angular CLI doesn't support version 2, as you mentioned, and you might come across different issues somewhere else down the line.

**Comment by rene-leanix** [comment]
Thanks for the hint! I didn't realise the docs were requiring the renaming to `workspace.json` when moving to version 2, but that makes a lot of sense!
