### ISSUE TITLE
command not found: npx

### ISSUE THREAD

**Issue by marcellkiss** [nrwl/nx-console#1189]
My default terminal is zsh, and I have node/npm/npx available (using nvm).

Although, when I try to run nx console, it complains:
```
zsh:1: command not found: npx
The terminal process "zsh '-c', 'npx ng generate @schematics/angular:component --name=test --no-interactive --dry-run'" terminated with exit code: 127.
```

What can be the difference? I can't digure it out... If I copy the command manually into my terminal, it works fine. Why nx console can't find npx?
`npx ng generate @schematics/angular:component --name=test --no-interactive --dry-run`

Note:
I also tried to check the "use nvm" option in the extension settings, but it didn't help. I uninstalled, reinstalled the extension, restarted VS Code, no result.

Version info:
- nx console v17.12.4
- nvm v0.32.1
- node v16.13.0
- npm v8.1.1
- VS Code  v1.62.3
- zsh v5.7.1
- macOS v12.0.1

**Comment by Cammisuli** [comment]
Sorry about that, but that `nvm` option doesn't do anything :( that should be cleaned up. 

Other than that, Nx Console doesn't do anything special with regards to running a terminal instance. That's handled by VS Code itself.

Have you tried playing with the VS Code terminal profiles to see if that can help?

https://code.visualstudio.com/docs/editor/integrated-terminal#_configuring-profiles

Specifically, Nx Console uses this setting via VS Code:
https://code.visualstudio.com/docs/editor/integrated-terminal#_configuring-the-taskdebug-profile

**Comment by marcellkiss** [comment]
Thanks for your help @Cammisuli, meanwhile the problem has gone, to be honest, I don't know, what caused the problem...

**Comment by Cammisuli** [comment]
I've noticed that sometimes yarn does the same thing while working on a client project. But that environment has proxies and other things that are wild. Usually restarting VS Code fixes it up 🤷🏼

**Comment by EthanSK** [comment]
having this isssue

**Comment by graphical-iain** [comment]
For those that get this in the future: Restarting VS Code seems to fix it. :)

**Comment by Carniatto** [comment]
The comment on this other issue solved for me: https://github.com/nrwl/nx/issues/8925#issuecomment-1065826677

**Comment by okaydokay97** [comment]
> For those that get this in the future: Restarting VS Code seems to fix it. :)

I have tried restarting VS Code and reinstalling the extension and am having the same issue.

**Comment by icaroerasmo** [comment]
you must put nx, yarn or whatever you want to call on your path environment variable. See link below:
https://www.baeldung.com/linux/path-variable

**Comment by gRoussac** [comment]
Curiously when just simply closing VsCode on Linux, it is not enough, some background processes need to be killed too with

```
killall code
```

**Comment by ZennerBlade** [comment]
Any solution to this?
Restarting doesn't work.
It only throws this error while using the extention. Copying the cmd and running it in terminal works fine

**Comment by MaxKless** [comment]
There's a few fixes propsed in here: 
https://github.com/nrwl/nx-console/issues/1424

I had the same issue but it resolved itself eventually. Looks like there's weird shenanigans happening with node's `exec` in vscode. Reinstalling VSCode might help too.

**Comment by Frikki** [comment]
If you upgrade node while VSCode is open, you must restart VSCode for NX Console to work again with npx.

**Comment by xiongemi** [comment]
1 got it when i upgrade my zsh version. just make sure the node dir is there when you run `echo $PATH`.
in my `.zshrc`, i got NVM_DIR.
```
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
```

then i have to close ALL my vscode windows and repoen them.

**Comment by stomvi** [comment]
In case someone is still facing this problem as I am.

In my case, the VS Code integrated terminal runs generator commands with `zsh -l -c`, so `.zshrc` will not be loaded. The `npm` (and `npx`) is only installed within `nvm` which is loaded in `.zshrc`.

Adding the following line to my `.zprofile` to load `.zshrc` fixes the problem:
```bash
[[ -f ~/.zshrc ]] && source ~/.zshrc
```
