### ISSUE TITLE
Nx console not working at all after updating

### ISSUE THREAD

**Issue by nurbashanghai** [nrwl/nx-console#1190]
Like month ago after I updated nx console in VScode market place NX console stopped working. All I see its this button "GET STARTED" that's all. I tried to rollback to all previous versions one by one and seems like only 17.11.1 and earlier versions working for me. But newer version not. What is the problem? Maybe I need to configure something I don't know, any help will be appreciated, thanks !
<img width="1212" alt="Screen Shot 2021-12-10 at 14 17 12" src="https://user-images.githubusercontent.com/63287548/145540546-425c47e7-514b-4c04-b70d-33b9fabb8299.png">

**Comment by nurbashanghai** [comment]
As I said 17.11.1 working for me. but newer versions are broken on my machine
<img width="1212" alt="Screen Shot 2021-12-10 at 14 20 41" src="https://user-images.githubusercontent.com/63287548/145540967-22ff2d0a-6eb1-472b-bacb-760705eb5f2a.png">

**Comment by Cammisuli** [comment]
What's your OS? What extensions are you running with it? If you open the Dev Tools 	`command prompt > Toggle Developer Tools` what message is that's related to Nx?

**Comment by Cammisuli** [comment]
Can I also get the contents of your package.json file?

**Comment by nurbashanghai** [comment]
After some cleaning in vscode extensions, it worked. I guess it was conflicting with some vscode extension
