### ISSUE TITLE
PNPM --dry-run does not seem to auto run on terminal

### ISSUE THREAD

**Issue by Balance8** [nrwl/nx-console#1193]
Usually, nx-console shows a dry run in the console if you use YARN or NPM; however, I am not getting that same functionality if I use PNPM.

**Comment by Balance8** [comment]
Side note: Nx console RUN button does not seem to function with PNPM

**Comment by Cammisuli** [comment]
Related to #1159

**Comment by Cammisuli** [comment]
Sorry @Balance8 I thought this was related to yarn pnp, but it's not. I'm trying pnpm and things are running with `dry-run` and the run button for me. 

Here's a screenshot of my run:
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/4332460/150548454-de2e2517-20a3-48eb-8fe6-ff58ce03b291.png">


So we're gonna need a little bit more information:

* What generator/schematic are you trying to use?
* What are the versions of your dependencies in package.json?
* What version of pnpm are you using?

**Comment by Balance8** [comment]
Closing due to it's age
