### ISSUE TITLE
[Bug] Seems like NX console not working after update  , OS Monterey

### ISSUE THREAD

**Issue by akirawinz** [nrwl/nx-console#1194]
<img width="286" alt="Screen Shot 2564-12-12 at 23 15 15" src="https://user-images.githubusercontent.com/30648805/145720145-62831dac-63bf-4017-845a-c08c5bd9766d.png">

I'm using NX console v17.13.1

npm v 6.14.15
node v 14.18.2

In The UI for nx is show noting

<img width="474" alt="Screen Shot 2564-12-12 at 23 16 18" src="https://user-images.githubusercontent.com/30648805/145720193-21103959-20af-4854-9ae2-eacc5057911d.png">

- when I cmd + shift + p and type serve or generated , it didn't show up 
- when I click Generate  the error show up 
<img width="634" alt="Screen Shot 2564-12-12 at 23 17 41" src="https://user-images.githubusercontent.com/30648805/145720254-7b0d3c79-efe4-4d2a-8c55-abe41620a481.png">
- cmd + shift +p > Toogle Developers tools here is an error

<img width="548" alt="Screen Shot 2564-12-12 at 23 18 45" src="https://user-images.githubusercontent.com/30648805/145720297-5dd5610d-c2a2-4ea3-b9ed-2d2f48b95d23.png">

**Comment by Cammisuli** [comment]
what does your package.json look like? There seemed to be a problem reading the `node_modules` directory.

**Comment by akirawinz** [comment]
well , I clone  https://github.com/nrwl/nx-examples everything work fine, but am not sure why my project cannot generated
here is my package.json

`"dependencies": {
    "@ant-design/charts": "1.2.7",
    "@apollo/client": "3.3.20",
    "@apollo/react-testing": "^4.0.0",
    "@babel/plugin-transform-react-jsx-source": "^7.14.5",
    "@casl/ability": "^5.4.3",
    "@fingerprintjs/fingerprintjs": "^3.2.0",
    "@golevelup/ts-jest": "^0.3.1",
    "@line/liff": "^2.12.0",
    "@magic-ext/webauthn": "^0.1.0",
    "@nestjs/common": "^8.0.0",
    "@nestjs/config": "^1.0.1",
    "@nestjs/core": "^8.0.0",
    "@nestjs/graphql": "^7.10.6",
    "@nestjs/jwt": "^7.2.0",
    "@nestjs/microservices": "^7.6.17",
    "@nestjs/passport": "^7.1.6",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/serve-static": "^2.1.4",
    "@nestjs/swagger": "^4.8.0",
    "@nestjs/terminus": "^7.2.0",
    "@nestjs/typeorm": "^7.1.5",
    "@nrwl/cli": "13.3.1",
    "@nrwl/cypress": "13.3.1",
    "@nrwl/devkit": "13.3.1",
    "@nrwl/eslint-plugin-nx": "13.3.1",
    "@nrwl/linter": "13.3.1",
    "@nrwl/nest": "13.3.1",
    "@nrwl/next": "13.3.1",
    "@nrwl/node": "13.3.1",
    "@nrwl/react": "13.3.1",
    "@nrwl/tao": "13.3.1",
    "@nrwl/web": "13.3.1",
    "@nrwl/workspace": "13.3.1",
    "@react-pdf/renderer": "^2.0.15",
    "@types/enzyme": "^3.10.8",
    "@types/multer": "^1.4.6",
    "@zeit/next-less": "^1.0.1",
    "@zeit/next-sass": "^1.0.1",
    "ant-table-extensions": "^1.1.7",
    "antd": "4.16.3",
    "antd-mask-input": "^0.1.15",
    "apollo-boost": "^0.4.9",
    "apollo-server-express": "^2.25.1",
    "apollo-upload-client": "^16.0.0",
    "app-root-path": "^3.0.0",
    "aws-sdk": "^2.966.0",
    "axios": "0.21.1",
    "babel-plugin-import": "^1.13.3",
    "babel-plugin-module-resolver": "^4.1.0",
    "babel-plugin-relay": "^12.0.0",
    "bcrypt": "^5.0.1",
    "class-transformer": "^0.4.0",
    "class-validator": "^0.13.1",
    "cookie": "^0.4.1",
    "core-js": "3.6.5",
    "date-fns": "^2.22.1",
    "document-register-element": "1.13.1",
    "faker": "^5.5.3",
    "fs-extra": "^10.0.0",
    "generate-password": "^1.6.1",
    "graphql": "^15.5.0",
    "graphql-tools": "^7.0.5",
    "graphql-upload": "^12.0.0",
    "joi": "^17.4.0",
    "js-cookie": "^3.0.1",
    "jsonwebtoken": "^8.5.1",
    "less-loader": "7.3.0",
    "less-vars-to-js": "^1.3.0",
    "lodash": "^4.17.21",
    "magic-sdk": "^4.3.0",
    "moment": "^2.29.1",
    "multer": "^1.4.2",
    "nestjs-typeorm-paginate": "^2.5.3",
    "next": "12.0.7",
    "next-compose-plugins": "^2.2.1",
    "next-link": "^2.0.0",
    "next-plugin-antd-less": "^1.4.3",
    "nodegit": "^0.27.0",
    "nodemailer": "^6.7.0",
    "passport": "^0.4.1",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "pdfkit": "^0.12.1",
    "pg": "^8.6.0",
    "postcss-loader": "^6.1.1",
    "rc-util": "^5.15.0",
    "react": "17.0.2",
    "react-apollo": "^3.1.5",
    "react-dom": "17.0.2",
    "react-google-login": "^5.2.2",
    "react-pin-input": "^1.0.1",
    "react-select-country-list": "^2.2.3",
    "react-slick": "^0.28.1",
    "recoil": "0.3.1",
    "reflect-metadata": "^0.1.13",
    "regenerator-runtime": "0.13.7",
    "request-ip": "^2.1.3",
    "rxjs": "^7.0.0",
    "slick-carousel": "^1.8.1",
    "supertest": "^6.1.3",
    "swagger-typescript-codegen": "^3.2.3",
    "swagger-ui-express": "^4.1.6",
    "tailwindcss-textshadow": "^2.1.3",
    "tslib": "^2.0.0",
    "typeorm": "^0.2.34"
  },
  "devDependencies": {
    "@angular/cli": "^12.2.6",
    "@babel/core": "7.12.13",
    "@babel/preset-env": "7.12.13",
    "@babel/preset-react": "7.12.13",
    "@babel/preset-typescript": "7.12.13",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@nrwl/jest": "13.3.1",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "12.1.2",
    "@testing-library/react-hooks": "7.0.2",
    "@types/app-root-path": "^1.2.4",
    "@types/file-saver": "^2.0.3",
    "@types/graphql-upload": "^8.0.6",
    "@types/jest": "27.0.2",
    "@types/jsonwebtoken": "^8.5.4",
    "@types/lodash": "^4.14.170",
    "@types/node": "^14.17.5",
    "@types/nodegit": "^0.27.2",
    "@types/passport-jwt": "^3.0.6",
    "@types/passport-local": "^1.0.34",
    "@types/pdfkit": "^0.11.0",
    "@types/react": "17.0.30",
    "@types/react-dom": "17.0.9",
    "@types/react-select-country-list": "^2.2.0",
    "@types/react-slick": "^0.23.5",
    "@types/request-ip": "0.0.37",
    "@typescript-eslint/eslint-plugin": "5.3.1",
    "@typescript-eslint/parser": "5.3.1",
    "autoprefixer": "^10.3.4",
    "babel-jest": "27.2.3",
    "css-loader": "^6.2.0",
    "cypress": "^7.7.0",
    "cypress-file-upload": "^5.0.8",
    "docker-compose": "^0.23.12",
    "dotenv": "10.0.0",
    "eslint": "8.2.0",
    "eslint-config-next": "12.0.7",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "eslint-plugin-import": "2.25.2",
    "eslint-plugin-jsx-a11y": "6.4.1",
    "eslint-plugin-react": "7.26.1",
    "eslint-plugin-react-hooks": "4.2.0",
    "husky": "^6.0.0",
    "jest": "27.2.3",
    "jest-sonar": "^0.2.12",
    "lint-staged": "^11.0.0",
    "nock": "^13.1.0",
    "papaparse": "^5.3.1",
    "postcss": "^8.3.6",
    "postcss-preset-env": "^6.7.0",
    "prettier": "2.4.0",
    "sass-loader": "10.1.1",
    "sonar-scanner": "^3.1.0",
    "style-loader": "^3.2.1",
    "tailwindcss": "^2.2.15",
    "tailwindcss-debug-screens": "^2.1.0",
    "ts-jest": "27.0.5",
    "ts-node": "^9.1.1",
    "typescript": "4.3.5"
  }`

**Comment by Cammisuli** [comment]
hmm, I just tried these dependencies on the Nx examples repo, and everything loaded correctly. What package manager are you using? 

Also is the workspace that shown in the `Generate & Run Targets` window (beside the change workspace item) match the current workspace in VS Code?
<img width="365" alt="image" src="https://user-images.githubusercontent.com/4332460/145835371-e57c88fb-5f05-4a35-aacd-cf532c932087.png">

**Comment by akirawinz** [comment]
change workspace is match in workspace vs code , I can use serve  , build normally

 the error also show this 
```@parcel/node-addon-api/package.json does not exist``` [ I already checked in node_modules I find @parcel/node-addon-api but didnt'r find package.Json but compare in Nx example all are same]

and I already try Nx examples  with my package.json with same  it's work well ,
not sure what package manger ? did you mean Nx console extension ? , Vscode 

I'm using npm

**Comment by Cammisuli** [comment]
What version of npm are you using?

**Comment by akirawinz** [comment]
npm v 6.14.15

**Comment by Cammisuli** [comment]
potentially fixed with https://github.com/nrwl/nx-console/pull/1199 where it will release as 17.13.2

**Comment by Cammisuli** [comment]
@akirawinz Can you try again with 17.13.2?

**Comment by akirawinz** [comment]
Sorry for lately reply, After I try error show up same as before

```
Nx Console encountered an error when activating
{}
TypeError: Cannot convert undefined or null to object
```

But If I start with new project , and try in nx-examples everything work well , 

Back to my project I start to change editor fromt VScode to Webstorm and use Nx console it also work well,

So wired probably something is missing in my project.

**Comment by Cammisuli** [comment]
Is your project on GitHub? Or is it a private repo for your company?

**Comment by akirawinz** [comment]
it a private repo for my company

**Comment by Cammisuli** [comment]
Can you try again with the latest version (17.3.3)?

**Comment by akirawinz** [comment]
17.3.3 confirmed it's work well again thanks !
