### ISSUE TITLE
BUG: Chai types for expect instead of Jest in Spec Files (v17.13.1 only)

### ISSUE THREAD

**Issue by PhilippSeitz** [nrwl/nx-console#1195]
We noticed a weird behaviour when we updated to `v17.13.1`. 
VSCode shows the wrong signature for `expect` in spec files.
Instead of: 
[version <= v17.13.0]
![version <= v17.13.0](https://user-images.githubusercontent.com/44158030/145859541-97ea6af7-0b04-4260-af2e-7fc9a218f211.png)

it displays an error (because it resolves expect as Chai):
![v17.13.1](https://user-images.githubusercontent.com/44158030/145859913-ef1b5507-4ba4-4a41-a3a9-d83f5cccda60.png)

**Comment by Cammisuli** [comment]
That's interesting... there's no change between 17.13.1 and 17.13.0 in regards to what we do with typescript. The .1 release fixed something with the UI portion of the generate functionality.

If you told me that this started happening with 17.3.0, then that would've been less interesting. 17.3.0 added a typescript plugin that enables VSCode to find imports to different libraries. 

Have you tried restarting VSCode?

**Comment by PhilippSeitz** [comment]
@Cammisuli ah, my bad. I only did a reload. I can confirm it also happens with 17.13.0 after a restart of the app. The same for my colleagues. We'll stick with  `v17.12.4` for now.

**Comment by Cammisuli** [comment]
Can you give me the contents of your package.json and tsconfig.base.json please?
