### ISSUE TITLE
Nx Console UI is empty after installing from vs code extentions

### ISSUE THREAD

**Issue by gschauhan** [nrwl/nx-console#1196]
I have installed nx console from vs code market place. After installing I am not able to see the UI for generate or run or any other options.I am able to execute commands via terminal like I created test workspace and test app via command line then it worked as intended but in vs code nx console doesnot show anything. 

Os: ubuntu 18.04
vs code: 1.54.3
node: 14.18.2
npm: 6.14.15

npm and node is installed via apt and I have configured global npm directory to avoid using sudo for installing global packages as suggested here: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally#manually-change-npms-default-directory

What I expect is it should show like this: https://imgur.com/a/JngsDRc
However I get empty window like this: https://imgur.com/a/OS1YZpj
Also I am not seeing commands for nx in commad pallet of vscode: https://imgur.com/FbGqZa7

How do I make nx console work in vs code?

**Comment by Cammisuli** [comment]
Are there any pop ups or error messages in the output terminal or dev tools?

Have you tried restarting vs code?

**Comment by gschauhan** [comment]
> Are there any pop ups or error messages in the output terminal or dev tools?
> 
> Have you tried restarting vs code? Or making sure that you opened a workspace that has a nx.json file?

Yes, I restarted vs code many times. I created workspace using nx command line and opened it in vs code but nothing worked.

**Comment by gschauhan** [comment]
Hi, I have reset my vscode from https://stackoverflow.com/a/64518036
This worked for me.
