### ISSUE TITLE
Map Run button to keyboard

### ISSUE THREAD

**Issue by moniuch** [nrwl/nx-console#1217]
Please map cmd/ctrl-enter to the Run button in generator wizard

**Comment by Cammisuli** [comment]
I actually thought about this today because I was running multiple generators 😅 

Thank you for the feature request! 😄

**Comment by moniuch** [comment]
Yes, yesterday I was all schematics, and as I am a keyboard person, the lack of shortcut came up quite quickly :) What would help would be also giving focus to the first field, once the wizard has loaded. Not sure if it should be a separate ticket?

**Comment by Cammisuli** [comment]
Yea, another issue should be created for that

**Comment by moniuch** [comment]
@Cammisuli In case you wanted to upvote: #1218 :)
