### ISSUE TITLE
Give focus to the first input field upon schematic wizard load

### ISSUE THREAD

**Issue by moniuch** [nrwl/nx-console#1218]
## Description

In the schematics wizard forms, let's give focus to the first input field, once the wizard has been loaded.

## Motivation

To enable streamlined and mouse-free operation as much as possible.
Currently, wizard requires using pointing device to give focus to the form. Combined with #1217, will provide a much better dev experience.

**Comment by Cammisuli** [comment]
I was looking into this the other day, and it's not as easy as I thought it would be 😅

I'll have to think of a good approach that works with the current architecture

**Comment by moniuch** [comment]
@Cammisuli Understood.
1. Would it be any easier if there was a dedicated command, say "Nx Console > Set focus", which I could map to a shortcut?
2. Would it help if the big param search input received focus? (not sure how tab-index works in this setup)

**Comment by Cammisuli** [comment]
I was thinking of putting the focus on the search, but there's some fiddling that needs to happen to make it work.

**Comment by MaxKless** [comment]
With https://github.com/nrwl/nx-console/pull/1528 the focus will be on the search bar when opening the generate ui. 
Initially I had it on the first input field, however this lead to an issue: whenever you click somewhere (for example the new `show more options` button), the validation would trigger. This meant a layout shift and was really irritating. 

Either way, once it's released, you will be able to press tab 3 times and start typing away without ever touching your mouse!
