### ISSUE TITLE
Title and description present in schema.json is not being shown in the NX console

### ISSUE THREAD

**Issue by sonikasharma1403** [nrwl/nx-console#1224]
## Current Behavior
- Title and description present in `schema.json` is not shown in the Nx Console Search Bar
![image](https://user-images.githubusercontent.com/86649832/150527332-3dfdf185-0205-4032-96aa-2b77a48c0aa2.png)

## Expected Behavior
- Values should be respected 
![image](https://user-images.githubusercontent.com/86649832/150527437-fe1be62e-e9c4-49b7-95bc-cf7d9e80b32b.png)

## Steps to Reproduce
- create a workspace generator
![image](https://user-images.githubusercontent.com/86649832/150527052-fff506b2-9c34-4287-9885-44397e19cbc8.png)
- Add title and description in `schema.json`
![image](https://user-images.githubusercontent.com/86649832/150527169-3b5bdb18-aabe-4c2b-bc4d-ed635d7cade3.png)
- Go to Nx Search bar and search for the generator. Notice that title and description is not shown
![image](https://user-images.githubusercontent.com/86649832/150527262-a852d180-985e-4b4d-a06b-06eec0d95bad.png)

**Comment by Cammisuli** [comment]
Good call! This was something that was never shown, but to keep it consistent with the other generators/schematics, this is something that can be fixed 😄

**Comment by sonikasharma1403** [comment]
Thank you for the quick fix

**Comment by Cammisuli** [comment]
Hopefully I'll have this released this week. There's some more things I need to test with some other features before I release it. And also, just as an FYI, only the description will show up because the title directly correlates to the cli command to be executed. So if you want the title to change, change the id property.
