### ISSUE TITLE
Dropdown list of declaring ng modules in wizard?

### ISSUE THREAD

**Issue by moniuch** [nrwl/nx-console#1231]
## Description

I was wondering if it were possible to have a better assistance with filling in the declaring ng module info

![image 2022-01-22 12-09-23](https://user-images.githubusercontent.com/681956/150636139-2913f4b3-2f67-4092-a4e8-fe77a0428e8f.png)

## Motivation

It is not clear from the interface what sort of expression the module input expects: is it path, class name (`AuthModule`), or file name (`auth.module`, `auth.module.ts`).

It would speed up the process, and also prevent user from typos.

## Suggested Implementation

I think a dropdown list with the module list would be fine.
The list, I guess, should be narrowed by the project, and include a blank item

**Comment by MaxKless** [comment]
Hey! We're looking to drop Angular CLI support in the not-too-far future, so I'm closing this issue. 
We've already added some 'magical' fields to provide better autocomplete in Nx Console. However, providing more framework-specific things here is not something we really think is a good fit right now.
