### ISSUE TITLE
...\schema.json does not exist

### ISSUE THREAD

**Issue by feidianbo** [nrwl/nx-console#1245]
Nx generate...

Select any action, then output panel (Nx Console) show:
file:\d:\Sources\demo\node_modules\@nestjs\schematics\dist\lib\application\schema.json does not exist
...
or
file:\d:\Sources\demo\node_modules\@nrwl\angular\src\generators\library\schema.json does not exist
...
How can I do?

**Comment by Cammisuli** [comment]
Can you try again with the latest version - (17.14.1), and report back?

**Comment by Cammisuli** [comment]
I'm fairly sure that this has been fixed as I didn't see any other issues reported. 

If it's still not fixed then please reply back here and I'll reopen and investigate more.
