### ISSUE TITLE
Running --parallel --parallel in the the nx console for test and e2e passes

### ISSUE THREAD

**Issue by yurisim** [nrwl/nx-console#1247]
## Current Behavior

Running a command like 
```
ng e2e waypoint-e2e --parallel --parallel
```

causes the operation to pass, whatever it is.

I expect it to fail.

**Comment by yurisim** [comment]
![image](https://user-images.githubusercontent.com/26447240/153478585-d044ad29-0862-47d5-9b0b-686eca8b2f0b.png)

![image](https://user-images.githubusercontent.com/26447240/153478643-e4dfedd9-2871-412a-bf70-584fac36df0d.png)

**Comment by Cammisuli** [comment]
hmm that's interesting. I wonder why the command showed up twice 🤔 

We'll look into this. Thank you for the report!
