### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by leaderiop** [nrwl/nx-console#1255]
- Issue Type: `Performance`
- Extension Name: `angular-console`
- Extension Version: `17.14.1`
- OS Version: `Linux x64 5.13.0-30-generic`
- VS Code version: `1.64.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///tmp/nrwl.angular-console-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Cammisuli** [comment]
Can you attach the cpuprofile, please?

**Comment by Cammisuli** [comment]
Well, I can't really help without the cpuprofile file. So I'm gonna have to close this. Please comment back or open a new issue if it's attached
