### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Musbell** [nrwl/nx-console#1257]
- Issue Type: `Performance`
- Extension Name: `angular-console`
- Extension Version: `17.14.1`
- OS Version: `Darwin x64 18.7.0`
- VS Code version: `1.58.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/r1/d4tmp2n96wbbhtwtxcc7d8dc0000gn/T/nrwl.angular-console-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Cammisuli** [comment]
Hey @Musbell, would it be possible to attach that cpuprofile file that was generated in the description?

If not, then I'm gonna have to close this in a week.

**Comment by Cammisuli** [comment]
Closing because there's nothing to investigate without the cpuprofile file :(
