### ISSUE TITLE
The Nx console UI is broken since the recent vs code update(1.66.1)

### ISSUE THREAD

**Issue by jangya** [nrwl/nx-console#1266]
## Current Behavior
The Nx console UI is broken since the recent vs code update(1.66.1).
<img width="400" alt="image" src="https://user-images.githubusercontent.com/7237378/162372528-3a936f9a-5958-4e20-b3e9-4bc75bbf7f4c.png">

## Expected Behavior
![image](https://user-images.githubusercontent.com/7237378/162373135-5b88dfb2-5d75-435e-ad4c-c92321f55621.png)

**Comment by Cammisuli** [comment]
Hey thanks for the report! 

Is the ui broken if you try a different workspace (for example this repo, or the nx examples repo)?

Can I also get your package.json dependencies and devDependencies?

**Comment by jangya** [comment]
Thanks, @Cammisuli for replying. Seems the issue is with my workspace only. Hence closing this ticket.
