### ISSUE TITLE
Better error reporting?

### ISSUE THREAD

**Issue by melMass** [nrwl/nx-console#1270]
This is both a feature request and a bug report I guess, but the focus is on providing better errors for users to debug their issues. I'll just use my current unsolved bug as a case.

## Description

When NX Console fails it suggests checking the console outputs.
Since I updated to 13.10 nx console is not working anymore, and I really have no idea what it could be.
I don't mind opening the hood when necessary, but it's very hard when you can't get the root cause.

This is what I got:

```ruby
Error loading Nx from the workspace. Falling back to extension dependency
local Nx dependency not found
    
Nx Console encountered an error when activating
Error: ENOENT: no such file or directory, stat '/Volumes/gits/mtb/node_modules/abortable-iterator'

```
I can't find any reference to this package, maybe some more context here would help.

## Motivation

Debugging simple issues on your own, as I said this is not a bug report, as soon as I finish writing this I will just clone the repo and run the extension locally to get the stack trace.

## Suggested Implementation

There a many ways to go about it when it comes to actually delivering meaningful informations and I guess maintainers/contributors would better know how to answer implementation details.

### Settings interface
```jsonc
// settings.json
{
    ...
    "nxConsole.loggingLevel": "verbose"; // 

}
```

```typescript
enum LoggingLevel {
  Never = "never",
  Default = "default",
  Verbose = "verbose"
}
```

**Comment by Cammisuli** [comment]
Hey thanks for the feature request! I understand when these issues come up they're very annoying. I was actually thinking of adding additional logging for every aspect of the extension, but I never got around to it. 

Hopefully we can get this in sooner rather than later because I think it's very valuable.

**Comment by melMass** [comment]
Do you have a rough release cycle ETA?

**Comment by Cammisuli** [comment]
I was planning on releasing sometime this week.

**Comment by melMass** [comment]
> I was planning on releasing sometime this week.

Yay I don't have the issue anymore!
To avoid having too much opened issue, can I close this one? Is there an issue relating to this or another way to "track" it?

**Comment by Cammisuli** [comment]
We have an internal board for prioritization and stuff, and I have this there. You're welcome to close this issue if you like. I still have the log levels support being tracked 😊
