### ISSUE TITLE
Add locally available plugin generators

### ISSUE THREAD

**Issue by spaceribs** [nrwl/nx-console#1271]
## Description

Now that <https://github.com/nrwl/nx/pull/9116> has been released, it would be an excellent enhancement for nx-console to be able to select locally available generators.

## Motivation

Ease of discoverability and alignment with the `nx` CLI.

## Suggested Implementation

When selecting "generate" from nx-console, the latest generators in all available local plugins should appear and be selectable. nx-console should also be able to detect when new plugins are initialized and present an updated list.

## Alternate Implementations

Unsure

**Comment by AgentEnder** [comment]
@Cammisuli Let's chat about this, there are some utility methods in 'nx/src/utils/nx-plugin' that you may be able to use to resolve the generators.

**Comment by Cammisuli** [comment]
I was actually working on this now 😅

I'll talk with you @AgentEnder sometime this week.
