### ISSUE TITLE
Add ability to exclude and/or include the list of generators available

### ISSUE THREAD

**Issue by rathpc** [nrwl/nx-console#1272]
## Description

Add the ability to exclude and/or include the list of generators available

## Motivation

Currently when opening the list of Generators, it simply shows any and every generator available to you. This is great for power users, but for orgs where maybe only the custom workspace-generators are needed, it would be nice to limit what is shown in that list to make it easier to target using the correct ones.

## Suggested Implementation

Add a configuration setting that can be passed a list of generators to explicitly show

## Alternate Implementations

Or in addition to that and/or instead of that, add a configuration setting where you can pass a list of generators to hide from that list.

**Comment by ZackDeRose** [comment]
@rathpc - interested in this. Is the issue that you don't see the generators you care about when you first open it up?

I'm wondering if we could start prioritizing generators in the list based on your recent usage.

**Comment by rathpc** [comment]
@ZackDeRose actually I see them, the issue is that I don't want to see them all. Basically only showing workspace-generators is my exact use case

**Comment by threehams** [comment]
I'm in the same boat here. Onboarding 50+ people will be a lot easier if there are 10 generators in the list. Currently, there are 41, and 31 of them aren't correct to use.

**Comment by szymdzum** [comment]
I just came to say exactly this :)

**Comment by rathpc** [comment]
@Cammisuli thank you for the work on this! Do you have an idea of what version this will be released under and a rough date?

**Comment by Cammisuli** [comment]
@rathpc hopefully by Friday, or early next week.
