### ISSUE TITLE
PNPX used when running generators

### ISSUE THREAD

**Issue by JakeGinnivan** [nrwl/nx-console#1278]
## Current Behavior

When using the console it runs `Executing task: pnpx nx generate` when using PNPM. For PNPM 6 it is recommended to run `pnpm exec` then pnpm 7 you can just run `pnpm nx`.

PNPX now installs dependencies globally instead of running cli tools in your project, this causes strange errors.

## Expected Behavior

`pnpm exec` should be used instead of `pnpx`

This issue has been fixed in NX, I think dependencies just need to be updated so it uses the latest package manager helper functions.

## Steps to Reproduce

Get dry run to execute in a project using PNPM. You should see dependencies being installed.

**Comment by Cammisuli** [comment]
Yea, you're right. I'm planning on updating the Nx Console dependencies soon, so that we can get the latest updates for this. Thanks for the heads up!
