### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ray-temtsen** [nrwl/nx-console#1279]
- Issue Type: `Performance`
- Extension Name: `angular-console`
- Extension Version: `17.16.0`
- OS Version: `Linux x64 5.13.0-40-generic`
- VS Code version: `1.66.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///tmp/nrwl.angular-console-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Cammisuli** [comment]
Can you upload the cpuprofile please?

**Comment by Cammisuli** [comment]
I have an idea where this might be coming from (at least from the attached cpuprofile)

I'll think of a solution to solve this as soon as I can.
