### ISSUE TITLE
ng run demo1:build should not use --prod 

### ISSUE THREAD

**Issue by doggy8088** [nrwl/nx-console#1281]
## Current Behavior

![image](https://user-images.githubusercontent.com/88981/167249957-e79be21a-212a-4ad4-8243-919817b2520f.png)

## Expected Behavior

I expected to produce this command:

```sh
ng run demo1:build -c=production 
```

## Steps to Reproduce

1. Create new project

    ```sh
    ng new demo1 --defaults
    code demo1
    ```

2. ng run

    ![image](https://user-images.githubusercontent.com/88981/167250053-a3be303a-2369-4762-a65a-2b489e371ea1.png)

3. Switch to `Production`. The Nx Console produce the wrong command

    ![image](https://user-images.githubusercontent.com/88981/167250090-8f62efcf-9681-4a39-9b01-fc8f3f5086f4.png)

4. Hit **Run**

    ![image](https://user-images.githubusercontent.com/88981/167250115-c9bef74e-08fe-49b4-bbe2-3fc0ef4b04f5.png)

### Failure Logs / Images / Videos

```log
> Executing task: npx ng run demo1:build --prod <

Unknown option: '--prod'
The terminal process "C:\WINDOWS\System32\cmd.exe /d /c npx ng run demo1:build --prod" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
```

### Environment

```log

   Node : 16.13.0
   OS   : win32 x64
   npm  : 8.1.0

   nx : 14.1.4
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : Not Found
   @nrwl/linter : Not Found
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : Not Found
   typescript : 4.6.4
   rxjs : 7.5.5
   ---------------------------------------
   Community plugins:
```

**Comment by Cammisuli** [comment]
sorry for the late response, and also thank you for the report! I'll get this taken care of asap.
