### ISSUE TITLE
Running tests via nx console does not load environment from .env files

### ISSUE THREAD

**Issue by janeklb** [nrwl/nx-console#1284]
## Current Behavior

When running tests via the cli (eg. `npm run nx test <project>`), the NX cli loads in all relevant `.env` files.
However this does not happen if you run a test using NX Console's VSCode integration.

## Expected Behavior

Running tests via NX Console loads in all relevant `.env` files (using the same [loading order](https://github.com/nrwl/nx/blob/d0ece6e1d2efdf3eb764776ef5271943919956e3/packages/nx/src/tasks-runner/forked-process-task-runner.ts#L339-L346) that's used in the `nx` cli)

## Steps to Reproduce

- create a test that depends on `process.env`
  ```ts
  it('should have env.VAR set correct', () => { expect(process.env.VAR).toEqual('HELLO'); });
  ```
- add an `.env.test` file with the desired value
  ```
  VAR=HELLO
  ```
- run test via the cli (`npm run nx test <project> -- --testFile <pathToTest>`)
  Result 👍 
- run test via NX Console
  Result 👎

**Comment by Cammisuli** [comment]
Does the test load environment variables when you run it through the built in vscode task launcher? https://code.visualstudio.com/Docs/editor/tasks

Nx Console uses the same internal mechanism as that, and if it doesn't work with the launch.json, then there's probably a vscode setting that needs to be changed. If it does work, then I'll investigate more.

**Comment by janeklb** [comment]
@Cammisuli thanks for having a look. I think you can close this issue - I got mixed up and now realise that the VSCode integration that I was using to launch _individual tests_ actually comes from the [Jest Runner](https://marketplace.visualstudio.com/items?itemName=firsttris.vscode-jest-runner) extension.

![image](https://user-images.githubusercontent.com/877396/169620904-c5905cc6-da7e-4e4c-bbda-62bcda3d6640.png)

Do you foresee this kind of functionality being offered by NX Console?

**Comment by janeklb** [comment]
In order to use Jest Runner w/ an NX codebase I've got the following setup now:

- a `jest.config.js` file with the following entry:
  ```ts
  {
     ...
     setupFilesAfterEnv: ['<rootDir>/jest.setup.ts']
   }
   ```
- a `jest.setup.ts` file that manually loads all the needed .env files (`.env.test` in this case) using [`dotenv`](https://www.npmjs.com/package/dotenv)
  ```ts
  import { config } from 'dotenv';
  if (!process.env['NX_INVOKED_BY_RUNNER']) {
    config({ path: __dirname + '/.env.test' });
  }
  ```

**Comment by Cammisuli** [comment]
Thanks for leaving a solution for others to find. I personally use the jest runner extension and having this knowledge around is good to have 👍🏼 

As for adding this feature to Nx Console, no. There was a time where I was planning on actually adding this very feature, but I didn't want to reinvent the wheel. So I decided to just fix the Jest implementation in Nx so that we can already use the extensions created by other tools.

**Comment by weilinzung** [comment]
In my case, it is not working on Github CI/CD, so I added `dotenv/config` which fixes the issue.

https://lusbuab.medium.com/using-dotenv-with-jest-7e735b34e55f

---

It is also able to load up `env.test` file when I have `env.local` as well.

```
// apps/xxx/jest.config.ts

  clearMocks: true,
  restoreMocks: true,
  setupFiles: ['dotenv/config'], => here

```
