### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by yongyiwong** [nrwl/nx-console#1285]
- Issue Type: `Bug`
- Extension Name: `angular-console`
- Extension Version: `17.16.0`
- OS Version: `Linux x64 5.13.0-41-generic`
- VS Code version: `1.67.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Cammisuli** [comment]
Can you give the data that was in the clipboard or something similar so that I can have more info?
