### ISSUE TITLE
VS-code failed to suggest for nx lib import after update nx-console

### ISSUE THREAD

**Issue by daveksb** [nrwl/nx-console#1297]
After updating nx-console to V.17.18.4 or V.17.18.3 
VS-code quick fixes will fail to load nx lib path

## Current Behavior
It show nothing when running VS-code quick fixes by press CTRL + >
![image](https://user-images.githubusercontent.com/15795314/174747968-2812d522-4e91-4b39-9132-e4624677a5b9.png)

## Expected Behavior
It should show the correct lib path as a suggestion
![image](https://user-images.githubusercontent.com/15795314/174745824-c6cc865f-e911-4882-8069-072174194796.png)

**Comment by Cammisuli** [comment]
Thanks for the report! I'll take a peek as soon as I can.
