### ISSUE TITLE
add option to name the Entity interface

### ISSUE THREAD

**Issue by nhhockeyplayer** [nrwl/nx-console#1298]
SUBJECT: add option to name the Entity interface

## Description

an option ( or better yet automate it silently) to name the Entity interface specific to the name of the store

## Motivation

its preventing fluid coding after adding multiple NgRX state/stores...developer has to backpedal and rename interfaces to keep them unique from colliding

all are generated with name Entity 
when if you create an spinner ngrx store, it should be called SpinnerEntity (if I am wrong please advise)

Example... this is what gets generated after

`nx g @nrwl/angular:ngrx spinner --module=libs/shared/root/data-access/src/lib/shared-root-data-access.module.ts --directory +state/spinner --facade  --syntax=classes --no-interactive`

```
/**
 * Interface for the 'Spinner' data used in
 *  - SpinnerState, and the reducer function
 *
 *  Note: replace if already defined in another module
 */
export interface Entity {
    id: string;
    name: string;
}
```

The fact that there is a note in the generated code means someone knows about this
But it should be automated not left to user to instrument and mangle... everything else is generated why not this?

Now if I add stores for APP, AUTH, USER and so on within same module they all collide because each store has Entity for its interface

Be nice to see this automated without having an option would be best way

this should have been automated from get go

Thanks for an awesome elite product

```
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : darwin x64
   yarn : 1.22.18
   
   nx : 14.3.6
   @nrwl/angular : 14.3.6
   @nrwl/cypress : 14.3.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.6
   @nrwl/eslint-plugin-nx : 14.3.6
   @nrwl/express : 14.3.6
   @nrwl/jest : 14.3.6
   @nrwl/js : 14.3.6
   @nrwl/linter : 14.3.6
   @nrwl/nest : 14.3.6
   @nrwl/next : Not Found
   @nrwl/node : 14.3.6
   @nrwl/nx-cloud : 14.1.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : 8.12.11
   @nrwl/storybook : 14.3.6
   @nrwl/web : 14.3.6
   @nrwl/workspace : 14.3.6
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
   	 @fortawesome/angular-fontawesome: 0.11.1
   	 @ionic/angular: 6.1.10
   	 @ngrx/component-store: 14.0.0
   	 @ngrx/effects: 14.0.0
   	 @ngrx/entity: 14.0.0
   	 @ngrx/router-store: 14.0.0
   	 @ngrx/store: 14.0.0
   	 @nxtend/capacitor: 13.0.0
   	 @nxtend/ionic-angular: 13.1.0
   	 @storybook/angular: 6.5.9
   	 angular-builder-custom-terser-options: 1.0.1
   	 @ngrx/schematics: 14.0.0
   	 @ngrx/store-devtools: 14.0.0
   	 @nxpm/stack: 4.21.0
   	 @nxtend/capacitor: 13.0.0
   	 @storybook/angular: 6.5.9
```

**Comment by AgentEnder** [comment]
This functionality is on the generator's side, not on Nx console. Can you inline these details in the issue on the NX repo? I'm going to close this out since no changes would be needed for console.
