### ISSUE TITLE
There seems to be a problem this watching too many files on windows WSL

### ISSUE THREAD

**Issue by richtera** [nrwl/nx-console#1301]
## Current Behavior

With the extension enabled I have about 470k notify records.
With the extension off I only have about 2k

## Expected Behavior

The extension should really only monitor files it absolutely needs to know changes for.

## Steps to Reproduce

Install extension on wsl visual studio code with a rather large repo and use 
https://gist.github.com/richtera/f6c228d0a28f69a213aa7afc38a1c98d
this script to list out notify record counts.

### Failure Logs / Images / Videos

This causes thousands of errors when trying to listen for new files during debugging because the max limit is about 524k or something like that. When repos are small then there are not 470k files, of course, but under normal circumstances even tsserver only monitors a couple of thousand files and not all of "node_modules" for example.

### Environment

Windows 11 WSL2 Ubuntu

**Comment by richtera** [comment]
Ref https://github.com/microsoft/vscode/issues/153731

**Comment by Cammisuli** [comment]
hmm interesting.. I know I recently added code to watch for package.json files, but I would've thought that VSCode wouldn't go into .gitignore folders. Thanks for the script to check the notifiers. I'll take a look as soon as I can.

**Comment by richtera** [comment]
Works thank you. I now see:
```sh
    1244         1     21253 andy        /home/andy/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/node /home/andy/.vscode-server/bin/30d9c6cd9483b2cc586687
```
1244 <<< 470104!!!!
Thank you
