### ISSUE TITLE
Upgrading to Angular 14 causes Unknown arguments: inlineStyle, inlineTemplate

### ISSUE THREAD

**Issue by ianvink** [nrwl/nx-console#1302]
## Current Behavior
When using the Generate Component option with inline style and template checkboxes checked the CLI errors out:

     Unknown arguments: inlineStyle, inlineTemplate
 
 
### Environment

		"@angular-devkit/build-angular": "^14.0.4",
		"@angular-eslint/builder": "^14.0.0",
		"@angular-eslint/eslint-plugin": "^14.0.0",
		"@angular-eslint/eslint-plugin-template": "^14.0.0",
		"@angular-eslint/schematics": "^14.0.0",
		"@angular-eslint/template-parser": "^14.0.0",
		"@angular/cli": "^14.0.4",
		"@angular/compiler-cli": "^14.0.4",

**Comment by Cammisuli** [comment]
If you restart vscode, is the error still reproducible?

There's some caching done when initially loading the workspace and if the upgrade happened while vscode was still opened, then we probably still have the old schema loaded.

**Comment by ianvink** [comment]
yes, what folders do i delete to clear the cache?

**Comment by Cammisuli** [comment]
There's no folders, it's in memory cache. That's why restarting clears it. 

If it didn't work after restarting vscode, I'll take a look today to see if I can reproduce it.

**Comment by Cammisuli** [comment]
I can't seem to reproduce it...
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/4332460/177153025-c63cf31a-6faa-4e28-8cfc-fd8f9f7005a5.png">


Delete your node_modules, reinstall the deps and try again

**Comment by ianvink** [comment]
On Windows 11 I can reproduce it. I uninstalled the wonderful nx-console, removed node_modules, rebooted, then reinstalled everything and it's unfortunately still using the old --inlineTemplate
![image](https://user-images.githubusercontent.com/112916/177187913-0d87b8ff-f222-427b-9103-047c330f491a.png)

**Comment by ianvink** [comment]
![image](https://user-images.githubusercontent.com/112916/177188103-bc48e74c-970e-4148-b034-ce6bfc554632.png)

**Comment by ianvink** [comment]
I believe the new CLI command is --inline-template instead of --inlineTemplate

Thank you for all your helpful work on this amazing project. Much appreciated.

**Comment by Cammisuli** [comment]
Weird.. I'm not sure where your `inline-template` is coming from. From the angular source, it shows as `inlineTemplate` and `inlineStyles`
https://github.com/angular/angular-cli/blob/87c7f4cbc89cb27cd975aadac442440a6fe61f84/packages/schematics/angular/component/schema.json#L40-L52

Do you happen to have angular cli installed globally? And if it is, is it the same version as your local workspace one?

**Comment by ianvink** [comment]
Projects based on Angular 13 work, but give this warning:

**Support for camel case arguments has been deprecated and will be removed in a future major version.
Use '--inline-style' instead of '--inlineStyle'.**

When I update them to 14 via ng update, then --inlineStyle eg no longer work

**Comment by Cammisuli** [comment]
Can you provide a reproduction in a repo I can clone? 

Nx Console reads the schema.json files in the node_modules folder. If you look into `node_modules/@schematics/angular/component/schema.json` does it show inlineTemplate or inline-template?

**Comment by ianvink** [comment]
Very strange. It shows:

    "inlineTemplate": {
      "description": "Include template inline in the component.ts file. By default, an external template file is created and referenced in the component.ts file.",
      "type": "boolean",
      "default": false,
      "alias": "t",
      "x-user-analytics": 10
    },

But the CLI's Generate command says that is deprecated now in 14.

Support for camel case arguments has been deprecated and will be removed in a future major version.
Use '--inline-style' instead of '--inlineStyle'.

**Comment by Cammisuli** [comment]
That's where we get the information from.. 🤔 

Is your angular cli installed globally?

**Comment by ianvink** [comment]
Yes, 14.0.4 everywhere
