### ISSUE TITLE
add proxy config to nx serve

### ISSUE THREAD

**Issue by ecohanim** [nrwl/nx-console#1307]
## Description

nx serve project --proxy=proxy.conf.json
the user will supply a ready made proxy.conf.json

## Motivation

currently there is no way to serve a project with proxy

## Suggested Implementation

add proxy config to the serve ability

## Alternate Implementations

just another serve config option

**Comment by ecohanim** [comment]
yes i have multiple proxy files that i use

**Comment by Cammisuli** [comment]
Ok sounds good. In the mean time, try setting up multiple configurations and running those.

**Comment by MaxKless** [comment]
@Cammisuli am I somehow missing how this issue is related to Nx Console? 
Cause I'd close it otherwise.

**Comment by MaxKless** [comment]
To me it looks like providing a `proxyConfig` is possible through Nx Console: 
<img width="721" alt="image" src="https://user-images.githubusercontent.com/34165455/219002404-ea44356c-d9d4-4bb1-ba82-7bb0e3e75a7a.png">

Feel free to provide more info on the excecutors, nx console & vscode version you're running into issues with. If this is still a problem for you, I will gladly have a look!
