### ISSUE TITLE
add ability to save run target configuration

### ISSUE THREAD

**Issue by ecohanim** [nrwl/nx-console#1308]
## Description

most times when i run tests i use --silent and --skip-nx-cache
i would like to have an option to save/delete constant config for run target
meaning if saved, "nx test project" will always use --silent --skip-nx-cache as the example above

## Motivation

no need to do such config multiple times if you always use those options

## Suggested Implementation

add save/delete and return to default config option to every run target

**Comment by Cammisuli** [comment]
Closing as it's the same as #144, but sorry, I don't have an eta for that yet 😞
