### ISSUE TITLE
Allow for ordering of schema.json generated UI fields in Generate Form.

### ISSUE THREAD

**Issue by spencer-easton-ait** [nrwl/nx-console#1310]
## Description
I would like to order the UI generated fields of my generator's schema.json. 

## Motivation
When the schema is rendered fields that logically are grouped together are rendered on different parts of the form.

## Suggested Implementation
I would add a tabOrder field that is used only when rending the fields in the UI

```
 "clientProject":{ 
       "tabOrder":"2",        
       "type":"string", 
       "$default":{ 
        "$source":"projectName" 
       }  
    }, 
 "generateClientProject":{ 
      "tabOrder":"3" 
      "type":"boolean", 
      "description": "Create a new Angular App. Will supersede selected clientProject", 
      "default":false 
    },
```

When this gets rendered these two fields would be next to each other, ordered by the tab order.

**Comment by Cammisuli** [comment]
Today, we sort the fields by argument position, required, some high priority items, then alphabetically. Having this configurable would be helpful, but I have to think of when to apply that sort. 

For reference, here's the sort:
https://github.com/nrwl/nx-console/blob/ebcd21767e2eaab1cf2cd216303d2578b22890ac/libs/server/src/lib/utils/utils.ts#L221-L250

**Comment by MaxKless** [comment]
Once https://github.com/nrwl/nx-console/pull/1528 gets merged, there's a new way of sorting that corresponds to how `--help` and nx.dev do it. 
This might not always be grouped by related fields but by importance. 
I think adding custom grouping functionalities to break this behaviour here wouldn't be a good idea.
