### ISSUE TITLE
NX Console extension breaks intellisense in VS Code

### ISSUE THREAD

**Issue by mwvalen** [nrwl/nx-console#1312]
## Current Behavior
NX Console extension is breaking VS Code intellisense

## Expected Behavior
NX Console extension should not break VS Code Intellisense

## Steps to Reproduce
Install NS Console extension in VS Code. Attempt to import something using intellisense's import suggestions.

## NX Report
Node : 16.13.1
OS   : darwin arm64
npm  : 8.3.0

nx : 13.10.6
@nrwl/angular : Not Found
@nrwl/cypress : 13.4.3
@nrwl/detox : Not Found
@nrwl/devkit : 13.4.3
@nrwl/eslint-plugin-nx : 13.4.3
@nrwl/express : 13.4.3
@nrwl/jest : 13.4.3
@nrwl/js : 13.4.3
@nrwl/linter : 13.4.3
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : 13.4.3
@nrwl/nx-cloud : Not Found
@nrwl/nx-plugin : Not Found
@nrwl/react : 13.10.6
@nrwl/react-native : Not Found
@nrwl/schematics : Not Found
@nrwl/storybook : 13.10.6
@nrwl/web : 13.4.3
@nrwl/workspace : 13.4.3
typescript : 4.4.4
rxjs : 6.6.7
---------------------------------------
Community plugins:

**Comment by AgentEnder** [comment]
I went ahead and moved this to console as part of issue triage

**Comment by Cammisuli** [comment]
Those characters shouldn't really affect intellisence... they're basically white space characters to get nice spacing within the settings window. 

The settings and intellisense are two completely different systems. 

But to just make sure, if you install a previous version of nx console do you still experience the issue?

**Comment by AgentEnder** [comment]
Hey @mwvalen, it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate {v}`, where `v` is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.

**Comment by mwvalen** [comment]
Update on this - migrated to latest nx version. Still not getting imports.

Tried an older version and played around a bit more, discovered the following:

- Latest version of NX console: No auto-import anywhere
- Old version of NX console: Auto-import within a project only
- No NX console: Auto-import within a project only

**Comment by mwvalen** [comment]
FYI this plugin is working for me, when I set a glob for scanning files to include in autoImport suggestions: https://marketplace.visualstudio.com/items?itemName=steoates.autoimport

**Comment by Cammisuli** [comment]
@mwvalen is this setting on for you?
<img width="973" alt="image" src="https://user-images.githubusercontent.com/4332460/181841847-8e5707d1-7142-4dcb-b9ef-7c3f7d081036.png">


And if it is, can you turn on TypeScript verbose logging in the settings:
<img width="917" alt="image" src="https://user-images.githubusercontent.com/4332460/181841975-55400e94-26ec-4bb0-86c8-d4d68716589b.png">

Then open the log file through the command palette:
<img width="965" alt="image" src="https://user-images.githubusercontent.com/4332460/181842110-19b0e378-9917-4339-8eb2-476036a1642e.png">

Then try to find entries that have `NX Imports Plugin`. Do you see anything similar to this log?
```
Info 259  [16:57:55.157] NX Imports Plugin: updating project: /Users/jon/Dev/nx-examples/libs/cart/cart-page/tsconfig.lib.json
Info 260  [16:57:55.157] NX Imports Plugin: get root files: {"externalFiles":[{"mainFile":"/Users/jon/Dev/nx-examples/libs/cart/cart-page/src/index.ts","directory":"/Users/jon/Dev/nx-examples/libs/cart/cart-page"},{"mainFile":"/Users/jon/Dev/nx-examples/libs/products/home-page/src/index.ts","directory":"/Users/jon/Dev/nx-examples/libs/products/home-page"},{"mainFile":"/Users/jon/Dev/nx-examples/libs/products/product-detail-page/src/index.ts","directory":"/Users/jon/Dev/nx-examples/libs/products/product-detail-page"},{"mainFile":"/Users/jon/Dev/nx-examples/libs/shared/cart/state/src/index.ts","directory":"/Users/jon/Dev/nx-examples/libs/shared/cart/state"},{"mainFile":"/Users/jon/Dev/nx-examples/libs/shared/cart/state/src/react.ts","directory":"/Users/jon/Dev/nx-examples/libs/shared/cart/state"},{"mainFile":"/Users/jon/Dev/nx-examples/libs/shared/e2e-utils/src/index.ts","directory":"/Users/jon/Dev/nx-examples/libs/shared/e2e-utils"},{"mainFile":"/Users/jon/Dev/nx-examples/libs/shared/header/src/index.ts","directory":"/Users/jon/Dev/nx-examples/libs/shared/header"},{"mainFile":"/Users/jon/Dev/nx-examples/libs/shared/jsxify/src/index.ts","directory":"/Users/jon/Dev/nx-examples/libs/shared/jsxify"},{"mainFile":"/Users/jon/Dev/nx-examples/libs/shared/product/data/src/index.ts","directory":"/Users/jon/Dev/nx-examples/libs/shared/product/data"},{"mainFile":"/Users/jon/Dev/nx-examples/libs/shared/product/data/src/testing.ts","directory":"/Users/jon/Dev/nx-examples/libs/shared/product/data"},{"mainFile":"/Users/jon/Dev/nx-examples/libs/shared/product/state/src/index.ts","directory":"/Users/jon/Dev/nx-examples/libs/shared/product/state"},{"mainFile":"/Users/jon/Dev/nx-examples/libs/shared/product/state/src/react.ts","directory":"/Users/jon/Dev/nx-examples/libs/shared/product/state"},{"mainFile":"/Users/jon/Dev/nx-examples/libs/shared/product/types/src/index.ts","directory":"/Users/jon/Dev/nx-examples/libs/shared/product/types"},{"mainFile":"/Users/jon/Dev/nx-examples/libs/shared/product/ui/src/index.ts","directory":"/Users/jon/Dev/nx-examples/libs/shared/product/ui"}]}
```

**Comment by Cammisuli** [comment]
I haven't been able to reproduce this, and I haven't heard anything back.
