### ISSUE TITLE
Nx generate in VS code not reflecting defaults in nx.json file

### ISSUE THREAD

**Issue by craigsh** [nrwl/nx-console#1313]
## Current Behavior
In my nx,json file, under the generators key, I have the following defaults set:

		"@nrwl/angular:component": {
			"style": "scss",
			"standalone": true,
			"inlineTemplate": true,
			"inlineStyle": true,
			"flat": true,
			"displayBlock": "true",
			"changeDetection": "OnPush"
		}

When I run Nx generate, the UI doesn't reflect all the defaults set above, though some of them are present. 

For example, change-detection shows as Default, not OnPush, and the inline-style and inline-template remain unchecked.

This is *only an issue with the UI* - actually generating the component uses the defaults set in the nx.json file. But it is confusing.

## Expected Behavior

The Nx Generate UI should reflect the defaults set in the nx.json file.

## Steps to Reproduce

I have reproduced this on a completely new workspace. i.e. npx create-nx-workspace, then npx nx migrate latest (@nrwl/workspace at 14.5.1)

Paste defaults for the generator into nx.json

Run Nx Generate in VS code.

I have tried restarting VS Code, but the problem remains.

### Failure Logs
None

### Environment

  NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : win32 x64
   npm  : 8.5.0

   nx : 14.5.1
   @nrwl/angular : 14.5.1
   @nrwl/cypress : 14.5.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.1
   @nrwl/eslint-plugin-nx : 14.5.1
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.1
   @nrwl/js : 14.5.1
   @nrwl/linter : 14.5.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.1
   @nrwl/web : 14.5.1
   @nrwl/workspace : 14.5.1
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:

**Comment by Cammisuli** [comment]
Do you happen to be using a angular.json or a workspace.json file?

**Comment by craigsh** [comment]
I have an angular.json file, no workspace.json file.

Generated from a completely new create-nx-workspace command:

{
  "version": 2,
  "projects": {
    "my-app": "apps/my-app",
    "my-app-e2e": "apps/my-app-e2e"
  }
}

**Comment by LuukMoret** [comment]
What I noticed for me using nx.json was that `"standAloneConfig": true` wasn't working but `"standalone-config": true` was. Try to use hyphen case instead of camelCase and see if that works.

**Comment by craigsh** [comment]
@LuukMoret ah, that's interesting. That does work for me.

Something has changed though - as the defaults used to work and be propagated into the fields in the Nx Console generate UI.

And certainly, the naming style for all other entries in nx.json is to use camelCase, including the defaults that get set up for a completely new nx workspace. e.g.:

```
"generators": {
    "@nrwl/angular:application": {
      "style": "scss",
      "linter": "eslint",
      "unitTestRunner": "jest",
      "e2eTestRunner": "cypress"
    },
    "@nrwl/angular:library": {
      "linter": "eslint",
      "unitTestRunner": "jest"
    },
```

**Comment by craigsh** [comment]
I just checked using generate for @nrwl/angular:application and the defaults listed above get propagated to the UI. So, maybe it's just a problem with the @nrwl/angular:component schematic?

**Comment by Cammisuli** [comment]
I know what's happening. There's a check seeing if the workspace has a angular.json file, and if it does, it makes all the arguments hyphenated. 

I know where to fix it 🙂

**Comment by craigsh** [comment]
Ah, great. Look forward to the fix!
