### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by myhaylo0000** [nrwl/nx-console#1318]
- Issue Type: `Performance`
- Extension Name: `angular-console`
- Extension Version: `17.19.1`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.70.0`
[nrwl.angular-console-unresponsive.cpuprofile.txt](https://github.com/nrwl/nx-console/files/9279796/nrwl.angular-console-unresponsive.cpuprofile.txt)

**Comment by Cammisuli** [comment]
Do you happen to be using WSL?

**Comment by myhaylo0000** [comment]
Hi.
No.

пт, 12 авг. 2022 г., 6:39 PM Jonathan Cammisuli ***@***.***>:

**Comment by Cammisuli** [comment]
Ok. The report is showing that requiring a package was taking too much time. I'm going to have to think about this because i dont know how to require something faster since it's using Node's require function. 🤔
