### ISSUE TITLE
Projects view adds node_modules packages as projects

### ISSUE THREAD

**Issue by angelfraga** [nrwl/nx-console#1320]
Hi first of all thanks for the extension and all the nx ecosystem 🚀.

I ve observe that in an angular < 13 with angular.json adds npm packages as projects

Version: 1.70.0 (Universal)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:55.829Z (5 days ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.3.0
Nx Console Version: 17.19.1 

![image](https://user-images.githubusercontent.com/11693938/183645603-df452784-c57d-43c7-baae-cb90fdd3ba9b.png)

After research a little bit I think the problem is here.

https://github.com/nrwl/nx-console/blob/b9bcbc9fe04c99a0a70d305552d41d61a9839dbe/libs/vscode/nx-workspace/src/lib/get-nx-workspace-config.ts#L65

After that commit 
https://github.com/nrwl/nx-console/commit/f8d32caf3224125228b6d677cd0271b80074e190

I've tested it locally debugging the extension pointing to my repo.  
If I use the previous method `readCurrentProjectGraph` everything works fine.

Actually the workaround is using nx-console v17.18.7

**Comment by Cammisuli** [comment]
Do you have a repo I can use and check? If not, then can you give me the report from `nx report`?

The `createProjectGraph` is from the core nx package, so if there's something that's broken in that package, we'll have to create a new issue on the main nx repo. 

But let's see what we can do first with the report, or a repro repo.

**Comment by angelfraga** [comment]
I do not have pushed it, yet but it is easy to reproduce it, running `npx create-nx-workspace@12` then choose angular.
Then install Nx console > v17.18.7
