### ISSUE TITLE
Improve NX Graph relations visibility in vscode tab

### ISSUE THREAD

**Issue by angelfraga** [nrwl/nx-console#1323]
## Description

When using dark theme and we open the NX Graph the relations arrows are hard to indentify.

## Motivation

Improve the experience in vscode dark themes.

## Suggested Implementation

Adding always a light/white background to the NX Graph tab.

**Comment by Cammisuli** [comment]
This one is a bit tricky. The graph is made in a canvas so it's not easy to change the colors there. We have to build in support into the actual graph (which is coming in an upcoming Nx release)

The graph naturally supports dark/light mode based on your systems setting. 

So if you change your OS to be dark the graph will change the nodes and the lines to be lighter. 

I know it's not the best solution as we would like to have the graph change colors better with your vscode theme, but that's what we can do today if you're having issues with the lines.

**Comment by angelfraga** [comment]
Thanks for quick answer

I've tried switching the system default theme, but it stills in light theme. I did also removed the nx cache located under node_modules and restarting vscode without success.

I am running in macOS Monterey version 12.2.1.

I guess there is an issue in somewhere when watching the media theme changes.

**Comment by angelfraga** [comment]
@Cammisuli maybe we can detect the vscode dark theme and apply `filter: invert(1);`  to the `graph-container`

**Comment by Cammisuli** [comment]
Oh. What version of Nx are you running? That looks like an older version

**Comment by Cammisuli** [comment]
For reference this is how the newer graph looks like:
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/4332460/184131010-f3f01c08-8cda-4406-9fa8-acb219c755c6.png">

**Comment by angelfraga** [comment]
That look much better than mine :D 

I see that is reason, the project nx workspace version is not up to date (12.8.0). 
It will be solved once we upgrade it.

I close the issue. Thanks for the support.
