### ISSUE TITLE
Option to run project tasks by skipping Nx cache 

### ISSUE THREAD

**Issue by dzhavat** [nrwl/nx-console#1325]
## Description

Having the "Execute task" icon for each project task (under "Projects") is super useful. 

Unfortunately making changes to a project and running a task sometimes results in getting a cached output when what I really wanted was a complete run. I've noticed that it happens with minor changes (e.g. changing a variable from `true` to `false`) and running a task quickly afterwards. In such cases I simply copy the command and run it with `--skip-nx-cache` flag. 

![image](https://user-images.githubusercontent.com/1096332/185403002-d6c7642b-20e6-496e-9af8-994341ed223a.png)

## Motivation

Having this option will save time in manual typing.

**Comment by Cammisuli** [comment]
Hey, thanks for the feature request! This is definitely something I've been thinking about as it annoyed me as well. But I have to think of a way to actually configure this. We need to be able to support the way it always was, and an option to `skip-nx-cache` without having to add a new button here.

It's something to ponder about 🤔

**Comment by dzhavat** [comment]
I think it's a fine.

There are a couple of things:
-  Discoverability - the list of tasks already includes two icons shown on hover ("Edit workspace definition" and "Execute task"). Having a context menu on right click might make the functionality harder to discover. 
- UX - I don't know Nx Console that well but it looks like a context menu here will be the first time such functionality is added to the panel. Doesn't look like one can right click on other things. 

Looking from my perspective, both of those points are for Nx to consider, so the solution is fine with you, it's fine with me too :)

**Comment by MaxKless** [comment]
I think we will soon shift to adding some more context menu options to the projects view anyways so this would be in line with that.

We definitely have to balance discoverability with clutter. I agree that having a button makes it easier to discover but having 10 buttons for all kinds of functionality also wouldn't be good UX.

**Comment by dzhavat** [comment]
Agree that adding a button for every little thing doesn't make sense. So I'll be more than happy with a context menu instead :)

**Comment by MaxKless** [comment]
Let me know if you're willing to contribute and I can point you in the right direction. It shouldn't be a very complicated feature.

**Comment by dzhavat** [comment]
That would be great. I have a bit of experience building VS Code extensions, so let's try it :)

**Comment by MaxKless** [comment]
Ok so you will find the code relating to the projects view in `libs/vscode/nx-project-view`.

You will need to register a command similar to `nxConsole.runTask` in `apps/vscode/src/package.json` and register the command as a context menu. [Related docs here.](https://code.visualstudio.com/api/references/contribution-points#contributes.menus)

Then you need to make the functionality similar to the `runTask` function in `nx-project-tree-provider.ts` only with the `--skip-nx-cache` flag.

Lmk if you have more questions!

**Comment by dzhavat** [comment]
Thanks for the detailed guidelines. I'll give it a shot and let you know how it goes.

**Comment by dzhavat** [comment]
I've made a bit of progress. It appears like this on Windows on right click.

![image](https://user-images.githubusercontent.com/1096332/207985892-d4e7f3c2-9436-41a2-99e2-8a104c7b9aab.png)

Do you have a suggestion about the wording of the command?

**Comment by MaxKless** [comment]
I think it could be shorter: `Execute task without Nx cache` seems more natural to me. What do you think?

**Comment by dzhavat** [comment]
@MaxKless a PR is now ready for review 🙂
