### ISSUE TITLE
Constant failures 'Request textDocument/documentLink failed'

### ISSUE THREAD

**Issue by cutterbl** [nrwl/nx-console#1359]
This morning I am getting the following error over and over while working in my repository, even after uninstalling NX Console. This was not occurring over the past week, beginning just this morning, even after uninstall and restarts.

> Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed unexpectedly without providing any details.
  Code: -32603 

### Failure Logs / Images / Videos

```
Unable to get Nx info: Unable to determine workspace path
[Error - 8:20:48 AM] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed unexpectedly without providing any details.
  Code: -32603 
[Error - 8:46:29 AM] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed unexpectedly without providing any details.
  Code: -32603 
[Error - 9:18:35 AM] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed unexpectedly without providing any details.
  Code: -32603 
[Error - 9:18:54 AM] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed unexpectedly without providing any details.
  Code: -32603 
```

### Environment

Mac OSX Monterey v12.6
VS Code 1.71.2
NX Console v17.23.0

**Comment by MaddMugsy** [comment]
Same issue here, only on Windows 10.  Same versions of VS Code and NX Console.

**Comment by Cammisuli** [comment]
Were these errors happening in a vscode workspace that wasnt a Nx project?

**Comment by Cammisuli** [comment]
Ah ya, it was. I found the issue. I'm going to fix it asap
