### ISSUE TITLE
Cannot run most Nx commands (since update ?)

### ISSUE THREAD

**Issue by remi2257** [nrwl/nx-console#1377]
Hi guys, I've been using Nx console for few months and the run & generate functions stopped to work.

## Current Behavior
I'm using VSCode 1.71 with the last version of NxConsole (17.23.2)

Nx generate & run are opening new tabs in which
- I can type in inputs
- But no dry run happens 
- Nothing happen when I pressed **Run** button
- I have nothing in the debug console

## Expected Behavior

- Generate Angular Components, Nest Controller ...

## Steps to Reproduce

I tried on multiple repo including _nx-examples_, and the behavior is still the same

### Failure Logs / Images / Videos

Sorry guys, I literally don't have anything else ... 

I tried to reinstall node-modules, disable all other extension, but nothing changes !

![image](https://user-images.githubusercontent.com/39727257/193669235-bc4e7ddf-2668-4538-8bdb-0db5db33222a.png)

### Environment

Report
```
  Node : 16.17.0
   OS   : linux x64
   yarn : 1.22.19
   
   nx : 14.8.2
   @nrwl/angular : 14.8.2
   @nrwl/cypress : 14.8.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.2
   @nrwl/js : 14.8.2
   @nrwl/linter : 14.8.2
   @nrwl/nest : 14.8.2
   @nrwl/next : Not Found
   @nrwl/node : 14.8.2
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.2
   @nrwl/web : Not Found
   @nrwl/webpack : 14.8.2
   @nrwl/workspace : 14.8.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @storybook/angular: 6.5.12
```

Dependencies
```
  "dependencies": {
    "@angular/animations": "~14.2.0",
    "@angular/cdk": "^14.2.2",
    "@angular/common": "~14.2.0",
    "@angular/compiler": "~14.2.0",
    "@angular/core": "~14.2.0",
    "@angular/forms": "~14.2.0",
    "@angular/material": "^14.2.2",
    "@angular/platform-browser": "~14.2.0",
    "@angular/platform-browser-dynamic": "~14.2.0",
    "@angular/router": "~14.2.0",
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/typeorm": "^9.0.1",
    "@nrwl/angular": "14.8.2",
    "class-validator": "^0.13.2",
    "mysql2": "^2.3.3",
    "pg": "^8.8.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "typeorm": "^0.3.9",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~14.2.0",
    "@angular-eslint/eslint-plugin": "14.0.4",
    "@angular-eslint/eslint-plugin-template": "14.0.4",
    "@angular-eslint/template-parser": "14.0.4",
    "@angular/cli": "~14.2.0",
    "@angular/compiler-cli": "~14.2.0",
    "@angular/language-service": "~14.2.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@nrwl/cli": "14.8.2",
    "@nrwl/cypress": "14.8.2",
    "@nrwl/eslint-plugin-nx": "14.8.2",
    "@nrwl/jest": "14.8.2",
    "@nrwl/linter": "14.8.2",
    "@nrwl/nest": "14.8.2",
    "@nrwl/node": "14.8.2",
    "@nrwl/storybook": "14.8.2",
    "@nrwl/workspace": "14.8.2",
    "@storybook/addon-essentials": "~6.5.9",
    "@storybook/angular": "~6.5.9",
    "@storybook/builder-webpack5": "~6.5.9",
    "@storybook/core-server": "~6.5.9",
    "@storybook/manager-webpack5": "~6.5.9",
    "@types/jest": "28.1.1",
    "@types/node": "16.11.7",
    "@typescript-eslint/eslint-plugin": "5.39.0",
    "@typescript-eslint/parser": "5.39.0",
    "class-transformer": "^0.5.1",
    "cypress": "^10.7.0",
    "eslint": "~8.15.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-prettier": "^4.2.1",
    "husky": "^8.0.0",
    "jest": "28.1.1",
    "jest-environment-jsdom": "28.1.1",
    "jest-preset-angular": "12.2.2",
    "nx": "14.8.2",
    "prettier": "^2.7.1",
    "stylelint": "^14.11.0",
    "stylelint-config-standard-scss": "^5.0.0",
    "stylelint-order": "^5.0.0",
    "ts-jest": "28.0.5",
    "ts-node": "10.9.1",
    "typescript": "4.8.4",
    "webpack": "^5.64.0"
  },
  "volta": {
    "node": "16.17.0",
    "yarn": "1.22.19"
  }
```

**Comment by remi2257** [comment]
I went back to version **17.19.1**, and it's now working again !
Nevertheless, I am still here to help finding the bug !

**Comment by Cammisuli** [comment]
Hmm interesting... I just gave it a shot and it appears to be working for me, although I am using MacOS. I'll have to install a linux distro and give it a shot there. Are you using Ubuntu or something else?

**Comment by remi2257** [comment]
Hey :)

Yep, I am on Ubuntu 20 (with ZSH as shell) ! And I checked : the extension is working on my Windows 10

**Comment by Cammisuli** [comment]
I gave this a shot with Ubuntu 22 and things appear to work there. I couldnt install Ubuntu 20, to check out. But I dont think there would be anything too different between the two versions. 

At first I saw the issue you mentioned, but then I gave the VM more resources and things worked. 🤷🏼‍♂️ 

So something isnt consistent with what I have and what you have. Can you think of anything else with your setup that could potentially cause issues?

**Comment by remi2257** [comment]
Nope, sadly, I have no idea.
Maybe I can give more log to help us finding the issue ? If not, let's close the issue, and I will buy a new computer :p

**Comment by devinshoemaker** [comment]
I'm actually experiencing something similar right after updating VS Code. I'm pretty bad about restarting the app (and my computer) and finally updated and now no generate or run commands seem to do anything. FWIW I'm on macOS 12.6. When running commands through Nx Console I get output like this with no actual commands ran or code generated.

```
Executing task: npx nx run my-app:sync --configuration=ios 

 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: npx nx add my-app --configuration=ios 

 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: npx nx build mobile 

 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: npx nx generate @nxext/ionic-react:application test --no-interactive --dry-run 

 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: npx nx generate @nxext/ionic-react:application test --no-interactive 

 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: npx nx generate @nrwl/js:library test --no-interactive --dry-run 

 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by Cammisuli** [comment]
@devinshoemaker what happens if you try to run an Nx command from the default vscode tasks.json? You can see the vscode docs for that here:
https://code.visualstudio.com/docs/editor/tasks#_custom-tasks

Let me know if that works or not because that's the same system that Nx Console uses to run tasks. Thank you!

**Comment by devinshoemaker** [comment]
Well it looks like I might have other issues. I stopped working right after I sent that message last night, and now my VS Code terminal is borked on all repos, regardless of the extensions enabled 😐  I'm going to try and get this issue squared away and I'll report back on if I still have Nx Console issues or not.

**Comment by devinshoemaker** [comment]
Reinstalling VS Code seems to have solved my issue and Nx Console is working as expected again. Something weird must have happened with my last VS Code update that broke something. All good on my end now!

**Comment by Cammisuli** [comment]
Looking at our analytics, it looks like a lot of folks are able to run their commands. 

I'm going to close this now. If something comes up again, please open a new issue. Thank you!
