### ISSUE TITLE
[Console] Ablity to edit the "Common Nx Commands"

### ISSUE THREAD

**Issue by iDVB** [nrwl/nx-console#1391]
## Description
It would be amazing to have a way to edit the “Common Nx Commands” area.
Our target is not `affected:apps` but instead `affected:backend`
Love the console, but need to be able to tweak things like that. 
Also want to have ALL those commands use ` --output-style=stream` Otherwise there seems to be no good way to know something is still running. (CLI)

## Motivation
Not everyone uses those exact commands or the flags for them. 
Seems fundamental to allow the list to be edited.

**Comment by MaxKless** [comment]
Hey @iDVB I agree, it really limits the usefulness of the Common Nx Commands view. 
Let me think about how to best configure it, though.

**Comment by MaxKless** [comment]
Fixed with #1403
