### ISSUE TITLE
🐛 BUG: nx Daemon does not exit on vscode shutdown

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [nrwl/nx-console#1392]
Type: <b>Bug</b>

After closing vscode there is still a process running.

`<path>\nx\src\daemon\server\start.js`

This prevents access for updating vscode manually because files are still in use.

Extension version: 17.23.3
VS Code version: Code - Insiders 1.73.0-insider (a803dc359aa1ed48c7acf074dd81d6af1525c8c8, 2022-10-25T05:18:55.889Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.75GB (2.77GB free)|
|Process Argv|--log-net-log=netlog.json --ignore-certificate-error --crash-reporter-id 5f9e326c-2a01-458b-95a4-f411641d6f56|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pylantcb52:30590116
pyind367:30587847
vscccc:30564267
pyindex848cf:30577859
nodejswelcome1:30587009
j6j51389:30595213

```

</details>

**Comment by Cammisuli** [comment]
Thanks for the report! I'll investigate this as soon as I can.
