### ISSUE TITLE
Workspace Generators not working with pnpm 7

### ISSUE THREAD

**Issue by thisotherthing** [nrwl/nx-console#1407]
## Current Behavior

Generators are no longer working, since a project was updated to pnpm 7 (from 6).

Also running `pnpm exec nx workspace-generator add-subpackage` directly returns `Not enough non-option arguments: got 0, need at least 1`

## Expected Behavior

Pressing run in the generator options screen should work.

Before the update `pnpm exec nx workspace-generator add-subpackage` used to work.
The cli starts to work again by adding `--`, like `pnpm exec nx workspace-generator -- add-subpackage`.

## Steps to Reproduce

Update global pnpm to 7 globally, and try to run a generator.

Or copy the generator code from the options screen, and try to run the command. It will then list the generator options and end with `Find more information and examples at https://nx.dev/cli/workspace-generator

Not enough non-option arguments: got 0, need at least 1`

### Environment

macOS 12.6.1
pnpm 7.14.2
Nx Console v17.25.0
Nx 14.8.3

**Comment by MaxKless** [comment]
First of all, sorry this hasn't been picked up in so long. 
However, with workspace generators being deprecated with v16, I will close this issue. 
Check out local plugins in the future: https://nx.dev/packages/plugin
If you run into any issues there, please respond here or make a new issue :) 
Thanks,
Max
