### ISSUE TITLE
Filter and grouping for generators list

### ISSUE THREAD

**Issue by Bullfrog1234** [nrwl/nx-console#1408]
## Description

The generator list being able to configured to have:

- sub folders per package of generators
- user list of generators to filter because they will never be used
   - This would be globs to make it match partial names like: `@nrwl/cypress**` to filter out all cypress packages

These features should work independently so that the user can set them as at workspace or user level and have different results

## Motivation

Makes using generators quicker as the ones that the user decides will never use are removed from the list. This could be partial packages or complete packages where they are dependiences of a package you use but not used directly.

Additionally, this can be used to filter out generators in larger teams that are not to be used as a business rule at the workspace level. This reduces the overhead on onboarding new people.

## Suggested Implementation

A setting that can be applied in the workspace settings json or user setting json.

The grouping feature would be a boolean in the settings that makes the list have sub lists

The filter would be an array of globs that the list is filtered based on before it is sent to be displayed

## Alternate Implementations

I am not sure if this has an alternative implementation method, but happy for someone to suggest an alternative. 

This could be applied to other areas like the Project panel and grouping into subfolders so that long lists of projects are quicker to manage

**Comment by MaxKless** [comment]
I can definitely see the value in this. Implementing a blacklist and filtering the generators shouldn't be complicated either. 

I think it would be valuable to make this transparent, though. So if the user types in a generator name and there's no or very few results, there could be a 'Show blacklisted items' option that enables them to find the specific generator they're looking for while still guiding newcomers to a project by not flooding them with options. 

What do you think about this? 
Would you be interested in implementing this? I think it should not be too hard and I'd be happy to point you in the right direction.

**Comment by Bullfrog1234** [comment]
I agree with the show hidden and extra recommendations. I can take it on in the new year (looking at empty calendar hoping it stay that way).

I would appreciate the pointing in the correct direction this my first contribution on a vscode extension.

**Comment by MaxKless** [comment]
Awesome! Love when people are willing to implement their suggestions! 

To read about VSCode extension basics, have a look at the docs: https://code.visualstudio.com/api/get-started/extension-anatomy

You can find the code relating to the project view under `libs/vscode/tasks`. Specifically the `selectGeneratorAndPromptForFlags` function in `cli-task-commands.ts` is responsible for rendering the list of generators.

To implement this feature, you're going to need to do the following things:

- Register a workspace setting (maybe called `generatorsBlacklist` or smth) in `apps/vscode/src/package.json` and in the `GlobalConfigurationStore`
- Consume that setting in the existing filter logic in `getGenerators` and add another option to show hidden generator options in case you're looking for something specific. 

You will probably need to mess around with [QuickPicks](https://code.visualstudio.com/api/ux-guidelines/quick-picks) to do that. So also check out the QuickPick API reference: https://code.visualstudio.com/api/references/vscode-api#QuickPick

Let me know if you have questions and I look forward to your PR :)

**Comment by Bullfrog1234** [comment]
Thanks for pointing it out, I didn't see this (even though it was obvious)
