### ISSUE TITLE
VS code extension doesnt recognize npx command

### ISSUE THREAD

**Issue by msacchetti** [nrwl/nx-console#1424]
## Current Behavior

NX commands in VS code do not recognize NPX, but running the same NPX command in the normal terminal works fine.

## Expected Behavior

It to work

## Steps to Reproduce

Open up VS code
try running npx nx affected --target=build --all=true  in the terminal - it works
try running it through the UI in VS Code 

### Failure Logs / Images / Videos

```
 *  Executing task: npx nx affected --target=build --all=true 

fish: Unknown command: npx
fish: 
npx nx affected --target=build --all=true
^

 *  The terminal process "/usr/local/bin/fish '-c', 'npx nx affected --target=build --all=true'" terminated with exit code: 127. 
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: npx nx affected:apps 

zsh:1: command not found: npx

 *  The terminal process "/bin/zsh '-c', 'npx nx affected:apps'" terminated with exit code: 127. 
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: npx nx affected:apps --verbose=true 

zsh:1: command not found: npx

 *  The terminal process "/bin/zsh '-c', 'npx nx affected:apps --verbose=true'" terminated with exit code: 127. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

### Environment

macOS

**Comment by MaxKless** [comment]
Wow I actually have had the same problem for a few days. I have tracked it down so far that inside `execSync` and other child process calls, the `PATH` env var is not set correctly. I thought it was just a quirk of my own setup, though. 

What VSCode and Nx Console versions are you on?

**Comment by MaxKless** [comment]
Do you have a value set for the `terminal.integrated.env.osx` setting?

**Comment by MaxKless** [comment]
Can you try to do the following:
- execute the command `Preferences: Open User Settings (JSON)`
- remove the `terminal.integrated.env.osx` setting

That fixed it for me.

**Comment by MaxKless** [comment]
Is this still happening for you? And have you reinstalled VSCode yet?

**Comment by Bforsyth1234** [comment]
I just started experiencing this as well.

**Comment by MaxKless** [comment]
Either of you tried reinstalling? It really looks more like a bug with vscode below the extension and fixed itself for me

**Comment by MaxKless** [comment]
Have you tried this fix from here https://github.com/nrwl/nx-console/issues/1288#issuecomment-1405084362 ?

> open VSCode setting page
> set terminal.integrated.defaultProfile.osx to null
> restart VSCode
> open terminal (in my case sh terminal was used instead of zsh I was using before)
> make sure pnpm command available in this shell
> a. I had to run npm install -g pnpm --force to make it work
> restart you VSCode
> at this point NX Console extension should work
> you can go to VSCode settings and revert terminal.integrated.defaultProfile.osx to whatever you like

It was a similar fix when I had this issue.

**Comment by markgoho** [comment]
this is also affecting me, I've tried everything mentioned but nothing seems to work

npx works fine from the integrated terminal, but does not when run from the nx console extension

**Comment by tomschreck** [comment]
I'm experiencing the same issue.  But, I get this error if I have more than 1 VSCode instance open.  Running `nx` commands work from the first instance, however, any subsequent instance open then I receive the error in the screenshot.  I have to force close all instances then reopen VSCode in order for `nx` commands to run from project.json.

I've tried the solution described in [issue 8925](https://github.com/nrwl/nx/issues/8925#issuecomment-1065826677), but no luck.

![image](https://user-images.githubusercontent.com/2521463/222798977-035469e9-81a9-4f19-80b8-9f6c53d80aa0.png)

**Comment by ziacik** [comment]
None of the mentioned helped me. I'm on manjaro, nvm, zsh. I have set terminal default profile to null. I've set nvm alias default 18. Npx works in vscode terminal, just not from the nx console generators.

**Comment by MaxKless** [comment]
@msacchetti @ziacik @mrfratello @markgoho @tomschreck @Bforsyth1234 is this still happening forr you all?
We've had some people report issues with nvm before, maybe this is related?

If it is, could you try the following: Please let me know if/which of these worked:

- Go to your default terminal (not iTerm) and change the node version there using nvm. VSCode should pick up the correct one
- Run nvm list and see if you have a system version installed there? If so, make sure to remove that version (using rm -rf /usr/local/bin/node). You've probably installed it using brew at some point and it might interfere with the nvm version.
- Run nvm use system which should fix the same problem. I haven't tried this one yet personally when I've run into it but it worked for some ppl. Thanks to @TomWhiteIMO for this solution.

**Comment by robert-levy** [comment]
> Added the following to my User Settings in VS Code:
> 
> ```
> "terminal.integrated.profiles.osx": {
>     "zsh": {
>         "path": "/bin/zsh",
>         "args": ["-l", "-i"]
>     }
>   },
> ```
> 
> Then everything started working again

Tried the above but didn't work for me. The specific error I see is:
```
Executing task: npx nx run <app-name>:serve 

/bin/sh: npx: command not found

 *  The terminal process "/bin/sh '-c', 'npx nx run <app-name>:serve'" failed to launch (exit code: 127). 
```

Everything worked fine until I ran an update on my Mac

**Comment by MaxKless** [comment]
Found this on stackoverflow. Have you tried it?

> On macOS, I addressed this by locating the inheritEnv option in VS Code settings.
Alternatively, you can include this line in your settings.json: "terminal.integrated.inheritEnv": false.

**Comment by robert-levy** [comment]
Found the fix. I added this to my settings.json:
```  "terminal.integrated.profiles.osx": {
    "zsh": {
        "path": "/bin/zsh",
        "args": ["-l", "-i"]
    }
  },
  "terminal.integrated.defaultProfile.osx": "zsh",
```
and then I set my my default profile to use Zsh by clicking the down caret button on the vscode terminal, and clicking 'Select default profile'

**Comment by MaxKless** [comment]
I'm closing this as it doesn't seem to be an Nx Console issues.
If you still experiencing this after doing all the steps outlined in this thread & going through [the steps on this page](https://nx.dev/recipes/nx-console/console-troubleshooting#vscode-nvm-issues), please let me know here :)
