### ISSUE TITLE
Tasks not visible in PROJECTS view of NX Console

### ISSUE THREAD

**Issue by pgfeller** [nrwl/nx-console#1433]
## Current Behavior

In `Nx Console` version 17.26.0 I only see the projects, but not the configured tasks:

![image](https://user-images.githubusercontent.com/9395643/205618130-1cbb6419-588d-4b60-8f7e-993881b1a538.png)

The output of `Nx Console`, `Nx Console Client` nor `Log (Extension Host)` show an error. Below the `Nx Console Client` output:

```console
Retrieving workspace configuration
Using local Nx package at c:/git/2nd/VMS.RO.Webviewer/node_modules/nx/src/project-graph/file-utils.js
Using local Nx package at c:/git/2nd/VMS.RO.Webviewer/node_modules/nx/src/project-graph/project-graph.js
[Nxls] - 2022-12-05T10:30:43.648Z - createProjectGraphAsync

Retrieved workspace configuration in: 2458.4880999922752 ms
[Nxls] - 2022-12-05T10:30:45.386Z - createProjectGraphAsync successful
```

The developer console of VS Code also does not show errors related to Nx. `npx nx reset" does not resolve the problem.

The view `GENERATE & RUN TARGET` lists the available targets from the libraries and app:

![image](https://user-images.githubusercontent.com/9395643/205619541-bb51d2fe-4335-4a88-bf1a-0ea8da25a7c2.png)

`npx nx repair` was not able to find a problem in the configuration:

```console
$ npx nx repair

 >  NX   No changes were necessary. This workspace is up to date!
```

If I downgrade `Nx Console` extension to version 17.20.0 the projects view works as expected:

![image](https://user-images.githubusercontent.com/9395643/205621095-0bc7b084-eb79-441c-b754-744561456d9c.png)

## Expected Behavior

The projects view should resolve the configured tasks as in earlier versions of the plugin.

## Steps to Reproduce

Potentially related issue: #1405

The workspace and nx files of the root folder are attached. The folder `repos/RTCP.Web.Viewer` is a git submodule.

### Failure Logs / Images / Videos
[nx & workspace.zip](https://github.com/nrwl/nx-console/files/10153514/nx.workspace.zip)

### Environment

`npx nx report`: 

```console
 >  NX   Report complete - copy this into the issue template

   Node : 16.10.0
   OS   : win32 x64
   npm  : 9.1.2
   
   nx : 15.0.0
   @nrwl/angular : 15.0.0
   @nrwl/cypress : 15.0.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.0
   @nrwl/js : 15.0.0
   @nrwl/linter : 15.0.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.0
   @nrwl/web : Not Found
   @nrwl/webpack : 15.0.0
   @nrwl/workspace : 15.0.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @ngrx/effects: 14.2.0
         @ngrx/store: 14.2.0
         @ngrx/store-devtools: 14.2.0
         @compodoc/compodoc: 1.1.19
         @ngrx/eslint-plugin: 14.2.0
         @twittwer/compodoc: 1.8.2
```

- Nx Console version: 17.26.0 (nx: 15.0.0)
- VSCode version: 1.73.1 (OS Windows x64 10)

**Comment by MaxKless** [comment]
Ok that's great to hear! Let us know if you run into any more issues :)
