### ISSUE TITLE
[v17.28.0] NX Cloud shows error about accesstoken with nx-cloud.env 

### ISSUE THREAD

**Issue by EelcoLos** [nrwl/nx-console#1472]
## Current Behavior

When updating to the VSCode extension to v17.28.0 I log in, the first message I get is:
> Successfully authenticated with Nx Cloud. Welcome, `username`

Then the second one immediatly pops up too:
> Error: No nx access token found.

## Expected Behavior

I'm expecting the accesstoken to be derived from a .env file if available and nx.json doesn't have the `accessToken` property.

## Steps to Reproduce

1. Have a NX MonoRepo. 
1. As we don't want accesstokens visible in our repo's, we remove the `accessToken` from the `taskRunnerOptions`
1. Create a `nx-cloud.env` file in the root directory. Make sure the .env file is set in the .gitignore
1. have the `NX_CLOUD_ACCESS_TOKEN=<YOUR_ACCESS_TOKEN>` in the aforementioned `nx-cloud.env` file
1. run NX. It will work with the .env file to run everything
1. update or run the vscode extension. It will ask to log in. It will show the successfull login and the error.

I don't know if this is a visible error, as I do see a green light at "Remote Cache"

### Environment

I tried the nx report version, which gave the following error:
> nx report
> nx.js report
> Reports useful version numbers to copy into the Nx issue template
> Options:
>  --help     Show help 
> --version  Show version number                                                                                                                                                              
> TypeError: lines_and_columns_1.default is not a constructor
>    at formatParseError (C:\Source\repos\DigitaalMeten\3d\meteninbim\node_modules\nx\src\utils\json.js:39:30)
>    at parseJson (C:\Source\repos\DigitaalMeten\3d\meteninbim\node_modules\nx\src\utils\json.js:24:25)
>    at readJsonFile (C:\Source\repos\DigitaalMeten\3d\meteninbim\node_modules\nx\src\utils\fileutils.js:23:37)
>    at Workspaces.readNxJson (C:\Source\repos\DigitaalMeten\3d\meteninbim\node_modules\nx\src\config\workspaces.js:172:70)
>    at readNxJson (C:\Source\repos\DigitaalMeten\3d\meteninbim\node_modules\nx\src\config\configuration.js:7:72)
>    at Object.<anonymous> (C:\Source\repos\DigitaalMeten\3d\meteninbim\node_modules\nx\src\daemon\client\client.js:288:72)
>    at Module._compile (node:internal/modules/cjs/loader:1239:14)
>    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
>    at Module.load (node:internal/modules/cjs/loader:1096:32)
>    at Module._load (node:internal/modules/cjs/loader:935:12)

- Nx Console version: 17.28.0
- NX Version: 15.5.1
- VSCode version: 1.74.3

**Comment by EelcoLos** [comment]
When Re-opening vscode, I don't get the status of NX Cloud any more. It shows the error
> Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

**Comment by MaxKless** [comment]
Thanks for reporting this! I honestly didn't know about the nx-cloud.env files.
I'll have a look right away :)

**Comment by MaxKless** [comment]
@EelcoLos a new version is released! Can you check and make sure that the issue is fixed for you as well?

**Comment by EelcoLos** [comment]
Can confirm. The NX-cloud option works properly now 🙌
