### ISSUE TITLE
Eliminate Annoying "Sign in Requested" Tooltip in VS Code

### ISSUE THREAD

**Issue by arthurgubaidullin** [nrwl/nx-console#1473]
## Current Behavior

I am consistently being prompted with a "Sign in Requested" tooltip in VS Code, even when I am not using Sign in feature. This notification is not only annoying, but it also slows down my workflow as I have to dismiss it every time it appears.

I have tried disabling the sign in feature and also restarting the application, but the tooltip still appears. It would be greatly appreciated if this issue could be resolved in a future update.

## Expected Behavior

The "Sign in Requested" tooltip should not appear when the user has not interested in the Sign feature.

### Failure Logs / Images / Videos

<img width="358" alt="Снимок экрана 2023-01-16 в 19 59 22" src="https://user-images.githubusercontent.com/522932/212722822-658fadf3-fa50-4b2a-852e-a29bcb2414fe.png">

### Environment

- Nx Console version: v17.28.0
- VSCode version: 1.74.3

**Comment by MaxKless** [comment]
on it :)
you're fast!

**Comment by MaxKless** [comment]
Just to clarify: Are you getting a notification when you open VSCode? Or just the `1` on the icon that I can see in your screenshot?

**Comment by arthurgubaidullin** [comment]
@MaxKless Just the 1 on the icon.

**Comment by MaxKless** [comment]
fixed in #1474 will release soon

**Comment by arthurgubaidullin** [comment]
@MaxKless Thank you so much!

**Comment by MaxKless** [comment]
it's released, would be great if you could confirm that it's also fixed for you :)

**Comment by arthurgubaidullin** [comment]
@MaxKless Yeah. It's fixed! Thank you.
