### ISSUE TITLE
Login to Nx Cloud fails redirect to GitHub Codespaces

### ISSUE THREAD

**Issue by markgoho** [nrwl/nx-console#1480]
### Current Behavior

Signing in to Nx Cloud in the browser, the redirect is hard-coded to assume the user is coming from desktop VS Code

<img width="331" alt="image" src="https://user-images.githubusercontent.com/9759954/212704840-3e21153d-e057-4f44-bc79-fd2effc513c3.png">
<img width="850" alt="image" src="https://user-images.githubusercontent.com/9759954/212704949-1f77e8d8-ff6a-4310-b76b-88e805e00bee.png">

### Expected Behavior

Auth redirect should correctly identify the source of the auth request and redirect based on that, rather than assuming VS Code is only run on the desktop.

### Steps to Reproduce

1. Use GitHub Codespaces
2. Install Nx Console extension
3. Try to sign in
4. See the failures

### Nx Report

```shell
This isn't relevant, but the Nx extension version is `17.28.0`
```

### Failure Logs

```shell
console
Failed to launch 'vscode://nrwl.angular-console?code=-FpQQ-zxaN_Sgh9GyVDuLEk7ZkqUi05q7ZaC9SbTsEM62&state=e137d8c2-f614-4fe9-b060-8c15d205740b' because the scheme does not have a registered handler
```
```


### Additional Information

_No response_

**Comment by MaxKless** [comment]
Can I ask what you use Nx Console for in codespaces? Because we don't currently support browser-based environments.

**Comment by markgoho** [comment]
Hey Max, I use Nx console as a VS Code extension in Codespaces. I've used Codespaces as my sole development environment since before its general availability (> 1 year). If you haven't checked it out yet, I would highly recommend you do. Just as we saw a shift from desktop executables to cloud native web applications, we're going to see this transition happen for our IDEs as well.

Of course this has already been possible for many years, but Codespaces is (essentially) VS Code in the browser, with the added advantage of not tying development to a local machine, and being able to completely customize the environment for the repository without needing to worry about what other repos you're developing with and the potential for conflicting needs.

Here is a full image of me developing on a Nx-based repository in Codespaces:
![image](https://user-images.githubusercontent.com/9759954/212978071-cfb63161-4cda-4152-8b40-1f75d80ab1d0.png)

**Comment by MaxKless** [comment]
Cool.
I'm looking into this but it would require some changes to our auth0 config. Because it needs to be clearly defined what urls auth0 is allowed to route back to and since I can't predict the exact URL of your codespace this is kind of tricky.

So no promises that this will work but I'll try :)

**Comment by markgoho** [comment]
Hmm, if it's the exact URL you need, I think this can be pieced together with Environment variables.

For example, when I serve the the application, this is the script I run:
`nx serve --project=slcsp-calculator --publicHost=${CODESPACE_NAME}-4206.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}:443`

This is needed because the webpack devserver needs to know what url to connect to.

The URL of the Codespace is `https://markgoho-literate-memory-v4x5vr699pcw79r.github.dev/` but as you can tell, the host name is somewhat dynamic.

These might be the two relevant variables in the environment:
``` console
CODESPACE_NAME=markgoho-literate-memory-v4x5vr699pcw79r
CODESPACES=true
```

**Comment by MaxKless** [comment]
Yeah, figuring out the URL isn't the problem, since VSCode takes care of that for us. 
The issue is the fact that the URLs that auth0 will redirect to can't be statically defined anymore. 
This poses a security risk and is discouraged by auth0: https://auth0.com/docs/get-started/applications/wildcards-for-subdomains#how-url-evaluation-works

I will do more research and come back to you :)

**Comment by MaxKless** [comment]
sorry it took so long but i have a PR up with a fix. Thanks for the report :)
