### ISSUE TITLE
Clicking 'migrate' under 'Common Nx Commands' errors for lack of package name and version

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [nrwl/nx-console#1484]
## Current Behavior

Clicking _nx migrate_ does nothing. The command requires a package namd and version, which aren't provided when clicking in the GUI.

<img width="1582" alt="image" src="https://user-images.githubusercontent.com/3335181/213285503-2d9538a8-8eba-4e6c-bc4d-243b80bd72d8.png">

## Expected Behavior

If `migrate` is expected to take in CLI flags, the console should either:

* Expose some way to provide them
* Not surface migrate in the first place
 
## Steps to Reproduce

1. Install the Nx Console in VS Code
2. Open a repo (I was on https://github.com/typescript-eslint/typescript-eslint)
3. Click _Common Nx Commands_ > _migrate_ 

### Failure Logs / Images / Videos

```plaintext
 *  Executing task: yarn nx migrate 

yarn run v1.22.19
$ /Users/josh/repos/typescript-eslint/node_modules/.bin/nx migrate

 >  NX   Provide the correct package name and version. E.g., my-package@9.0.0.

   Pass --verbose to see the stacktrace.

Command failed: /var/folders/1_/pn8_jg_93cqdnkyswmmr5sxm0000gn/T/tmp-56163-T3ZeQVd4zR4N/node_modules/.bin/nx _migrate 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment

- Nx Console version: v17.28.2
- VSCode version: Version: 1.74.3 (Universal)

```plaintext
$ npx nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.7.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx : 15.3.2
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.2
   @nrwl/js : Not Found
   @nrwl/linter : 15.3.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.3.2
   typescript : 4.9.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         lerna: 6.4.0
```

cc @AgentEnder, who was helping me with Nx things when we bumped into this. 😄

**Comment by MaxKless** [comment]
Looking into this, I think I have a culprit too (most probably my fault)

**Comment by MaxKless** [comment]
This is also a good first issue in case anyone wants to contribute @dzhavat @martinakraus

Basically we just have to show a quickpick with prompts for the package name and info and then fill in the returned values in the task.

**Comment by dzhavat** [comment]
Looks interesting. I'd like to give it a try :)

As for showing the quickpick prompt, is something similar already used in the extension? Should the package name and info be taken from `package.json` (so the user can simply select the desired package) or is it free text?

**Comment by MaxKless** [comment]
Well the package name should probably be read from `package.json` because you migrating a package you don't have installed doesn't really make sense.

As for the version selection, have a look at https://github.com/nrwl/nx-console/blob/3f6b2f6c06c4065a6054b8ffe898b4f5cfed9863/libs/vscode/add-dependency/src/lib/dependency-versioning.ts#L1

It shows a somewhat complicated but imo pretty nice prompt for selection package versions. You can refactor this out into a util and reuse, probably. 

Lmk how it goes :)
