### ISSUE TITLE
XState config recommendation

### ISSUE THREAD

**Issue by dzhavat** [nrwl/nx-console#1495]
## Current Behavior

When I run the extension locally, I get the following message in the "Debug Console" tab (highlighted in the screenshot).

![image](https://user-images.githubusercontent.com/1096332/214971618-6cbc96c7-5129-40f4-9914-1a9cfccd4166.png)

I haven't used XState myself and am not familiar with its configuration, so I don't have an opinion about this config option. Only reporting it because I saw it in there. But if XState recommends it, then it's probably a good thing :)

## Expected Behavior

The recommendation message is not shown.

## Steps to Reproduce

1. Run `yarn watch` command
2. Start the extension using `Launch Client + Server` debug menu option 
3. Look at the "Debug Console" tab

### Environment

- Nx Console version: 17.29.0
- VSCode version: 1.74.3

**Comment by Cammisuli** [comment]
That message wasnt there when I first wrote it, and showed up after a release of xstate. I just didnt change it because things still worked 😅
