### ISSUE TITLE
Unused variable

### ISSUE THREAD

**Issue by dzhavat** [nrwl/nx-console#1496]
## Current Behavior

According to TypeScript, the `DEP_GRAPH_OPTIONS` variable in `\nx-console\libs\vscode\tasks\src\lib\nx-task-commands.ts#204` is not used.

![image](https://user-images.githubusercontent.com/1096332/214974739-bd998e4f-268a-4a63-9a50-dc9278148174.png)

Is the variable meant to be used? If not, can it be removed?

### Environment

- Nx Console version:
- VSCode version:

**Comment by MaxKless** [comment]
Yeah you should be able to remove it safely. Just check that the dep graph still works when you do it :) 
In general, all the variables in this file are very old and should be removed, even though some refactorings will be necessary to do so.

Feel free to ping me on twitter for stuff like this too, no need to open an issue :)
