### ISSUE TITLE
Unwanted terminal popups

### ISSUE THREAD

**Issue by joewearing** [nrwl/nx-console#1524]
## Current Behavior

This extension causes quick flashes / popups of the windows terminal

- Consistently, when opening VSCode, the windows terminal app will flash up - for perhaps 50ms - then disappear
  - This often happens twice in quick succession
- Sometimes, but not always, this happens after running an nx command from the integrated terminal
  - When this happens the popup un-focuses the integrated terminal, which is frustrating

## Expected Behavior

There should be no popups whatsoever
This is not a regression, as far as I know

## Steps to Reproduce

1. `npx create-nx-workspace@latest bug --preset=ts`
2. `cd bug && code .`

### Failure Logs / Images / Videos

![nx-bug](https://user-images.githubusercontent.com/6508094/218221940-b56223f0-9584-4aa3-9ff3-f2eb9b54bde8.gif)

### Environment

- Windows 11 22H2
- Git bash configured as default shell
- Nx Console version: `v17.29.0`
- VSCode version: `v1.75.1`
- The new nx beta build (15.7.0-beta.4) is no different

```sh
$ nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.14.0
   OS   : win32 x64
   pnpm : 7.26.3
   
   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : 15.6.3
   @nrwl/linter : Not Found
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

```

**Comment by MaxKless** [comment]
Hey @joewearing! Thanks for the issue report. 
Since you're on windows, it looks like a duplicate of https://github.com/nrwl/nx/issues/10822 to me. You're not the first to report this, see https://github.com/nrwl/nx-console/issues/1442. 

@Cammisuli has tracked it down to the git hasher and @parcel/watcher, which we use both in Nx and Nx Console. 
So a fix is coming!

**Comment by meeroslav** [comment]
Closing this as a duplicate of [#10822](https://github.com/nrwl/nx/issues/10822)

**Comment by MaxKless** [comment]
I think it's not a 100% duplicate since we use @parcel/watcher - which is the root cause of the issue - independently of nx. 
So we'll have to apply the eventual fix in here as well.

**Comment by ChocoMelvin** [comment]
Commenting here since the #2180 has been closed.

I think this exact issue might have been reintroduced in v20.
Every save, and probably any other trigger, opens up several terminals for half a second.
A downgrade back to 19.8.8 resolves the issue immediately.

**Comment by MaxKless** [comment]
Hey @ChocoMelvin :) 
Can you please create a new issue with additional details. 
Could you share a minimal reproduction? This doesn't happen in every nx workspace so if you can share where it happens for you it will be wayyyyyy easier for me to track down what's causing this for you.

**Comment by Hazem-Gamp** [comment]
Hi, I'm on windows 11 and I have the same issue termina keep flashes with or without VScode  NX extension, 
This start to happen after i added vite react app to my workspace. it happen with every script i run and also with every save "ctrl + s"

`Node           : 22.12.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.9.0

nx                     : 20.3.1
@nx/js                 : 20.3.1
@nx/jest               : 20.3.1
@nx/eslint             : 20.3.1
@nx/workspace          : 20.3.1
@nx/angular            : 20.3.1
@nx/cypress            : 20.3.1
@nx/devkit             : 20.3.1
@nx/eslint-plugin      : 20.3.1
@nx/module-federation  : 20.3.1
@nx/playwright         : 20.3.1
@nx/react              : 20.3.1
@nx/storybook          : 20.3.1
@nx/vite               : 20.3.1
@nx/web                : 20.3.1
@nx/webpack            : 20.3.1
typescript             : 5.6.3
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/eslint/plugin
@nx/storybook/plugin
@nx/jest/plugin
@nx/vite/plugin
---------------------------------------
Community plugins:
@storybook/angular                : 8.4.7
angular-server-side-configuration : 19.0.1`

**Comment by MaxKless** [comment]
@Hazem-Gamp these sound like `vite` issues to me that we inherit when executing `vite` in order to generate the project graph - same goes for the tmp file, those come from `vite`. Any fix will have to be upstream

**Comment by Hazem-Gamp** [comment]
> [@Hazem-Gamp](https://github.com/Hazem-Gamp) these sound like `vite` issues to me that we inherit when executing `vite` in order to generate the project graph - same goes for the tmp file, those come from `vite`. Any fix will have to be upstream

The thing is it keep flashing without touching the react project, ex: when i run the start command for the angular app it keeps flashes, I spent too much time debugging this with no hope, the only issue similar to what i face is here 😪

https://github.com/user-attachments/assets/fd191160-2be5-4984-9809-26911b03e5c5

**Comment by RoeeIfergan** [comment]
This still happens in nx 22.0.2 on windows. Tried removing all extensions, reinstalling vscode, git, wsl & NodeJS. even disabled git in vscode and cleared all vscode configs.

When stopping the nx daemon these flickers of CMD stop and when the daemon starts they return. They happen every time a file changes.
Debugging via activity monitor and found out the command thats being run is "git rev-parse HEAD".

Any solutions? this is preventing my team from working..

**Comment by Hazem-Gamp** [comment]
> This still happens in nx 22.0.2 on windows. Tried removing all extensions, reinstalling vscode, git, wsl & NodeJS. even disabled git in vscode and cleared all vscode configs.
> 
> When stopping the nx daemon these flickers of CMD stop and when the daemon starts they return. They happen every time a file changes. Debugging via activity monitor and found out the command thats being run is "git rev-parse HEAD".
> 
> Any solutions? this is preventing my team from working..

I removed this from my NX project and add it to external directory from the /nx work space created a new project for the theme, them created a script that copy the output jar to the required directory after build, 
My recommendation don't use it inside NX and start new Vite project separated just for the theme
Good luck

**Comment by MaxKless** [comment]
> Debugging via activity monitor and found out the command thats being run is "git rev-parse HEAD".

this is so strange to me. If you look at the nx-console and nx source code, there are very few places that call this command. All of them run triggered by an explicit user action, not in the background.
You're seeing it just randomly appear in the background? Not when taking any actions?

**Comment by NicolaLovo** [comment]
I can confirm this still happens on nx 22.6.4 on windows. For me, it happens every time I edit a file, even if I am not serving(`nx serve`)  or building (`nx build`) anything
