### ISSUE TITLE
Support wildcards in `nxConsole.generatorBlocklist` and `nxConsole.generatorAllowlist`

### ISSUE THREAD

**Issue by Tungsten78** [nrwl/nx-console#1527]
## Description

Currently, the array values must be of the value `[package]:[generator]` such as `@nrwl/workspace:library`.
From #1309.

In order to curate a refined list for a team this means potentially dozens of explicit callouts.   Not to mention new generators may sneak in when unwanted.

Would like the ability to block all generators within a package, or a subset of generators possibly via wildcard.

## Motivation

Nx generators are ubiquitous.  Being able to limit the options benefits team adoption and lowers cognitive load.

## Suggested Implementation

Match all within a package by omitting the generator.   `@nrwl/workspace`
Or if explicit is preferred via wildcard `@nrwl/workspace:*`.

Optionally by pattern could be useful `@nrwl/cypress:cypress*`

**Comment by MaxKless** [comment]
Yeah this is a great point, I agree. Would you be willing to contribute this? Because it shouldn't be too hard to implement.
Either way, it's going on my list :)

**Comment by Tungsten78** [comment]
I would be happy to - I'll see if I can allocate cycles this week to put it together.
