### ISSUE TITLE
nx generate @nrwl/react:application - JS check not working

### ISSUE THREAD

**Issue by MuhammadAnas190** [nrwl/nx-console#1538]
## Current Behavior

Generating react application not working after selecting the `Generate JavaScript files rather than TypeScript files.`

## Expected Behavior

Generating react application should be able to generate app by JS after selecting JS boolean. 

### Failure Logs / Images / Videos

<img width="1121" alt="Screenshot 2023-02-17 at 10 52 25 AM" src="https://user-images.githubusercontent.com/42142889/219563383-c7170042-dfdc-4237-8876-83655e30f87a.png">

### Environment

- Nx Console version: v17.30.1
- VSCode version: v1.75.1 (Universal)

### Nx Report
   Node : 16.19.0
   OS   : darwin arm64
   npm  : 8.19.3
   
   nx : 15.1.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.2.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.2.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.2.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.0
   @nrwl/js : 15.2.0
   @nrwl/linter : 15.2.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.2.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.2.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.3.3
   @nrwl/web : 15.2.0
   @nrwl/webpack : 15.2.0
   @nrwl/workspace : 15.1.1
   typescript : 4.8.4

**Comment by MaxKless** [comment]
It looks like the positional argument is being picked up as a value to `--js` here. This could be due to the new sorting of flags.
I'm having a look.

**Comment by MaxKless** [comment]
my suspicion proved right and it's fixed. We'll release it soon.

**Comment by MuhammadAnas190** [comment]
Thanks @MaxKless! Working like a charm now 😊
