### ISSUE TITLE
generator options with type: "array" cannot be run

### ISSUE THREAD

**Issue by dmitry-stepanenko** [nrwl/nx-console#1540]
## Current Behavior
If generator has an option like this, Nx Console will not invoke it.
```json
 "remotes": {
      "type": "array",
      "description": "A list of remote application names that the host application should consume.",
      "default": [],
      "x-priority": "important"
    }
```
 Removing the `"default": []` property solves an issue.

To reproduce, try running via Nx Console `@nrwl/angular:host` generator, that doesn't have `default` property and `@nrwl/react:host` that does have it.

## Expected Behavior
Presence of "default" property should not affect the ability to run generator.

## Steps to Reproduce
- npm install --save-dev @nrwl/react
- Nx Console => Generate => @nrwl/react:host
- Fill the "name" input, notice it invokes the dry run
- type anything under "remotes" property, notice it won't invoke neither the dry run, nor the regular one via "Run" button

### Failure Logs / Images / Videos
No errors or validation messages, simply nothing happens when attempting to run the generator

### Environment

>  NX   Report complete - copy this into the issue template

   Node : 18.13.0
   OS   : darwin x64
   npm  : 8.19.3
   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.6.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.6.3
   @nrwl/vite : 15.6.3
   typescript : 4.8.4

   ---------------------------------------
   Local workspace plugins:

   ---------------------------------------
   Community plugins:

- Nx Console version: 17.30.1
- VSCode version: 1.74.3

**Comment by MaxKless** [comment]
Hi @dmitry-stepanenko , thanks for reporting this. We do have some limitations for dealing with array properties in Nx Console so I can imagine funky stuff happens there sometimes.
But when I tried running `@nrwl/angular:host` and `@nrwl/react:host`, both of them worked just fine. 

Please provide your nx version by running `nx report` and your Nx Console version as well. If you have a minimal reproduction repo, that would make our work much easier and I could get this fixed ASAP. 

Thanks!

**Comment by dmitry-stepanenko** [comment]
@MaxKless I've added additional details to the ticket, please try to reproduce now
