### ISSUE TITLE
dep-graph

### ISSUE THREAD

**Issue by Skcsfar** [nrwl/nx-console#1547]

**Comment by Cammisuli** [comment]
The dep graph is already available in the vscode extension. You can open it in the command palette or within the projects:
![image](https://user-images.githubusercontent.com/4332460/220353755-eced3cf7-8e83-45f9-a8fa-983036b7cb13.png)
![image](https://user-images.githubusercontent.com/4332460/220353870-201668fc-e21b-480e-b2c5-4eb5146a8e0f.png)
