### ISSUE TITLE
[Intellij] Scrollbar is not visible/transparent on Nx Generate page (Windows)

### ISSUE THREAD

**Issue by Den-dp** [nrwl/nx-console#1583]
## Current Behavior

NX Generate page has a transparent scrollbar.

## Expected Behavior

Minor, but in some cases, it is pretty useful to see a scrollbar

## Steps to Reproduce

https://user-images.githubusercontent.com/1770529/222527766-59120347-216c-4ed4-b8f0-2ca3b249fe1a.mp4

### Environment

Windows 10
Nx Console version: 1.2.0
JetBrains Webstorm version: 2023.1 EAP

**Comment by Cammisuli** [comment]
This looks like it's part of the JCEF. I can reproduce it with nx console, but I want to get a smaller repro so that I can report it to jetbrains.

**Comment by MaxKless** [comment]
I couldn't repro this anymore with the new generate UI on my windows laptop. 
I've made a PR to make it look better, though. Tested on my windows laptop too :)
https://github.com/nrwl/nx-console/pull/1837
