### ISSUE TITLE
[intelliJ]: run in project.jsons

### ISSUE THREAD

**Issue by g-cheishvili** [nrwl/nx-console#1594]
## Description
Nice to finally see official thing for jetbrains users, but it lacks tight integration with intellij ecosystem just yet.
One of the most important things is this "run" button on project.json files. Currently other Nx plugin has it, but the problem is that lately it is failing to detect the name of the project properly. I suspect it is related to the workspace.json removal on my side, but I believe nx-console is able to understand that way better
<img width="147" alt="Screenshot 2023-03-06 at 19 23 10" src="https://user-images.githubusercontent.com/28543391/223153817-e55264fc-8857-48b7-897f-37cdeb3beac6.png">

## Motivation

It is very comfortable and this is just what IntelliJ folks are expecting

## Suggested Implementation
No idea

**Comment by MaxKless** [comment]
Hi, this will be available shortly! PR is already up. 
I'll ping you once it's available for use and you can confirm that it works for you. Sound good?

https://github.com/nrwl/nx-console/pull/1584

**Comment by MaxKless** [comment]
fixed with #1584
