### ISSUE TITLE
[Intellij] Configure node + npm binaries

### ISSUE THREAD

**Issue by bulldog98** [nrwl/nx-console#1614]
If you installed node + npm/yarn via nvm, nx console is not able to run a serve for an app.

## Description
Being able to configure where node/npx binary is or reuse the info from the ?node? plugin

## Motivation
Being able to use nvm to install node.

## Suggested Implementation
Reuse config information from the corresponding plugin

## Alternate Implementations
Being able to configure it for the plugin itself

**Comment by Cammisuli** [comment]
Which nvm package are you using? I have nvm installed on my Windows and macOS machines, and the run commands work in both. 

When running commands, we dont use npx/yarn, but rather the bin file directly in node_modules/.bin folder.

**Comment by bulldog98** [comment]
@Cammisuli I'm on linux with zsh

**Comment by Cammisuli** [comment]
Ahh ok, I see where this issue is happening. We're not using the Node interpreter for running commands, but we have it using the interpreter to use the language server. 

I'll fix it.
