### ISSUE TITLE
projects array does not update after creating a new library

### ISSUE THREAD

**Issue by rubenheymans** [nrwl/nx-console#1616]
### Current Behavior

A newly created library does not appear in the list of projects when you generate a new component

### Expected Behavior

The new library should appear in the projects list when generating a new component
Without restarting vscode

### Steps to Reproduce

1. Create a new library 
2. Inside the libs folder of this library, create a components folder
3. Generate a new component inside the components folder
4. In the project field, search for the library
5. The library does not appear in the list
6. Restart vscode to fix the problem

### Nx Report

```shell
$ nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.17.0
   OS   : win32 x64
   npm  : 8.15.0

   nx                      : 15.8.6
   @nrwl/js                : 15.8.6
   @nrwl/jest              : 15.8.6
   @nrwl/linter            : 15.8.6
   @nrwl/workspace         : 15.8.6
   @nrwl/angular           : 15.8.6
   @nrwl/cli               : 15.8.6
   @nrwl/cypress           : 15.8.6
   @nrwl/devkit            : 15.8.6
   @nrwl/eslint-plugin-nx  : 15.8.6
   @nrwl/tao               : 15.8.6
   @nrwl/webpack           : 15.8.6
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @fortawesome/angular-fontawesome : 0.12.1
   @ngneat/transloco                : 4.2.6
```

### Additional Information

Nx: Refresh workspace does not help

**Comment by MaxKless** [comment]
Hi @rubenheymans, I just tried reproducing this on my mac and the project view automatically refreshes just fine. 
Maybe this is a windows problem? 
Could you please share more details about your VSCode & Nx Console version?

**Comment by rubenheymans** [comment]
VSCode:
Version: 1.76.2 (user setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

nx: 
Both `nx --version` and `nx` in `package.json`, don't know if that matters
15.8.6

Windows:
Edition	Windows 11 Home
Version	22H2
Installed on	‎04/‎10/‎2022
OS build	22621.1413
Experience	Windows Feature Experience Pack 1000.22639.1000.0

**Comment by Cammisuli** [comment]
There was a few fixes to the daemon i did for windows thats in 15.8.9 or 15.9.0. Can you try with that version and let me know? 

I tried with 15.9.0 and it worked locally for me.

**Comment by rubenheymans** [comment]
it does not seem to work for `15.8.9`, don't know how to update to `15.9.0`.
`nx migrate latest` updated to `15.8.9`

**Comment by MaxKless** [comment]
hey @rubenheymans there have been changes to how Nx Console uses the daemon in the past weeks. Does this issue still occur with the latest version?

**Comment by rubenheymans** [comment]
Hi @MaxKless , I updated to `15.9.2` and now it works, thanks.
However, when I create a new component, I can select the correct project in the list, but it doesn't autoselect the project after creating a new library. So that's still a small bug I guess. Autoselecting does work with libraries I created earlier or after a vscode restart.

I had to run `nx reset` after migration to fix some errors.

**Comment by MaxKless** [comment]
okay thanks for the report, I'll have a look :) what version of nx console are you on?

**Comment by rubenheymans** [comment]
`v18.0.4`

**Comment by MaxKless** [comment]
Hey there's been some changes and a new generate UI. Can you check whether this still happens on the latest Nx Console?

**Comment by MaxKless** [comment]
yeah that's a good point. Because of the implementation in @microsoft/fast-combobox, we need to decide between having inline autocomplete or matching across the word... not sure what's more important
