### ISSUE TITLE
[Webstorm] Error: Cannot find a local installation of Nx. (WSL)

### ISSUE THREAD

**Issue by zwif** [nrwl/nx-console#1632]
## Current Behavior

Can't run any nx run configuration - throws an error like: `Error running 'serve my-app': Cannot find a local installation of Nx.`
Trying to use "Nx Generate (UI)" will open the UI (screenshot attached below) but no matter what text is entered, it fails silently: nothing happens.

## Expected Behavior

nx console should be usable in WebStorm for a project in a WSL directory. Maybe allow to manually define the path to the nx interpreter.

## Steps to Reproduce

1. Clone https://github.com/nrwl/nx-examples to a **WSL path** under windows, e.g. via Webstorm UI: File>New>Project from Version Control... (see example image below).
2. Run npm install in that folder (via WSL terminal).
3. Create a nx "run configuration" (see example below).
4. Trying to run that configuration will result in the following error: 
![image](https://user-images.githubusercontent.com/18686636/227513713-1636327d-ff43-458a-a50a-325ebed88df5.png)

(Note: running `npx nx serve cart` in terminal works perfectly fine - `./node_modules/.bin/nx` is present).

### Failure Logs / Images / Videos

- This is shown when triggering "Nx Generate (UI)" (but no further actions possible):
![image](https://user-images.githubusercontent.com/18686636/227510124-3bde3cd2-8281-4d0e-b6d7-cdc9835b2135.png)

- Git clone via webstorm UI to wsl directory Screenshot:
![image](https://user-images.githubusercontent.com/18686636/227512356-b74d0863-7119-4f1b-9235-b4d5dcd3d47f.png)

- Example run configuration for nx-examples repo:  
```
<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="serve cart" type="NxRunConfigurationType">
    <option name="nx-projects" value="cart" />
    <option name="nx-targets" value="serve" />
    <envs />
    <option name="arguments" value="" />
    <method v="2" />
  </configuration>
</component>
```

### Environment

- Nx Console version: 1.2.0
- VSCode version: n/a
- Webstorm version: 2022.3.4 (Build #WS-223.8836.50)

**Comment by Cammisuli** [comment]
I'll have to check it out with wsl myself. I'm pretty sure we use the WSL node interpreter to find your install of node. 

Let me double check.
