### ISSUE TITLE
"should never be logged" has been logged

### ISSUE THREAD

**Issue by hgschwibbe** [nrwl/nx-console#1637]
"Should never be logged" has been logged, muhahaha:

![Screenshot](https://user-images.githubusercontent.com/1725648/227996745-846c4e95-0146-433f-a565-6ae38f345d67.jpg)

Next time please program with more humility

**Comment by Cammisuli** [comment]
Wrong plugin ☹️ 

https://github.com/iguissouma/nx-console-idea-plugin/issues
