### ISSUE TITLE
Consider generators UI persistent customizations

### ISSUE THREAD

**Issue by moniuch** [nrwl/nx-console#1642]
## Description

I would like some way to customize generators UI to be able to better understand and memorize options, as well as share it with my team.

## Motivation

I constantly find myself forgetting how to properly fill in the fields, and which fields are essential (this might change per project), and what means what. Esp. the introduction of `standalone` has made some of the options (`routing`, `lazy`) convoluted and confusing. I imagine this can also be intimidating to others. As I don't work in an Nx workspace on a daily basis, I would appreciate if UI could be customized in a persistent way to reduce the mental overhead of remembering a lot of changing stuff.

## Suggested Implementation

Being aware that these forms are generated from schemas, I think Dx should involve an intermediate customization step (ie. between parsing schema and generating UI out of it). Unfortunately, over time schematics options have grown tremendously and become harder to grasp and remember. This is also due to very succinct descriptions which don't say much to a beginner. Regardless of whether the schematics will eventually migrate away from @angular/cli or not, my suggestions would be as follows:

1. Remove the 'Show more / Show less' view toggling feature. Its default state to show less makes discovery of options more difficult (at least in dark mode). Besides, I don't see a value in having it unless user is able to customize which are to be hidden as non-essential (per generator)
2. Either allow custom grouping (as described above) or at least allow flagging options as essential (flagging would actually be a very easy win - via a button that flags all options capture from the most recent run command).
3. Allow inserting custom description/hints. For example, I am never sure of things like:
 - whether a path should start at `libs` or `libs/src`,
 - should I include full or shortened module file name (`app.module.ts` or without `.ts` or maybe app alone),
 - whether the description for `lazy` (mentioning `RouterModule.forChild`) is relevant with `standalone`, etc.
 If I were able to leave this sort of "UI annotations" for every generator and share (track) those within project, this would make the learning curve less steep and it would bring value for my team's DX.

**Comment by AgentEnder** [comment]
You can set default values inside nx.json for generators to best suit your use case, and I believe console picks them up: https://nx.dev/reference/nx-json#generators

**Comment by MaxKless** [comment]
I think to start, default values are the quickest way to help you out here. 

As for UI customizations, I've also thought about this before. I'm not sure about how exactly it should work ideally but I appreciate your input. We're probably going to redesign the entire generator form from the ground up soon so I will see if customization can be incorporated well then.
