### ISSUE TITLE
Incorrect naming of module and module-file

### ISSUE THREAD

**Issue by CramericaIndustries** [nrwl/nx-console#1645]
## Current Behavior
I was generating a new nest library which should be placed in a subdirectory of libs like so...

![grafik](https://user-images.githubusercontent.com/5860703/228894610-93f15d5c-8eeb-4edc-b714-c3916eb7af93.png)

Everything went like it should, except the naming of the TS module class and its filename. Both were prepended with the directory name.

Filename in that case was `commons-my-new-common-lib.module.ts`
Class name of the module was `CommonsMyNewCommonLibModule`

Same behaviour is when generating angular libs while using the "Directory" option.

## Expected Behavior

Filename of the module should be `my-new-common-lib.module.ts`
Class name of the module should be `MyNewCommonLibModule`

## Steps to Reproduce
see screenshot

- Nx Console version: v17.32.0
- VSCode version:
```
Version: 1.76.2 (user setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
```

```

$ nx report
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.1
   OS   : win32 x64
   yarn : 1.22.0
   
   nx                      : 15.8.6
   @nrwl/js                : 15.8.6
   @nrwl/jest              : 15.8.6
   @nrwl/linter            : 15.8.6
   @nrwl/workspace         : 15.8.6
   @nrwl/angular           : 15.8.6
   @nrwl/cli               : 15.8.6
   @nrwl/cypress           : 15.8.6
   @nrwl/devkit            : 15.8.6
   @nrwl/eslint-plugin-nx  : 15.8.6
   @nrwl/nest              : 15.8.6
   @nrwl/node              : 15.8.6
   @nrwl/nx-plugin         : 15.8.6
   @nrwl/tao               : 15.8.6
   @nrwl/webpack           : 15.8.6
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @nguniversal/express-engine : 15.2.0
   @nguniversal/builders       : 15.2.0
```

**Comment by AgentEnder** [comment]
This isn't an issue with Nx Console, you'd see the same behavior if you ran the commands directly via the command line. Its also the expected behavior on the Nx + Plugin's side of things, as Nx projects need to have unique names so we tend to prepend the directories. The module names are based on the project names, which have the directory.

Some generators have a flag https://nx.dev/packages/angular/generators/library#simplename that lets you keep this from happening.
