### ISSUE TITLE
Nx generate context menu provides invalid directory value

### ISSUE THREAD

**Issue by pcurrivan** [nrwl/nx-console#1646]
### Problem
If you right click on a directory and select "Nx Generate...", the directory field is set to an invalid value (for at least some generators).

### Expected behavior

Directory field should be set to a valid value. (Some generators seem to expect the directory path to start after 'apps'.)

### Steps to Reproduce

1. Right click a directory in the VS Code file tree, e.g. apps/foo/
2. Select Nx Generate...
3. Use the '@nrwl/angular - remote' generator (probably other generators have the same issue)
4. Type a name for the remote app, e.g. 'bar'
5. See error message during dry run: 'Cannot find configuration for 'apps-foo-bar''
6. See that the directory field is set to 'apps/foo'.  Change this to just 'foo'.
7. Error goes away.

### Environment

- Nx Console version: 17.32.0
- Nx version: 15.8.9
- VSCode version: 1.77.0-insider

**Comment by eilensm** [comment]
### Problem
The issue also occurs in the IDEA plugin.

### Environment
- Nx Console version: 1.3.0
- Nx version: 15.6.2
- IDEA version: IntelliJ IDEA 2023.1 (Ultimate Edition), Build #IU-231.8109.175

**Comment by MaxKless** [comment]
Hey thanks for the report! I'll look into this :)

**Comment by MaxKless** [comment]
Ok nevermind this is already fixed on master and will be released with v16 :) 
check out https://github.com/nrwl/nx/pull/16113
