### ISSUE TITLE
VSCode: Nx-Console does not generate dependencies in workspace

### ISSUE THREAD

**Issue by jabbrwcky** [nrwl/nx-console#1647]
## Current Behavior

I have one nx workspace (e.g. foo) opened in a VSCode editor that has mutiple (non-nx) projects. (e.g. /bar, /baz, /foo in order of display top down in the sidebar)

Nx-Console has the nx workspace selected, but the actions `add dependency` and `add dev dependency` add a `project.json` fragment containing the dependencies in the first folder (e.g /bar/project.json)

## Expected Behavior

I would expect the actioon to use the configured workspace, not the first random folder in VS Code.

### Environment

1. Open a nx project in VSCode and configure the workspace.
2. Add another Folder to the VSCode workspace
3. Usually the folder order will be (1. nx, 2. foo)
4. Run `add (dev) dependency` -> adds dependency to nx-project
6. Reorder the folders in the sidebar so it is (1. foo, 2. nx)
7. Run `add (dev) dependency` again -> Console shows that it runs in folder `foo`

- Nx Console version: v17.32.0
- VSCode version: 
```
Version: 1.77.0
Commit: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63
Date: 2023-03-29T09:55:48.214Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No
```

**Comment by Cammisuli** [comment]
There's a few thing that don't work well in vscode's multi-root workspace. 

It's definitely something we need to invest time in.
