### ISSUE TITLE
[Feature] Prefer/Support the long syntax `nx run [project]:[command]` to run an executor

### ISSUE THREAD

**Issue by tinesoft** [nrwl/nx-console#1648]
## Description

Nx Console fails to execute executors with special names (like `run`):

![image](https://user-images.githubusercontent.com/4053092/229127257-ae532308-5ff3-48a3-bf24-6ee2e9bb6664.png)
![image](https://user-images.githubusercontent.com/4053092/229127298-64d48ae5-428f-4129-a6ff-14ddbdd82ffa.png)

_(here `run` is a **valid executor** of the `@nxrocks/nx-flutter` plugin, that can be run successfully with `npx nx run <project>:run` syntax)_

## Motivation
When running an executor, Nx Console uses the **shorthand syntax** to invoke the executor: `nx [command] [project]`
While this works most of the time, it will fail if the  executor name conflicts with an existing Nx command (for eg `run`)
https://nx.dev/plugin-features/use-task-executors#running-executors

## Suggested Implementation
Instead of using the **shorthand syntax**, Nx should use the **full syntax**  (i.e `nx run [project]:[command]`, which is **always** safe to use)  or at the very least, default to it when shorthand syntax failed (due to conflicting executor name vs Nx commands)

**Comment by MaxKless** [comment]
Yeah good point, I'll fix it. If you want to provide a fix I'm also happy to help out :)
