### ISSUE TITLE
Nx Console plugin not supported in WebStorm 2023.1

### ISSUE THREAD

**Issue by jambudipa** [nrwl/nx-console#1650]
### Current Behavior

Using the Nx Console plugin in WebStorm 2023.1 causes the IDE to crash.

### Expected Behavior

The IDE should not crash.

### Steps to Reproduce

1. Install the Nx Console plugin in WebStorm 2023.1

### Nx Report

```shell
n/a
```

**Comment by jambudipa** [comment]
Well it seems there are a couple of plugins, one of which works, the other not. Need to check which is official but not at my computer at the moment. Let me get back to you!Sent from my iPhoneOn 31 Mar 2023, at 20:53, Jonathan Cammisuli ***@***.***> wrote:﻿
I'm using Intellij 2023.1 and I'm not experiencing any crashes.
Whats the particular error message that you're seeing?

**Comment by Cammisuli** [comment]
I'm seeing stats showing that we are running on Webstorm 2023.1. So I'm going to close this issue.
