### ISSUE TITLE
Nx Console does not start on Rider

### ISSUE THREAD

**Issue by jvskriubakken** [nrwl/nx-console#1652]
## Current Behavior

I install the Nx Console plugin to Rider 2022.3.3. Restart Rider as asked. Open my nx project. No trace of the plugin.

## Expected Behavior

I expected to see the tool window of the plugin.

## Steps to Reproduce

As described under "Current behaviour".

### Failure Logs / Images / Videos

I see not logging of the plugin...

### Environment

- Nx Console version: 1.2.0
- Jetbrains Rider version: 2022.3.3

**Comment by Cammisuli** [comment]
The tool window isnt there in the current release. In 1.2.0 we currently only support generators and auto complete in nx.json/project.json files.

Do you see those?

**Comment by jvskriubakken** [comment]
OK. 

Not sure where I can see those... but ok, I'll wait until you have a proper tool window in place (like in Nx Console IDEA). I like Nx Console IDEA a lot, and thought this was a replacement (but I did not know it was "unfinished" so to speak).

Jørund
