### ISSUE TITLE
Nx Console showing deleted library

### ISSUE THREAD

**Issue by geraparra** [nrwl/nx-console#1659]
## Current Behavior

I've created a new nx monorepo angular project and after removing a library I still see the library in the projects section.

is there any chance to update the view to prevent showing deleted libraries?

## Expected Behavior

Would be nice to see only available apps or libraries but not deleted ones.

## Steps to Reproduce

1) Create a new project with nx using the following command: npx create-nx-workspace@latest

Choose your style                     · integrated
✔ What to create in the new workspace   · angular
✔ Repository name                       · myorg
✔ Application name                      · store
✔ Default stylesheet format             · css
✔ Enable distributed caching to make your CI faster · Yes

2) Created two apps and one library as in the following capture:

![image](https://user-images.githubusercontent.com/7715578/229913319-b2a96036-7e7c-4bbe-ad8c-56f3fb1389a6.png)

3) remove the library using npx remove command
4) refresh nxconsole projects section
5) deleted library is still showed in the list:
![image](https://user-images.githubusercontent.com/7715578/229915932-ce0e419e-1239-413e-ad62-684ee3594e13.png)

### Environment

- Nx Console version: v17.32.0
- VSCode version: 1.76.2

**Comment by doug-shontz** [comment]
This to me is something "below" the VS Code plugin.  I have no affiliation with the toolset at all.  But I have found that when you move things or delete things in your workspace...NOTHING updates.  You can run "nx graph" and still see the deleted libraries as well.

What I have found I have to do is perform my moves/deletes and then run "nx reset".  That restarts the nx daemon and clears up both the graph and the nx console plugins.

**Comment by AgentEnder** [comment]
This is an error with Nx itself in latest versions, I'm pushing a PR.
