### ISSUE TITLE
Cannot run any command using wsl on windows 11

### ISSUE THREAD

**Issue by NorthwooDzp** [nrwl/nx-console#1665]
## Current Behavior
For each command I see /bin/sh: 1: Syntax error: "&&" unexpected error

## Expected Behavior
Commands work

### Environment

- Nx Console version: 1.3.1
- WebStrom version: 2023.1

**Comment by Cammisuli** [comment]
Appears to be working for me... 
![image](https://user-images.githubusercontent.com/4332460/230652130-e07bc16a-3aea-45a1-8782-298e3cd5a8d3.png)

If you copy the command (click the top line that says `Ubuntu` or whatever other distribution you're using) and run that in another terminal window in cmd, what does it say?

For me it would be like this `C:\WINDOWS\system32\wsl.exe --distribution Ubuntu --exec /bin/sh -c "export PATH=\"/home/jon/.nvm/versions/node/v18.13.0/bin:$PATH\" && export COLORTERM=true && export FORCE_COLOR=true && export npm_config_color=always && export DEBUG_COLORS=true && export MOCHA_COLORS=1 && cd /home/jon/dev/monodon && /home/jon/dev/monodon/node_modules/.bin/nx run 'rust:test'"`

**Comment by Cammisuli** [comment]
Since I havent heard anything back in a couple weeks, I'm going to close this issue.

For others who are having issues with wsl, follow these instructions (which are also on the readme)

```
The Node interpreter under Languages & Frameworks > Node.js needs to be configured to use the Node executable within the WSL distribution. You can read more on the official Jetbrains docs.
```
