### ISSUE TITLE
Cannot run Nx commands from VSCode Command Palette

### ISSUE THREAD

**Issue by andy-bond** [nrwl/nx-console#1666]
## Current Behavior

As seen in the screenshot below - attempting to run any Nx command via VS Code Command Palette results in a "command not found" error.

This occurs for all Nx Commands that I attempt to run via the command palette in VS Code: serve, test, build, run, generate, etc

## Expected Behavior

The command should run.

## Steps to Reproduce

This issue seems to only occur in the latest major version of the Nx Console extension for VS Code (v18.0.2).
**If I revert to v17.32.0 the issue goes away and commands work again.**

### Failure Logs / Images / Videos

![image](https://user-images.githubusercontent.com/10934345/230603367-1fc7750c-f677-4810-85ec-88dfcfd5e85b.png)

### Environment

- Nx Console version: 18.0.2
- VSCode version: 1.77.1 (Universal)
- MacOS Ventura 13.3 (Intel MacBook Pro, 2019)

**Comment by Cammisuli** [comment]
Oh those single commands shouldnt be there anymore. Sorry about that. 

You should use the `Nx: Run Target` command instead to get access to all those different commands.

**Comment by andy-bond** [comment]
Not sure how the command palette is populated, but perhaps they were only in my history?

I confirmed that I can still run commands using `Nx: Run Target`.
