### ISSUE TITLE
Cannot select workspace when the Nx workspace is not at the root

### ISSUE THREAD

**Issue by haven2world** [nrwl/nx-console#1670]
## Current Behavior
In our repo, we have dir structure like below, and the Nx workspace is not at the root
```
repo root
- Nx workspace
- some other directories ...
- ...
- ...

```
When I open VS code at the root, Nx console doesn't work and show me
<img width="468" alt="image" src="https://user-images.githubusercontent.com/17299418/231048212-8d9d8590-fc61-422f-9f2a-36d193b7d36e.png">

## Expected Behavior

In the past, when I do the same, there is an option in Nx console pane named `change workspaces`. And then I can change the workspace to the correct path `./Nx-workspace` so it works well.
![image](https://user-images.githubusercontent.com/17299418/231049286-fb897fb8-f939-4444-b087-58004a08272c.png)

I think it's a regression unless it's on purpose.

## Steps to Reproduce

Just open VS Code at the parent directory of a Nx workspace and see the Nx Console Pane

### Failure Logs / Images / Videos
<img width="468" alt="image" src="https://user-images.githubusercontent.com/17299418/231048212-8d9d8590-fc61-422f-9f2a-36d193b7d36e.png">

### Environment

I'm using Mac (Intel chips)
Feels like the dependencies don't matter since the Nx console doesn't detect the Nx workspace...

- Nx Console version: v18.0.2
- VSCode version: Version: 1.77.1 (Universal)

In addition, if I open VS Code at the Nx workspace directly, it works well. But it's really inconvenient since I need to change the files in the root frequently and they shouldn't be moved into Nx workspace.

**Comment by Cammisuli** [comment]
Oh no, that shouldn't be the case. We should still have the select workspace button available. 

Let me double check.
