### ISSUE TITLE
UI for serve and build commands no longer opens in VS Code

### ISSUE THREAD

**Issue by dgbau** [nrwl/nx-console#1673]
## Current Behavior

The UI for build and serve commands is no longer available, these commands can only be launched and configured in the VSC command palette. 

## Expected Behavior

clicking "build" or "serve" in the Nx Console sidebar should open up a tab with the UI for that command

## Steps to Reproduce

Happens 100% of the time when trying to use the extension. Open the extension sidebar, click serve or build. results in command palette options, no UI

### Failure Logs / Images / Videos

![Screenshot 2023-04-11 at 10 41 51 AM](https://user-images.githubusercontent.com/9829656/231234244-a7dfe17c-dd67-4427-a174-f53f27c44965.png)

### Environment

MacOS 13.3 (22E252)

- Nx Console version: v18.0.2

- VSCode version: Version: 1.77.1 (Universal)

**Comment by varzaman** [comment]
I'll second this. Exact behavior as described. 

MacOS 13.2.1
VSCode: 1.77.1
Nx Console: 18.0.2

**Comment by Frotty** [comment]
Sweet, an update that doesn't bring anything useful new to our workflow but removes a feature we constantly used, what a joy.
At least one can downgrade the plugin version.

**Comment by MaxKless** [comment]
Can I ask what your use case was for running targets with the UI? Versus just calling targets (that maybe have different configurations for different scenarios)?

**Comment by MaxKless** [comment]
Also check out VSCode's task functionality. It remembers which nx tasks you run from the command prompt and allows you to easily rerun them.
