### ISSUE TITLE
[intellij] nodejs14 breaks the plugin so it prevents IDE from closing (even in non-nx projects)

### ISSUE THREAD

**Issue by Den-dp** [nrwl/nx-console#1677]
## Current Behavior

If an unsupported nodejs version is installed:
* all nx-related actions don't work and nx-related panel is empty (which is ok)
* the plugin prevents IDE from closing - IDE stucks on "Closing project" window (that's bad)
* even non-nx projects can't be closed

## Expected Behavior

I'd expect:
* to have some IDE warning about unsupported nodejs 
* to not break non-nx projects

## Steps to Reproduce
* use nodejs 14

### Failure Logs / Images / Videos

[idea.log](https://github.com/nrwl/nx-console/files/11225730/idea.log)

![image](https://user-images.githubusercontent.com/1770529/231863907-f5ab51d5-e004-40ad-8757-29c86bbe071b.png)
![image](https://user-images.githubusercontent.com/1770529/231863990-acc94622-6a4e-458a-8b9b-f5bdb842015b.png)
![image](https://user-images.githubusercontent.com/1770529/231864070-5525d4fe-564f-44c7-90e9-28b0bbec9788.png)

### Environment

```
> nx report

 >  NX   Report complete - copy this into the issue template
                                                            
   Node : 14.20.0                                           
   OS   : win32 x64                                         
   npm  : 6.14.18                                           
                                                            
   nx (global)             : 15.9.2                         
   nx                      : 15.9.2                         
   @nrwl/js                : 15.9.2                         
   @nrwl/jest              : 15.9.2                         
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
```

- Nx Console version: 1.3.1
- IDE version: WebStorm 2023.1

**Comment by Den-dp** [comment]
Ok, I found that nodejs@14 caused this issue.

And the most unfortunate part: if you have a global installation of an old nodejs and you want to open a **non-nx** project - you will not be able to close it (see "Closing Project..." screenshot above), **which is a problem, that should be addressed**.

----------------------

For folks like me who can't update a globally installed nodejs at the moment - you all can switch the version via "node interpreter" (but this will be applied only for the current project)

![image](https://user-images.githubusercontent.com/1770529/231866626-e6eaeb27-2afb-4024-ab50-f83a4eeebd24.png)

**Comment by Cammisuli** [comment]
Thank you for providing more information about it! I'll take a look first thing in the morning and try and reproduce it.

**Comment by Cammisuli** [comment]
I dont want the plugin to leave a bad impression, so I did fix support for Node 14.

But keep in mind that it goes end of life on April 30, 2023 (https://github.com/nodejs/Release) and users should _**really**_ update to a more recent LTS.

**Comment by Den-dp** [comment]
thanks for the fix! 👍 and sure, I am aware of this date 

overall I see this issue more like an opportunity to provide proper handling in a fail-fast manner to cover such rare scenarios

**Comment by Cammisuli** [comment]
yea, for sure, thats why i dont want it to leave a bad impression 😄
