### ISSUE TITLE
Unable to create a guard via nx console plugin

### ISSUE THREAD

**Issue by mnkyjs** [nrwl/nx-console#1681]
## Current Behavior

When I try to generate a Angular Guard in my Intellij IDE, I get an error from the NX Console Plugin

## Expected Behavior

NX Console Plugin is able to generate a new guard

## Steps to Reproduce

In Intellij right click -> New -> Nx Generate (UI) -> Select @schematics/angular - guard

### Failure Logs / Images / Videos

<img width="352" alt="image" src="https://user-images.githubusercontent.com/71262926/232405119-19d77d07-8267-4295-8c9f-9ce6ddbfa0e6.png">

Error message

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/71262926/232405312-f4b59e22-f34b-43a2-944a-685c1fe6e6c9.png">

### Environment

IntelliJ IDEA 2023.1 (Ultimate Edition)
MacOS

- Nx Console version: 1.31
- VSCode version: -

**Comment by Cammisuli** [comment]
hmm this one is interesting.. Thank you for the report. I'll look into it 🙂
