### ISSUE TITLE
Could not run nx:server from command panel since Nx console version 18 updates in VS Code.

### ISSUE THREAD

**Issue by iambpn** [nrwl/nx-console#1682]
## Current Behavior
When running `nx serve` command using command panel it errors out stating `nx:server command not found`. 

## Expected Behavior
Should give list of project to select which one to server. Similar to `Nx Console Tab` > `Generate & Run Target` > `Serve`

![image](https://user-images.githubusercontent.com/21078512/232422258-1192fc4d-7072-4eb2-a76a-b69a47b45d22.png)

## Steps to Reproduce

- install Nx console version 18.0.4
- open command panel of vscode 
- search for `nx:serve` command

### Failure Logs / Images / Videos

![image](https://user-images.githubusercontent.com/21078512/232421214-ae289fec-68a1-44de-aa20-f85f46ea5172.png)

### Environment

- Nx Console version: 18.0.4
- VSCode version: 1.77.3

**Comment by iambpn** [comment]
I have also tried downgrading nx console to version 17.32.0 and it worked fine. I think, the issue lies in version 18 upgrade.

**Comment by markusfalk** [comment]
All commands seem to have been removed. Is there any way left to start commands like `test` or `serve` with keyboard only? 😬

**Comment by MaxKless** [comment]
how about the `nx.run.target` command?
