### ISSUE TITLE
[intellij] wrong character encoding in PhpStorm terminal output

### ISSUE THREAD

**Issue by quirin-buechner-mdctec** [nrwl/nx-console#1685]
## Current Behavior
When serving an angular application the output terminal of the run configuration window prints some invalid characters:
```
Build at: 2023-04-18T09:22:07.971Z - Hash: f11780097d4cdf60 - Time: 24179ms

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


âˆš Compiled successfully.
```
## Expected Behavior
```
Build at: 2023-04-18T09:22:07.971Z - Hash: f11780097d4cdf60 - Time: 24179ms

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


√ Compiled successfully.
```
## Steps to Reproduce
 * create a nx workspace with an angular preset
 * create a Nx Run Configuration for the `serve` target of this angular app
 * launch this run configuration via the PhpStorm UI

### Failure Logs / Images / Videos
![image](https://user-images.githubusercontent.com/57623536/232737611-47e80859-0297-4432-a8ab-7cc71bf3bab8.png)

![image](https://user-images.githubusercontent.com/57623536/232737526-88146710-ed66-41a4-bd91-ce7d44885910.png)

### Environment
- Nx Console version: 1.3.2
- PhpStorm version: 2023.1 Build #PS-231.8109.199, built on March 29, 2023
- OS: Windows 11 Pro 22H2

**Comment by MaxKless** [comment]
Hey can you try this when serving an angular app without using Nx Console? Does it work via the built in terminal or the built in angular plugin?
What shell are you using? 

The character encoding works fine for me so I'm trying to get to the root of your issue here. We don't really do anything except for delegating the terminal creation and execution of a command to editor.

**Comment by quirin-buechner-mdctec** [comment]
The root cause of this problem was probably in some strange encoding settings of the underlying shell.

I was able to fix it by changing the windows "Region" settings as described here:
[https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window/57134096#57134096](https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window/57134096#57134096)

I enabled the "Unicode UTF-8" setting and now the Plugin spawns a shell with the correct encoding settings.

**Comment by Den-dp** [comment]
I'm experiencing the same issue on 2 different Windows boxes (one from UA, another from the US) when running `nx run some-app:serve` via Nx Console UI.

Interestingly, the same command works just fine if used via Intellij' terminal (in both powershell and cmd).

Also, I found that `chcp` for both powershell and cmd is 437.

Are we sure that this shouldn't be handled on a plugin's side? 😅
