### ISSUE TITLE
[intellij] nx console empty

### ISSUE THREAD

**Issue by wingy3181** [nrwl/nx-console#1688]
## Current Behavior

Nx Console contents is empty

Example with our project in webstorm (v1.3.2 of Nx Console plugin installed)
![image](https://user-images.githubusercontent.com/1212576/233210273-77c6ef40-f4f0-4011-b76a-b192f3cad000.png)

Example with our project in VSCode (v18.04 of Nx Console extension installed)
<img width="383" alt="image" src="https://user-images.githubusercontent.com/1212576/233210916-3359eb1d-15e2-40eb-8673-5a293d50f4d5.png">

## Expected Behavior

Nx Console contents to be populated with Targets and Projects 

Example with https://github.com/nrwl/nx-workshop
![image](https://user-images.githubusercontent.com/1212576/233210510-b9bf4b90-03cb-4063-9ff9-330259dfd79e.png)

## Steps to Reproduce

1. Open up project
2. Open up Nx Console Tab
3. See empty nx console tab

Have attempted the following to see if it is resolved

- `nx repair` (as I believe some of our nx project files might be corrupt due to previous upgrades being done manually)
- Updated to latest nx 15.9.2 following `nx migrate latest` (and subsequent steps)
- `nx reset`

### Failure Logs / Images / Videos

No logs that i can see in Webstorm problems, etc

#### Operating System
- Mac OS Ventura 13.3.1

#### VSCode
- Nx Console version: 18.0.4
- VSCode version: 1.77.3

#### Webstorm
- Nx Console version: 1.3.2
- Webstorm version: WebStorm 2023.1 / Build #WS-231.8109.174, built on March 28, 2023

#### nx report
```
$ nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.14.2
   OS   : darwin x64
   yarn : 1.22.19
   
   nx : 15.5.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.5.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.1
   @nrwl/esbuild : 15.5.1
   @nrwl/eslint-plugin-nx : 15.5.1
   @nrwl/expo : Not Found
   @nrwl/express : 15.5.1
   @nrwl/jest : 15.5.1
   @nrwl/js : 15.5.1
   @nrwl/linter : 15.5.1
   @nrwl/nest : Not Found
   @nrwl/next : 15.5.1
   @nrwl/node : 15.5.1
   @nrwl/nx-cloud : 15.1.1
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.5.1
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.5.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.5.1
   @nrwl/web : 15.5.1
   @nrwl/webpack : 15.5.1
   @nrwl/workspace : 15.5.1
   @nrwl/vite : 15.5.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @webpro/nx-tsc: 0.0.1

```

Is there any other way I can debug this to provide more information on what the root cause might be?
(that is, it does work with `nx-workshop` project so trying to work out what is invalid in our repo to resolve this...but it works in VSCode)

**Comment by MaxKless** [comment]
This empty tree with an `nx-workspace` root means that we cannot correctly retrieve information about your current workspace. There is probably something wrong with the LSP or an error is thrown somewhere. 

Can you reproduce this error and paste your `idea.log` here? 
I assume you can't somehow give me access to the codebase where this happens? If I had a repro it would be easier to get to the bottom of this.

**Comment by MaxKless** [comment]
Thanks for noticing the cause! 
Yeah as far as we're concerned, that's a malformed `project.json` - the difference between IntellIJ and VSCode is that Kotlin is a lot more strict when it comes to type-safety. So as soon as the target definition doesn't match the object type we expect, it throws an error during parsing. VSCode doesn't care, which is why the parsing still works there. 

How about you just move the comment into the target definition where it shouldn't cause problems like this?

**Comment by wingy3181** [comment]
> Thanks for noticing the cause! Yeah as far as we're concerned, that's a malformed `project.json` - the difference between IntellIJ and VSCode is that Kotlin is a lot more strict when it comes to type-safety. So as soon as the target definition doesn't match the object type we expect, it throws an error during parsing. VSCode doesn't care, which is why the parsing still works there.
> 
> How about you just move the comment into the target definition where it shouldn't cause problems like this?

thanks @MaxKless for the suggestion
Yes that worked
Just double checking that when you say move the comment into the target definition, that you meant this?

```
+  "// custom-target-name-a": "comment explaining use and reasoning for custom target name",
  "targets": {
-  "// custom-target-name-a": "comment explaining use and reasoning for custom target name",
    "custom-target-name-a": {
      "executor": "nx:run-commands",
      "options": {
        "commands": [
            ...
        ]
      }
    }
  }
 //...
 
```

**Comment by MaxKless** [comment]
that, or 
```
  "targets": {
-  "// custom-target-name-a": "comment explaining use and reasoning for custom target name",
    "custom-target-name-a": {
+  "// custom-target-name-a": "comment explaining use and reasoning for custom target name",
      "executor": "nx:run-commands",
      "options": {
        "commands": [
            ...
        ]
      }
    }
  }
 //...
```

not that that's necessarily recommended but it works :P
