### ISSUE TITLE
Limit list of generators and executors

### ISSUE THREAD

**Issue by leonardlinkowski** [nrwl/nx-console#1703]
## Description

Configuration Options to limit the generators and executors offered for execution to the user by the interface.

## Motivation

In our Workflow we use a lot of custom generators that built on top of default generators like @nrwl/nest to provide structuring and additional functionality to the project, like built in features for Docker. These default generators should therefore never be used by our developers. However they can not be made invisible at the moment. This results in unnecessary confusion. 

In addition to that we use executors that are only intended for use inside of the CI-System, like for example a step to publish Containers or apply Infrastructure as Code. Their appearance in the interface is not needed as well.

The implementation of these features would reduce the complexity of the developer experience, especially with larger teams.

## Suggested Implementation

A possible way to limit the generators would be to modify the language Server to limit the given list of generators to a list of whitelisted plugins in the nx.json. After adding an enabled : false attribute to the plugins not needed in the generators section, the generators should be removed from the list. This format is compatible with the existing schema.

### Example
```
{
  "$schema": ...,
  "npmScope": ..,
  "plugins": [],
  "tasksRunnerOptions": {...}
  "generators": {
    "@nrwl/react": {
      enabled": false,
      "application": {
        "babel": true
      },
      "library": {
        "unitTestRunner": "jest"
      }
    },
  }
}
```
As for available executors the attribute CI could be added to the executor in the project.json file. If this is set to true, the executor should not be displayed in the interface.

### Example

```
"publish": {
      "executor": "...",
      "ci": true,
      "options": {
        "outDir": "..."
      }
}
```
Thanks for your Feedback :)

**Comment by MaxKless** [comment]
Hey there 👋 
If you're using VSCode, you can use this feature today. Just go to the extension settings and look for `nxConsole.generatorAllowlist` and `nxConsole.generatorBlocklist`. 
For IntelliJ, we still need to implement this feature. I will try to get to it soon.

**Comment by leonardlinkowski** [comment]
Hi, thanks for your feedback. Since my Team is using IntelliJ I am very much looking forward to the implementation.
Do you have any thoughts on the second suggestion regarding ci only executors? Thanks for your help :)

**Comment by MaxKless** [comment]
Cool, I already started working on it. 

Your second suggestion is about filtering targets from the UI, right? So we wouldn't see some targets in the nx toolwindow or be able to run them from the integration?

**Comment by leonardlinkowski** [comment]
Yes, excluding some targets that are only meant to be run by the ci-system, like for example infrastructure deployments or oci image build with buildpack.

**Comment by MaxKless** [comment]
Yeah that makes sense. On the other hand, there's still value in seeing that these targets exist for a project. Even if you don't want to run it, you might want to look at the config or the graph and see what the target depends on. 
Removing it would take away those use cases.

**Comment by leonardlinkowski** [comment]
Hm.. I have to say I must agree with your argument. As my request is just a "visual" improvement for the developer experience it should not affect other features.
