### ISSUE TITLE
build and run commands not working

### ISSUE THREAD

**Issue by vicatcu** [nrwl/nx-console#1713]
In 18.1.0 when I click Nx -> build, an alert pops up in the bottom right of the screen that "no projects have a target command for build" but of course the cli `nx build` certainly still works. This was working in the previous version 18.0.4 (albeit without presenting a dialog like it does with `generate` commands).

I should still be able to build from Nx console like I have in the past.

## Steps to Reproduce

Not sure if this is something specific about my project or not. It's a monorepo with a single Angular app and a bunch of libs.

### Environment
- VSCode version 1.77.3
- Nx Console version 18.1.0

```
   Node : 18.15.0
   OS   : linux x64
   npm  : 9.6.1
   
   nx : 14.7.3
   @nrwl/angular : 14.8.7
   @nrwl/cypress : 14.7.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.7
   @nrwl/eslint-plugin-nx : 14.7.3
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.7
   @nrwl/js : 14.8.7
   @nrwl/linter : 14.7.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.2.1
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.7
   @nrwl/web : Not Found
   @nrwl/workspace : 14.7.3
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @ionic/angular: 7.0.2
         @nxtend/capacitor: 13.0.0
         @nxtend/ionic-angular: 13.1.0
```

**Comment by louiss0** [comment]
I'm also dealing with the same problem. 

**Nx Console version:** 18.1.0   

The problem begins at the start of 18.0.0 and up. 
**Relevant dependencies**

``` 
"@nrwl/vite": "15.9.2",
 "@nrwl/workspace": "16.0.1",
"@nxtensions/astro": "^3.5.0",

"nx": "16.0.1",
        
```

**Comment by ak274** [comment]
No Project have a target command for test | serve | lint. Nothing is working after updating to latest Nx console

**Comment by dimd13** [comment]
Same problem 
Nx Console v18.1.0
"@nrwl/react": "15.8.7"
"@nrwl/vite": "15.8.7"
"@nrwl/workspace": "15.8.7"
nodejs 18.14.2

VSCODE 
Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:52.732Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.19.0-41-generic snap
Sandboxed: No

**Comment by keaston67** [comment]
I have the same problem after latest update:
VSCode version 1.77.3
Nx Console version 18.1.0

**Comment by my-random-username** [comment]
none of items in nx vscode extension (GENERATE & RUN TRAGET) working after updating to v18.1.0

![image](https://user-images.githubusercontent.com/68753961/235425450-293b0222-f99d-40d8-b6e8-a3c155142de1.png)

also works when I downgrade to version 18.0.4 :
![image](https://user-images.githubusercontent.com/68753961/235425716-fff821b9-9b32-4449-bf73-fd03b77f9524.png)
