### ISSUE TITLE
Add possibility to select nx workspace root (nx.json) in JetBrains IDEs

### ISSUE THREAD

**Issue by jakubwojcik** [nrwl/nx-console#1720]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

NX Console plugin for WebStorm doesn't parse NX configuration if `nx.json` is not in the root directory.

Considering the following project structure:

```
- .git/
- some_common_things/
- src/
-- backend/
-- frontend/
--- src/
--- nx.json
--- ...
```

If you open the project's root, the NX doesn't show any targets or projects.
If you open the project's src/frontend, the NX correctly parses targets and projects.

## Motivation

In the VSCode version of the plugin, I could select the workspace root for this repository structure and had access to common/backend/frontend sources in one IDE window while preserving the possibility to run NX-related tasks for the frontend part of the repo.

I think adding this feature to the JetBrains plugin version will give more flexibility to the developers working with similar repository structures.

## Suggested Implementation

It can look exactly like the VSCode's plugin implementation (when no `nx.json` is detected, there's a button to select the directory with NX configuration).

## Alternate Implementations

I think there's no need for another approach, the existing VSCode version (button if no `nx.json` is detected in the root) is fine.

---

Thanks for considering my request 🙂

**Comment by MaxKless** [comment]
Hi @jakubwojcik, thanks for your input and wanting to make Nx Console better!

This feature exists already, check out the Nx Console settings: 
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/34165455/236449069-c389f283-9428-409a-9e62-f1d059e73c51.png">

It was added in this PR: https://github.com/nrwl/nx-console/pull/1569

make sure you're on the latest version and you should see it :)
