### ISSUE TITLE
Show target configuration gutter icons in IntelliJ

### ISSUE THREAD

**Issue by jakubwojcik** [nrwl/nx-console#1721]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

NX Console plugin for WebStorm doesn't show targets configurations to run under:
- NX Console -> Targets -> $TARGET_NAME -> $PROJECT_NAME 
- NX Console -> Projects -> $PROJECT_NAME -> $TARGET_NAME

I think it's a good idea to implement that as the current NX Console plugin in VSCode has that feature.

## Motivation

Easier access to target configurations defined in the project's project.json.

## Suggested Implementation

It can look exactly like the VSCode's plugin implementation.

## Alternate Implementations

I think there's no need for another approach, the existing VSCode version tree structure is fine.

--- 

Thanks for considering my request 🙂

**Comment by MaxKless** [comment]
You're absolutely right! 
For the toolwindow, this is already enabled on master and should be released soon: https://github.com/nrwl/nx-console/pull/1717

As for the gutters (in `project.json`) it still needs to be done and I will see how soon I can get to it.
