### ISSUE TITLE
"Nx generate..." contextual menu not work to generate a new component

### ISSUE THREAD

**Issue by zaquas77** [nrwl/nx-console#1722]
## Current Behavior

When I try to generate a new angular component through the "Nx generate..." contextual menu, in my "integrated monorepo" project, I receive this complain: 

> The path provided (ngthi/src/app/containers) does not exist under the project root (packages/ngthi). Please make sure to provide a path that exists under the project root."

If I prefix the path with "packages" folder it works

## Expected Behavior
The autocomplete of nx console form would have to fill the "path" field with the correct path

## Steps to Reproduce

1. Create a  empty "integrated monorepo" with `npx create-nx-workspace@latest` command.
2. Adding the `@nrwl/angular` plugin
3. Generate a new angular application with "nx console" utility
4. Create a new angular component through "Nx generate..." contextual menu. 
5. Look in the console log...

### Failure Logs / Images / Videos

<img width="1301" alt="error" src="https://github.com/nrwl/nx-console/assets/40612319/5f6f64ce-e463-4392-b3d1-15760e706671">

### Workaround

<img width="1283" alt="works" src="https://github.com/nrwl/nx-console/assets/40612319/90c9d362-b13a-4692-90d5-ebd35d8df3c4">

### Environment

- Nx Console version: v18.1.1
- VSCode version: 1.78.1 on macOS Monterey 12.6.3

**Comment by MaxKless** [comment]
Hey I'm looking into this :) Do you have anything set in `nx.json` under `workspaceLayout`?

**Comment by seeiuu** [comment]
Hi @MaxKless,

thanks for your interest.

I found this 

> "workspaceLayout": {
    "appsDir": "packages",
    "libsDir": "packages"
  },

it is right?

thanks again.

**Comment by seeiuu** [comment]
Thanks to you. 
Ciao.

**Comment by MaxKless** [comment]
I'm closing this to consolidate discussion in a central issue 👆.
This will be done as the ongoing work in Nx core completes. 

Thanks for the report, @zaquas77
