### ISSUE TITLE
VS Code: e2e flag list truncated after upgrade to nx 16

### ISSUE THREAD

**Issue by CMadden8** [nrwl/nx-console#1723]
## Current Behavior

After upgrading to nx 16, if I select `e2e` in from the nx console UI in VS Code, and I then select the e2e project, I receive a truncated list of flags that no longer shows, for example, `watch `. This means I cannot run the e2e in headless mode.

## Expected Behavior

I should be able to select the `watch ` flag from the list of e2e flag options, as was the case in nx 15.

## Steps to Reproduce

1. Install version 16 of nx
2. Install nx console for VS Code
3. Click e2e from the nx console UI (after creating an e2e project)
4. Select the e2e project
5. Watch is missing from the flag options, among many others

### Failure Logs / Images / Videos

Screenshot of the issue below:

![nx-console-e2e-bug](https://github.com/nrwl/nx-console/assets/7581485/c31267c0-a1b8-434a-9975-64ddfc4e019f)

### Environment

VS Code

- Nx Console version: 16
- VSCode version: 1.78

**Comment by MaxKless** [comment]
Hi @CMadden8 you're completely right that this features needs to be updated. The flags are still written down statically somewhere so it will always be prone to errors. I'll look into making it more robust :)

**Comment by CMadden8** [comment]
Nice one @MaxKless, thanks for the quick response!

**Comment by CMadden8** [comment]
@MaxKless Yes, NX Version 16.1.1 and NX Console version 18.1.1. All of the app `e2e` projects are for Angular applications.

**Comment by CMadden8** [comment]
@MaxKless actually I tested this now with a fresh Angular mono-repo and there are no issues.

The issue occurs on our company Angular mono-repo, and is still there with the latest version of the nx console extension.

Only thing that I see is different is that the nx version for the company mono-repo is lower than the fresh install I just tried. I'll see about upgrading it and will let you know if that fixes it.

**Comment by CMadden8** [comment]
@MaxKless Follow up to the above comment - I tried a fresh install of nx on the Mac and this problem doesn't exist for that either.

Then I tried to create a new project within the company nx repo, and I added an e2e project to it. And it works...

However, it remains broken for the existing e2e projects within the repo. 

I'll have to do some more testing. We do make some slight changes to cypress by adding the cucumber preprocessor - https://github.com/badeball/cypress-cucumber-preprocessor

However, I removed all of that and seemingly have the broken project's config identical to the the working project's config. And it still doesn't generate the missing options...

I will close this ticket if I can't reliably reproduce this over the next few days.

**Comment by CMadden8** [comment]
@MaxKless The issue was the below in the project.json for the e2e projects:

`"executor": "@nrwl/cypress:cypress"`

It needed to be:

`"executor": "@nx/cypress:cypress"`

The commands are now generating correctly again. It seems the migration to V16 of NX missed the update of this, for whatever reason. And since we don't currently use generators for e2e (as we use a custom cypress setup for cucumber), we were copying this broken boilerplate for each e2e.

It seems to be resolved now anyway, so I'm closing the ticket.
