### ISSUE TITLE
[intellij] `Nx Graph: View Full Graph` as a button

### ISSUE THREAD

**Issue by Den-dp** [nrwl/nx-console#1727]
## Description

Show `Nx Graph: View Full Graph` as a button

## Motivation

Looks handy + VSCode has that

## Suggested Implementation

Might look like a button on the tool panel or/and in the "Projects" context menu (which also feels convenient)
![image](https://github.com/nrwl/nx-console/assets/1770529/3d194b2b-6281-46ab-8ffb-baa636fb3eb6)

**Comment by MaxKless** [comment]
I agree, this should be added :) Not super high on the prio list but I'll tackle it when I have time.

**Comment by Den-dp** [comment]
> this would be a good first issue

tbh that's what I thought before creating it, but I gave up since I spent too much time tinkering with my development environment

While installing and configuring Java was pretty easy, I was surprised by how slow was the Maven and JB indexing thing.

And on the top of the pie, I caught a Windows-related issue with a path while trying to run `intellij:runIde`:
https://github.com/nrwl/nx-console/blob/8c3a119abd05f8b147ab4b1c16a0ef0b6889f4dd/apps/intellij/project.json#L9

![image](https://github.com/nrwl/nx-console/assets/1770529/0cf5a986-d966-4cc9-b6e8-305eeb0e315a)

So I would say I'm closer and closer to start learning Kotlin, so maybe one day 🤷

**Comment by MaxKless** [comment]
Well now I made a solution anyways! 
But it's cool that you tried contributing, really appreciate it when ppl from the community step up :) 

Interesting issue, I'm trying to get my hands on a windows machine and will try to fix it when I have one.

**Comment by Cammisuli** [comment]
@Den-dp its much more effective to use IntelliJ to run the plugin through Gradle with the "Run Plugin" gradle task:
<img width="243" alt="image" src="https://github.com/nrwl/nx-console/assets/4332460/34b49b21-1b27-43ac-a6c9-f0385c8cf770">
