### ISSUE TITLE
[intellij] Enable grouping projects by folder in toolwindow

### ISSUE THREAD

**Issue by Den-dp** [nrwl/nx-console#1728]
## Description

Show apps/libs (and grouping folders) for big workspaces

![image](https://github.com/nrwl/nx-console/assets/1770529/3599d2e5-d337-40fc-ba22-215836334722)

## Motivation

it simplifies navigation

## Suggested Implementation

Similar to what we already have in VSCode

![image](https://github.com/nrwl/nx-console/assets/1770529/3c4f03dd-75ff-45af-9b38-3f16f1231243)

## Alternate Implementations

Add a "Group By Directory" button somewhere on the Nx Console tool panel.

F.e. here is a similar feature from the Commit panel:
![image](https://github.com/nrwl/nx-console/assets/1770529/61f13915-d7a1-457b-9ac6-35fe5451618b)

**Comment by MaxKless** [comment]
I agree, this is on my to-do list already.

**Comment by jvskriubakken** [comment]
Great! Looking forward to use this feature in Jetbrains Rider :)

**Comment by ctaepper** [comment]
yes, that would really improve the DX by a lot on large workspaces. this is really the only thing working much better in vscode as compared to webstorm... endless scrolling through 100s of projects :(

**Comment by MaxKless** [comment]
yes it will come I just haven't found the time for it :) 
We're open to contributions too!

**Comment by MaxKless** [comment]
This is added with https://github.com/nrwl/nx-console/pull/1814
Let me know what you think once it releases :)
