### ISSUE TITLE
[intellij] Context menu Nx Refactorings should prefill the selected project name

### ISSUE THREAD

**Issue by Den-dp** [nrwl/nx-console#1729]
## Description

Context menu Refactorings such as "Move Nx Project" and "Remove Nx Project" should prefill the selected project name (if possible)

![image](https://github.com/nrwl/nx-console/assets/1770529/6a6fc021-9159-48d9-adb5-a6a1b9bdfb3a)

## Motivation

Typing the project name after right-clicking on it feels lame

## Suggested Implementation

Prefill the project in this dialog

![image](https://github.com/nrwl/nx-console/assets/1770529/f32047a6-6756-4f66-bc60-22d1e5946072)

**Comment by MaxKless** [comment]
hmmm this was working in the past, looks like a regression. I'll try to reproduce.

**Comment by MaxKless** [comment]
Hey! 
I have a feeling this was fixed in https://github.com/nrwl/nx-console/pull/1792, can you check @Den-dp ?

**Comment by MaxKless** [comment]
I just tried reproducing this on my windows machine, worked for me. 
Let me know if it's still broken for you :)

**Comment by Den-dp** [comment]
@MaxKless now it works for me on windows 🎉

Thanks and sorry for the delay
