### ISSUE TITLE
VSCode: background resources consuming even after quit VSCode

### ISSUE THREAD

**Issue by mordgard** [nrwl/nx-console#1731]
## Current Behavior
When I completely quit the editor, seems that NX plugin continue to run in the background. I've tried to disable all the plugins one by one, and only NX plugin still continue to run after quit VSCode (cmd+q). If I disable this plugin, it doesn't appear in the running processes anymore after quit the editor.

## Expected Behavior
It shouldn't be alive after quitting the editor.

## Steps to Reproduce
Just enable this plugin and completely quit VSCode, then open Activity Monitor and in the Memory tab type "code" to find the running process.

### Failure Logs / Images / Videos
<img width="476" alt="Screenshot 2023-05-15 at 11 26 27 AM" src="https://github.com/nrwl/nx-console/assets/22856938/522182ee-377b-4c72-ab0a-32337825c1fa">

### Environment
MacOS: 13.3.1 2023 M2

- Nx Console version: 18.1.1
- VSCode version: 1.78.2

**Comment by MaxKless** [comment]
@Cammisuli could this be related to the nxls debugging problems we had recently? Maybe it's still not shutting down correctly.

**Comment by Cammisuli** [comment]
Interesting.. It could be related, but that issue is a real pain in the butt 😓

**Comment by mordgard** [comment]
Is there any plans to solve this? 👉👈 Cuz it's really annoying issue

**Comment by Cammisuli** [comment]
Of course, but it's a very tricky issue because we're not doing anything special to launch the lsp. We're using the official VSCode apis, so it's a bit challenging to get right. 

I'm annoyed at it too, so it'll get fixed 😅

**Comment by MaxKless** [comment]
I think this has to do with @parcel/watcher... maybe we're not shutting it down correctly. 
This is the open files & ports on one of those leftover processes: 
```
/Users/maxkless/Projects/nx-console
/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin)
/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle
/Library/Preferences/Logging/.plist-cache.t80UKCYx
/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/ReactiveObjC.framework/Versions/A/ReactiveObjC
/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/v8_context_snapshot.arm64.bin
/Users/maxkless/.vscode-insiders/extensions/nrwl.angular-console-17.28.2/node_modules/@parcel/watcher/prebuilds/darwin-arm64/node.napi.glibc.node
/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib
/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/icudtl.dat
/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
/usr/share/icu/icudt70l.dat
->(none)
->(none)
->(none)
/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/icudtl.dat
count=0, state=0xa
->0x78f0e34ff6e3c98f
->0x7000c6bb28d9bc2c
->0xe806ee2d8381bff2
->0x15e45c8ec91e9bfa
->0xeb7faed011f91934
->0xba380b3bd5d693c9
/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/v8_context_snapshot.arm64.bin
count=0, state=0
->0x3517f0af0cfb8be7
->0xeb152ab923cf517d
->0xf4375a5ac549e7ef
->0xd12d8baa3f983e1e
count=0, state=0xa
->0xf6f79f3377f5f4f3
->0x94a5dab26b23558f
->0x13cd40ee5849440c
->0xb8c2016693ee8531
count=0, state=0x12
/dev/null
```

**Comment by MaxKless** [comment]
hey @devongovett sorry to ping you like this. Feel free to ignore but I've seen you in this repo so I thought you might be interested.

Do you have any idea what could cause our `@parcel/watcher` subscription to stay alive even after we cancel it? 

We're watching for changes like this:
```ts
export async function languageServerWatcher(
  workspacePath: string,
  callback: () => unknown
): Promise<() => void> {
  const subscription = await watcher.subscribe(
    workspacePath,
    (err, events) => {
      if (err) {
        lspLogger.log('Error watching files: ' + err.toString());
      } else if (
        events.some(
          (e) =>
            e.path.endsWith('project.json') ||
            e.path.endsWith('package.json') ||
            e.path.endsWith('nx.json') ||
            e.path.endsWith('workspace.json')
        )
      ) {
        lspLogger.log('Project configuration changed');
        debounce(callback, 500)();
      }
    },
    watcherOptions(workspacePath)
  );

  return () => {
    lspLogger.log('Unregistering file watcher');
    subscription.unsubscribe();
  };
}
```

I've confirmed that the `unsubscribe` call is happening, but no idea why there's still an active process holding on to that `.node` file... any clue?
