### ISSUE TITLE
After executing `npx nx migrate latest` nx.console no longer can find workspace

### ISSUE THREAD

**Issue by cforsyth68** [nrwl/nx-console#1737]
### Current Behavior

After executing `npx nx migrate latest` to migrate form @nrwl to @nx 16 packages, NX Console VS Code Extension no longer functions. It asks me to change workspace, but fails to connect to the workspace. Refresh does nothing.

### Expected Behavior

NX.Console tools should still be connected to my NX monorepo after migrating to nx 16 packages.

### Steps to Reproduce

1. Start with a working NX monorepo (using nx.json) that was using @nrwl packages
2. Execute `npx nx migrate latest`
3. Execute `npx nx migrate --run-migrations`
4. Click on the NX console in VS Code sidebar

Expected result, NX console should connect and provide commands the same way as it did prior to upgrade

Actual result, NX console fails to connect to the workspace.

Attempts to "change workspace" do nothing to solve the problem.

### Nx Report

```shell
Node   : 14.19.1
   OS     : darwin x64
   npm    : 6.14.16
   Hasher : Native
   
   nx                 : 16.1.4
   @nx/js             : 16.1.4
   @nx/jest           : 16.1.4
   @nx/linter         : 16.1.4
   @nx/workspace      : 16.1.4
   @nx/cypress        : 16.1.4
   @nx/devkit         : 16.1.4
   @nx/eslint-plugin  : 16.1.4
   @nx/react          : 16.1.4
   @nx/rollup         : 16.1.4
   @nx/storybook      : 16.1.4
   @nrwl/tao          : 16.1.4
   @nx/web            : 16.1.4
   typescript         : 5.0.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by MaxKless** [comment]
did you try running 'nx reset'?

**Comment by cforsyth68** [comment]
> did you try running `nx reset`?

I upgraded my version of NX Console to latest, that resolved this issue.

But now I am running into massive problem rabbit holes related to peer deps mismatched and other things.  I was so hoping the migration scripts would help. This upgrade is frustrating, we can't afford 5 days to work out all the kinks. 😞

**Comment by MaxKless** [comment]
Glad the console issue resolved itself. 
Regarding the update, if there's anything wrong with the migrators or nx in general, I'm sure the team at `nrwl/nx` would be happy to help out :) 
Just open a new issue with the details and ideally a reproduction :)
