### ISSUE TITLE
Log In to Nx Cloud button does nothing in VSCode

### ISSUE THREAD

**Issue by vladorbulescu** [nrwl/nx-console#1739]
## Current Behavior

Cloning a repo that has Nx Cloud configured and trying to log in to Nx Cloud by clicking the button in Nx Console does not work with VsCode. I am clicking the button (see images) and nothing happens. 

## Expected Behavior

I guess it should open a window in the browser where I could log in.

## Steps to Reproduce

As stated in the "Environment" section and in the "Current Behavior" I'm using VsCode. Open Nx Console and navigate to NX CLOUD.
Clicking on 'Log In to Nx Cloud' does nothing.

### Failure Logs / Images / Videos

This is the button I am referring to:
![image](https://github.com/nrwl/nx-console/assets/133101718/5fffab19-b4bc-4b7a-9763-7d491a1a629d)

### Environment

**Nx report:**
```
   Node   : 18.16.0
   OS     : win32 x64
   pnpm   : 8.5.1
   Hasher : Native
   
   nx                 : 16.1.4
   @nx/js             : 16.1.4
   @nx/jest           : 16.1.4
   @nx/linter         : 16.1.4
   @nx/angular        : 16.1.4
   @nx/cypress        : 16.1.4
   @nx/devkit         : 16.1.4
   @nx/eslint-plugin  : 16.1.4
   @nrwl/tao          : 16.1.4
   @nx/web            : 16.1.4
   @nx/webpack        : 16.1.4
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
```

- Nx Console version: 18.1.1
- VSCode version: 1.78.2

Thank you very much for your time!

**Comment by MaxKless** [comment]
No problem at all :) Please open a new issue once you find a reproducible bug. 
I'm sure there's some constellations where bugs can be found. Next time you can also try the refresh button on top of the webview, which should reload everything and hopefully fix any issues with modified `nx.json` etc.

Have a wonderful weekend :)
