### ISSUE TITLE
Able to group projects by directory structure

### ISSUE THREAD

**Issue by jvskriubakken** [nrwl/nx-console#1748]
## Description

In the lists that now lists all projects flat, it would be nice to if they projects could be grouped by the directories they reside in.

```
appgroup-app1-client-ts
appgroup-app1-webapp-cs
appgroup-app2-client-ts
appgroup-app2-functions-cs
appgroup-app2-webapp-cs
```

```
firefly
  app1
    client-ts
    webapp-cs
  app2
    client-ts
    functions-cs
    webapp-cs
```

## Motivation

When I am working on an app or a group of apps it would be easier to find the projects under: Targets -> serve/lint/test

## Suggested Implementation

Add a button in toolbar where you can choose to group projects on directory

**Comment by MaxKless** [comment]
Closing this as a duplicate of https://github.com/nrwl/nx-console/issues/1728 :) 
If you're using VSCode, this feature exists already. Check out `nxConsole.projectViewingStyle`
