### ISSUE TITLE
Multiple terminal popups on Windows, NxConsole Webstorm Plugin

### ISSUE THREAD

**Issue by michaelbromley** [nrwl/nx-console#1751]
## Current Behavior

When I have the NxConsole Webstorm plugin enabled and Webstorm running, running any Nx command in a separate Windows Terminal tab will trigger multiple popups. See this video for a demo:

https://github.com/nrwl/nx-console/assets/6275952/5d318c99-446e-437e-a07c-27be49b6e311

If I disable the NxConsole plugin, this no longer occurs.

Relates to

- https://github.com/nrwl/nx/issues/16876
- https://github.com/nrwl/nx/issues/10822#issuecomment-1426849595

## Expected Behavior

No popups.

## Steps to Reproduce

Have Webstorm running with the NxConsole plugin enabled, run an `nx run ...` command.

### Environment

- Nx Console version: 1.5.0 (Webstorm)
- Webstorm version: 2023.1.2
- Windows 11 22H2
- Node v16.9.1

**Comment by MaxKless** [comment]
Yeah this doesn't really surprise me, we probably have to toggle a setting where the scripts are run. 
Maybe @Cammisuli you can look at it while I don't have a windows laptop yet?

**Comment by Cammisuli** [comment]
Yea, it's annoying 😅 

Basically, when trying to run commands with `exec`, `spawn`, `fork` with Node on Windows, a cmd is created behind the scenes. With these exec functions, they accept a parameter called `hideWindows`, that's not true by default 😒, setting this to true, will hide those popups. 

Nx Console doesn't use these functions, but Nx Core itself does. I just recently went through some of the core to fix these, and those fixes are in 16.3.

If you update to 16.3 and are still seeing those popups, let us know, and we can investigate it further.

**Comment by michaelbromley** [comment]
@MaxKless not yet. I'll have some time to update and try it out in the coming week or so, and I'll update this issue when I do.

**Comment by michaelbromley** [comment]
I just updated to 16.3.2 and this looks to be fixed now, thanks!

**Comment by LironHazan** [comment]
We see it happens with 16.8.1 as well actually, no directly related to webstorm terminal, any terminal, we tried to downgrade to 16.3.2 globally but same result @MaxKless any advice pls?

**Comment by MaxKless** [comment]
That's probably not an Nx Console issue but nx itself. If you upgrade to latest, these should all go away afaik

**Comment by LironHazan** [comment]
> That's probably not an Nx Console issue but nx itself. If you upgrade to latest, these should all go away afaik

Yes thanks sorry, I was navigating between GitHub issues and thought I was commenting on the Nx repo :|

**Comment by francobasilico** [comment]
Hi, I started to experience this since migrating to the latest version of nx
Node   : 20.13.1
OS     : win32-x64
yarn   : 1.22.22

nx                 : 19.5.3
@nx/js             : 19.5.3
@nx/jest           : 19.5.3
@nx/linter         : 19.5.3
@nx/eslint         : 19.5.3
@nx/workspace      : 19.5.3
@nx/angular        : 19.5.3
@nx/devkit         : 19.5.3
@nx/esbuild        : 19.5.3
@nx/eslint-plugin  : 19.5.3
@nx/nest           : 19.5.3
@nx/node           : 19.5.3
@nx/playwright     : 19.5.3
@nx/plugin         : 19.5.3
@nrwl/tao          : 19.5.3
@nx/vite           : 19.5.3
@nx/web            : 19.5.3
@nx/webpack        : 19.5.3
typescript         : 5.5.4

**Comment by MaxKless** [comment]
Could you create a new issue in the nx repo with more information and a repro? On my windows machine, `19.5.3` doesn't have any windows popups.

**Comment by mklueh** [comment]
Facing the same when running `nx g app` and it also happened a lot with the Intellij Nx Plugin so I had to disable it, because the terminal windows stayed open
