### ISSUE TITLE
Nested folders libs don't show in the projects

### ISSUE THREAD

**Issue by fmontes** [nrwl/nx-console#1753]
## Current Behavior

If you create a `library` inside a folder, like `/libs/nested/my-lib` the library, don't show in the projects panel

<img width="750" alt="image" src="https://github.com/nrwl/nx-console/assets/751424/cb7b6a57-333e-46e5-9e0e-01cb9dcd2bd3">

## Expected Behavior

Even nested folder libraries should be accessible from the projects panels.

## Steps to Reproduce

1. Generate a library
2. In the **directory** field add a nested path `nested/mylib`
3. Go to the "Projects" in the Nx Console and see the new library is not showind.

### Environment

- Nx Console version: 18.1.2
- VSCode version: 1.78.2 (Universal)

**Comment by fmontes** [comment]
Also, the inline links to run the commands in the `projects.json` are not showing.

<img width="888" alt="image" src="https://github.com/nrwl/nx-console/assets/751424/4402a398-bbfb-420a-9192-b9542f35441f">

**Comment by MaxKless** [comment]
Hey can you tell me what Nx version this is? 
If you have a repro that would be perfect too :)

**Comment by fmontes** [comment]
Hey @MaxKless thanks for the reply, I don't what happened but started to work. Thanks for the reply, closing this one.

**Comment by qFamouse** [comment]
As I understand it, the display will change depending on the number of libraries, projects, etc. you have created.

If it is >= 10 then the nesting will be displayed
