### ISSUE TITLE
createProjectFileMapUsingProjectGraph is not a function

### ISSUE THREAD

**Issue by luchillo17** [nrwl/nx-console#1758]
## Current Behavior

Can't find the projects, not sure how it happened, regardless whether I open a VSCode workspace with a NX monorepo inside or directly opening the NX monorepo.

![image](https://github.com/nrwl/nx-console/assets/9698639/4fcbd4b6-b1b7-4214-b213-dd493b30cc7e)

## Expected Behavior

Should find the project regardless if inside a monorepo or in a VSCode workspace with multiple folders.

## Steps to Reproduce

Yes I can reproduce it with the `nx-example` indeed.

![image](https://github.com/nrwl/nx-console/assets/9698639/cb525661-440a-40df-a7e2-495f909178ab)

### Failure Logs / Images / Videos

```sh
[Nxls] - 2023-06-09T04:21:47.599Z - Retrieving workspace configuration

[Nxls] - 2023-06-09T04:21:47.600Z - Using local Nx package at /home/carlos/Projects/graph-meister/node_modules/nx/src/project-graph/file-utils.js

[Nxls] - 2023-06-09T04:21:47.600Z - Using local Nx package at /home/carlos/Projects/graph-meister/node_modules/nx/src/project-graph/project-graph.js

[Nxls] - 2023-06-09T04:21:47.600Z - Using local Nx package at /home/carlos/Projects/graph-meister/node_modules/nx/src/utils/output.js

[Nxls] - 2023-06-09T04:21:47.600Z - Using local Nx package at /home/carlos/Projects/graph-meister/node_modules/nx/src/project-graph/file-map-utils.js

[Nxls] - 2023-06-09T04:21:47.602Z - createProjectGraphAsync

[Nxls] - 2023-06-09T04:21:47.618Z - createProjectGraphAsync successful

[Nxls] - 2023-06-09T04:21:47.618Z - Unable to get nx workspace configuration: TypeError: H?.createProjectFileMapUsingProjectGraph is not a function
```

### Environment

- Nx Console version: v18.2.0
- VSCode version: 1.79.0
- WSL2 Ubuntu with remote plugin
```
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.2 LTS on Windows 10 x86_64
    .ossssssssssssssssssdMMMNysssso.       Kernel: 5.15.90.1-microsoft-standard-WSL2
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Uptime: 9 hours, 58 mins
  +ssssssssshmydMMMMMMMNddddyssssssss+     Packages: 799 (dpkg), 9 (snap)
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Shell: zsh 5.8.1
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Adwaita [GTK3]
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Icons: Adwaita [GTK3]
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Terminal: Windows Terminal
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: Intel i9-9900K (16) @ 3.600GHz
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   GPU: 4d27:00:00.0 Microsoft Corporation Device 008e
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Memory: 6376MiB / 15960MiB
```

**Comment by MaxKless** [comment]
I'll have a look! What Nx version did you test it with?

**Comment by luchillo17** [comment]
If it's the example project I cloned it today, not sure what version it is, but my project uses `"@nx/next": "16.3.0",`

**Comment by MaxKless** [comment]
I got it! Looks like the behavior was changed between 16.3.0 and 16.3.1. So what you can do right now is update to latest (which is just 3 patch versions) and it will work again. 
I'm also making a PR to differentiate between the patch versions to make sure this error doesn't happen again.

Thanks for the report!
