### ISSUE TITLE
Goland error

### ISSUE THREAD

**Issue by aarifkhamdi** [nrwl/nx-console#1762]
## Current Behavior

If you press "shift" twice in goland with this plugin, error is occurred and search tab is not showing

## Expected Behavior

"shift" double press opens search tab

## Steps to Reproduce

install goland, install nx console plugin, press "shift" twice

### Failure Logs / Images / Videos

org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request nx/generators failed with message: ENOENT: no such file or directory, stat '/Users/USER/Development/PROJECT/node_modules/default-exclude'
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at dev.nx.console.nxls.NxlsWrapper.start$lambda$7$lambda$6(NxlsWrapper.kt:94)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

### Environment

   ```
Node   : 18.16.0
   OS     : darwin arm64
   pnpm   : 8.5.1
   Hasher : Native
   
   nx                 : 16.1.1
   @nx/js             : 16.1.1
   @nx/jest           : 16.1.1
   @nx/linter         : 16.1.1
   @nx/workspace      : 16.1.1
   @nx/angular        : 16.1.1
   @nx/cypress        : 16.1.1
   @nx/devkit         : 16.1.1
   @nrwl/devkit       : 15.9.3
   @nx/eslint-plugin  : 16.1.1
   @nx/nest           : 16.1.1
   @nx/node           : 16.1.1
   @nrwl/tao          : 16.1.1
   @nx/webpack        : 16.1.1
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @ngneat/transloco           : 4.2.6
   @nguniversal/builders       : 16.0.0
   @nguniversal/express-engine : 16.0.0
   @nx-go/nx-go                : 2.7.0
   @nx-tools/nx-container      : 4.0.3
   @nx-tools/nx-prisma         : 4.0.3
   @rx-angular/template        : 2.0.0
   @taiga-ui/cdk               : 3.27.0
   @taiga-ui/core              : 3.27.0
   ---------------------------------------

```

- Nx Console version: 1.6.1
- Goland version: 2023.1.2

**Comment by MaxKless** [comment]
Hm, I can't repro this in other JetBrains IDEs... I will look at it but have you force deleted `node_modules` and cleared the npm cache?

**Comment by aarifkhamdi** [comment]
I use pnpm

I tried `rm -rf node_modules/ && pnpm store prune && pnpm i` after your comment, but it didn't help

**Comment by MaxKless** [comment]
This is SUCH a weird error, we're not using any dependency called `default-exclude` nor are any of our transitive dependencies... I can't repro it either so sorry that I have no idea how to fix this. 
You've tried reinstalling Nx Console?

**Comment by aarifkhamdi** [comment]
I thought the problem was related to this plugin, because Goland wrote that the problem arose in this plugin

I reset system to default settings, then install Goland and this plugin, and problem disappeared

**Comment by aarifkhamdi** [comment]
Oops. Closed too early

https://github.com/aarifkhamdi/nx-issue-goland here is repository to reproduce the error

try install dependencies, then "double shift"

**Comment by MaxKless** [comment]
Thanks for the repro, I understand it now. 
It's happening because we're trying to read the package.json from the default_exclude file but because it doesn't exist this error pops up
