### ISSUE TITLE
"Log In to Nx Cloud" button does nothing in VSCode

### ISSUE THREAD

**Issue by joeldbirch** [nrwl/nx-console#1765]
I am having the [same issue as this closed one](https://github.com/nrwl/nx-console/issues/1739) with my fairly new integrated monorepo. It worked for a while, but I think this issue arose around the time I used the button to login and accidentally used the wrong login method (Github rather than Google).

I have tried:

- reinstalling VS Code
- reinstalling NX Console
- `nx reset`
- refreshing workspace and NX Console views
- adjusting nx.json to bare minimum (attached screenshot)
- checked devtools for errors (attached screenshot)
- logging out of nx-cloud via the UI, etc.
- everything else I can think of.

   Node   : 18.15.0
   OS     : darwin arm64
   pnpm   : 8.6.2
   Hasher : Native

   nx                 : 16.2.2
   @nx/js             : 16.2.2
   @nx/jest           : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/cypress        : 16.2.2
   @nx/devkit         : 16.2.2
   @nx/esbuild        : 16.2.2
   @nx/eslint-plugin  : 16.2.2
   @nx/plugin         : 16.2.2
   @nx/react          : 16.2.2
   @nrwl/tao          : 16.2.2
   @nx/vite           : 16.2.2
   @nx/web            : 16.2.2
   @nx/webpack        : 16.2.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Local workspace plugins:
   	 @myorg/s-admin
   	 @myorg/s-nx

<img width="700" alt="Screenshot 2023-06-14 at 12 41 31 pm" src="https://github.com/nrwl/nx-console/assets/75602/b5662c30-8db7-4f3e-95b5-1184a5ab77a0">
<img width="766" alt="Screenshot 2023-06-14 at 12 43 44 pm" src="https://github.com/nrwl/nx-console/assets/75602/6d443ef6-e1cb-48be-a330-3b779b2caadf">

**Comment by MaxKless** [comment]
Hmm, usually there are errors in the console when the login process doesn't work. I can't repro it on my machine either but here's some more questions: 
- What Nx Console version are you on?
- Does the same happen in a fresh nx repo on your machine? Or just the one you're in? 
- Have you logged out of GitHub on the browser? Since you accidentally signed in there it might have an effect (probably a long shot as you logged out of Nx Cloud but still).

**Comment by joeldbirch** [comment]
Thanks for your reply!

> What Nx Console version are you on?

Nx Console v18.2.1

> Does the same happen in a fresh nx repo on your machine? Or just the one you're in?

Thanks for the suggestion. I created a new integrated monorepo and yes, the NX Cloud section of NX Console has the exact same behaviour. "Remote cache" icon is green (I connected to NX Cloud successfully), but the "Log In to Nx Cloud" button still does nothing when clicked. I don't see the recent runs even though they are clearly connected, as I can see them in the NX Cloud app.

> Have you logged out of GitHub on the browser? Since you accidentally signed in there it might have an effect (probably a long shot as you logged out of Nx Cloud but still).

I have tried logging out of GitHub, but no change. Also logged out of Google, again no change.

I have just now tried creating a new VS Code profile with only NX Console extension installed. Again, same behaviour and zero errors in the developer tools.

However, when I download VS Code Insiders app, the NX Console login button does finally prompt me to login and successfully shows me the recent runs!

I'm not sure what that means. Maybe there is an NX Console setting being saved to the app preferences? (I don't know what I'm talking about).

Thanks again for your interest.

**Comment by MaxKless** [comment]
Yeah that's a good point, it seems likely that something like this happened. 
During development I had a command to manually clear the sessions and tokens from vscode in case I messed something up during development. 
It seems totally possible that some faulty values were put into the cache and now they're screwing things up for you. 

I've made a PR that adds that manual session clearing - once it lands please try it and let me know if that fixes things for you :) 
https://github.com/nrwl/nx-console/pull/1769

**Comment by joeldbirch** [comment]
That sounds promising, thank you! I’ll look forward to trying it and will let you know how it goes.

**Comment by joeldbirch** [comment]
I see this is merged, but I'm not seeing how to trigger it. Maybe we are still awaiting a release.

**Comment by MaxKless** [comment]
yeah release should come soon

**Comment by MaxKless** [comment]
it's released, can you check it if it helps?

**Comment by joeldbirch** [comment]
It has! Thanks so much.

It opened the website to login, and I chose the right account. Then it sent me back to VS Code, but the NX Cloud sidebar still showed the login button, etc. I clicked it to try again and redid the same process, and this time I clicked the small "don't ask again" link at the bottom of the prompt that appears after login sends you back to VS Code, and now I can see the "Runs" list, as normal.

Cheers!

**Comment by MaxKless** [comment]
Hmmmm can you reproduce it? 
If so, does refreshing the webview fix it?

**Comment by joeldbirch** [comment]
I can't reproduce it, but I'll be helping some team members fix the same issue later in the week. I'll keep a closer eye on what happens and attempt to refresh the webview prior to doing a second login. Thanks again!

**Comment by MaxKless** [comment]
Ok cool! Let me know if anything else comes up
