### ISSUE TITLE
Plugin causes Webstorm to freeze on closing project if running Nodejs v10

### ISSUE THREAD

**Issue by geraldcsoftware** [nrwl/nx-console#1766]
## Current Behavior
If Nodejs v10 is installed, and I open Webstorm IDE with the plugin active, when I try to close the project/IDE window, the IDE hangs with a window "Closing project" open, until process is terminated via Task Manager.

This only happens with Nodejs v10. I tried Nodejs v16 and v18, and the issue did not reproduce with these versions.

## Expected Behavior

I expect the IDE to close without freezing, irrespective of Node version installed.

## Steps to Reproduce

1. Install Nodejs v10, and webstorm IDE
2. Install Nx Console plugin on webstorm IDE
3. Open a project in Webstorm IDE (or even an empty directory)
4. Close the IDE (File -> Close Project, or [X] button in top right corner)
5. A popup window with message "Closing project" appears, and hangs indefinitely until process is killed.

### Failure Logs / Images / Videos

Please see issue [here](https://youtrack.jetbrains.com/issue/WEB-61364/Close-project-freezes) where I initially reported to Jetbrains.

### Environment

- OS: Windows 11.0
- WebStorm Version: 2023.1.2
- Nx Console Version: 1.5.0
- NodeJs version: 10

**Comment by MaxKless** [comment]
Hi, when you say "Install Node v10", do you mean 
- having it installed to your system, or
- having it selected as your node interpreter in webstorm? (see image below)

Also, may I ask why you want to use Node v10 in the first place?

<img width="615" alt="image" src="https://github.com/nrwl/nx-console/assets/34165455/660ba0b7-8dd3-4b43-b5d7-4a9ec672354c">

**Comment by geraldcsoftware** [comment]
Yes to both, see screenshots below.

I need nodejs 10 for a legacy project, I cannot change it for the time being.

![image](https://github.com/nrwl/nx-console/assets/16701085/b8446bfb-f5d3-40f1-a919-661a3ebbfd74)
![image](https://github.com/nrwl/nx-console/assets/16701085/ae5cf45d-dd04-40b4-b8ac-250c4812066c)

**Comment by MaxKless** [comment]
I'm sorry but Node 10 is just too old for us to support. 
You can have a look at the Nx + Node compatibility matrix here:
https://nx.dev/packages/workspace/documents/nx-nodejs-typescript-version-matrix
