### ISSUE TITLE
Opening a non-Nx project in Webstorm 2023.1.2 keeps you from closing Webstorm

### ISSUE THREAD

**Issue by jahumes** [nrwl/nx-console#1773]
## Current Behavior

When used with a project that doesn't contain an Nx workspace, or have a node_modules folder, it has an error message "There was a problem analyzing the current workspace." If I refresh the workspace, there is an error. This breaks the IDE because when I try to close the project, it opens a window that says "Closing Project" with a progress bar that never goes away. This causes the whole IDE to be unusable since Webstorm doesn't allow you to work while a progress bar modal is open. This also requires me to force restart the IDE but the project returns. It keeps me from being able to close Webstorm at all while this project is open and this extension is enabled.

## Expected Behavior

I expect the IDE to be able to close projects that don't have Nx installed or even a node_modules folder.

## Steps to Reproduce

1. Install Nx Console
2. Open a project without a node_modules folder

### Failure Logs / Images / Videos

![Screenshot 2023-06-20 at 8 11 50 AM](https://github.com/nrwl/nx-console/assets/2252877/21e3c957-1342-4eb9-9641-f548fb525e46)
![Screenshot 2023-06-20 at 8 12 26 AM](https://github.com/nrwl/nx-console/assets/2252877/3fe0861f-1c0f-4f9b-bbd6-e7f1c23ed438)
![Screenshot 2023-06-20 at 8 12 43 AM](https://github.com/nrwl/nx-console/assets/2252877/3b34cedb-03ad-4fb8-b59a-c31016562e6f)
![Screenshot 2023-06-20 at 8 13 04 AM](https://github.com/nrwl/nx-console/assets/2252877/4a95db0e-de15-491c-b0ea-b138019bea7b)

### Environment

- Nx Console version: 1.6.1
- Webstorm 2023.1.2
- This is a project without nx or even a package.json or node_modules

**Comment by MaxKless** [comment]
Thanks for the report :) What OS is this?

**Comment by jahumes** [comment]
Ventura 13.4 and Apple M1 Max

**Comment by jahumes** [comment]
Any updates on this?

**Comment by MaxKless** [comment]
sorry, been busy but it's on my radar :) will check it out asap!

**Comment by MaxKless** [comment]
Sorry but I can't reproduce this on my end. Do you have any more info or even a minimal repro I could try out? 
That would be a huge help.
