### ISSUE TITLE
Little inline buttons to run commands aren't showing up anymore

### ISSUE THREAD

**Issue by tnrich** [nrwl/nx-console#1782]
I don't know where the little grey buttons to run nx commands went:

![image](https://github.com/nrwl/nx-console/assets/2730609/71a63f89-84ca-40e1-a67d-0de146e94bbc)

### Environment

- Nx Console version: v18.2.1
- VSCode version: 1.79.2 

Thanks!

**Comment by MaxKless** [comment]
hey! 
i just saw this issue too but wasn't able to 100% repro. 
Something probably changed between versions, I'll have a look tomorrow :)

**Comment by MaxKless** [comment]
can you let me know what version of Nx you're using?

**Comment by MaxKless** [comment]
can you let me know what version of Nx you're using?

**Comment by tnrich** [comment]
@MaxKless 

"nx": "16.4.0",

Yeah must've been from my update of nx recently. Thanks for looking into this

**Comment by tnrich** [comment]
@MaxKless thanks for the quick fix! Lemme know when it gets released! 🙏

**Comment by tnrich** [comment]
@MaxKless it looks like the button are back but they aren't actually working when I press them - 
<img width="472" alt="image" src="https://github.com/nrwl/nx-console/assets/2730609/403ed481-2cad-4888-a370-b1c53f31df39">

You seeing that as well?

**Comment by MaxKless** [comment]
yes and it's already fixed, sorry about that. I messed up during a rework. 
We'll release the fix soon
