### ISSUE TITLE
Nx buttons in project.json stopped working with version 18.3.0 of Nx Console

### ISSUE THREAD

**Issue by tomschreck** [nrwl/nx-console#1800]
## Current Behavior

With upgrading to version `18.3.0` Nx Console in Visual Studio Code, the buttons in `project.json` above each target have stopped working.

## Expected Behavior

I expect the buttons above each target to work in project.json.

## Steps to Reproduce
- install version `18.3.0` of Nx Console in Visual Studio Code
- attempt to invoke a button in project.json

I downgraded to version `18.2.1` of Nx Console in VSC and buttons started working again.

### Failure Logs / Images / Videos

![image](https://github.com/nrwl/nx-console/assets/2521463/ac1341ef-1088-4ef5-a3b9-f8b5b080ac97)

### Environment

Visual Studio Code

![image](https://github.com/nrwl/nx-console/assets/2521463/5da3c8a4-8fe2-4ae1-acd4-fb839ecb7a3d)

- Nx Console version:  18.3.0
- VSCode version: 
- Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:33.551Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 21.6.0

**Comment by MaxKless** [comment]
Hey thanks for the report! This was an oversight by me and is already fixed with https://github.com/nrwl/nx-console/pull/1795

We'll release it ASAP and get it working again. Sorry!
