### ISSUE TITLE
Nx Console does not execute Nx tasks in a pnpm managed monorepo

### ISSUE THREAD

**Issue by peterstockwell-sagov** [nrwl/nx-console#1802]
Hello, we recently migrated from npm to pnpm as our package manager for our monorepo. After migrating, we are no longer able to use Nx Console to execute any tasks defined in any `project.json` file. Nx Console is still able to find all of our tasks, but the "execute task" button does not do anything. Tasks also do not run after attempting to execute them using the command palette. No errors show up in the Output tab of VS Code with Nx Console or Nx Console Client selected. We are still able to use Nx to run these tasks manually from the command line.

## Current Behavior
Nx Console does not execute tasks in a pnpm managed monorepo.

## Expected Behavior
Nx Console should be able to execute tasks in a monorepo managed by pnpm and Nx.

## Steps to Reproduce
This also happens with one of the nrwl test monorepos.
1. Clone this repo https://github.com/nrwl/large-ts-monorepo and open it in VS code
2. Attempt to run any of the tasks with Nx Console, either from the sidebar or the command palette

### Failure Logs / Images / Videos
No logs are generated in the Output tab for `Nx Console` or `Nx Console Client`.

### Environment
- Nx Console version: v18.3.0
- VSCode version: v1.79.2
- `nx report` output from our private repo:
```
   Node : 18.16.0
   OS   : darwin x64
   pnpm : 7.33.2

   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/esbuild           : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/express           : 15.9.2
   @nrwl/node              : 15.9.2
   @nrwl/nx-plugin         : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/webpack           : 15.9.2
   @nrwl/nx-cloud          : 16.0.5
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   nx-cloud : 16.0.5
   ---------------------------------------
   Local workspace plugins:
   	 @dpc-odg/nx-plugin
```

**Comment by MaxKless** [comment]
Hey! The fact that `project.json` annotations don't work is my fault, I fixed it in this PR: https://github.com/nrwl/nx-console/pull/1795
Can you provide any more info on the commands not running via the command prompt? Because it works for me

**Comment by apostopher** [comment]
I'm facing the same issue. the latest version (18.4.0) with pnpm monorepo does not work.
1. buttons in `project.json` don't work.
2. cmd+shift+p and selecting nx commands doesn't work
3. nx console UI to generate new components (react) isn't working.

**Comment by MaxKless** [comment]
Hi @apostopher @peterstockwell-sagov can you provide any more info? I just tried this on two pnpm repos: large-ts-monorepo and the nx repo. Everything worked on both. 
- What OS are you on? 
- Can you provide a minimal repro?

**Comment by apostopher** [comment]
@MaxKless interesting. I checked on my old macbook (intel mac) and the latest nx console worked beautifully. So it must be something with my vscode / os settings. my OS is Ventura 13.4.1 (m2 mac). I'll investigate further and let you know. cheers!

**Comment by MaxKless** [comment]
Interesting. Let me know if you find anything, maybe in the output logs or the developer console? 
I'm also on an M2 mac for the record so that should still work...

**Comment by apostopher** [comment]
@MaxKless i found the issue with my setup. I'm using volta to manage my node toolchain. i had enabled volta's experimental pnpm support which fails to find pnpm in tasks.
<img width="600" alt="CleanShot 2023-07-06 at 05 43 21@2x" src="https://github.com/nrwl/nx-console/assets/270924/b008402d-3294-49df-b5ae-830b749ad97a">

i disabled the [experimental pnpm setup](https://docs.volta.sh/advanced/pnpm) and the nx-console is working again.

so its not a bug in nx-console. @peterstockwell-sagov could you pls check what error you see in the `runtime status`? (see the screenshot above).

**Comment by peterstockwell-sagov** [comment]
Ah, yep. We're also using volta to manage our node toolchain and have the same error. Interesting..I didn't realise there were logs for extensions there, would've made diagnosing this much simpler. @apostopher, appreciate your efforts diagnosing this.

**Comment by apostopher** [comment]
Thanks! @peterstockwell-sagov glad it worked for you too. I think we can close this issue now?

**Comment by peterstockwell-sagov** [comment]
Yep, thanks again.

**Comment by MaxKless** [comment]
thanks for the investigation 🙏 glad it worked out for you

**Comment by brentrager** [comment]
I think I'm hitting a similar problem.

NX Console v18.8.1
VSCode Version: v1.8.3.1

NX Rpoert:

` >  NX   Report complete - copy this into the issue template

   Node   : 18.18.0
   OS     : darwin-arm64
   pnpm   : 8.9.0
   
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/esbuild        : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/plugin         : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/vite           : 16.10.0
   nx-cloud           : 16.5.2
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @theunderscorer/nx-semantic-release : 2.6.2
   ---------------------------------------
   Local workspace plugins:
         @smooai/smoo-nx`
         

I have been STRUGGLING for months (off and on) to get an e2e test working for my create-* install package generator working. 

In my current situation, when running nx run smoo-nx-e2e:e2e, which internally runs:

`
execSync(`npx --yes --verbose create-smoo-nx@e2e --skip-nx-cache --packageManager=npm ${projectName}`, {
        cwd: projectParentDirectory,
        env: process.env,
        stdio: 'inherit',
    });`



no matter what I do, this ultimately does nothing (running from NX Console in VSCode). 

The output is:

`
npm verb cli /Users/brentrager/.nvm/versions/node/v18.18.0/bin/node /Users/brentrager/.nvm/versions/node/v18.18.0/lib/node_modules/npm/bin/npm-cli.js
npm info using npm@9.8.1
npm info using node@v18.18.0
npm verb title npm exec create-smoo-nx@e2e --skip-nx-cache --packageManager=npm test-project
npm verb argv "exec" "--yes" "--loglevel" "verbose" "--" "create-smoo-nx@e2e" "--skip-nx-cache" "--packageManager=npm" "test-project"
npm verb logfile logs-max:10 dir:/Users/brentrager/.npm/_logs/2023-10-16T21_46_53_943Z-
npm verb logfile /Users/brentrager/.npm/_logs/2023-10-16T21_46_53_943Z-debug-0.log
npm http fetch GET 200 http://localhost:4873/create-smoo-nx 135ms (cache miss)
npm verb exit 0`



However, when I run the very same command in the integrated terminal or a separate terminal, everything goes off without a hitch.

I've done all sorts of things. My path matches in the integrated terminal, and the NX Console.

I have verified that the output of echo echo $PATH | sed 's/:/\n/g' in a terminal and 

`
    execSync(`echo $PATH | sed 's/:/\\n/g'`, {
        cwd: projectParentDirectory,
        env: process.env,
        stdio: 'inherit',
    });`


Running in the NX Console are the same

I don't get why the npx command just stops. Anybody have anything like this? Driving me crazy.

**Comment by MaxKless** [comment]
@brentrager are you also using volta?

**Comment by brentrager** [comment]
> @brentrager are you also using volta?

No sadly I am not. NVM yes.

**Comment by MaxKless** [comment]
It might be an nvm / node version issue then. Can you try these and let me know if/which of these worked:

- Go to your default terminal (not iTerm) and change the node version there using nvm. VSCode should pick up the correct one
- Run nvm list and see if you have a system version installed there? If so, make sure to remove that version (using rm -rf /usr/local/bin/node). You've probably installed it using brew at some point and it might interfere with the nvm version.
- Run nvm use system which should fix the same problem. I haven't tried this one yet personally when I've run into it but it worked for some ppl.
