### ISSUE TITLE
In vscode, the path generated by right-clicking on a project folder is empty

### ISSUE THREAD

**Issue by EnochGao** [nrwl/nx-console#1805]
## Current Behavior

In vscode, the path generated by right-clicking on a project folder is empt
nxconsole version 18.2.1 is normal
nxconsole version >18.2.1 is unormal

## Expected Behavior

Automatically generate path

### Failure Logs / Images / Videos

![image](https://github.com/nrwl/nx-console/assets/41459067/4128e28c-eb96-4182-9a73-006d7c36ab89)

https://github.com/nrwl/nx-console/assets/41459067/65e6fa5e-43fa-414c-a0d7-e0ca7453a5a2

### Environment

   Node   : 18.16.0
   OS     : win32-x64
   npm    : 8.19.2

   nx                 : 16.4.3
   @nx/js             : 16.4.3
   @nx/jest           : 16.4.3
   @nx/linter         : 16.4.3
   @nx/workspace      : 16.4.3
   @nx/angular        : 16.4.3
   @nx/cypress        : 16.4.3
   @nx/devkit         : 16.4.3
   @nx/eslint-plugin  : 16.4.3
   @nrwl/tao          : 16.4.3
   @nx/web            : 16.4.3
   @nx/webpack        : 16.4.3
   nx-cloud           : 16.0.5
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   ng-zorro-antd           : 16.0.0
   ng-zorro-antd-extension : 15.8.4

- Nx Console version:  >18.2.1
- VSCode version: May 2023 (version 1.79)

**Comment by MaxKless** [comment]
I'm closing this to consolidate discussion in a central issue 👆.
This will be done as the ongoing work in Nx core completes. 

Thanks for the report, @EnochGao
