### ISSUE TITLE
Standardize `path` & `dir` prefilling in generate ui

### ISSUE THREAD

**Issue by MaxKless** [nrwl/nx-console#1806]
There are a bunch of issues all related to inconsistencies and flakiness in prefilling the `path` and `dir` options in the generate ui. 

In core Nx, there is work being done to remove `workspaceLayout` and at the same time standardize how `path` and `dir` options work in generators. This will eliminate edge cases and enable Nx Console to do more accurate prefilling. 

Until then, the new Generate UI will only prefill `project` options - if you really need the (sometimes buggy) `path` & `dir` prefilling, use the old Generate UI. 

I'm using this issue to streamline the discussion and close some other duplicate issues: 
- no path prefilling in new generate ui: https://github.com/nrwl/nx-console/issues/1805
- `workspaceLayout` causing prefilling issues: https://github.com/nrwl/nx-console/issues/1722
- inconsistency in relative / absolute path requirements: https://github.com/nrwl/nx-console/issues/1608
- unspecified error with the path: https://github.com/nrwl/nx-console/issues/1732

I'll be closing these issues because the work that needs to be done for all of them is the same. 
Please let me know if you have any thoughts or input!

**Comment by MaxKless** [comment]
For anyone interested in this, the first step towards more standardized generators is being rolled out with the new [`projectNameAndRootFormat`](https://nx.dev/packages/react/generators/library#projectnameandrootformat) option in multiple generators that controls how/where projects are generated.
The next step will be generators for things like components that happen inside projects.

**Comment by cre8** [comment]
@MaxKless is there any short fix for the path problem? Right now I have to type in the directory every time and it's really time consuming.

**Comment by MaxKless** [comment]
you can go to the settings and toggle off the new ui. The old UI still does path prefilling even though it's not always correct.

**Comment by mrbeku** [comment]
path of folder is not working with context menu

**Comment by MaxKless** [comment]
Yes, that's the topic of this issue :) If you need this feature right now, go to the settings and enable the old generate UI

**Comment by MaxKless** [comment]
Good news everyone! With Nx 17, all `directory` options have been standardized. 
This means that on the latest Nx Console & Nx, you can get completely consistend right-click prefilling in the generate UI. 
It will prefill the cwd that the generator will be run from. Together with the new `projectNameAndRootFormat` and `nameAndDirectoryFormat` options set to `as-provided` by default, this will make for a really nice and consistent experience across ALL generators. 
You can read more here https://nx.dev/deprecated/workspace-layout#workspace-layout-and-projectnameandrootformat and on the individual generator docs.

**Comment by zaquas77** [comment]
Hi @MaxKless perhaps this the right docs [https://nx.dev/deprecated/as-provided-vs-derived](https://nx.dev/deprecated/as-provided-vs-derived ) ?
