### ISSUE TITLE
IntelliJ: Non-English keyboard layouts producing incorrect characters in generator parameters form

### ISSUE THREAD

**Issue by radekbusa** [nrwl/nx-console#1818]
## Current Behavior

I use Czech keyboard layout where a slash character is produced by pressing Shift+the key to the right of "P".
When I use it in a parameter form field of a generator form, for example "path" which we use very often, trying to type a slash produces a question mark character.

## Expected Behavior

It should produce a proper character according to my keyboard layout (i.e. "/")

## Steps to Reproduce

In the "Current Behavior" section.

### Failure Logs / Images / Videos

https://ibb.co/ct3MbQz

### Environment

Platform: Mac,
Product:
```
WebStorm 2023.1.3
Build #WS-231.9161.29, built on June 15, 2023
Runtime version: 17.0.7+10-b829.16 aarch64
```
Plugin version: 1.9.0
System locale: cs-CZ
Keyboard layout: Czech (QWERTZ)

**Comment by radekbusa** [comment]
Dear MaxKless,

Got: !@#$%^&*()
Expected: 123456789 (numbers are written with shift on Czech keyboards)

Best regards
radekbusa

**Comment by MaxKless** [comment]
Hey just FYI: this really does seem like an upstream bug after all
It's reported here and I've attached some info from my repro: https://youtrack.jetbrains.com/issue/IDEA-319575/Cannot-type-slash-in-CodeStream-and-NX-Console-plugins?s=Connot-type-slash-in-plugins

I talked to someone at JetBrains and apparently they've been able to repro it but I'm not sure what the next steps are...

**Comment by LouisLecouturier** [comment]
I hope that they will fix it soon because it's really annoying :'(

**Comment by MaxKless** [comment]
Talked to someone from JetBrains, they're tackling it. You can see there's some activity on the youtrack issue

**Comment by MaxKless** [comment]
Looks like it's fixed now: https://github.com/JetBrains/jcef/commit/5e74e8b028681c1eb637bb8a27a1e79ba4f1e1e1
