### ISSUE TITLE
Nx Console is not refreshing

### ISSUE THREAD

**Issue by LouisLecouturier** [nrwl/nx-console#1824]
## Current Behavior

I can't refresh my Nx console when clicking on the refresh button or using cmd + R

## Expected Behavior

It should refresh my targets

### Environment

MacOS M1

```nx report

   Node   : 18.16.0
   OS     : darwin-arm64
   pnpm   : 8.6.6
   
   nx                 : 16.5.2
   @nx/js             : 16.5.2
   @nx/jest           : 16.5.2
   @nx/linter         : 16.5.2
   @nx/workspace      : 16.5.2
   @nx/cypress        : 16.5.2
   @nx/devkit         : 16.5.2
   @nx/eslint-plugin  : 16.5.2
   @nx/nest           : 16.5.2
   @nx/next           : 16.5.2
   @nx/node           : 16.5.2
   @nx/react          : 16.5.2
   @nx/storybook      : 16.5.2
   @nrwl/tao          : 16.5.2
   @nx/web            : 16.5.2
   @nx/webpack        : 16.5.2
   nx-cloud           : 16.1.0
   typescript         : 5.1.6
```

- Nx Console version: 1.10
- VSCode version: Webstorm 2023.1.4, Build #WS-231.9225.18

**Comment by MaxKless** [comment]
So if I'm understanding correctly, you've made a change to a project.json file and added a target - now it's not showing up in the nx toolwindow?

**Comment by LouisLecouturier** [comment]
Exactly ! Even if i click on the reload button...

I have to close and reopen Webstorm to make it refresh

**Comment by MaxKless** [comment]
I was just able to repro this so I'll have a look and see what I can find soon :) thanks!

**Comment by MaxKless** [comment]
Do you happen to be using `.nx`syntax?

**Comment by LouisLecouturier** [comment]
I have a .nxignore file but it was already happening before

**Comment by joeldbirch** [comment]
I've noticed this too. I was about to make an issue.

**Comment by MaxKless** [comment]
Could you provide some logs @LouisLecouturier @joeldbirch?

Go to Help > Diagnostic Tools > Debug Log Settings... and then insert #dev.nx.console:trace. Then paste the `idea.log` or sections of it when the error happens.

Also the `daemon.log`  & `daemon-error.log` would be useful. You can find their location by running `nx daemon --log`.

Thank you 🙏 
I was only able to repro this in a non-js repo that uses the `.nx` executable but I guess you two aren't using that setup

**Comment by MaxKless** [comment]
Can you confirm one more thing for me: 
- If you change a target name, let's say `build` -> `build1`, it's not picked up in the toolwindow
- If you change the target name again, let's say `build1` -> `build2`, it picks up the last change and updates the toolwindow to `build1`

Are you seeing the same thing?

**Comment by LouisLecouturier** [comment]
> Could you provide some logs @LouisLecouturier @joeldbirch?
> 
> Go to Help > Diagnostic Tools > Debug Log Settings... and then insert #dev.nx.console:trace. Then paste the `idea.log` or sections of it when the error happens.
> 
> Also the `daemon.log` & `daemon-error.log` would be useful. You can find their location by running `nx daemon --log`.
> 
> Thank you 🙏 I was only able to repro this in a non-js repo that uses the `.nx` executable but I guess you two aren't using that setup

I don't have any errors when it happens... So I'm not sure of what logs I can provide you 😅

**Comment by LouisLecouturier** [comment]
> Can you confirm one more thing for me:
> 
> * If you change a target name, let's say `build` -> `build1`, it's not picked up in the toolwindow
> * If you change the target name again, let's say `build1` -> `build2`, it picks up the last change and updates the toolwindow to `build1`
> 
> Are you seeing the same thing?
> 
> Edit: can you install the plugin below from disk (via `Preferences -> Plugins -> ⚙️ -> Install Plugin from Disk`) and see if that fixes it? It worked for me :)
> 
> [nx-console-0.0.1.zip](https://github.com/nrwl/nx-console/files/12093860/nx-console-0.0.1.zip)

Well I restarted my IDE since yesterday and things seems to be working as expected right now 🤔

**Comment by MaxKless** [comment]
yes it's a subtle timing issue so it won't be consistently reproducible... good that it works for you now :)

**Comment by LouisLecouturier** [comment]
Hope I could help at least a bit 😅

Thanks a lot @MaxKless for the time and work you put into solving my issues !

**Comment by MaxKless** [comment]
No worries, I appreciate you helping to make Nx Console the best it can be :) 
@joeldbirch if things didn't magically get better for you, I'd appreciate it if you could try out the plugin I linked above.

**Comment by joeldbirch** [comment]
> Go to Help > Diagnostic Tools > Debug Log Settings... and then insert #dev.nx.console:trace. Then paste the `idea.log` or sections of it when the error happens.
> 
> Also the `daemon.log` & `daemon-error.log` would be useful. You can find their location by running `nx daemon --log`.

Sorry @MaxKless I can't follow those instructions as I can't find where "Go to Help > Diagnostic Tools > Debug Log Settings" is. I'm missing something silly aren't I.

**Comment by joeldbirch** [comment]
I tried adding a new target to a project and the console updated fine. My issue occurs when creating new projects, they don't show up until I restart VS Code.
