### ISSUE TITLE
Could not find configuration file in selected directory:

### ISSUE THREAD

**Issue by kevinMartellotti** [nrwl/nx-console#1827]
## Current Behavior

When I select a workspace, it produces an error saying: "Could not find configuration file in selected directory:", when the file nx.json is indeed in the folder.

## Expected Behavior

The extension should be able to locate the nx.json file and pick the folder that contains it.

## Steps to Reproduce

Clone any repo that has set up the nx tool. cd to the src/projectfolder. Check that you can run nx commands like "npx nx run". Click on the visual studio tab for the nx console extension. Click on 'Select workspace' choose the folder that has the nx.json file.

### Failure Logs / Images / Videos

Invalid workspace: c:\Users\******************\src\project
Error: Could not find configuration file in selected directory: c:\Users\****************\src\customerz

### Environment

- Nx Console version: latest
- VSCode version: 1.49.2
{
  "name": "******",
  "devDependencies": {
    "@capacitor/cli": "^5.0.3",
    "@capacitor/ios": "../../node_modules/@capacitor/ios",
    "@capacitor/android": "../../node_modules/@capacitor/android"
  }
}

**Comment by MaxKless** [comment]
Can I ask why you're on such an outdated vscode version? 
What OS are you on?
Is there any more information available on that error or in the `Output: Nx Console` panel?

**Comment by kevinMartellotti** [comment]
Updating VSC solved the problem, thank you. OS is windows by the way.

**Comment by MaxKless** [comment]
Cool! I'll close this issue as updating VSCode isn't really a deal breaker most of the time and supporting older versions isn't really in scope
