### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by AlcuZan** [nrwl/nx-console#1834]
## Current Behavior

Whenever I try to use nx generate in Webstorm using the Nx Generate (Ui) feature to create NgRx files, I get an unexpected token error.

## Expected Behavior

I can use nx generate to create NgRx related files like selectors or effects. This used to work fine until the newest version came around.

## Steps to Reproduce

In WebStorm, right click on a folder and select New -> Nx Generate (Ui)...., then try to create a selector or an effect or anything NgRx related.

### Failure Logs / Images / Videos

"C:\Program Files\nodejs\npx.cmd" ng generate @ngrx/schematics:selector --name=test --project=MyProject --path=src/app/modules/project-details/store/selectors
Unexpected token } in JSON at position 2774
Done

### Environment

- Nx console version: 1.10.0
- WebStorm version: 2023.1.3

**Comment by MaxKless** [comment]
it seems to me like your `project.json` is broken and there's an extra `{` lying around. 
Can you check?

**Comment by AlcuZan** [comment]
I don't have a project.json. I actually don't even have NX set up in my project, I'm just using NX console because I love the UI for generating stuff

**Comment by MaxKless** [comment]
so how about your `angular.json`? Any extra `}` in there?

**Comment by AlcuZan** [comment]
Not a `}`, but there was a trailing comma that caused the issue. Thank you!

**Comment by MaxKless** [comment]
Can I ask, @AlcuZan how did you come to use Nx Console for JetBrains if you don't use Nx at all? :)

**Comment by AlcuZan** [comment]
When I worked at a different place, we used NX there, because we had a monorepo and there I came to know and love Nx Console. In our current project we don't use NX (yet), because it's too much overhead

**Comment by MaxKless** [comment]
cool! Yes it's another tool you have to explain to ppl so there's overhead for sure. But it will make sense for sure as the app grows :P
