### ISSUE TITLE
Nx console context menu create new component does not selct project and set path

### ISSUE THREAD

**Issue by lemonCMS** [nrwl/nx-console#1839]
## Current Behavior
In version 1.6.1 when right clicking on a folder and select nx generate ui -> generate @nx/angular - component.

The window that showed up used the have the project selected and also had the relative path "set" to where i clicked on wich folder.

The current behavior is that the project is not selected and also not the path is set.

![image](https://github.com/nrwl/nx-console/assets/4980003/b0965dd9-c402-4fdf-ac64-71a197e7084b)

Unfortunately version 1.6.1 keeps crashing on the latest WebStorm 2023.2.

## Expected Behavior

Expected that the project is selected and context path is "set"

## Steps to Reproduce
create a new project 
`npx create-nx-workspace@latest`

right click on `apps/{project}/src/app` -> `nx generate (ui)` -> `@nx/angular - component`

The project field is not selected and path is not "set"

### Environment

- Nx Console version: 1.10.0

- WebStorm version:
- WebStorm 2023.2
Build #WS-232.8660.143, built on July 21, 2023
Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 20
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.github.leomillon.uuidgenerator (4.5.1)
    com.jetbrains.space (232.8660.158)
    dev.nx.console (1.10.0)
    mdx.js (232.8660.129)

 Node   : 18.16.0
   OS     : win32-x64
   npm    : 9.5.1

   nx                 : 16.5.0
   @nx/angular        : 16.5.0
   @nx/cypress        : 16.5.0
   @nx/devkit         : 16.5.0
   @nx/eslint-plugin  : 16.5.0
   @nrwl/tao          : 16.5.0
   @nx/web            : 16.5.0
   @nx/webpack        : 16.5.0
   nx-cloud           : 16.0.5
   typescript         : 5.1.6

**Comment by MaxKless** [comment]
Hmm there's some conflicting info on your issue - are you on nx console version `1.6.1` or `1.10.0`?

Regarding the paths: this is working as intended right now, see https://github.com/nrwl/nx-console/issues/1806
We are working on standardizing the behavior across generators. 
If you really need it, you can enable the old generate UI where the path prefilling still works for generators with a `project` option - it's not 100% correct tho.

Regarding the `project` prefilling, that should really work. I'll try to repro it on my windows machine.

**Comment by lemonCMS** [comment]
Thank you for your reply. I was using nx console 1.6.1 because that was the last version where project and path filling worked as expected.

But ever upgrading Webstorm to 2023.2 that version makes Webstorm crash. Therefor I've upgraded to version 1.10.0. In that version the project and path stays empty.

I read the linked issue I will wait patiently until path is working again.

**Comment by lemonCMS** [comment]
That solved the issue for me :) thank you
