### ISSUE TITLE
Unhandled exception in [CoroutineName ... 

### ISSUE THREAD

**Issue by PatrykKuniczak** [nrwl/nx-console#1854]
I have Exception from your plugin, but i open issue in other repo, cause i think it's exception from webstorm plugin :)

Here's the link:

https://github.com/etkachev/nx-webstorm/issues/114

There you can see all necessary details, and info about my PC config.

If u have something more, tell me ;)

**Comment by MaxKless** [comment]
Hey! Sorry this got lost. 
@PatrykKuniczak is still still happening?
If yes, what steps do you have to take to see the error?
Can you post the result of your `nx report`?

**Comment by PatrykKuniczak** [comment]
> Hey! Sorry this got lost. 
> @PatrykKuniczak is still still happening?
> If yes, what steps do you have to take to see the error?
> Can you post the result of your `nx report`?

IDN i don't programming on Mac currently 😁

**Comment by PatrykKuniczak** [comment]
I don't see that error anymore, but the fact is i don't using nx on last time, if it occur i will reopen this issue.
