### ISSUE TITLE
Debug support in intellij Plugin run configurations

### ISSUE THREAD

**Issue by thomasburguiere** [nrwl/nx-console#1868]
## Description
The now deprecated [Nx Console Idea](https://plugins.jetbrains.com/plugin/15101-nx-console-idea) Jetbrains plugin allows to debug run configurations.

This plugin is now marked as deprecated (as of version `0.59.0`) and recommends using [Nx Console](https://plugins.jetbrains.com/plugin/21060-nx-console) instead.

However, as far as I could see, after creating a run configuration for this new plugin, its not possible to run it in debug mode

- old plugin;
![Screenshot 2023-08-28 at 11 43 02](https://github.com/nrwl/nx-console/assets/1648283/f6dcc8e8-4d79-42b5-a252-4b93f752d438)
- new plugin;
![Screenshot 2023-08-28 at 11 47 29](https://github.com/nrwl/nx-console/assets/1648283/852cc55a-b4db-4808-8224-2d2791f92913)

## Motivation

Being able to debug an application is quite nice to have.

**Comment by MaxKless** [comment]
thanks for the report! I'll look into it, we want to make sure all functionality is covered. 
 @iguissouma do you know how much of an effort this would be? Since you wrote the run configuration features for both plugins :p

**Comment by lucassith** [comment]
+1, came here because got deprecation note from Nx Console Idea plugin with the suggestion to use this one however I'm really surprised that it does not offer the debug option.

**Comment by MaxKless** [comment]
I'm working on it, currently making sure it's supported everywhere you can run stuff. 
Gutters and the toolwindow work already.

**Comment by MaxKless** [comment]
if any of you want to test the changes to make sure I didn't miss anything I'd be super glad too.
Just clone Nx Console, open it in IntelliJ and execute the runIde gradle task.
