### ISSUE TITLE
Clicking project sub configuration runner does not run the correct command

### ISSUE THREAD

**Issue by tnrich** [nrwl/nx-console#1875]
## Current Behavior

Clicking one of the project sub config runners like so: 
![image](https://github.com/nrwl/nx-console/assets/2730609/c02717a8-4395-4a3b-985f-9fea30088c8a)

Doesn't actually run the correct command: 
![image](https://github.com/nrwl/nx-console/assets/2730609/25c2ebb9-b291-428a-9aa9-4b1b16c99217)

## Expected Behavior
It should run `nx run ove:build:demo` but instead just runs `nx rn ove:build`

## Steps to Reproduce
- Open the https://github.com/TeselaGen/tg-oss repo in vscode 
- open file tg-oss/packages/ove/project.json
- click 
<img width="255" alt="image" src="https://github.com/nrwl/nx-console/assets/2730609/6f66cb5e-4c5e-4910-967a-f65debb53e5f">

I'm cloning https://github.com/nrwl/nx-examples and will try it there but my internet connection is slow rn.. I'll update this ticket once that finishes.

### Environment

nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 16.13.0
   OS     : darwin-arm64
   yarn   : 1.22.19
   
   nx                 : 16.4.1
   @nx/js             : 16.4.1
   @nx/jest           : 16.4.1
   @nx/linter         : 16.4.1
   @nx/workspace      : 16.4.1
   @nx/cypress        : 16.4.1
   @nx/devkit         : 16.4.1
   @nx/esbuild        : 16.4.1
   @nx/eslint-plugin  : 16.4.1
   @nx/react          : 16.4.1
   @nrwl/tao          : 16.4.1
   @nx/vite           : 16.4.1
   @nx/web            : 16.4.1
   nx-cloud           : 16.4.0-beta.1
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @jscutlery/semver : 3.1.0
   ---------------------------------------
   Local workspace plugins:
         @teselagen/sequence-utils
         @teselagen/bounce-loader
         @teselagen/bio-parsers
         @teselagen/range-utils
         @teselagen/file-utils
         @teselagen/ui

- Nx Console version:
v18.8.0
- VSCode version:
Version: 1.81.1 (Universal)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:20:33.924Z (3 wks ago)
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 21.6.0

**Comment by MaxKless** [comment]
That's my bad, I'm fixing it.

**Comment by tnrich** [comment]
Thanks @MaxKless !
