### ISSUE TITLE
NX Console plugin 1.13.1 is not configured correctly

### ISSUE THREAD

**Issue by richlackey** [nrwl/nx-console#1884]
## Current Behavior

Webstorm project configuration reports an error in the NX Console plugin.

## Expected Behavior

The plugin should be properly configured.

## Steps to Reproduce

Install Webstorm.
Install the NX Console plugin.
Create a new project.

### Failure Logs / Images / Videos

<img width="320" alt="Screenshot 2023-09-14 at 2 13 00 PM" src="https://github.com/nrwl/nx-console/assets/346291/20d5a2b7-8c08-4d26-a596-0eb8e55b5bba">

### Environment

MacOS Ventura 13.5.2
- Nx Console version: 1.13.1
- VSCode version:

**Comment by MaxKless** [comment]
Is there any more info other than that screenshot? 
Is there something in `idea.log`? 
Are you seeing any issues with Nx Console beyond the error? That would give us a hint as to what's wrong.

**Comment by MaxKless** [comment]
I'm closing this issue since I can't reproduce it and am not getting any more information.
If you have a minimal repro or more logs please let me know so I can look into it!
