### ISSUE TITLE
Tasks running on old node version

### ISSUE THREAD

**Issue by conormcafee** [nrwl/nx-console#1893]
## Current Behavior

Really strange behaviour (which could very likely be a local env issue).  But when I try and run a build or serve command for example, doing this manually in iTerm or in the terminal within VSCode works as expected.  However trying to run the task using the NX Console / Generate & Run Target / build for example, seems to try and run the command against an older node version on my system.   The reason I was able to verify its an older node version issue is by changing that in iTerm and rerunning the command and then I can replicate what happens when using the NX Console GUI.

Very much feels like a local issue on my machine, but would be keen to raise this to see if anyone has encountered before and knows what could be causing it.

### Failure Logs / Images / Videos
<img width="1220" alt="Screenshot 2023-10-03 at 16 50 57" src="https://github.com/nrwl/nx-console/assets/6804345/9d7edf68-9bb6-449b-8aa1-ce498b3148b6">
<img width="1440" alt="Screenshot 2023-10-03 at 16 51 14" src="https://github.com/nrwl/nx-console/assets/6804345/ef06643e-6da5-4318-9219-966bb16af423">

### Environment

- Nx Console version: 18.8.1
- VSCode version: 1.82.3

**Comment by MaxKless** [comment]
Hi @conormcafee!
Thanks for the report. This is definitely a known issue and has to do with how VSCode & nvm interact. 
There are a couple of options to fix this. Please let me know if/which of these worked:
- Go to your default terminal (not iTerm) and change the node version there using nvm. VSCode should pick up the correct one
- Run `nvm list` and see if you have a `system` version installed there? If so, make sure to remove that version (using `rm -rf /usr/local/bin/node`). You've probably installed it using brew at some point and it might interfere with the nvm version.
- Run `nvm use system` which should fix the same problem. I haven't tried this one yet personally when I've run into it but it worked for some ppl. Thanks to @TomWhiteIMO for this solution.

I will work on some docs so this will be easier to troubleshoot in the future. Closing this for now, should it not work let's reopen this.

**Comment by conormcafee** [comment]
@MaxKless ah thanks very much - there was a rogue system version floating around.  No matter what I had set globally, VS Code was still picking that up when running tasks.

To answer your question, point 2 worked for me:

> Run nvm list and see if you have a system version installed there? If so, make sure to remove that version (using rm -rf /usr/local/bin/node). You've probably installed it using brew at some point and it might interfere with the nvm version.

Thank you

**Comment by caridley** [comment]
Note that the system version isn't always installed in `/usr/local/bin/node`. Mine was located in `/opt/homebrew/bin/node`

You can determine the location as follows
`nvm use system`
`where node`
