### ISSUE TITLE
nx-console should not keep a file locked in node_modules when not using nx

### ISSUE THREAD

**Issue by Ionaru** [nrwl/nx-console#1896]
## Current Behavior

Having the nx-console plugin enabled in Webstorm (and I am guessing IntelliJ too) and having a non-nx-angular-project open keeps `node_modules\@nx\nx-win32-x64-msvc\nx.win32-x64-msvc.node` locked, causing `npm ci` or any other command that removes the `node_modules` folder to error.

## Expected Behavior

nx-console should not keep files locked in node_modules so I am able to use `npm ci` whenever I am not actively using the nx-console plugin.

## Steps to Reproduce

1. Run `ng new --no-routing --style css nx-console-eperm-test`
2. Run `cd nx-console-eperm-test`
3. Run `ng add @angular-eslint/schematics` (this pulls in `nx` as a dependency of `@angular-eslint`)
4. Start WebStorm
5. Run `npm ci`

### Failure Logs / Images / Videos

![image](https://github.com/nrwl/nx-console/assets/3472373/f2bb9a2c-d25f-4b46-9fd4-929aa564fb1e)

```
❯ npm ci
npm ERR! code EPERM
npm ERR! syscall unlink
npm ERR! path C:\Users\Jeroen\Projects\PROJECT\node_modules\@nx\nx-win32-x64-msvc\nx.win32-x64-msvc.node
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\Jeroen\Projects\PROJECT\node_modules\@nx\nx-win32-x64-msvc\nx.win32-x64-msvc.node'
npm ERR!  [Error: EPERM: operation not permitted, unlink 'C:\Users\Jeroen\Projects\PROJECT\node_modules\@nx\nx-win32-x64-msvc\nx.win32-x64-msvc.node'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Users\\Jeroen\\Projects\\PROJECT\\node_modules\\@nx\\nx-win32-x64-msvc\\nx.win32-x64-msvc.node'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in: C:\Users\Jeroen\AppData\Local\npm-cache\_logs\2023-10-09T09_33_59_492Z-debug-0.log
```

![273550818-9e009860-1411-43ce-b5fd-82e6612d78c6 (1)](https://github.com/nrwl/nx-console/assets/3472373/b515b11c-11c6-4f47-9fd1-c0c66d0905e5)

![image](https://github.com/nrwl/nx-console/assets/3472373/b168de00-0128-4ecc-a6f7-cbb78aba38a9)

### Environment

WebStorm 2023.2.2
Build #WS-232.9921.42, built on September 12, 2023
Runtime version: 17.0.8+7-b1000.22 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 32
Non-Bundled Plugins:
    dev.nx.console (1.13.1)

**Comment by MaxKless** [comment]
Hey @Ionaru thanks for reporting this! 
I really appreciate the in-depth screenshots. While we don't have a good solution to not keep this file locked yet (see https://github.com/nrwl/nx-console/issues/1863), we should be smart enough to not start the nxls & daemon when not in an nx workspace to make sure your `@angular-eslint` use case stays trouble-free.
