### ISSUE TITLE
Request to Publish NX Console in Open VSX 

### ISSUE THREAD

**Issue by JasonSamraj** [nrwl/nx-console#1898]
Hello,

Thank you for developing the NX Console extension; it's been very useful! I noticed that the extension is available on the Microsoft Marketplace but not on open-vsx.org, which is an open-source alternative that serves the broader community, including VSCodium users.

Would you consider publishing your extension on open-vsx.org as well? It would benefit users who prefer or are required to use open-source software. The process is outlined here: [Publishing Extensions](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

Thank you for considering this request. I'm looking forward to continuing to use NX Console in my development environment.

Best regards,
Jason Samraj

**Comment by MaxKless** [comment]
Hi @JasonSamraj, thanks for the input. It seems like a good idea to me. Until then, you can download the .vsix manually from the releases page, for example https://github.com/nrwl/nx-console/releases/tag/vscode-v18.8.1

**Comment by JasonSamraj** [comment]
Thank you much for considering @MaxKless
