### ISSUE TITLE
Can not select skipFormat option on @nx/workspace:move 

### ISSUE THREAD

**Issue by flynncodeit** [nrwl/nx-console#1906]
## Current Behavior
I can`t select skipFormat option on @nx/workspace:move with GUI

## Expected Behavior
It should be selectable.

### Environment

- Nx Console version: v18.8.1
- VSCode version: v1.83.1 (Universal)

**Comment by MaxKless** [comment]
Hey @flynncodeit thanks for letting me know :) In the UI, we filter internal & deprecated options to keep the schema as simple as possible. You can use the `Nx: generate` command to run it without the UI or use the CLI directly. 
Can I ask why you're trying to set `skipFormat` in the first place?
