### ISSUE TITLE
add dependency with yarn 4.x.x not work

### ISSUE THREAD

**Issue by zaquas77** [nrwl/nx-console#1923]
With yarn 4.x.x the `-W` (or `--ignore-workspace-root-check`) param no more exists.
When I try to add dependency I get this error

````
 *  Executing task: yarn add -W  @nrwl/angular@17.0.3 

Unknown Syntax Error: Unsupported option name ("-W").

$ yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
````

I suspect the problem is here

https://github.com/nrwl/nx-console/blob/8351e655684292f7f13d2270c2ad86a7ff6965fb/libs/vscode/add-dependency/src/lib/vscode-add-dependency.ts#L264

thanks in advance for your help

**Comment by MaxKless** [comment]
Hey that sounds like you found the spot right away too! Would you be interested in contributing the fix as well? :)

**Comment by zaquas77** [comment]
Hi @MaxKless,

How can I do it?

thx

**Comment by MaxKless** [comment]
Well in this file we're already reading the package.json contents, so we can also read the yarn version and see whether it's > 4.x.x. You can adapt that line you found where we decide on the `-W` flag and take the yarn version into account. 

Check out `CONTRIBUTING.MD` in the repo root to read up on how to set up nx console locally and let me know if you have any questions :)
