### ISSUE TITLE
NX console on Rider not able to find any projects.

### ISSUE THREAD

**Issue by michaelolson01** [nrwl/nx-console#1925]
## Current Behavior
After updating, NX Console is not able to find the projects in the monorepo

## Expected Behavior
A list of all the projects, and available tasks

## Is this a regression?
Yes, it was working perfectly until I updated the plugin.

## Steps to Reproduce
Open rider with the NX plugin installed in an nx project.

### Failure Logs / Images / Videos
![image](https://github.com/nrwl/nx-console/assets/13995785/978ad0d8-e764-4e81-8138-97d624e5ef44)

### Environment

Ubuntu X86:  22.04.3 LTS x86_64 
JetBrains Rider: 2023.2.2,
NX Console: 1.15.0,
NX Version: 17.0.2

**Comment by dolnikmate** [comment]
I came across the same behaviour in vscode, reverted to `v18.9.0` and now everything works just fine.

**Comment by MaxKless** [comment]
Sorry, we had a bad release

**Comment by MaxKless** [comment]
We deleted version 1.15.0 , can you check that things work normally if you go to the last version?
