### ISSUE TITLE
Make local executor cmd+clickable

### ISSUE THREAD

**Issue by MJez29** [nrwl/nx-console#1936]
## Description

Cmd + clicking (or control + clicking on non-mac) on an executor name in a project.json/nx.json opens the executor's implementation. The behaviour would be identical to clicking on the path of a typescript ESM import

```
{
  "targets": {
    "example": {
      "executor": "@myorg/plugin:executor"
                   ^^^^^^^^^^^^^^^^^^^^^^
    }
  }
}
```

## Motivation

I make extensive use of local executors and often need to jump from a project.json to the executor's implementation

**Comment by MaxKless** [comment]
If you'd be interested in contributing this yourself, I'm also happy to help out!

**Comment by MJez29** [comment]
I have some time next week so I'll give it a try!

**Comment by MJez29** [comment]
@MaxKless I put up a PR here
https://github.com/nrwl/nx-console/pull/1962
