### ISSUE TITLE
Add view target defaults codelens action for project.json

### ISSUE THREAD

**Issue by MJez29** [nrwl/nx-console#1937]
## Description

Add `view target defaults` codelens action for project.json targets that links to the target's defaults specified in nx.json (if applicable)

This would exist alongside the `nx run [target] | show nx task graph for [target]` ones

## Motivation

I often need to jump from a project.json to the nx.json to figure out what defaults are being applied to a target. It would be useful if my editor bring me there

**Comment by MaxKless** [comment]
Hi @MJez29 I don't think we're going to do this - codelens space is limited and we don't want to overcrowd things. We are working on a new project details view though, which will be important with upcoming changes to Nx. 
So I will keep showing target defaults in mind in regards to that. Thank you!
