### ISSUE TITLE
Incorrect (different?) package naming

### ISSUE THREAD

**Issue by BojanKogoj** [nrwl/nx-console#1938]
## Current Behavior

When creating new library it sets incorrect (or different from what it used to) name in project.json

```
{
  "name": "data-access",
  "$schema": "../../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "modules/notifications/data-access/src",
  "prefix": "lib",
  ...
}
```

## Expected Behavior
It would generate (as it has with others in the past)

```
{
  "name": "modules-notifications-data-access",
  "$schema": "../../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "modules/notifications/data-access/src",
  "prefix": "lib",
  ...
```

## Steps to Reproduce

In VS Code doing the following
 - Right click on (empty) folder /modules/notifications
 - Nx Generate
 - @nx/angular:library
 - Enter name (data-access)
 - Generate

```
npx nx generate @nx/angular:library --name=data-access --projectNameAndRootFormat=as-provided --standalone=false --no-interactive
```

### Environment
```
Node   : 18.18.2
   OS     : win32-x64
   npm    : 9.8.1

   nx (global)        : 16.7.2
   nx                 : 17.1.1
   @nx/js             : 17.1.1
   @nx/jest           : 17.1.1
   @nx/linter         : 17.1.1
   @nx/eslint         : 17.1.1
   @nx/workspace      : 17.1.1
   @nx/angular        : 17.1.1
   @nx/cypress        : 17.1.1
   @nx/devkit         : 17.1.1
   @nx/eslint-plugin  : 17.1.1
   @nx/playwright     : 17.1.1
   @nrwl/tao          : 17.1.1
   @nx/web            : 17.1.1
   @nx/webpack        : 17.1.1
   typescript         : 5.2.2
```
- Nx Console version: v18.10.1

- VSCode version: 1.84.2

- Angular version: 17.0.2

### More

The only way I can get it to generate as it used to is to set
- projectNameAndRootFormat:  'derived'
- directory: 'modules/notifications'

**Comment by MaxKless** [comment]
you can still use this naming structure! We just don't assume for you anymore to give everyone more flexibility
