### ISSUE TITLE
NX Generate does not respect  "nameAndDirectoryFormat" from nx.json

### ISSUE THREAD

**Issue by montella1507** [nrwl/nx-console#1942]
## Current Behavior
 "@nx/angular:component": {
      "nameAndDirectoryFormat": "derived"
    }
    
    but it still preselects as-provided
<img width="673" alt="image" src="https://github.com/nrwl/nx-console/assets/10418323/b232150c-f89a-4ee0-8f19-baaf7ab9789c">

## Expected Behavior
It should have respected  the defaults from nx.json 

### Environment
- Latest NX (17.1.0)
- NX Console Version: 1.15.1
- Webstom 2023.2.4
- macOS M2 Air

**Comment by montella1507** [comment]
Same for lib and projectNameAndRootFormat

**Comment by MaxKless** [comment]
yeah good point that was just an oversight on my end. Thanks for reporting this!

**Comment by montella1507** [comment]
> yeah good point that was just an oversight on my end. Thanks for reporting this!

I do for your fix PR.

**Comment by montella1507** [comment]
@Cammisuli  hello, was this released yet?
