### ISSUE TITLE
How to categorize the item under "projects"

### ISSUE THREAD

**Issue by tirelyl** [nrwl/nx-console#1954]
## Current Behavior

When I upgraded Nx from version 14 to 16, the folder categories in "projects" were missing.

<img width="407" alt="image" src="https://github.com/nrwl/nx-console/assets/20921324/57cf3825-0b6e-4120-aada-e93a45c2ac82">

## Expected Behavior

I want "lib" and "app" to be categorized according to the folder they are in.

This image below is version 13 of the Nx
![image](https://github.com/nrwl/nx-console/assets/20921324/31d88b74-40c2-4ab8-b7de-28093b886a09)

## Steps to Reproduce

Maybe it's not a bug, because I see that after Nx upgraded to 16 you have to specify explicit paths to create both libs and apps. But I'm still wondering how I should categorize my projects according to the folder where the apps and libs are located?

### Environment

- Nx Console version: v18.10.1
- VSCode version:  1.85.0 (Universal)

**Comment by MaxKless** [comment]
Hey there :)
Looks like the setting was changed. Can you go to the settings and check out the `nxConsole.projectViewingStyle` setting?

If that's set to tree view, you will get the nested view.

I'm closing this for now but if there really is a bug, please post your `nx report` results and I can have a look.
