### ISSUE TITLE
Option to sort targets alphabetically

### ISSUE THREAD

**Issue by pietdevries94** [nrwl/nx-console#1959]
## Description

I would like it if the targets were to be sorted alphabetically. An option for this is fine.

## Motivation

We have around 20 targets in a large project and we want to group some targets that do similar things or are related in some way, like seperate, but related steps in our deployment. A prefix (release:foo, release:bar) would be good option for this, but without a way to sort the targets, this would still be chaotic in the vs code extension, where we use `run target` a lot.

## Suggested Implementation

Add an option to sort targets alphabetically in all lists of targets.

## Alternate Implementations

No option and change this. It feels intrusive to other users.

**Comment by MaxKless** [comment]
I like the idea in general :) 
Sorting when we retrieve the targets seems like it would be the easiest solution. However, that would introduce a performance overhead. Especially for large workspaces, iterating over every single project and sorting keys will take time. 
Thus, we should sort targets where they are used to save time for everything else... 
Probably:
- the `Nx: Run Target` and `Nx: run` commands
- The project view
- The `Generate & Run Target` section

Doesn't seem like it would be an intrusive change to me. Right now there's no sorting so it's not like we're breaking any other uses cases...

**Comment by pietdevries94** [comment]
The only case I can think of is that people have made an explicit choice in the order of the targets of their apps (first serve than build for example). Due to the way the targets get retrieved, the result is somewhat predictable. Insert the xkcd about every change breaking a workflow here, haha
