### ISSUE TITLE
WebStorm: Generate UI does not respect generator defaults from nx.json

### ISSUE THREAD

**Issue by jase88** [nrwl/nx-console#1964]
## Current Behavior

- If creating a new library _Generate UI_ uses nx generator default values

## Expected Behavior

- If creating a new library _Generate UI_ uses project generator default values defined in `nx.json`

## Steps to Reproduce

`nx.json`
```json
{
  // ..
  "generators": {
    // ...
    "@nx/js:lib": {
      "bundler": "none",
      "unitTestRunner": "jest",
      "testEnvironment": "jsdom"
    }
  }
}
```

### Failure Logs / Images / Videos

![image](https://github.com/nrwl/nx-console/assets/804836/fbcc703f-63d6-46bf-a5f5-fbc001948c83)

all three predefined values are not applied

### Environment

- Nx Console version: 1.15.1
- WebStorm 2023.3.1

**Comment by MaxKless** [comment]
Hey :) Thanks for reporting the issue. 
Setting the `generators` property in `nx.json` only works with the full generator specifier and not an alias, i.e. `@nx/js:library` instead of `@nx/js:lib` as you have specified above. 

I'm closing this for now as it works as expected. If it still doesn't work with the full specifier, please provide a minimal repro and I'll be glad to reopen and look into it.

**Comment by knotekbr** [comment]
@MaxKless I'm experiencing this same issue while using the full generator specifier. Not sure what counts as a minimal repro, but the problem can be replicated with these steps:

1. Create a new workspace with `yarn create nx-workspace test-repo --preset=npm`
2. Add the following to `nx.json`:
   ```json
   "generators": {
     "@nx/js:library": {
       "bundler": "rollup",
       "directory": "packages",
       "publishable": true,
       "unitTestRunner": "vitest"
     }
   }
   ```
3. Open the Nx Console UI and select the "@nx/js - library" generator. None of the fields specified in `nx.json` are set to their provided values.

This was tested in VS Code version 1.87.0 on a Windows 11 machine. Here are the full contents of the root `package.json`:

```json
{
  "name": "test-repo",
  "version": "0.0.0",
  "license": "MIT",
  "private": true,
  "devDependencies": {
    "@nx/js": "18.0.6",
    "nx": "18.0.6"
  },
  "workspaces": [
    "packages/*"
  ],
  "packageManager": "yarn@4.0.2"
}
```

**Comment by MaxKless** [comment]
I'll check it out, thanks for letting me know :)

**Comment by troywweber7** [comment]
This issue is also a problem in the VSCode version of Nx Console. Are they likely related? Or should we create an issue for the VSCode side of things?

**Comment by MaxKless** [comment]
No, this is because of the nxls and will be shared across IDEs :)
