### ISSUE TITLE
Setting multiple tags throws: Schema does not support positional arguments

### ISSUE THREAD

**Issue by Tom4U** [nrwl/nx-console#1965]
## Current Behavior

Running an UI generator that provides **tags** field throws error `Schema does not support positional arguments.` if multiple tags are defined.

This only happens if tags are comma separated and space is set after comma. Without space it would work, but than it's not passed as string and only first tag is used.

Question remains if there's a specific format to use in form field.

However, if using the first approach and picking up the generated command, running it manually on console, it works fine. So something seems to pass something in.

## Expected Behavior

Multiple, comma separated tags, should be passed to nx generate command as it would be if running it manually.

## Steps to Reproduce

1. Run a UI generator for an app or library that uses **-tags** argument.
2. Set multiple tags like `tag1, tag2`
3. Monitor dry run output in console.

### Failure Logs / Images / Videos

Command generated: `nx g @nx/nest:application --name=api --frontendProject=ui --directory=apps/api --projectNameAndRootFormat=as-provided --tags="tag1, tag2"`

Error thrown if running through UI: `>  NX   Schema does not support positional arguments. Argument 'tag2' found`

### Environment

```
   Node   : 20.9.0
   OS     : win32-x64
   npm    : 10.2.5

   nx (global)        : 17.2.3
   nx                 : 17.2.3
   @nx/js             : 17.2.3
   @nx/jest           : 17.2.3
   @nx/linter         : 17.2.3
   @nx/eslint         : 17.2.3
   @nx/workspace      : 17.2.3
   @nx/angular        : 17.2.3
   @nx/cypress        : 17.2.3
   @nx/devkit         : 17.2.3
   @nx/eslint-plugin  : 17.2.3
   @nx/nest           : 17.2.3
   @nx/node           : 17.2.3
   @nx/playwright     : 17.2.3
   @nrwl/tao          : 17.2.3
   @nx/web            : 17.2.3
   @nx/webpack        : 17.2.3
   typescript         : 5.2.2
```

- Nx Console version: 18.10.1
- VSCode version: 1.85.1

**Comment by MaxKless** [comment]
Do you have a minimal repro for me to use?
I tried this on both my mac and windows laptop and it worked the same from the CLI and from nx console generate ui...
and the command looks correct too, doesn't it?

**Comment by Tom4U** [comment]
While trying to reproduce it on a new workspace I've noticed the following:

**Using `tag1, tag2`**
* @nx/web:application **no error, but only first tag is used**
* @nx/js:library **no error, but only first tag is used**
* @nx/angular:application **no dry-run preview in terminal, throws error**
* @nx/nest:application **throws error**

Here's the repo I've tested on: [tmp-nx-console-issue-tags](https://github.com/Tom4U/tmp-nx-console-issue-tags)

And just to be sure, here's a list of all extensions currently in that VS Code instance:
```
Angular.ng-template
austenc.tailwind-docs
bradlc.vscode-tailwindcss
cyrilletuzi.angular-schematics
dbaeumer.vscode-eslint
deniszholob.angular-files-generator
eamodio.gitlens
esbenp.prettier-vscode
firsttris.vscode-jest-runner
hbenl.vscode-test-explorer
miclo.sort-typescript-imports
mrmlnc.vscode-scss
ms-azure-devops.azure-pipelines
MS-CEINTL.vscode-language-pack-de
ms-playwright.playwright
ms-vscode-remote.remote-wsl
ms-vscode.azure-account
ms-vscode.live-server
ms-vscode.test-adapter-converter
nrwl.angular-console
Orta.vscode-jest
ryanluker.vscode-coverage-gutters
softwaredotcom.swdc-vscode
SonarSource.sonarlint-vscode
syler.sass-indented
vivaxy.vscode-conventional-commits
zerotask.firebase-configuration-schema
```

**Comment by MaxKless** [comment]
Hey! Sorry forgot to respond here as there was a duplicate issue. 
This should be fixed in the latest versions since https://github.com/nrwl/nx-console/pull/2189

Let me know if it still happens to you after updating :)
