### ISSUE TITLE
Generate Ext is not working in NX Console 

### ISSUE THREAD

**Issue by vinaytejamm** [nrwl/nx-console#1966]
![image](https://github.com/nrwl/nx-console/assets/152269777/882f7c65-9362-4ed8-af1e-63be79568cb0)

**Comment by MaxKless** [comment]
Hi :) Thanks for reporting a bug but I really need more info to be able to help here. Generate UI works for me.
I'm closing this until there's more info like `nx report`, a detailed description, ...
