### ISSUE TITLE
Nx commands have suddendly started to create the .nx folder on the project root folder instead node_modules on version 16.10

### ISSUE THREAD

**Issue by andreaSimonePorceddu** [nrwl/nx-console#1975]
### Current Behavior

Since this morning, I have issues running the `nx` command with no changes to the codebase or dependencies:

- A `.nx` folder is created in project root folder (file added to the git status because the `.nx` folder is not present in the `.gitignore`). Till yesterday the cache was added into the `node_module` folder.

<img width="256" alt="Screenshot 2024-01-04 alle 14 22 31" src="https://github.com/nrwl/nx/assets/55460313/5f85a967-2518-4dad-baf1-8d25ecda36a3">

- The command fails with this error:
```
Could not find 'nx' module in this workspace. Error: [readCachedProjectGraph] ERROR: No cached ProjectGraph is available.
If you are leveraging \`readCachedProjectGraph()\` directly then you will need to refactor your usage to first ensure that
the ProjectGraph is created by calling \`await createProjectGraphAsync()\` somewhere before attempting to read the data.
```

I'm using the last 16 version `16.10.0`, node version 18.18.

```json
"@nrwl/js": "16.10.0",
"@nx/cypress": "16.10.0",
"@nx/detox": "16.10.0",
"@nx/eslint-plugin": "16.10.0",
"@nx/jest": "16.10.0",
"@nx/js": "16.10.0",
"@nx/linter": "16.10.0",
"@nx/next": "16.10.0",
"@nx/react": "16.10.0",
"@nx/react-native": "16.10.0",
"@nx/storybook": "16.10.0",
"@nx/web": "16.10.0",
"@nx/webpack": "16.10.0",
"@nx/workspace": "16.10.0",
```

I wonder if it could be related to yesterday's release of the 17 (some common dependencies changed).

### Expected Behavior

No error and nx command successfully executed, cache still placed on node_modules

### Steps to Reproduce

Run an nx command

### Nx Report

```
shell
Node   : 18.18.0
   OS     : darwin-arm64
   yarn   : 1.22.19
   
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/detox          : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/next           : 16.10.0
   @nx/react          : 16.10.0
   @nx/react-native   : 16.10.0
   @nx/storybook      : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/web            : 16.10.0
   @nx/webpack        : 16.10.0
   nx-cloud           : 16.5.2
   typescript         : 4.9.4
   ---------------------------------------
   Community plugins:
   @jscutlery/semver : 2.29.3
```

### Failure Logs

```shell
Could not find 'nx' module in this workspace. Error: [readCachedProjectGraph] ERROR: No cached ProjectGraph is available.

If you are leveraging \`readCachedProjectGraph()\` directly then you will need to refactor your usage to first ensure that
the ProjectGraph is created by calling \`await createProjectGraphAsync()\` somewhere before attempting to read the data.

If you encounter this error as part of running standard \`nx\` commands then please open an issue on https://github.com/nrwl/nx
    at readCachedProjectGraph [90m(/Users/app/[39mnode_modules/[4mnx[24m/src/project-graph/project-graph.js:30:15[90m)[39m
    at run [90m(/Users/app/[39mnode_modules/[4mnx[24m/src/command-line/run/run.js:151:69[90m)[39m
    at process.<anonymous> [90m(/Users/app/[39mnode_modules/[4mnx[24m/bin/run-executor.js:59:48[90m)[39m
[90m    at process.emit (node:events:517:28)[39m
[90m    at emit (node:internal/child_process:944:14)[39m
[90m    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)[39m
```

### Package Manager Version

1.22.19

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Hotell** [comment]
we are facing same issue https://github.com/microsoft/fluentui-contrib

this makes nx console not usable for more than 1 project unfortunately. would be great if it would always use workspace installed nx version and only if not present fall back to global one.

**Comment by MaxKless** [comment]
Hey!
I just pushed a PR that should fix this. I'll cut a release soon and would be very grateful for your feedback on whether any issues persist on your end.
When you upgrade, please make sure to run `nx reset`, delete the `.nx` folder and restart vscode just to be sure to clean any weird leftover state.

**Comment by stavalfi** [comment]
it doesn't work @MaxKless . I have nx@19.1.0

**Comment by MaxKless** [comment]
hey @stavalfi couks you create a new issue with a detailed description of the error and your nx report? Then we can have a look again :)
