### ISSUE TITLE
Failed to install Nx Plugin with Access Denied

### ISSUE THREAD

**Issue by anthony-ilsc** [nrwl/nx-console#1983]
## Current Behavior

After installing the plugin, restart webstorm plugin installation causes an error with Access Denied.

## Expected Behavior

The plugin to successfully install

### Failure Logs / Images / Videos

![image](https://github.com/nrwl/nx-console/assets/141194410/90e5603e-5663-4302-b7df-5a4a677dc4dd)

### Environment

Machine - Windows 
- Nx Console version: 1.17.0
- Webstorm: 2023.3.2

**Comment by MaxKless** [comment]
Hey! Yes this is a known issue on windows currently. You can free up this file by running `npx nx daemon --stop`.

Closing as a duplicate of https://github.com/nrwl/nx-console/issues/1863.
It's on my radar, I'll fix it asap.
