### ISSUE TITLE
nxConsole not loading for an existing installed project that i just took a pull from github

### ISSUE THREAD

**Issue by amermalik01** [nrwl/nx-console#1988]
Error running command nxConsole.refreshWorkspace: command 'nxConsole.refreshWorkspace' not found. This is likely caused by the extension that contributes nxConsole.refreshWorkspace.

my dependencies files are like

"@angular/animations": "~13.3.0",
    "@angular/cdk": "^13.3.2",
    "@angular/common": "~13.3.0",
    "@angular/compiler": "~13.3.0",
    "@angular/core": "~13.3.0",
    "@angular/forms": "~13.3.0",
    "@angular/platform-browser": "~13.3.0",
    "@angular/platform-browser-dynamic": "~13.3.0",
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/cqrs": "^8.0.3",
    "@nestjs/jwt": "^8.0.0",
    "@nestjs/mongoose": "^9.0.3",
    "@nestjs/passport": "^8.2.1",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/platform-socket.io": "^8.4.4",
    "@nestjs/serve-static": "^2.2.2",
    "@nestjs/websockets": "^8.4.4",
    "@ngx-translate/core": "^14.0.0",
    "@ngx-translate/http-loader": "^7.0.0",
    "@ngxs/store": "^3.7.3",
    "@nrwl/angular": "13.10.1",
    "@sentry/angular": "^7.16.0",
    "@sentry/node": "^7.16.0",
    "add": "^2.0.6",    
    "jsonwebtoken": "^8.5.1",
    "jwks-rsa": "^2.0.5",
    "mangopay2-nodejs-sdk": "1.42.0",
    "masonry-layout": "^4.2.2",
    "memfs": "^4.6.0",
    "mongoose": "^6.2.10",
    "ngx-clipboard": "^15.1.0",
    "ngx-filesize": "^2.0.16",
    "ngx-image-cropper": "^6.1.0",
    "ngx-infinite-scroll": "^13.0.1",
    "ngx-masonry": "^13.0.0",
    "ngx-socket-io": "4.2.0",
    "ngx-timeago": "^2.0.0",

**Comment by MaxKless** [comment]
Hey! 
Could you provide some more info like the repo you used (so I can repro it) as well as the nx console version and the results of `nx report`?

I want to help fix it but I need more info.

**Comment by amermalik01** [comment]
Thanks for help MaxKless

Basically my project is based on monorepos library.
Its frontend in angular based and backend is in nestjs.

I am facing issue in installing nx console from VS code

**Comment by MaxKless** [comment]
please paste the results from `nx report` so I know about your environment

**Comment by amermalik01** [comment]
Here is the report 

nx report

>  NX   WARNING  Running global Nx CLI with PNPM may have issues.

  Prefer to use "pnpm" (https://pnpm.io/cli/exec) to execute commands in this workspace.
   TIP  create a shortcut such as: doskey pnx=pnpm nx -- $*



 >  NX   Report complete - copy this into the issue template

   Node : 16.14.1
   OS   : win32 x64
   pnpm : 8.14.1

   nx : 13.10.1
   @nrwl/angular : 13.10.1
   @nrwl/cypress : 13.10.1
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/eslint-plugin-nx : 13.10.1
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.1
   @nrwl/js : Not Found
   @nrwl/linter : 13.10.1
   @nrwl/nest : 13.10.1
   @nrwl/next : Not Found
   @nrwl/node : 13.10.1
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 13.10.1
   typescript : 4.6.4
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
         @fortawesome/angular-fontawesome: 0.10.2

**Comment by yurisim** [comment]
I'm having the same problem as well

`  Node   : 20.11.0
   OS     : win32-x64
   npm    : 10.2.1

   nx (global)        : 17.3.1
   nx                 : 17.3.1
   @nx/js             : 17.3.1
   @nx/jest           : 17.3.1
   @nx/linter         : 17.3.1
   @nx/eslint         : 17.3.1
   @nx/workspace      : 17.3.1
   @nx/angular        : 17.3.1
   @nx/cypress        : 17.3.1
   @nx/devkit         : 17.3.1
   @nx/eslint-plugin  : 17.3.1
   @nx/playwright     : 17.3.1
   @nrwl/tao          : 17.3.1
   @nx/web            : 17.3.1
   @nx/webpack        : 17.3.1
   typescript         : 5.3.3`
   
   this is just a repo that is fresh from a nx create workspace. I have not made any modifications. 
   
   https://github.com/yurisim/nxconsolebug
   
   I have version v18.14.1 of the NX console VS Code app.

**Comment by IgorVyatkin** [comment]
Confirmed in the WebStorm. For me it has stopped to work for @nx starting from 17.3.0. Rolling back to @nx 17.2.8 resolves the problem.

**Comment by VitProg** [comment]
I am having the same problem in WebStorm, after updating the NX version

`    "@nx/cypress": "17.3.1",
    "@nx/eslint": "17.3.1",
    "@nx/eslint-plugin": "17.3.1",
    "@nx/jest": "17.3.1",
    "@nx/js": "17.3.1",
    "@nx/nest": "17.3.1",
    "@nx/node": "17.3.1",
    "@nx/react": "17.3.1",
    "@nx/rollup": "17.3.1",
    "@nx/rspack": "17.2.8",
    "@nx/vite": "17.3.1",
    "@nx/web": "17.3.1",
    "@nx/webpack": "17.3.1",
`

**Comment by MaxKless** [comment]
fix is in https://github.com/nrwl/nx-console/issues/2005

release will come later today
