### ISSUE TITLE
Generating angular libraries/components has a strange behaviour 

### ISSUE THREAD

**Issue by mackelito** [nrwl/nx-console#1993]
## Current Behavior
````
Executing task: npx nx generate @nx/angular:library --name=test-lib --directory=libs/ui --projectNameAndRootFormat=as-provided --no-interactive --dry-run 


>  NX  Generating @nx/angular:library


 >  NX   Cannot create a new project test-lib at libs/ui. It already exists.

   Pass --verbose to see the stacktrace.
````

## Expected Behavior

When using the the OLD generate Ui (uncheck box in nx console settings) it works as expected

````
Executing task: npx nx generate @nx/angular:library test-lib --directory=libs/ui --no-interactive --dry-run 

>  NX  Generating @nx/angular:library

In Nx 18, generating projects will no longer derive the name and root.
Please provide the exact project name and root in the future.
Example: nx g @nx/angular:library ui-test-lib --directory libs/ui/test-lib
UPDATE nx.json
CREATE libs/ui/test-lib/project.json
CREATE libs/ui/test-lib/README.md
CREATE libs/ui/test-lib/ng-package.json
CREATE libs/ui/test-lib/package.json
CREATE libs/ui/test-lib/tsconfig.json
CREATE libs/ui/test-lib/tsconfig.lib.json
CREATE libs/ui/test-lib/tsconfig.lib.prod.json
CREATE libs/ui/test-lib/src/index.ts
CREATE libs/ui/test-lib/jest.config.ts
CREATE libs/ui/test-lib/src/test-setup.ts
CREATE libs/ui/test-lib/tsconfig.spec.json
CREATE libs/ui/test-lib/src/lib/ui-test-lib/ui-test-lib.component.scss
CREATE libs/ui/test-lib/src/lib/ui-test-lib/ui-test-lib.component.html
CREATE libs/ui/test-lib/src/lib/ui-test-lib/ui-test-lib.component.spec.ts
CREATE libs/ui/test-lib/src/lib/ui-test-lib/ui-test-lib.component.ts
CREATE libs/ui/test-lib/.eslintrc.json
UPDATE tsconfig.base.json
````

## Steps to Reproduce
create a folder named `libs/ui`
generate a new lib and add `libs/ui` as path

### Environment

- Nx Console version: v18.14.0
- VSCode version: 1.85.2

**Comment by mackelito** [comment]
Update:
I can verify that this breaks in v18.7.0
v18.6.0 works just fine..

**Comment by mackelito** [comment]
I also note that when generating it does not consider that patch for component name
Old behaviour would result in `export class FeatureTestLibComponent {}`
New behaviour is `export class TestLibComponent`

This means that if you have eg. a startpage component for several features it would fail
Old behaviour:
FeatureA --> `export class FeatureAStartpageComponent`
FeatureB --> `export class FeatureBStartpageComponent`

New behaviour:
FeatureA --> `export class StartpageComponent`
FeatureB --> `export class StartpageComponent`
.... ops! 😬

**Comment by MaxKless** [comment]
Hey! 
This is expected behavior because we set the `--projectNameAndRootFormat=as-provided` option by default in nx console.
You should be able to see it in a yellow header & the commands you pasted are also different.

From Nx 19 later this year, the `derived` format you're describing won't exist anymore.

Check out https://nx.dev/deprecated/as-provided-vs-derived for more info :)
