### ISSUE TITLE
Version 18.15.x can't find any projects in the workspace

### ISSUE THREAD

**Issue by ivanolarocca** [nrwl/nx-console#2013]
## Current Behavior
Updating to the latest minor version (18.15.x) the workspace projects are no longer detected.
This message appears "**We couldn't find any project in this workspace**"

Downgrade to version 18.14.1 the problem doesn't occur.

## Expected Behavior
Detect projects and loads targets commands

### Failure Logs / Images / Videos
![nx-console-18 15 1](https://github.com/nrwl/nx-console/assets/33010720/fd462eb7-9666-46f3-9934-fdd3b5606c19)

### Environment
- Nx Console version: 18.15.0, 18.15.1
- VSCode version: 1.86.0 (Windows x64)
- Workspace is an Integrated Repo Angular based with use of angular.json and project.json in every project
- NX Report:
`Node : 18.7.0
   OS   : win32 x64
   npm  : 9.4.2
   
   nx : 14.1.9
   @nrwl/angular : 14.1.9
   @nrwl/cypress : 14.1.9
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.9  
   @nrwl/eslint-plugin-nx : 14.1.9
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.9
   @nrwl/js : 14.1.9
   @nrwl/linter : 14.1.9
   @nrwl/nest : 14.1.9
   @nrwl/next : Not Found
   @nrwl/node : 14.1.9
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.9
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.9
   typescript : 4.6.4
   ---------------------------------------
   Community plugins:
         @nebular/theme: 9.1.0-rc.6
         ngx-bootstrap: 8.0.0 `

**Comment by MaxKless** [comment]
Hi, 
could you provide some logs and ideally a minimal repro? That will make it easier for us to fix the issue. 
- Go to `Output -> Nx Console Client` and paste what you see there. 
- Run `Toggle Developer Tools` and paste what you see there too
- Finally, run `nx daemon` and provide the contents of the `daemon.log` file linked there

Thank you!

**Comment by ivanolarocca** [comment]
> Hi, could you provide some logs and ideally a minimal repro? That will make it easier for us to fix the issue.
> 
> * Go to `Output -> Nx Console Client` and paste what you see there.
> * Run `Toggle Developer Tools` and paste what you see there too
> * Finally, run `nx daemon` and provide the contents of the `daemon.log` file linked there
> 
> Thank you!

Thank you! This is the relevant error in the Nx Console Client output:

`Unable to get nx workspace configuration: TypeError: Cannot read properties of undefined (reading 'reset')`

The problem may be related to this recent change #2006 (Resetting daemon client) where `nxDaemonClientModule.daemonClient` is undefined

**Comment by ivanolarocca** [comment]
Release `18.15.3` fixes this issue. Thank you.

**Comment by artuska** [comment]
This is still an issue — VSCode's NX console just does not show more than 3 apps:
![image](https://github.com/nrwl/nx-console/assets/1013856/c6ec5d59-52fa-4e8e-96e1-8a5af95a96bc)

**Comment by MaxKless** [comment]
does `nx reset` fix it?

**Comment by artuska** [comment]
> does `nx reset` fix it?

No. I also tried to close VSCode and delete `.nx` folder and then open VSCode again — NX Console searches for the projects and then just shows project name as on screenshot above.

Installing previous versions of NX Console does not help — the result is the same.

**Comment by MaxKless** [comment]
Can you paste the full output? Is there anything else after `createProjectGraphAsync`?

**Comment by artuska** [comment]
> Can you paste the full output? Is there anything else after `createProjectGraphAsync`?

Typically there is this output in Output tab:

```
[Nxls] - 2024-04-03T10:09:06.221Z - Project configuration changed
[Nxls] - 2024-04-03T10:09:07.235Z - Retrieving workspace configuration
[Nxls] - 2024-04-03T10:09:07.236Z - Using local Nx package at c:/Users/artus/3D Objects/pochta/lkul-monorepo-nx/node_modules/nx/src/project-graph/file-utils.js
[Nxls] - 2024-04-03T10:09:07.237Z - Using local Nx package at c:/Users/artus/3D Objects/pochta/lkul-monorepo-nx/node_modules/nx/src/project-graph/file-map-utils.js
[Nxls] - 2024-04-03T10:09:07.237Z - Using local Nx package at c:/Users/artus/3D Objects/pochta/lkul-monorepo-nx/node_modules/nx/src/project-graph/project-graph.js
[Nxls] - 2024-04-03T10:09:07.237Z - Using local Nx package at c:/Users/artus/3D Objects/pochta/lkul-monorepo-nx/node_modules/nx/src/utils/output.js
[Nxls] - 2024-04-03T10:09:07.237Z - Using local Nx package at c:/Users/artus/3D Objects/pochta/lkul-monorepo-nx/node_modules/nx/src/daemon/client/client.js
[Nxls] - 2024-04-03T10:09:07.237Z - createProjectGraphAndSourceMapsAsync
[Nxls] - 2024-04-03T10:09:07.247Z - createProjectGraphAndSourceMapsAsync successful
[Nxls] - 2024-04-03T10:09:07.251Z - Resetting daemon client
[Nxls] - 2024-04-03T10:09:07.251Z - Retrieved workspace configuration in: 15.767800003290176 ms
```

**Comment by artuska** [comment]
NX Graph works as expected, i think:

![image](https://github.com/nrwl/nx-console/assets/1013856/71ceba1c-40fc-48ec-872c-13a12fc85ce7)

**Comment by MaxKless** [comment]
Could you try something out for me?
Paste this to a file at the root `test.js` and run with `node ./test.js`
```
(async () => {
    const projectGraph = require('nx/src/project-graph/project-graph')
    const result = await projectGraph.createProjectGraphAndSourceMapsAsync()
    console.log(result.projectGraph.nodes)
})() 
```

Is the full project graph being returned there? Or is it also just one project like in the screenshot?

**Comment by artuska** [comment]
```
import projectGraph from 'nx/src/project-graph/project-graph.js';

(async () => {
  // const projectGraph = require('nx/src/project-graph/project-graph')
  const result = await projectGraph.createProjectGraphAndSourceMapsAsync()
  console.log(result.projectGraph.nodes)
})()
```

Ugh, it took him ~2 minutes to output my ~40 projects in json. So, yes, it outputs full project graph not just one project.
