### ISSUE TITLE
Unable to run NX Console commands - The engine "node" is incompatible with this module.

### ISSUE THREAD

**Issue by paustint** [nrwl/nx-console#2018]
## Current Behavior

When I run any command from the NX Console in VSCode, I get the following error.

```
Executing task: yarn nx generate @nx/express:application --name=test --directory=apps --projectNameAndRootFormat=as-provided --no-interactive --dry-run
...
The engine "node" is incompatible with this module. Expected version "20". Got "18.16.0"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Expected Behavior

Command should with any node version and should not be impacted by the node version I have specified in my package.json

## Steps to Reproduce

Add this to your package.json
```json
  "engines": {
    "node": "20"
  },
```

attempt to run any nx console command.

I can run `yarn nx generate @nx/express:application --name=test --directory=apps --projectNameAndRootFormat=as-provided --no-interactive --dry-run` from the command line and it runs successfully, and only fails when running from nx console.

My workaround is to remove my engines specification and run the nx console commands, then revert the change in my package.json

### Environment

```
$ nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 20.10.0
   OS     : darwin-arm64
   yarn   : 1.22.19
   
   nx                 : 17.2.7
   @nx/js             : 17.2.7
   @nx/jest           : 17.2.7
   @nx/linter         : 17.2.7
   @nx/eslint         : 17.2.7
   @nx/workspace      : 17.2.7
   @nx/cypress        : 17.2.7
   @nx/devkit         : 17.2.7
   @nx/eslint-plugin  : 17.2.7
   @nx/express        : 17.2.7
   @nx/next           : 17.2.7
   @nx/node           : 17.2.7
   @nx/playwright     : 17.2.7
   @nx/plugin         : 17.2.7
   @nx/react          : 17.2.7
   @nx/storybook      : 17.2.7
   @nrwl/tao          : 17.2.7
   @nx/vite           : 17.2.7
   @nx/web            : 17.2.7
   @nx/webpack        : 17.2.7
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @mands/nx-playwright : 0.6.2
   nx-electron          : 15.0.0
   ---------------------------------------
   Local workspace plugins:
         @jetstream/workspace-plugin
```

- Nx Console version: `v18.15.3`
- VSCode version: tried with `1.85.2` and `1.86.0`

**Comment by Cammisuli** [comment]
are you using `nvm` or some other kind of node version manager?

can you add this task to your `.vscode/tasks.json` file, run it and tell me what version it outputs?

```
// .vscode/tasks.json
{
  "version": "2.0.0",
  "tasks": [
    {
		"type": "shell",
		"command": "node -v",
		"label": "node version",
		"problemMatcher": []
	}
  ]
}
```

**Comment by paustint** [comment]
Yes, I am using `nvm` and it looks like running the task did print out an unexpected version of node:

```
 *  Executing task: node -v 

v18.16.0
 *  Terminal will be reused by tasks, press any key to close it.
```

Looks like this isn't related to `nx console`, but vscode. If you have any tips on how I can fix this, that would be great - otherwise i will go research and try to figure it out.

**Comment by Cammisuli** [comment]
@paustint try giving this a read and see if it helps you out
https://nx.dev/recipes/nx-console/console-troubleshooting#vscode-nvm-issues

**Comment by paustint** [comment]
@Cammisuli - Nice! this worked, thank you for your help!
