### ISSUE TITLE
Webstorm new File menu no angular choice

### ISSUE THREAD

**Issue by pliersch** [nrwl/nx-console#2033]
## Current Behavior

I cant create Angular (Nest JS too) Schematics / Dependency from the menu. Only NX is available.

## Expected Behavior

Same before install NX Console. In non NX projects is this possible. Disabling plugin doesn´t help.

### Environment

- Nx Console version: 1.18.0
- Webstorm version: 2023.3.3

**Comment by MaxKless** [comment]
should should be fixed with https://github.com/nrwl/nx-console/pull/2022
