### ISSUE TITLE
Nx Console Graph is not working with Yarn 4

### ISSUE THREAD

**Issue by Arilas** [nrwl/nx-console#2057]
Yarn 4 (and possibly 2 and 3) doesn't have `--silent` flag, so the command `yarn --silent nx graph  --file` that Nx Console is trying to execute is failing.

Line of code where Nx Console incorrectly builds command.

https://github.com/nrwl/nx-console/blame/c6b94bcfe8d8dd8c6a1c229b45400f6af1f84e18/libs/shared/utils/src/lib/get-nx-execution-command.ts#L26

Error exists in both VS Code and in WebStorm

**Comment by MaxKless** [comment]
makes sense, @xiongemi maybe you want to have a look at it?

**Comment by MaxKless** [comment]
related: https://github.com/nrwl/nx-console/issues/1923
