### ISSUE TITLE
Nx console not working on M1 chips

### ISSUE THREAD

**Issue by CesarGPX** [nrwl/nx-console#2059]
### Current Behavior

When trying to execute any of the tasks on the nx console extension on vs code, I get an error in console:

env: node: Bad CPU type in executable

If I copy and paste that command in another terminal window, it works fine

### Expected Behavior

The commands should run directly in the zsh terminal window that nx console extension automatically opened

### GitHub Repo

It is a private repository

### Steps to Reproduce

1. In an nx project, on an M1 mac, try to execute any of the nx tasks

### Nx Report

```shell
Node   : 18.19.1
   OS     : darwin-arm64
   npm    : 10.2.4
   
   nx                 : 16.7.0
   @nx/js             : 16.7.0
   @nx/jest           : 16.7.0
   @nx/linter         : 16.7.0
   @nx/workspace      : 16.7.0
   @nx/angular        : 16.7.0
   @nx/cypress        : 16.7.0
   @nx/devkit         : 16.7.0
   @nx/eslint-plugin  : 16.7.0
   @nx/storybook      : 16.7.0
   @nrwl/tao          : 16.7.0
   @nx/web            : 16.7.0
   @nx/webpack        : 16.7.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @storybook/angular : 7.6.5
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by MaxKless** [comment]
Hey thanks for reporting this @CesarGPX. It looks to me like a misconfiguration with your node environment? You probably have a weird node version installed via homebrew or similar and then `nvm` on top of that? 
Can you double check that the `nxConsole.showNodeVersionOnStartup` setting is enabled and look at the node version being loaded by VSCode? Is it the same as the noder version in your terminal?

There are a couple of options that might fix this. Please let me know if/which of these worked:

- Go to your default terminal (not iTerm) and change the node version there using nvm. VSCode should pick up the correct one
- Run nvm list and see if you have a system version installed there? If so, make sure to remove that version (using rm -rf /usr/local/bin/node). You've probably installed it using brew at some point and it might interfere with the nvm version.
- Run nvm use system which should fix the same problem. I haven't tried this one yet personally when I've run into it but it worked for some ppl. Thanks to @TomWhiteIMO for this solution.

**Comment by CesarGPX** [comment]
Hi Max,

Thank you for your answer. Indeed, it was the system version installed that
was conflicting. After uninstalling it it works fine.

Thanks again for your help,

Cesar
