### ISSUE TITLE
Project Graph Application Error

### ISSUE THREAD

**Issue by kylebjordahl** [nrwl/nx-console#2060]
## Current Behavior

In IDE project graph fails to render in VS Code, returns error:
```
TypeError: Cannot read properties of undefined (reading 'projects')
```

> **Note: running the project graph in the browser via `nx graph` _still_ works as expected**

## Expected Behavior

Project Graph should render within VS Code

## Steps to Reproduce

Command Palette > `Nx: Show full project graph`

### Failure Logs / Images / Videos

![Screenshot 2024-03-18 at 10 35 35 AM](https://github.com/nrwl/nx-console/assets/3489222/c267e78c-b56c-49e2-8698-e0ae65646ded)

#### Nx Report
```
Node   : 20.11.1
OS     : linux-arm64
npm    : 10.2.4

nx                 : 18.0.7
@nx/js             : 18.0.7
@nx/jest           : 18.0.7
@nx/linter         : 18.0.7
@nx/eslint         : 18.0.7
@nx/workspace      : 18.0.7
@nx/cypress        : 18.0.7
@nx/devkit         : 18.0.7
@nx/eslint-plugin  : 18.0.7
@nx/plugin         : 18.0.7
@nx/react          : 18.0.7
@nx/remix          : 18.0.7
@nx/storybook      : 18.0.7
@nrwl/tao          : 18.0.7
@nx/vite           : 18.0.7
@nx/web            : 18.0.7
typescript         : 5.3.3
---------------------------------------
Community plugins:
@nxlv/python : 18.0.0
```

- Nx Console version: `v18.17.0`
- VSCode version: `1.87.2`

**Comment by MaxKless** [comment]
Hi thanks for reporting this!
could you provide some logs and ideally a minimal repro? That will make it easier for us to fix the issue. 
- Go to `Output -> Nx Console Client` and paste what you see there. 
- Run `Toggle Developer Tools` and paste what you see there too
- Finally, run `nx daemon` and provide the contents of the `daemon.log` file linked there

Thank you!

**Comment by kylebjordahl** [comment]
# Nx Console Client Log
```
[Nxls] - 2024-03-21T18:22:01.126Z - Using local Nx package at /home/vscode/workspace/node_modules/nx/src/utils/cache-directory.js

[Nxls] - 2024-03-21T18:22:01.138Z - Using local Nx package at /home/vscode/workspace/node_modules/nx/src/utils/cache-directory.js

[Nxls] - 2024-03-21T18:22:01.141Z - Generating graph with command: `npx nx graph  --file ./.nx/cache/nx-console-project-graph/project-graph.html`

[Nxls] - 2024-03-21T18:22:03.317Z - Using local Nx package at /home/vscode/workspace/node_modules/nx/src/utils/cache-directory.js

[Nxls] - 2024-03-21T18:22:03.319Z - Generating graph with command: `npx nx graph  --file ./.nx/cache/nx-console-project-graph/project-graph.html`

[Nxls] - 2024-03-21T18:22:05.079Z - Using local Nx package at /home/vscode/workspace/node_modules/nx/src/utils/cache-directory.js
```

# Dev Tools Log
[vscode-app-1711045399451.log](https://github.com/nrwl/nx-console/files/14705490/vscode-app-1711045399451.log)

![Screenshot 2024-03-21 at 11 24 00 AM](https://github.com/nrwl/nx-console/assets/3489222/6b9822e2-1a13-42a4-8d52-1e0355ff7054)

# `nx daemon` Output
```
Nx Daemon is not running.
```

**Comment by kylebjordahl** [comment]
Thanks @MaxKless, haven't seen this since!
