### ISSUE TITLE
IDE Errors in PhpStorm Nx Console 1.20.0

### ISSUE THREAD

**Issue by guyhirsch** [nrwl/nx-console#2074]
com.intellij.diagnostic.PluginException: Illegal char <:> at index 4: node:internal/console/constructor [Plugin: dev.nx.console]
[error.txt](https://github.com/nrwl/nx-console/files/14785552/error.txt)

**Comment by MaxKless** [comment]
Thanks for the report @guyhirsch :) Could you provide some more info on how this happened, ideally a minimal repro?
I'm not sure how that invalid file is getting there, honestly.
I will add a catch to prevent this error in the future, though.

**Comment by MaxKless** [comment]
This is fixed with https://github.com/nrwl/nx-console/pull/2076, please let me know if this error continues to show up once this fix is released
