### ISSUE TITLE
vscode nx extension starting, no errors in console, but does nothing when trying to run tasks

### ISSUE THREAD

**Issue by tnrich** [nrwl/nx-console#2080]
## Current Behavior

https://github.com/nrwl/nx-console/assets/2730609/35506403-57ba-4c40-a9a6-dead6b17c6f9

https://github.com/nrwl/nx-console/assets/2730609/5d068d8e-493d-4c64-bca2-ae0f56e2951e

https://github.com/nrwl/nx-console/assets/2730609/79d24a16-85ad-4658-8054-8bb6f5bdd847

<img width="1128" alt="image" src="https://github.com/nrwl/nx-console/assets/2730609/220da7e7-3b33-4af3-ab0b-f68407ec9406">
<img width="1148" alt="image" src="https://github.com/nrwl/nx-console/assets/2730609/5d167a37-77d2-48da-959a-997b5e976666">

## Expected Behavior
For tasks to run like normal..?

## Steps to Reproduce

- clone the tg-oss repo https://github.com/TeselaGen/tg-oss

- open vscode with nx extension installed

- try to run commands

- nothing happens

### Environment

x report

 >  NX   Report complete - copy this into the issue template

   Node   : 16.20.2
   OS     : darwin-arm64
   yarn   : 1.22.21
   
   nx                 : 17.1.2
   @nx/js             : 17.1.2
   @nx/jest           : 17.1.2
   @nx/linter         : 17.1.2
   @nx/eslint         : 17.1.2
   @nx/workspace      : 17.1.2
   @nx/cypress        : 17.1.2
   @nx/devkit         : 17.1.2
   @nx/esbuild        : 17.1.2
   @nx/eslint-plugin  : 17.1.2
   @nx/react          : 17.1.2
   @nrwl/tao          : 17.1.2
   @nx/vite           : 17.1.2
   @nx/web            : 17.1.2
   nx-cloud           : 16.5.2
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @jscutlery/semver : 4.2.0

thomasrich@Thomass-MacBook-Pro tg-oss % 

- Nx Console version:
- VSCode version:
- Version: 1.87.2 (Universal)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:21:31.043Z (3 wks ago)
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.4.0

**Comment by MaxKless** [comment]
I've been able to reproduce this and I'm pretty sure it's a node issue. Can you toggle the `nxConsole.showNodeVersionOnStartup` on and see whether the node version is what you expect? Refer to the troubleshooting guide for more information about nvm & node issues: https://nx.dev/recipes/nx-console/console-troubleshooting

I was able to find an error in the developer console (`Help -> Toggle Developer Tools`). I'll make a PR to surface this information to users better.

**Comment by MaxKless** [comment]
In my case the problem was that for the version that was loaded in VSCode (16), I didn't have `yarn` installed globally so an error was thrown.

**Comment by tnrich** [comment]
Hi @MaxKless sounds like this is probably the issue. Surfacing what is going wrong would be super useful! I think some sort of editor warning popping up saying something like "no global node binary found" or something like that would be excellent for figuring out these issues. 

Here's what my dev console looks like: 
<img width="1371" alt="image" src="https://github.com/nrwl/nx-console/assets/2730609/2fa06d06-9011-450e-aa2c-bf778370de10">


Thanks for the quick response! 

By the way, I tried setting nxConsole.showNodeVersionOnStartup to true but wasn't able to see the node version any where in the logs. Is this setting supposed to pop up a toast on startup? Doesn't seem to be working for me.

**Comment by tnrich** [comment]
Oh, it is supposed to pop a toast up, but without a global node installed I didn't get one.. haha

After installing node globally it works:
<img width="681" alt="image" src="https://github.com/nrwl/nx-console/assets/2730609/dade0fd2-431b-49e4-88cd-85b2e342310a">

**Comment by MaxKless** [comment]
The errors will be shown with https://github.com/nrwl/nx-console/pull/2082
I appreciate the thorough bug documentation & videos it really helped me get to this fast :) 

Though unrelated pings maybe aren't best practice I've asked around internally about that PR :)
