### ISSUE TITLE
Breakpoints Don't Hit -- WebStorm

### ISSUE THREAD

**Issue by marc-wilson** [nrwl/nx-console#2095]
## Current Behavior
Debugging an nx project in webstorm doesn't work. No breakpoints are ever hit.

## Expected Behavior
If I set a breakpoint in debug mode, the breakpoint should hit.

## Steps to Reproduce
1. Create new nx workspace using nestjs
2. Once repo is generated, go the nestjs app
3. open the project.json file
4. Click on serve and select debug in the context menu
5. Set a breakpoint anywhere
6. Observe that it does not hit.

Breakpoints hit in a regular node app in webstorm just fine.

### Environment

- Nx Console version: 1.21.0
- Webstorm Version: 2024.1.1
- VSCode version:

 NX   Report complete - copy this into the issue template

Node   : 18.13.0
OS     : darwin-x64
npm    : 8.19.3

nx (global)        : 18.3.3
nx                 : 18.3.3
@nx/js             : 18.3.3
@nx/jest           : 18.3.3
@nx/linter         : 18.3.3
@nx/eslint         : 18.3.3
@nx/workspace      : 18.3.3
@nx/devkit         : 18.3.3
@nx/eslint-plugin  : 18.3.3
@nx/nest           : 18.3.3
@nx/node           : 18.3.3
@nrwl/tao          : 18.3.3
@nx/web            : 18.3.3
@nx/webpack        : 18.3.3
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin

**Comment by marc-wilson** [comment]
If you add `debugger;` to the code, the breakpoints hit, but they are hit in a js file in the dist. Then, there's also a suspicious line in the `serve` now:

> nx run myproj:build  [existing outputs match the cache, left as is]

> webpack-cli build --node-env=production

Looks like something is forcing a production build during `serve`. I'm assuming this is what's leading the prod build and therefore berakpoints not working.

**Comment by marc-wilson** [comment]
Found the reason in https://github.com/nrwl/nx-console/issues/2042.

Sourcemaps should be enabled by default for any development configuration. With today's monitoring solutions available, it's also very beneficial to have hidden source maps generated for the underlying monitoring software. Making a change that makes debugging not work out of the box is completely counter-intuitive for why someone would want to use something like nx-console.

**Comment by marc-wilson** [comment]
Judging from the comment in the other issue, that seems to be the culprit. Whether that is an nx-console or an nx thing is beyond me. But, I do know that this was working perfectly fine so either nx-console did something or nx did something.

I haven't ever developed a plugin for a JetBrains IDE so I am not sure what the process is. But, I would imagine that the plugin is generating a profile/configuration to run the underlying project based on the project.json.

That configuration has arguments and properties. For example, angular cli has `--source-map`. So, when you're generating the configuration, maybe throw that flag in?

The reason why I think this is more of an nx-console problem is that you get the below UI in WebStorm when you install nx-console:

<img width="408" alt="image" src="https://github.com/nrwl/nx-console/assets/19480392/43bcb6d8-9ab2-4b5e-8beb-19fac408487a">


This implies that I am able to set a breakpoint and run the project if I chose to run the Debug profile. Even the console output says a debugger is attached. It's extremely misleading.

**Comment by MaxKless** [comment]
Ultimately, we can't guarantee that whatever is run will have source maps. You can also run any arbitrary command through this debug button and those might not support source maps or be configured correctly. So while this should handle more use cases natively, it's no guarantee.

**Comment by marc-wilson** [comment]
I'm not sure what was in place before, but this was most definitely working. Breakpoints used to hit without any additional configuration -- so not sure why this is a feature opposed to a bug.

Kind of seems like this was broke in NX 17 per this comment: https://github.com/nrwl/nx-console/issues/1967#issuecomment-1871095243

But, I can confirm that I never manually configured source mapps and breakpoints were working just fine. I upgraded to nx 18 (from 17) and updated the webstorm plugin and it doesn't work now.

Assuming the comment is correct, I would agree this is more of an nx change that had a negative side effect to the web storm plugin as the plugin assumes source maps are going to be there. I think simply adding the source maps flag to the command on the development profile is a good fix.

**Comment by MaxKless** [comment]
hey!
So I just did some more research. There actually aren't very many executors left that expose a `--sourcemap` flag or something similar. You have to configure it yourself in the underlying tooling config, for example webpack or vite.

This means that I've chosen not to build logic that automatically generates source maps for those few executors that still support it. It's not worth the maintenance burden on the team & I want to reduce the amount of magic that happens.

I have, however, added a periodic notification when running targets through debugging. This means that users will find the root cause of their breakpoints not hitting faster (see the PR above).

I know this probably won't make you very happy, but since Nx is technology-agnostic, we can't assume too much about the things you're using and how to ensure debugging works.

Thanks :)

**Comment by marc-wilson** [comment]
With the new terminal UI, breakpoints do not hit when it's enabled. If you set `tui.enabled` to `false` in the nx.json, breakpoints magically work. Nx console is definitely doing something to influence whether or not breakpoints work or not in webstorm.

https://github.com/nrwl/nx/issues/31587
