### ISSUE TITLE
Move Nx Project refactor action - Project text field too narrow

### ISSUE THREAD

**Issue by mkapal** [nrwl/nx-console#2104]
## Current Behavior

When I invoke the Move Nx Project refactor action, the Project text filed is very narrow, making it impossible to see what's being entered.

## Expected Behavior

The Project text field is as wide as the window (same like the Destination field).

## Steps to Reproduce

- Open an Nx project
- Select Refactor -> Move Nx Project

### Failure Logs / Images / Videos

<img width="436" alt="image" src="https://github.com/nrwl/nx-console/assets/6420535/16fb228c-4311-40f4-8385-d2683b4f9b9c">

### Environment

- Nx Console version: 1.21.0
- WebStorm version: 2024.1.1

**Comment by MaxKless** [comment]
Thanks for the report! I've created a PR that adresses this issue
