### ISSUE TITLE
Custom tasks won't start in VS Code ("There is no task provider registered for tasks of type "nx")

### ISSUE THREAD

**Issue by pebell** [nrwl/nx-console#2116]
## Current Behavior

In my project, I have a "tasks.json" that launches a custom task of type "nx" when I open the workspace in VS Code. Up to version v18.20.0, this worked flawlessly. But the moment I installed v18.21.0, it stopped working. Whether the task is executed automatically on startup, or launched manually using "Tasks | Launch Task", a popup error message appears with the message `There is no task provider registered for tasks of type "nx".`. After downgrading to v18.20.0, the custom task launches without problems again.

This exact same behavior was reproducable on the laptop of another project member: upgrade to v18.21.0 and it stops working, downgrade to v18.20.0 and it works again.

## Expected Behavior

I expect the task to launch correctly, instead of an error message indicating there is no task provider for "nx" tasks.

It worked flawlessly up to and including v18.20.0

## Steps to Reproduce

I am hoping the issue is generic and recognizable enough without having to describe the steps needed to create a custom "nx" task in Visual Code. I can share my tasks.json if needed.

### Failure Logs / Images / Videos

A screenshot of the error popups, and the error log showing  part of the task configuration in the tasks.json file (including the `type="nx"` bit).
![image](https://github.com/nrwl/nx-console/assets/17027218/ad06020b-43fd-473c-a707-e6ac5fe3190c)

### Environment

 NX  Report complete - copy this into the issue template

  Node : 18.16.0
  OS   : darwin arm64
  npm  : 9.5.1
  
  nx : Not Found
  @nrwl/angular : 11.2.12
  @nrwl/cli : 11.2.12
  @nrwl/cypress : 11.2.12
  @nrwl/devkit : 11.2.12
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.12
  @nrwl/linter : 11.2.12
  @nrwl/nest : 11.2.12
  @nrwl/next : Not Found
  @nrwl/node : 11.2.12
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.12
  @nrwl/web : Not Found
  @nrwl/workspace : 11.2.12
  typescript : 4.1.5

*****

What I notice as strange in this output, is the 'nx: Not Found'. I have a global installation; when I execute `ng --version` it returns `11.2.12`.

*****

- Nx Console version: v18.21.0
- VSCode version: 1.89.0

**Comment by MaxKless** [comment]
Hey! Thanks for taking the time to report this issue.
I just tried reproducing this with a newer version of Nx and it worked without a problem.
<img width="922" alt="image" src="https://github.com/nrwl/nx-console/assets/34165455/4be30aa0-9bd6-407f-81ef-b699073a6f69">

Sadly, nx 11 is too old for us to support on the console side. 
If you can reproduce this issue with a newer version of nx, I'll look into it again. Ideally provide a small minimal repro so I can just clone it, see it and fix the error. That makes it easiest for me and maximises your chances of getting your issue fixed. 

Thank you! 

I'm closing this for now but if the issue persists, I'll be glad to reopen it.

**Comment by pebell** [comment]
Thank you for taking the time to investigate! We scheduled an upgrade of nx in the near future; I trust that will resolve the issue for us. Thanks again.

**Comment by MaxKless** [comment]
That sounds good! If it doesn't report back and we'll have another look. Have a nice day :)
