### ISSUE TITLE
Rerunning a run-many task results in undefined command being run

### ISSUE THREAD

**Issue by tnrich** [nrwl/nx-console#2126]
## Current Behavior
If I go to re-run a recently run `run-many` task in vscode's task runner dropdown: 
![image](https://github.com/nrwl/nx-console/assets/2730609/3de942c4-e69b-46a3-89a6-0a43243d9f00)

When it runs, it looks like this: 
![image](https://github.com/nrwl/nx-console/assets/2730609/570689cc-3375-48ff-ac6b-6f79db69209e)

## Expected Behavior
I would expect it to not have undefined in the task being re-run1

```
yarn nx run undefined:run-many --target=publish --projects=ove,ui
```

Also I should note that this task command ran fine when I ran it for the first time, it is just on the re-run that it messes up.

### Environment

- Nx Console version: v18.21.1

- VSCode version:

Version: 1.89.0 (Universal)
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:10:10.196Z (6 days ago)
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

**Comment by MaxKless** [comment]
Thanks for the report, I have a fix in the PR listed above.

**Comment by tnrich** [comment]
@MaxKless love it! Thanks for the quick fix!

**Comment by MaxKless** [comment]
You got it :) Thanks for catching the bug
