### ISSUE TITLE
Spaces being removed in generators parameters in UI

### ISSUE THREAD

**Issue by Swanzor** [nrwl/nx-console#2138]
## Current Behavior

Currently, if you create a generator that has a parameter with a space in the text (such as "Something Cool" or "Foo Bar") it will disregard everything after the space and only take the first word. See the image below of the result after using the generator UI.

![broken-template-generator](https://github.com/nrwl/nx-console/assets/61963904/bbb871fb-ac89-417c-8d4f-8e570825cacc)

## Expected Behavior

The expected result should be that like the image below. This was done using the integrated terminal of VS Code and I just copy-pasted the command in the terminal to check the result.

![image](https://github.com/nrwl/nx-console/assets/61963904/bc959ea8-61c6-4960-a049-9ff30461626f)

This problem has been like this since the conversion to the Lit interface. Before that, it was working fine. 

## Steps to Reproduce

1. Create a generator that needs a text input box.
2. Add a piece of text with a space in it. 
3. You can console log the object using `console.dir` and you should see the result

### Failure Logs / Images / Videos

![broken-template-generator](https://github.com/nrwl/nx-console/assets/61963904/bbb871fb-ac89-417c-8d4f-8e570825cacc)

![image](https://github.com/nrwl/nx-console/assets/61963904/bc959ea8-61c6-4960-a049-9ff30461626f)

### Environment

- Nx Console version: v18.21.3
- VSCode version: 1.89.1

**Comment by mkapal** [comment]
Is there a public generator that it can be tested with?

**Comment by MaxKless** [comment]
I think the `@nx/plugin` package has generators with a 'description' or similar field... haven't had the time to repro yet, sorry. If you can confirm @mkapal that would be amazing!

**Comment by mkapal** [comment]
I've tried using `@nx/plugin:generator` and the parsed options look fine even with spaces:

<img width="1351" alt="image" src="https://github.com/nrwl/nx-console/assets/6420535/56fb10e0-de55-47e8-88a2-1f1a65a7a6a7">

**Comment by MaxKless** [comment]
@Swanzor can you share a repro with a publicly available executor or the one you're using in a repro?

**Comment by Swanzor** [comment]
@MaxKless @mkapal Unfortunately, I can't share my source code as it is a company project. However, I did create a repo where I replicated the circumstances: [https://github.com/Swanzor/sample-string-bug](https://github.com/Swanzor/sample-string-bug).

**Comment by mkapal** [comment]
@Swanzor Thanks for the example repo. I've tried running the generator in there but everything works as expected on my end, very strange. 

<img width="1038" alt="image" src="https://github.com/nrwl/nx-console/assets/6420535/ffbfae6a-9d6f-43de-8a48-9aea61d9532f">

**Comment by Swanzor** [comment]
@mkapal Plugins maybe? Or is it the integrated terminal of VS Code? As I am using PowerShell and Windows 11. This seems like one of those annoying weird bugs. 

I can at least narrow it down that it is not any other plugins as I just ran the same test with only NxConsole enabled: 

![image](https://github.com/nrwl/nx-console/assets/61963904/6b38e8af-42c6-435e-8833-bc24d32d21ca)
![image](https://github.com/nrwl/nx-console/assets/61963904/727481fa-8fdc-45ed-9924-48dfab436eaf)

So I have to conclude that it has something to do with VS Code on Windows or something else?

**Comment by MaxKless** [comment]
I think it could be powershell, yes... can you test whether it works when using the command prompt in vscode instead of powershell?

**Comment by Swanzor** [comment]
@MaxKless OK so I decided to change some settings and see if that works. It works on PowerShell if you run it directly (See image below).

![image](https://github.com/nrwl/nx-console/assets/61963904/b1399215-9e6e-4dab-a053-002805cc93db)

However, as we can see from previous tests, if you run the integrated terminal in PowerShell, it does not work. This means that the setting for VS Code for the terminal is as follows: `"terminal.integrated.defaultProfile.windows": "PowerShell"`.

I tried switching it to "Command Prompt" and presto it works:

![image](https://github.com/nrwl/nx-console/assets/61963904/31d5344c-43ae-40ad-bd45-9b6905ba23cd)

So I tested various configs and it seems that this is a flaw in PowerShell and VS Code. I do not know why, but it seems it is removing the double quote (`"`) when the command is run. I believe it has to do with the way it runs it's command.

![image](https://github.com/nrwl/nx-console/assets/61963904/3b05b632-5a60-440c-8059-a47cd3a8e79d)

So the question is this something that should just be reported to the VS Code team?

**Comment by MaxKless** [comment]
yes it's probably something we can fix. We have some logic to make sure that if there's spaces, we add a quote to each parameter. Maybe that's faulty on windows powershell and we need to escape it manually with backslashes like you did

**Comment by MaxKless** [comment]
Hey! I want to say thanks again @Swanzor and @mkapal  for the thorough investigation - made it way easier for me to handle this issue. 
It really was a PowerShell issue and by escaping any `"` signs on windows & powershell, the generator is now run with the correct information: 
![image](https://github.com/nrwl/nx-console/assets/34165455/7b8e20de-2b22-483e-a0ec-95ded8278b27)

Keep in mind that if you need your string to include quotes itself, you have to escape them with `\\` now
![image](https://github.com/nrwl/nx-console/assets/34165455/90f33228-090f-4934-993b-e6f19c4cd5bd)


Anyways that seems more rare than just spaces so I think it's a fine tradeoff vs just not working at all with spaces :D 
Thanks again, the PR is here https://github.com/nrwl/nx-console/pull/2189
