### ISSUE TITLE
Multiple terminal popups on Windows

### ISSUE THREAD

**Issue by cskiwi** [nrwl/nx-console#2149]
## Current Behavior

Whenever I make a change in my project after updating to 19.1.0 a couple of terminals popup for a millisecond and then closing again.
Making the whole experience very disturbing because it takes the focus. Making it very hard to work

## Expected Behavior

No popups or at least not ones that take the active focus 

## Steps to Reproduce

Have a project using nx 19.1.0 on windows

### Failure Logs / Images / Videos

This is the same as: https://github.com/nrwl/nx-console/issues/1751

### Environment

- Nx Console version: 19.1.0
- VSCode version: 1.89.1

nx report:
```
Node   : 20.12.2
OS     : win32-x64
bun    : 1.1.10

nx                 : 19.1.0
@nx/js             : 19.1.0
@nx/jest           : 19.1.0
@nx/linter         : 19.1.0
@nx/eslint         : 19.1.0
@nx/workspace      : 19.1.0
@nx/angular        : 19.0.2
@nx/devkit         : 19.1.0
@nx/eslint-plugin  : 19.1.0
@nx/nest           : 19.1.0
@nx/node           : 19.1.0
@nx/playwright     : 19.1.0
@nrwl/tao          : 19.1.0
@nx/web            : 19.1.0
@nx/webpack        : 19.1.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/jest/plugin
@nx/playwright/plugin
@nx/webpack/plugin
---------------------------------------
Community plugins:
@auth0/auth0-angular : 2.2.3
apollo-angular       : 7.0.1
ng-apexcharts        : 1.10.0
ng-process-env       : 16.0.6
ngxtension           : 3.3.0
---------------------------------------
The following packages should match the installed version of nx
  - @nx/angular@19.0.2
  - @nrwl/angular@19.0.2
```

I know that angular is still on a prev version of nx because one package hasn't updated to the new angular material formatting giving an error.
but I wouldn't think this would cause that issue

**Comment by MaxKless** [comment]
Hey @cskiwi thanks for the report!
We're aware of this issue and are working on a fix :) It has to do with a misconfiguration in how Nx runs things. The default set by Node.js when running any commands on windows is to show a popup like this. So sometimes we miss instances and forget to disable this "feature".
I'll let you know once we land something to fix it.

**Comment by Den-dp** [comment]
@MaxKless if I understand the problem correctly, it can be solved once and for all by implementing workspace-wide ESLint rule that fails if `exec`, `spawn`, `fork` etc are used without `hideWindows` parameter

**Comment by CodeWithBryan** [comment]
Everytime I come back to NX, this continues to be an issue. As someone that used to be a supporter of NX, it's very frustrating to be unable to use it outright. Given the severity of this issue, I would've expected an urgent fix, yet here we are months later still dealing with this on windows.

Yet another project I've had to pass NX usage on because of this exact cmd prompt popping issue.

**Comment by MaxKless** [comment]
Hey @CodeWithBryan I'm really sorry to hear about this. I tried reproducing on my windows machine and didn't see any popups on neither `19.1` nor `latest`. Could you paste your `nx report` and let me know what steps you're taking to see the popups? Like, what commands are you running, are you using them from just the `nx` cli or Nx Console?

@cskiwi are you still running into this too on the latest versions?

**Comment by nicolasebner** [comment]
I have the same issue, my colleague working on the same project as well.
This is really annoying.

I get cmd consoles popping up from: nx\src\daemon\server\start.js

 Here my nx report:
 
 Node   : 20.14.0
OS     : win32-x64
bun    : 1.1.6

nx                 : 19.2.3
@nx/js             : 19.2.3
@nx/jest           : 19.2.3
@nx/linter         : 19.2.3
@nx/eslint         : 19.2.3
@nx/workspace      : 19.2.3
@nx/cypress        : 19.2.3
@nx/devkit         : 19.2.3
@nx/eslint-plugin  : 19.2.3
@nx/nest           : 19.2.3
@nx/node           : 19.2.3
@nx/react          : 19.2.3
@nrwl/tao          : 19.2.3
@nx/web            : 19.2.3
@nx/webpack        : 19.2.3
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin

**Comment by MaxKless** [comment]
Hey thanks everyone for the reports! @cskiwi @nicolasebner 
Thanks to the `nx report` results I could track it down to the bun usage and have a fix in this PR https://github.com/nrwl/nx/pull/26718

@Den-dp you're right it might be time to find a solution to prevent this behaviour altogether. I'll talk about it with the team.

**Comment by MaxKless** [comment]
Should be released later this week :)

**Comment by francobasilico** [comment]
Hi I keep getting this on windows
nx                 : 19.5.3
@nx/js             : 19.5.3
@nx/jest           : 19.5.3
@nx/linter         : 19.5.3
@nx/eslint         : 19.5.3
@nx/workspace      : 19.5.3
@nx/angular        : 19.5.3
@nx/devkit         : 19.5.3
@nx/esbuild        : 19.5.3
@nx/eslint-plugin  : 19.5.3
@nx/nest           : 19.5.3
@nx/node           : 19.5.3
@nx/playwright     : 19.5.3
@nx/plugin         : 19.5.3
@nrwl/tao          : 19.5.3
@nx/vite           : 19.5.3
@nx/web            : 19.5.3
@nx/webpack        : 19.5.3
typescript         : 5.5.4

**Comment by Den-dp** [comment]
> @MaxKless if I understand the problem correctly, it can be solved once and for all by implementing workspace-wide ESLint rule for Nx Monorepo that fails if `exec`, `spawn`, `fork` etc are used without `hideWindows` parameter

@MaxKless speaking of the workspace-wide ESLint rule... Not sure whether it is still relevant to you, but while trying to fix a similar issue in nx-dotnet/nx-dotnet#887, I came up with the following rule https://github.com/nx-dotnet/nx-dotnet/pull/887/commits/253663f2ad5d0a377ae830cade74cc19868eeb7e#diff-8f4b5073d52c957e7a4de5f5972eff8864a33308a60905f02cc5f80964e9fde8

**Comment by mklueh** [comment]
Still happening with `19.7.3`...

no matter if I run serve, nx g app or just use IntelliJ with the Nx Plugin installed, I constantly see these windows popping up.

I had to disable the IntelliJ plugin because those windows stayed open and were frozen all the time

**Comment by MaxKless** [comment]
Yikes I'm sorry to hear that :/ I'll check it out today and see if I can repro it. Can you post your `nx report` results. Since it doesn't happen for me, I assume it's some code in a specific plugin on windows.

**Comment by absurdism2** [comment]
guys, please prioritize this as much as it is possible for you. This really reduces productivity by a lot, on every file change in either of main IDEs you get n (3-10) popping out cmd windows (windows platform). 

Node           : 20.17.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.8.1

nx (global)        : 19.1.2
nx                 : 19.6.4
@nx/js             : 19.6.4
@nx/jest           : 19.6.4
@nx/linter         : 19.6.4
@nx/eslint         : 19.6.4
@nx/workspace      : 19.6.4
@nx/angular        : 19.6.4
@nx/cypress        : 19.6.4
@nx/devkit         : 19.6.4
@nx/eslint-plugin  : 19.6.4
@nx/react          : 19.6.4
@nx/storybook      : 19.6.4
@nrwl/tao          : 19.6.4
@nx/vite           : 19.6.4
@nx/web            : 19.6.4
@nx/webpack        : 19.6.4
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/storybook/plugin
@nx/vite/plugin
---------------------------------------
Community plugins:
@koliveira15/nx-sonarqube : 4.1.0
@storybook/angular        : 8.2.9
angular-auth-oidc-client  : 18.0.1

**Comment by MaxKless** [comment]
Will do! On it today :)

**Comment by absurdism2** [comment]
any update on the issue? this issue is literally unbearable.

**Comment by MaxKless** [comment]
I've seen these before but I'm really struggling to reproduce the issue on my windows machine. Could you provide a reproduction repo that I can clone and see the issue myself @absurdism2 ? It must be some specific combination of plugins or the like that's causing this. Usually these popups don't come from Nx Console but from the underlying nx version itself.

I'd love to fix this ASAP but it's hard if I don't see the error myself.

**Comment by MaxKless** [comment]
You could try setting `NX_VERBOSE_LOGGING=true` and run some commands like `nx show projects` that calculate the project graph. Then you should also see the popups. Or is it only ever happening in Nx Console and never in the cli itself?

**Comment by absurdism2** [comment]
it does pop up whether you have nx-console installed or not (in my case Webstorm), "nx show projects" does trigger, popups, to check i uninstalled it. If i have nx console installed when it refreshes the workspace automatically it does trigger them too, it is not only when you save the file. Work like that is a torment.

**Comment by Den-dp** [comment]
@absurdism2 from my experience - it is always some plugin.

To determine which one it would be helpful to see your `npx nx report` output (or repository with reproduction).

**Comment by Den-dp** [comment]
@MaxKless I found one of the problematic places while going through @absurdism2's report:

@nx/vite : 19.6.4
https://github.com/nrwl/nx/blob/19.6.4/packages/vite/src/utils/executor-utils.ts#L34

**Comment by absurdism2** [comment]
hi, unfortunately i can not share my repo. What i could add is that i see these terminals being run for e.g. git config, npm evec vite, both as admin and normal user, mainly these are "npm exec vite", run could of time. I did not have this issue before updating nx to latest version.

**Comment by MaxKless** [comment]
So I couldn't figure out exactly where the issue was in the nx repo but I do have a PR to prevent all these messages: https://github.com/nrwl/nx/pull/28073

Once it's released, let's make sure this is resolved!

**Comment by absurdism2** [comment]
when r u guys planning on releasing it ?

**Comment by MaxKless** [comment]
very soon, you should see a beta or canary release within the day. Proper release this week I think

**Comment by MaxKless** [comment]
Hey! We just cut a release `19.8.1` that contains this. Can you update and confirm that the issue is gone?

**Comment by absurdism2** [comment]
Hi. Problems still there, however i see this is happening only on latest webstorm only now.

**Comment by absurdism2** [comment]
your fixes however did move issue forward, previously on every file change (save) I had ton of these terminals, now they only appear when workspace is being refreshed via nx console (webstorm plugin). after uninstalling it all seems fine now, which is inline with what people report here too: https://github.com/nrwl/nx-console/issues/1751

**Comment by MaxKless** [comment]
That's nice! Are you on the latest nx console version for webstorm? I just released `1.32.1` which adds `windowsHide` in a couple of places in Nx Console as well. So those notifications should be gone.... Can you confirm that it still happens with that version?

**Comment by sk-tjdownes** [comment]
This is happening to me on 20.0.3. It only started after I ran `pnpm nx migrate latest` and `pnpm nx g infer-targets`

**Comment by MaxKless** [comment]
Can you check whether it happens if you remove the vite plugin? 
Iirc I found some code in vite itself that doesn't use windowsHide

**Comment by biansor** [comment]
Happening to me. Using powershell/cmd

```
Nx Version:
- Local: v21.1.3
- Global: v21.2.1
```

Only in my windows, works fine on Mac.

```
NX   Report complete - copy this into the issue template

Node           : 22.14.0
OS             : win32-x64
Native Target  : x86_64-windows
pnpm           : 10.12.1

nx (global)        : 21.2.1
nx                 : 21.2.1
@nx/js             : 21.2.1
@nx/jest           : 21.2.1
@nx/eslint         : 21.2.1
@nx/eslint-plugin  : 21.2.1
@nx/nest           : 21.2.1
@nx/node           : 21.2.1
@nx/web            : 21.2.1
@nx/webpack        : 21.2.1
typescript         : 5.8.3
---------------------------------------
Registered Plugins:
@nx/js/typescript
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin
@nx/js/typescript
```


It triggers after logging `Nx read the output from the cache instead of running the command for 1 out of 2 tasks.`

`NX   Storing terminal outputs for @packages/my-package with hash 14536401881812623568`

```
 NX   Running target build for project @mypackage and 1 task it depends on:
> nx run @packages/legacy-db:build
> tsc -p tsconfig.lib.json
> nx run @mypackage   [local cache]
> webpack-cli build node-env=development
chunk (runtime: main) main.js (main) 3.44 MiB (javascript) 670 bytes (runtime) [entry] [rendered]
webpack compiled successfully (3d74a2a134a1faaf)
 NX   Successfully ran target build for project @mypackage  and 1 task it depends on
Nx read the output from the cache instead of running the command for 1 out of 2 tasks.
```

**Comment by adlion** [comment]
I am on Debian 12 and have same issue 

```
 nx --version
 Nx Version:
  - Local: v21.3.11
  - Global: v21.3.11
```

In my case it opens 2 windows of VS Code.

Does not matter what command I run it opens the VS Code empty windows.

This happens only when I run from the integrated VS Code terminal.
Have uninstalled NX Console extension and same issue.

**Comment by MaxKless** [comment]
Hey, this sounds like a Linux issue I've heard of before. Could you check your vscode version and let me know what it is? If it's not the very latest, can you update and check? Either way, it's unrelated to this issue so please create a new one
