### ISSUE TITLE
works if the project is in the root folder

### ISSUE THREAD

**Issue by motionrus** [nrwl/nx-console#2157]
if the project folder is not at the very top, an error will appear

<img width="395" alt="image" src="https://github.com/nrwl/nx-console/assets/14940768/907d7909-347a-4ca1-a8f8-2ad40772c4a0">

how do I set the root folder in which the project itself is located?

the folder is called frontend

**Comment by MaxKless** [comment]
There should be some info text about this in the nx toolwindow :) You can change the workspace path in the nx console settings
