### ISSUE TITLE
[Jetbrains] Nx Console cannot run any task from IDE if there's a folder named `nx` in workspace root

### ISSUE THREAD

**Issue by Arilas** [nrwl/nx-console#2159]
We have some local Nx Plugins in our setup that are placed in `nx` folder of workspace Root. When you want to run any task from an IDE it's failing with error code 127, because it's trying to run a folder instead of nx from node_modules/.bin folder

## Current Behavior

Nx Console incorrectly looks for `nx` binary and uses folder as a binary

## Expected Behavior

Nx Console should check that nx is a file and not a folder, also it would be good to allow to select nx binary like it was done with prettier, eslint and other plugins

## Steps to Reproduce

1. Create a monorepo with Nx
2. Create a folder named `nx` in workspace root, maybe place something inside
3. Try to run any command from Nx Console

### Failure Logs / Images / Videos

```
/Volumes/Dev/Projects/project-name/nx run host:serve

Process finished with exit code 127
```

### Environment

- Nx Console version: 1.25.0
- WebStorm version: 2024.2 (checked also on latest stable 2023.1.3)

**Comment by MaxKless** [comment]
Huh this is an interesting bug but it makes sense. I'll have a look at it ASAP!
