### ISSUE TITLE
Add `Move/Remove/etc` actions to the Nx Console context menu in Intellij/Webstorm/Rider

### ISSUE THREAD

**Issue by Den-dp** [nrwl/nx-console#2170]
## Description

For Intellij/Webstorm/Rider, add `Move/Remove` actions to the Nx Console context menu to better feature parity with Nx Console in VS Code.

## Motivation

Since VS Code times, I used to run move/remove from here:

![image](https://github.com/nrwl/nx-console/assets/1770529/1f006409-5039-49af-9389-4d9dc3f32e28)

## Suggested Implementation

like in VS Code

![image](https://github.com/nrwl/nx-console/assets/1770529/4133b26d-b4a9-47a0-97f3-4d204fd979de)

**Comment by MaxKless** [comment]
Good idea! It already exists in the context menu of the file tree in IntelliJ. But adding it here could also be smart. 
I won't have the time to work on this too soon but would love to collab if anyone is interested. It shouldn't be too difficult.
@mkapal maybe?
