### ISSUE TITLE
question: how to use new command ui?

### ISSUE THREAD

**Issue by AdditionAddict** [nrwl/nx-console#2177]
I can see https://github.com/nrwl/nx-console/pull/2166 removes the generate ui page and we're left with the below

![image](https://github.com/nrwl/nx-console/assets/48436581/8deed394-b905-434e-a811-6e437b42f96a)

But how to use this, is it a case now of manually writing the whole command out?

**Comment by MaxKless** [comment]
you can still use the normal generate ui :) That PR only removed the old ui implementation. 
just run the command 'nx generate (ui)'

**Comment by MaxKless** [comment]
let me know if you encounter any issues with this
