### ISSUE TITLE
Generate UI window does not render in VSCode 

### ISSUE THREAD

**Issue by Spencer-Easton** [nrwl/nx-console#2181]
When I select a generator the VSCode command pallet interface prompts me for each of the generator settings. It looses context if you click away, does not offer suggestions like project name, does not have a dry run preview.  

When I select a generator, VSCode opens a Generate UI window where I can input my settings for the generator

Must have been in the last week,

This is a regression from previous behavior

## Steps to Reproduce
![image](https://github.com/nrwl/nx-console/assets/9576580/11856268-672d-4d3d-a322-926de5b72f22)  
  
![image](https://github.com/nrwl/nx-console/assets/9576580/a451a4c2-403a-4b55-ab74-8447cd11080b)  
  
![image](https://github.com/nrwl/nx-console/assets/9576580/9e6d11eb-fe43-4b8f-b7e9-1a324ec158d9)  
  

### Environment

VSCode 1.90.1
NX Console: 18.22.0

 Node   : 18.16.0
   OS     : linux-x64
   npm    : 9.5.1

   nx                 : 16.8.1
   @nx/js             : 16.8.1
   @nx/jest           : 16.8.1
   @nx/linter         : 16.8.1
   @nx/workspace      : 16.8.1
   @nx/angular        : 16.8.1
   @nx/cypress        : 16.8.1
   @nx/devkit         : 16.8.1
   @nx/esbuild        : 16.8.1
   @nx/eslint-plugin  : 16.8.1
   @nx/express        : 16.8.1
   @nx/nest           : 16.8.1
   @nx/node           : 16.8.1
   @nx/plugin         : 16.8.1
   @nx/storybook      : 16.8.1
   @nrwl/tao          : 16.8.1
   @nx/web            : 17.3.2
   @nx/webpack        : 16.8.1
   nx-cloud           : 16.5.2
   typescript         : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 15.3.0
   @ngrx/effects         : 15.3.0
   @ngrx/entity          : 15.3.0
   @ngrx/router-store    : 15.3.0
   @ngrx/schematics      : 15.3.0
   @ngrx/store           : 15.3.0
   @ngrx/store-devtools  : 15.3.0
   @storybook/angular    : 7.4.6
   ngrx-immer            : 2.2.1

**Comment by MaxKless** [comment]
Hey! Can I ask how you're starting the generate form? Is it via the sidebar?

**Comment by Spencer-Easton** [comment]
I've always launched it via the command pallet (crtl-shft-a) NX:generate

EDIT: DOH we can close this issue. 
I see there is BOTH NX:generate and NX:generate (UI)

The NX:generate (UI) was always at the top of the list, now it sorts NX:generate first.  

Now I know there is two of them I can pick the right one. 

Sorry and Thanks.

**Comment by MaxKless** [comment]
No worries. You're not the first one to run into this, I'll make the behaviour more explicit and have "Generate (UI)" be the default here https://github.com/nrwl/nx-console/pull/2182
