### ISSUE TITLE
Save my choices in Generate UI

### ISSUE THREAD

**Issue by davidda** [nrwl/nx-console#2187]
## Description

I would like the choices and inputs I make in Generate UI to be persisted, so I can quickly generate components without having to enter all my default options every time I open the UI again. This should not apply to fields that are very likely to change for each generation (mainly the name of the generated entity)

## Motivation

It saves a lot of time.

**Comment by MaxKless** [comment]
Hey! 
This already exists in core nx.[ You can just specify defaults in `nx.json`](https://nx.dev/reference/nx-json#generators)and Nx Console will pick up on them. Let me know if you've tried that :)
