### ISSUE TITLE
Nx-related VSCode processes remains not disposed after closing VSCode

### ISSUE THREAD

**Issue by Den-dp** [nrwl/nx-console#2216]
## Current Behavior

Nx-related VSCode processes remains not disposed after closing VSCode.

## Expected Behavior

I expect no Nx-related processes after closing VSCode.

## Steps to Reproduce

* Generate an empty nx project `npx create-nx-workspace@19 nx19empty --preset=apps --workspaceType=integrated --ci=skip`
* Open it in VS Code with Nx Console installed.
* Close it and look at the list of processes.

### Failure Logs / Images / Videos

https://github.com/user-attachments/assets/b4448ca0-4eca-4fc8-b3c3-22f6eeae897c

### Environment

create-nx-workspace@19
Windows 10 Pro

- Nx Console version: 18.25.0
- VSCode version: 1.19.1

**Comment by MaxKless** [comment]
Hey thanks for the report! It looks to me like this has the same root cause as https://github.com/nrwl/nx/issues/27006 which is an issue with plugin workers not being shut down correctly somehow... will investigate further

**Comment by MaxKless** [comment]
try with `19.5.4` for now, it should solve the issue :)

**Comment by Den-dp** [comment]
thanks, it works
