### ISSUE TITLE
Terminal Popup with new webstorm version

### ISSUE THREAD

**Issue by StevenSchoening** [nrwl/nx-console#2243]
## Current Behavior

With the new webstorm version i always get a popup from a terminal which closes really fast.
When i deactivate the nx console it it works fine. 

## Expected Behavior

i expect that i can use the nx console without any popup terminals opening and closing.

## Steps to Reproduce

it happened for me and a coworker in this way: we have the new webstorm version installed and the nx console and while working, saving a file the popup terminal opened and closed instantly.

### Failure Logs / Images / Videos
-

### Environment
Webstorm: 2024.2.0.1
Nx console: 1.30.0

**Comment by MaxKless** [comment]
Hey! This is probably to do with the underlying nx version. Can you please post your `nx report` so we can make sure this is fixed?

**Comment by ghost23** [comment]
I have the same issue. My nx report:

```
NX   Report complete - copy this into the issue template

Node           : 22.3.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.8.1

nx (global)        : 19.6.4
nx                 : 19.6.4
@nx/js             : 19.6.4
@nx/linter         : 19.6.4
@nx/eslint         : 19.6.4
@nx/workspace      : 19.6.4
@nx/cypress        : 19.6.4
@nx/devkit         : 19.6.4
@nx/esbuild        : 19.6.4
@nx/eslint-plugin  : 19.6.4
@nx/playwright     : 19.6.4
@nx/storybook      : 19.6.4
@nrwl/tao          : 19.6.4
@nx/vite           : 19.6.4
@nx/vue            : 19.6.4
@nx/web            : 19.6.4
@nx/webpack        : 19.6.4
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/vite/plugin
@nx/playwright/plugin
@nx/storybook/plugin
```

**Comment by MaxKless** [comment]
Hey! I've seen these before but I'm really struggling to reproduce the issue on my windows machine. Could you provide a reproduction repo that I can clone and see the issue myself? It must be some specific combination of plugins or the like that's causing this. Usually these popups don't come from Nx Console but from the underlying nx version itself.

I'd love to fix this ASAP but it's hard if I don't see the error myself.

**Comment by ghost23** [comment]
Hi @MaxKless , I am not sure I understand your request. How would I provide a repo with the webstorm plugins that I use?

**Comment by MaxKless** [comment]
Hey :) Can you try this again on the newly-released nx `19.8.1`? 
The issue should be gone!

**Comment by ghost23** [comment]
Hi, I have updated to the latest, 19.8.2. The issue is still there. It happens especially when I open a project.json or nx.json or package.json file. And if I run a target command via the nx console.

During normal coding it rarely happens.

**Comment by MaxKless** [comment]
Did you run `nx reset`, kill the daemon and restart the extension after updating?
Are you on the latest nx console version?

**Comment by ghost23** [comment]
No, I did not. Yes, I am on the latest nx console version.

I will test again.

**Comment by ghost23** [comment]
OK, I have tested now for a while. So it definitely happens less often now. It still happens at least once when I start the IDE, but I guess that is OK. So for me, this is fine now, definitely not as annoying as it used to be. Thank you.

**Comment by mklueh** [comment]
Still seing them here and then

**Comment by Nosfistis** [comment]
This happens in a new project with nx 22.
