### ISSUE TITLE
Cannot open project.json in Webstorm 2024.2.1 with NX Console plugin enabled

### ISSUE THREAD

**Issue by lhoosconciso** [nrwl/nx-console#2251]
## Current Behavior

When I try to open any `project.json` in Webstorm 2024.2.1 with the NX Console plugin enabled, the editor tab pops up briefly without any content rendered and immediately closes again. The issue doesn't occur in Webstorm to 2024.1.5 or when the NX Console plugin is disabled.

## Expected Behavior

The Ability to open `project.json` files normally

## Steps to Reproduce

1. Clone https://github.com/nrwl/nx-examples
2. Open it in Webstorm 2024.2.1 with NX Console plugin enabled
3. Try to open any `project.json`

### Failure Logs / Images / Videos

No error message is displayed in the IDE.  
I also couldn't find anything interesting in `idea.log`. It just says:
```
2024-09-03 11:07:04,425 [ 124003]   INFO - #dev.nx.console.listeners.NxEditorListener - Connecting /tmp/nx-examples/apps/products/project.json to lsp
2024-09-03 11:07:04,426 [ 124004]   INFO - #dev.nx.console.nxls.NxlsWrapper - Connecting textService to file:///tmp/nx-examples/apps/products/project.json
```
Please tell me if there are any other places I should look.

### Environment

- Nx Console version: 1.30.1
- Webstorm version: 2024.2.1
- OS: Arch Linux with all packages up to date

`nx report`:
```
Node           : 20.17.0
OS             : linux-x64
Native Target  : x86_64-linux
yarn           : 4.2.2

nx (global)        : 19.3.1
nx                 : 19.6.0-beta.6
@nx/js             : 19.6.0-beta.6
@nx/jest           : 19.6.0-beta.6
@nx/linter         : 19.6.0-beta.6
@nx/eslint         : 19.6.0-beta.6
@nx/workspace      : 19.6.0-beta.6
@nx/angular        : 19.6.0-beta.6
@nx/cypress        : 19.6.0-beta.6
@nx/devkit         : 19.6.0-beta.6
@nx/eslint-plugin  : 19.6.0-beta.6
@nx/react          : 19.6.0-beta.6
@nrwl/tao          : 19.6.0-beta.6
@nx/web            : 19.6.0-beta.6
@nx/webpack        : 19.6.0-beta.6
typescript         : 5.5.3
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/cypress/plugin
@nx/jest/plugin
---------------------------------------
Community plugins:
@ngrx/component-store : 18.0.2
@ngrx/effects         : 18.0.2
@ngrx/entity          : 18.0.2
@ngrx/operators       : 18.0.2
@ngrx/router-store    : 18.0.2
@ngrx/store           : 18.0.2
@ngrx/store-devtools  : 18.0.2
```

**Comment by MaxKless** [comment]
That's awesome, glad to hear it! Thank you :)
