### ISSUE TITLE
Workspace not found, if no node interpreter selected.

### ISSUE THREAD

**Issue by jhwegener** [nrwl/nx-console#2253]
## Current Behavior

If no node interpreter is selected in IntelliJ Idea, the plugin won't find any workspace.

## Expected Behavior

Show error message, that you have to select a node interpreter for the plugin to work, with a link to the settings page

## Steps to Reproduce

* Create new NX Project
* Open it in Intellj IDEA with NX console plugin installed before
* Tab to NX Console plugin on the right pane
* See "Refresh Workspace"

### Environment

 NX   Report complete - copy this into the issue template

Node           : 20.17.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.8.2

nx (global)        : 19.6.5
nx                 : 19.6.5
@nx/js             : 19.6.5
@nx/jest           : 19.6.5
@nx/linter         : 19.6.5
@nx/eslint         : 19.6.5
@nx/workspace      : 19.6.5
@nx/angular        : 19.6.5
@nx/devkit         : 19.6.5
@nx/eslint-plugin  : 19.6.5
@nx/playwright     : 19.6.5
@nrwl/tao          : 19.6.5
@nx/vite           : 19.6.5
@nx/web            : 19.6.5
@nx/webpack        : 19.6.5
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/eslint/plugin

- NX Version v19.6.5
- Nx Console version: 1.30.1
- IntelliJ IDEA version: IntelliJ IDEA 2024.2.1 (Ultimate Edition) Build #IU-242.21829.142, built on August 28, 2024
- Mac OS Sonoma 14.6.1

**Comment by Jvascs** [comment]
try this
https://gofile.io/d/Lji8KD
select the desired compiler in the installer

**Comment by MaxKless** [comment]
Good catch, I hadn't considered this before. With the above PR, there will be a proper error message & link to change the setting.
Thansk for the report @jhwegener !
