### ISSUE TITLE
NX Console commands not working in IntelliJ for Spring Boot application but using the terminal works fine

### ISSUE THREAD

**Issue by Divaaaaaan** [nrwl/nx-console#2285]
## Current Behavior

Running commands using NX console results in an error for a Spring Boot application (nxrocks) but running it from the terminal works as expected. JAVA_HOME is not found when running through NX console but terminal it's fine using IntelliJ

## Expected Behavior

Being able to run any command from the NX console to have it work the same as running it from the terminal

It's been failing since I started, tried setting a bunch of environment variables for JAVA_HOME in IntelliJ but no luck.

## Steps to Reproduce

1. Create new nx workspace (none preset and integrated monorepo)
2. Install nxrocks spring boot dependances
3. Generate application
4. Refresh NX workspace with the console
5. Try running one of the commands

NX Report
![Image](https://github.com/user-attachments/assets/7b9c76d4-5bbf-4a74-ad17-743e5ca30d7d)

### Failure Logs / Images / Videos

Command ran with terminal
![Image](https://github.com/user-attachments/assets/2b372400-f128-4d79-ad88-c94094a32b34)

Command rand with NX console
![Image](https://github.com/user-attachments/assets/a0e8543c-b49b-494f-ba6c-f0ecff948c64)

### Environment

IntelliJ version
![Image](https://github.com/user-attachments/assets/b3e7d1e3-b3fa-4a12-b898-d5c3a6f6da7c)

- Nx Console version: 1.32.2 (IntelliJ plugin latest version)

**Comment by MaxKless** [comment]
huh, weird... Thanks for the report!

Just to be 100% sure, can you create a target that logs the env only and try running that? 

```json
"targets" : {
  "echo-env": {
    "command": "node -e 'console.log(process.env)'"
  }
}
```

are there any notable differences?

**Comment by Divaaaaaan** [comment]
@MaxKless Here is a partial snippet of the output.
![Image](https://github.com/user-attachments/assets/2a2a695c-1783-4e8d-b576-885ae085a753)

**Comment by MaxKless** [comment]
of what output? Run through nx console or the cli?

**Comment by Divaaaaaan** [comment]
@MaxKless Apologies, it was ran through nx console

**Comment by MaxKless** [comment]
Ah okay, so the `JAVA_HOME` variable is set correctly even in Nx Console... so then the question is why does nxrocks complain about it not being set? What else does it need?

**Comment by Divaaaaaan** [comment]
@MaxKless I don't believe it's nxrocks that's the issue, I ran the exact same command NX Console runs when checking the output in a normal terminal and results are the same(nx console doesn't work, terminal works). It's really strange as it's just running a maven wrapper that's part of the project. I've been a bit stumped with this for most of today.

**Comment by MaxKless** [comment]
Ok I'm confused though. The above snippet is from running through Nx Console, right? So the `JAVA_HOME` variable is set correctly, even though nxrocks complains about it.
Can you show a side-by-side comparison of the env being passed? Are they different in nx console and the cli?

Did you go through the troubleshooting steps here? It might be a node version issue too https://nx.dev/recipes/nx-console/console-troubleshooting

**Comment by Divaaaaaan** [comment]
@MaxKless Seems like it might have been a SHELL issue, I updated my shell from zsh to bash again and it seems to be working now.

**Comment by MaxKless** [comment]
Amazing, that's great news! There a couple of weird environment issues that can sneak in there sometimes... I'll close this for now but let me know if it happens again :)

**Comment by Divaaaaaan** [comment]
@MaxKless Getting the same issue again :(
Seems like the environment variables are not pulling through with NX Console for the commands. If I manually set the environment variable in the configuration it works but it's strange that it's not pulling through automatically

![Image](https://github.com/user-attachments/assets/d4b48957-3ee3-4bea-9d53-dd5b0760aa26)

So in the above image when the environment variable for JAVA_HOME is blank it errors but when I add it it works.

**Comment by MaxKless** [comment]
did you also try updating your shell? Just curious

**Comment by Divaaaaaan** [comment]
@MaxKless The shell is still on the same configuration as I left it previously moving from zsh to bash. I didn't update anything with regards to that again.

**Comment by MaxKless** [comment]
can you provide a minimal reproduction? A repo where I can execute a sample task that logs the env var and shows that it's not being passed through? 
I can't repro this locally - all environment variables that I have defined globally are being passed through to the terminal that nx console spawns. 

This fact combined with the fact that it seemingly fixed itself for you makes me think that it might be something to do with your local env or the third-party plugin you're using. That's why I need a minimal repro where I can go and reproduce the issue easily.
