### ISSUE TITLE
Webstorm NX Console Plugin does not wokring in yarn pnp

### ISSUE THREAD

**Issue by ChoSeoHwan** [nrwl/nx-console#2296]
## Current Behavior

"We couldn't find any projects in this workspace." notification in "NX Console UI".

And infinity loading when click "REFRESH WORKSPACE" button.

## Expected Behavior

Running the NX Console plugin with Yarn PnP without issues.

## Steps to Reproduce

1. clone git repository
```bash
git clone https://github.com/ChoSeoHwan/nx-bug-report.git
```

2. yarn install
```bash
yarn install
```

3. enable nx console plugin in webstorm

![Image](https://github.com/user-attachments/assets/c9ab5d9c-696f-4bda-9425-aff458732781)

4. Click "REFRESH WORKSPACE" button

- stuck in loading

![Image](https://github.com/user-attachments/assets/4051d30f-f8cf-483c-ad98-afeda2e73fa0)

### Environment

- OS : windows 10
- Webstorm : Build #WS-242.23726.96, built on October 22, 2024
- Node : v22.9.0
- NX Console : 1.32.4
- Yarn : 4.5.1

**Comment by MaxKless** [comment]
Hey! I can reproduce this, it definitely seems related to `yarn pnp`. I have an idea for fixing this, will report back :)

**Comment by MaxKless** [comment]
Here's a PR to fix it, will add some tests as well so we can make sure that yarn pnp keeps working in the future :) 
https://github.com/nrwl/nx-console/pull/2301

**Comment by MaxKless** [comment]
fixed with https://github.com/nrwl/nx-console/pull/2301
