### ISSUE TITLE
NX Workspace empty

### ISSUE THREAD

**Issue by lenav99** [nrwl/nx-console#2306]
## Current Behavior

When I try to use the NX Console in VS Code, no projects are found:
![Image](https://github.com/user-attachments/assets/6dfcda4f-84ee-415a-9775-3580e3df54d4)

## Expected Behavior

There should be projects listed, as it works for me on another device and for other collaborators as well. 

## Steps to Reproduce

Init mono repo and see the console is empty. 

### Failure Logs / Images / Videos

In the Output of the Nx Language Server i receive this error:
Unhandled exception: e.Watcher is not a constructor
TypeError: e.Watcher is not a constructor
    at bp.initWatcher (c:\Users\<user>\.vscode\extensions\nrwl.angular-console-18.29.1\nxls\main.js:94:3092)

### Environment

Node           : 22.11.0
OS             : win32-x64
Native Target  : wasm32
npm            : 10.9.0

nx                 : 20.0.10
@nx/js             : 19.7.3
@nx/jest           : 19.7.3
@nx/linter         : 19.7.3
@nx/eslint         : 19.7.3
@nx/workspace      : 19.7.3
@nx/angular        : 19.7.3
@nx/devkit         : 19.7.3
@nx/esbuild        : 19.7.3
@nx/eslint-plugin  : 19.7.3
@nx/express        : 19.7.3
@nx/node           : 19.7.3
@nrwl/tao          : 19.7.3
@nx/web            : 19.7.3
@nx/webpack        : 19.7.3
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/jest/plugin
@nx/webpack/plugin
---------------------------------------
The following packages should match the installed version of nx
  - @nx/js@19.7.3
  - @nrwl/js@19.7.3
  - @nx/jest@19.7.3
  - @nrwl/jest@19.7.3
  - @nx/linter@19.7.3
  - @nx/eslint@19.7.3
  - @nx/workspace@19.7.3
  - @nrwl/workspace@19.7.3
  - @nx/angular@19.7.3
  - @nrwl/angular@19.7.3
  - @nx/devkit@19.7.3
  - @nrwl/devkit@19.7.3
  - @nx/esbuild@19.7.3
  - @nrwl/esbuild@19.7.3
  - @nx/eslint-plugin@19.7.3
  - @nrwl/eslint-plugin-nx@19.7.3
  - @nx/express@19.7.3
  - @nrwl/express@19.7.3
  - @nx/node@19.7.3
  - @nrwl/node@19.7.3
  - @nrwl/tao@19.7.3
  - @nx/web@19.7.3
  - @nrwl/web@19.7.3
  - @nx/webpack@19.7.3
  - @nrwl/webpack@19.7.3

To fix this, run `nx migrate nx@20.0.10`

Side Note: I did run nx migrate nx@20.0.10. Didn't fix the problem.

**Comment by MaxKless** [comment]
Hi :) Thanks for the report.
It looks like you have different nx & nx plugin versions. Please try the following: 
- remove all `@nrwl` packages from your `package.json`. They have since been replaced by the `@nx` versions. You must've missed running a migration to update this at some point
- change the version of the `nx` package to `19.7.3` to be in line with the other packages
- run `npm i`
- restart your VSCode and try again

**Comment by lenav99** [comment]
> Hi :) Thanks for the report. It looks like you have different nx & nx plugin versions. Please try the following:
> 
> * remove all `@nrwl` packages from your `package.json`. They have since been replaced by the `@nx` versions. You must've missed running a migration to update this at some point
> * change the version of the `nx` package to `19.7.3` to be in line with the other packages
> * run `npm i`
> * restart your VSCode and try again

Hi :) i don’t have @nrwl packages in the package.json so i don’t think this will fix it.

**Comment by MaxKless** [comment]
How about aligning the nx version with the @nx packages? Have you tried that?

**Comment by lenav99** [comment]
> How about aligning the nx version with the [@nx](https://github.com/nx) packages? Have you tried that?

I did. The nx report looks like this now:

Node           : 22.11.0
OS             : win32-x64
Native Target  : wasm32
npm            : 10.9.0

nx                 : 20.0.10
@nx/js             : 20.0.10
@nx/jest           : 20.0.10
@nx/eslint         : 20.0.10
@nx/workspace      : 20.0.10
@nx/angular        : 20.0.10
@nx/devkit         : 20.0.10
@nx/esbuild        : 20.0.10
@nx/eslint-plugin  : 20.0.10
@nx/express        : 20.0.10
@nx/node           : 20.0.10
@nx/web            : 20.0.10
@nx/webpack        : 20.0.10
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/jest/plugin
@nx/webpack/plugin

but i still get the same error in the ouput and it's still not working.

**Comment by MaxKless** [comment]
The fact that the native target is `wasm32` is a bit confusing to me, it should just be a windows distribution, I think?
Can you double check that you've installed `Node.js` for the right platform? You're on a 64-bit windows machine, I imagine? Just check that it's not installed for 32 bit.
Also check out this guide and read through it: https://nx.dev/troubleshooting/troubleshoot-nx-install-issues

**Comment by lenav99** [comment]
It works now. I installed an older version of node, 20.18.0 and i also installed Latest Microsoft Visual C++ Redistributable Version and after that it worked. I’m not really sure why. But it also changed the native target.

**Comment by MaxKless** [comment]
ok nice glad it worked out for you! Sometimes this whole node + windows thing is weird... But it seems like the troubleshooting guide worked out for you. Do you have any input on how we could improve it?
I'll close this for now as it's fixed

**Comment by lenav99** [comment]
The troubleshooting guide wasn’t really the nudge in the right direction, more your input that the native target looked off. And when i looked that up along with my error i found another issue where people had different solutions that i tried and those two worked! Thank you for your time and help!
