### ISSUE TITLE
VSCode for Windows: Adding a dev-dependency from Nx Console ends up adding an extra @ to the packages

### ISSUE THREAD

**Issue by ErickRodrCodes** [nrwl/nx-console#2314]
### Current Behavior

I noted after installing Nx 20 and the latest Nx Console that in Windows, when you select a dev-dependency from your nx console panel, the available packages has an extra `@` character:

![Image](https://github.com/user-attachments/assets/5edd7a4b-954d-42ae-a2b3-ee3397fffa55)

### Expected Behavior

It shouldn't have an extra character!

### Steps to Reproduce

1. in a windows machine (windows 11, 

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 20.17.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.8.2

nx (global)        : 20.0.12
nx                 : 20.0.12
@nx/js             : 20.0.12
@nx/jest           : 20.0.12
@nx/eslint         : 20.0.12
@nx/workspace      : 20.0.12
@nx/angular        : 20.0.12
@nx/devkit         : 20.0.12
@nx/eslint-plugin  : 20.0.12
@nx/playwright     : 20.0.12
@nx/plugin         : 20.0.12
@nx/react          : 20.0.12
@nx/vite           : 20.0.12
@nx/web            : 20.0.12
@nx/webpack        : 20.0.12
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/vite/plugin
---------------------------------------
Local workspace plugins:
         @erickrodrcodes/nx-electron-vite
```

### Failure Logs

```shell

```

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by MaxKless** [comment]
Thanks for the report! I should've caught this right away but didn't. Here's a fix: https://github.com/nrwl/nx-console/pull/2327
