### ISSUE TITLE
VSCode ./nx.bat: No such file or directory

### ISSUE THREAD

**Issue by MJLHThomassenHadrian** [nrwl/nx-console#2319]
## Current Behavior

For VS Code

When i run any command via the plugin (F1 -> NX: List for example) i get the following error in my console:
```
Executing task: ./nx.bat list

bash: ./nx.bat: No such file or directory

 *  The terminal process "C:\Program Files\Git\bin\bash.exe '--login', '-i', '-c', './nx.bat list'" terminated with exit code: 127. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

Now i thought this was due to me having bash as default terminal, but when i set it back to cmd, i get a similar error:

```
Executing task: ./nx.bat list 

'.' is not recognized as an internal or external command,
operable program or batch file.

 *  The terminal process "C:\WINDOWS\System32\cmd.exe /d /c ./nx.bat list" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

nx does run properly when using `npx nx list` for example.

## Expected Behavior

I expect the command to run :)

## Steps to Reproduce

<Can you reproduce this on https://github.com/nrwl/nx-examples?
When using this repo, i get a similar error, only this repo seems to be configured to use yarn by default:

```
 *  Executing task: yarn nx list 

'yarn' is not recognized as an internal or external command,
operable program or batch file.

 *  The terminal process "C:\WINDOWS\System32\cmd.exe /d /c yarn nx list" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

### Failure Logs / Images / Videos

See above.

### Environment

- Nx Console version: v18.30.4
- VSCode version: 1.95.3

nx report:

```
Node           : 22.11.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.9.0

nx             : 19.8.6
@nx/js         : 19.8.6
@nx/workspace  : 19.8.6
@nx/devkit     : 19.5.3
@nrwl/tao      : 19.8.6
typescript     : 5.6.3
---------------------------------------
Registered Plugins:
@nx-dotnet/core
---------------------------------------
Community plugins:
@nx-dotnet/core        : 2.4.5
@nx-tools/nx-container : 6.1.0
```

**Comment by MaxKless** [comment]
Hey @MJLHThomassenHadrian can you paste your `nx.json`? It seems like a misconfiguration, maybe the `installation` property is set?

**Comment by MaxKless** [comment]
The `nx-examples` error is only because you don't have yarn installed, if you install it it should go away

**Comment by MJLHThomassenHadrian** [comment]
Hey @MaxKless , here is our nx.json:

```
{
  "installation": {
    "version": "19.8.6"
  },
  "plugins": [
    {
      "plugin": "@nx-dotnet/core",
      "options": {
        "moduleBoundaries": [
          ...
        ]
      }
    }
  ],
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "defaultBase": "main",
  "nxCloudId": "<our cloud id."
}
```

I'll install yarn and try it out with the examples repo. I thought I had it installed, but apparantly i dont.

**Comment by MaxKless** [comment]
it might me worth adding some check or better error message for the installation property, you're right... glad it fixed it though!

**Comment by MJLHThomassenHadrian** [comment]
Yes, thanks for the input. I'm closing the ticket now as the problem is solved. But maybe you could clarify on -why- this is a problem when the installation property is there?

**Comment by MaxKless** [comment]
The `installation` property is what separates a regular installation of nx (in a root `package.json`) from a `.nx` (sometimes called encapsulated) installation where we hide `node_modules` in the `.nx` folder so it's not as confusing for non-js devs. 

Tasks are run differently when the `installation` property is set and that's why this error pops up.

**Comment by MJLHThomassenHadrian** [comment]
Ah yes, i see a mention of the encapsulated .nx in the docs now: https://nx.dev/recipes/installation/install-non-javascript (though it does not mention the exact setup. We did not have this method of installation (though the installation property was set somehow), so thats where the conflict was. Thanks for clearing this up!
