### ISSUE TITLE
Unexpected behavior with Webstorm NX Console

### ISSUE THREAD

**Issue by kwood-gmr** [nrwl/nx-console#2323]
## Current Behavior

I right click on the folder where I want to add an angular component, then choose that option from the list that appears. Inside the UI I am prompted for "path" with a note that this will be relative to the workspace root. (It is actually relative to the location I right clicked and launched from.) Then for a component named "foo" in its own dedicated dir I must put in "foo/foo"

## Expected Behavior

- I would expect to have a field "name" for the component.
- I would also expect the default to be placing it in a directory with the same name
- It would be nice to have eiter
  - a checkbox to place in dedicated dir or where I started from
  - a separate path textbox to add the directory (from the launch point)
 
 

This used to have "name" and "path" textboxes

## Steps to Reproduce

In a WebStorm project:

- Right click on a folder inside the "src" folder of an angular project
- Choose NX Generate (UI) from the list
- Choose @nx/angular - component

### Failure Logs / Images / Videos

![Image](https://github.com/user-attachments/assets/f45c635e-bf11-4a8d-a30f-a0261e9cc9f2)

![Image](https://github.com/user-attachments/assets/7f5b81e5-17bd-48f3-a424-cf0d6fba1d4b)

### Environment

![Image](https://github.com/user-attachments/assets/411e1bdd-60d8-4095-b529-910ff5fb13ad)

![Image](https://github.com/user-attachments/assets/f0661109-090e-4cbe-a44d-1cff265c3702)

  "dependencies": {
    "@angular/animations": "18.2.11",
    "@angular/common": "18.2.11",
    "@angular/compiler": "18.2.11",
    "@angular/core": "18.2.11",
    "@angular/forms": "18.2.11",
    "@angular/platform-browser": "18.2.11",
    "@angular/platform-browser-dynamic": "18.2.11",
    "@angular/router": "18.2.11",
    "@ngneat/until-destroy": "^10.0.0",
    "@ngrx/component-store": "18.1.1",
    "@ngrx/signals": "18.0.0",
    "@nx/angular": "20.1.0",
    "@sentry/angular": "^8.20.0",
    "@tanstack/angular-query-experimental": "^5.49.1",
    "ngx-extended-pdf-viewer": "21.4.6",
    "oidc-client-ts": "^3.0.1",
    "primeicons": "^7.0.0",
    "primeng": "^17.18.1",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zod": "^3.23.8",
    "zone.js": "0.14.10"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "18.2.9",
    "@angular-devkit/core": "18.2.9",
    "@angular-devkit/schematics": "18.2.9",
    "@angular-eslint/eslint-plugin": "^18.0.1",
    "@angular-eslint/eslint-plugin-template": "^18.0.1",
    "@angular-eslint/template-parser": "^18.0.1",
    "@angular/cli": "~18.2.0",
    "@angular/compiler-cli": "18.2.11",
    "@angular/language-service": "18.2.11",
    "@nx/devkit": "20.1.0",
    "@nx/eslint": "20.1.0",
    "@nx/eslint-plugin": "20.1.0",
    "@nx/jest": "20.1.0",
    "@nx/js": "20.1.0",
    "@nx/playwright": "20.1.0",
    "@nx/workspace": "20.1.0",
    "@playwright/test": "^1.36.0",
    "@schematics/angular": "18.2.9",
    "@swc-node/register": "~1.9.1",
    "@swc/core": "~1.5.7",
    "@swc/helpers": "~0.5.11",
    "@types/jest": "29.5.14",
    "@types/node": "18.16.9",
    "@typescript-eslint/eslint-plugin": "7.16.0",
    "@typescript-eslint/parser": "7.16.0",
    "@typescript-eslint/utils": "7.16.0",
    "autoprefixer": "^10.4.0",
    "eslint": "~8.57.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-playwright": "^0.15.3",
    "fantasticon": "^2.0.0",
    "install-peerdeps": "^3.0.3",
    "jest": "29.7.0",
    "jest-environment-jsdom": "29.7.0",
    "jest-preset-angular": "~14.1.0",
    "nx": "20.1.0",
    "postcss": "^8.4.5",
    "prettier": "^2.6.2",
    "prettier-plugin-organize-imports": "^3.2.4",
    "tailwindcss": "^3.0.2",
    "ts-jest": "^29.1.0",
    "ts-node": "10.9.1",
    "typescript": "5.5.4"
  },

- Nx Console version: 1.33.0
- WebStorm version: 2024.3

(@mandarini

**Comment by MaxKless** [comment]
Hello @kwood-gmr, thanks for the input! It helped uncover some inconsistencies in how we do things. 
The behaviour that you're seeing seems mostly expected to me. 

> I would expect to have a field "name" for the component.

This exists if you expend the UI to show all options. To make it easier for folks (so they only have to specify the name and location once, we expose the `path` option as a shortcut that also sets the name)

> I would also expect the default to be placing it in a directory with the same name

From what I can see, this happens. You have a `foo` component that ends up in a `foo` folder, right?

>It would be nice to have eiter
a checkbox to place in dedicated dir or where I started from
a separate path textbox to add the directory (from the launch point)

This is handled via the `Working Directory` controls below the search bar. This reflects the place you launched the UI from and will be where the generator is executed from. You can delete the path and run the generator from the workspace root instead.


The biggest problem I see here is the description of the `path` option, it's wrong and misleading. You're right, it's not relative to the workspace root. It's relative to the current working directory. I think if this was correct there would be less confusion.

Do you think it would help if we added a tooltip next to the `path` option to let folks know the name is controlled by this as well?
Let me know what you think :)

**Comment by kwood-gmr** [comment]
I am going to strongly disagree that the behavior is anything reasonably expected. In fact -- the name seems to be ignored. Below I have captured the generate text having done some testing. Clearly the "name" is ignored. PErsonally, upon thinking about it I don't have an issue with "name" going away but.... The text "The path at which to create the component file, relative to the workspace root. By default, it is set to the root of the project." is not misleading it is wrong. 

Name should either be removed completely or fixed. I can understand a desire to keep the label as "path" given it is simply passed as that into the cli. But... the note needs changed. Perhaps it should say the name/path for the component relative to the launch point. Forcing me to go from root would cause me to reconsider the role of the product. 

Further - given that the ecosystem seems to prefer placing every component in its own directory having a means to do this short of repeating myself (either in two text boxes or one) seems less than ideal.

C:/_repos/merlin-0/frontend/node_modules/.bin/nx.cmd g @nx/angular:component --path=foo --name=foo --no-interactive --dry-run

 NX  Generating @nx/angular:component


NOTE: The "dryRun" flag means no changes were made.
CREATE apps/merlin/src/app/features/foo.component.html
CREATE apps/merlin/src/app/features/foo.component.spec.ts
CREATE apps/merlin/src/app/features/foo.component.ts
CREATE apps/merlin/src/app/features/foo.component.css


C:/_repos/merlin-0/frontend/node_modules/.bin/nx.cmd g @nx/angular:component --path=foo --name=foobat --no-interactive --dry-run

 NX  Generating @nx/angular:component

CREATE apps/merlin/src/app/features/foo.component.html
CREATE apps/merlin/src/app/features/foo.component.spec.ts
CREATE apps/merlin/src/app/features/foo.component.ts
CREATE apps/merlin/src/app/features/foo.component.css

NOTE: The "dryRun" flag means no changes were made.

C:/_repos/merlin-0/frontend/node_modules/.bin/nx.cmd g @nx/angular:component --path=foo/foo --name=foobat --no-interactive --dry-run

 NX  Generating @nx/angular:component


NOTE: The "dryRun" flag means no changes were made.
CREATE apps/merlin/src/app/features/foo/foo.component.html
CREATE apps/merlin/src/app/features/foo/foo.component.spec.ts
CREATE apps/merlin/src/app/features/foo/foo.component.ts
CREATE apps/merlin/src/app/features/foo/foo.component.css

**Comment by MaxKless** [comment]
> The text "The path at which to create the component file, relative to the workspace root. By default, it is set to the root of the project." is not misleading it is wrong.

Agreed, we have a task to fix this internally and it should go out next week :)

> Clearly the "name" is ignored. 

I don't think that's true, as you can see below I generated a component that has a different name than path. I think you're expecting the `name` property to change the filename that is controlled via the path? Is that right?
![Image](https://github.com/user-attachments/assets/ca247f63-931a-47d7-a275-a8146c139438)

> having a means to do this short of repeating myself (either in two text boxes or one) seems less than ideal.

I get where you're coming from. We used to infer these kinds of conventions but were running into other kinds of problems when folks wanted to do their own thing. So since Nx 17, we've been assuming as little as possible. So if you want to generate a component in a nested path, you have to provide the folder name & file name. You can read more about the philosophy of the decision here: https://nx.dev/deprecated/as-provided-vs-derived


So as concrete actions we'll take right now, we will fix the option description to acurately reflect what's going on instead of the wrong text right now.

**Comment by kwood-gmr** [comment]
This falls into "unexpected behavior" territory. I would not expect (and doubt more than a few others would) that the name field causes the internal name to not match the file name. I would be surprised if there isn't at least 2 people who would want that feature. I would be shocked if 2% would expect that. Again - I would suggest a change in the explanation to indicate that the name will **not** affect the file names.

While I understand the issue(s) with trying to figure out what a developer is thinking - I also strongly believe that having an option (preferably in the "common" area of the UI) to allow one to only type the name and get it in a nested directory of the same name would be good. Thus if I want a component "foo" in the "foo" directory relative to where I launched from I just have to type "foo" and not "foo/foo".

I have no idea how common it is, but I often create multiple components that relate to each other. Then again - this might push me to stop putting each in its own directory and they have several share. To be sure google didn't do your company any favors with a convention that doesn't match their recomendations.

**Comment by MaxKless** [comment]
Alright it makes sense what you're saying. I see how it can be confusing to have a `path` and `name` property that might appear conflicting or not do what they should. I'll bring it up internally and we can discuss a bit how we want to proceed here.
Thanks for taking the time to help out with your feedback :) Be on the lookout for changes in the generator description for sure and maybe other parts of the schema as well. 

I'll close this issue for now as it doesn't really have anything to do with nx console, it's more about nx itself and the generator definitions. 

Let me know if you have any other insights :)
