### ISSUE TITLE
Nx Console for Zed editor

### ISSUE THREAD

**Issue by BeliliFahem** [nrwl/nx-console#2335]
## Description

Have the Nx Console on the Zed Editor (www.zed.dev) 

## Motivation

I've tested Zed and noticed that it consumes significantly fewer resources compared to VS Code, which is impressive. I believe it would be highly beneficial to integrate NX Console into Zed alongside other tools.

**Comment by MaxKless** [comment]
Zed looks very cool!
It doesn't have quite the amount of users it would need for us to seriously consider supporting it with a first-party implementation of Nx Console, though. 
I will work on regularly publishing the language server again, which means you can at least use some of Nx Console's features without needing a full integration. If you're open to building a community extension for Zed, I'd love to help out and support you on the way :)

**Comment by Forceres** [comment]
any updates?
