### ISSUE TITLE
Nx processes not quitting, consuming 100% CPU

### ISSUE THREAD

**Issue by louisnw01** [nrwl/nx-console#2364]
## Current Behavior

When running `nx serve` in terminal, if that terminal window is quit (without CTRL+C'ing the nx server) there will be dangling node processes visible in Activity Monitor that consume 100% CPU; they will not stop until we manually force quit.

## Expected Behavior

All scenarios of terminating nx should kill all processes, rather than needing to be manually quit.

## Steps to Reproduce

(on macOS)

1. Run any process that uses `nx serve` in Terminal
2. cmd+W the terminal (or quit it) without CTRL+C'ing the process
3. Check Activity Monitor; a node process will be consuming 100% CPU

### Environment

Occurs in macOS terminal, Zed, etc.

**Comment by MaxKless** [comment]
Hey :) I just released a new version of Nx Console that has a fix for this 100% CPU issue. Can you try on `18.33.2` and check if this issue still persists?

**Comment by louisnw01** [comment]
> Hey :) I just released a new version of Nx Console that has a fix for this 100% CPU issue. Can you try on `18.33.2` and check if this issue still persists?

Ah; I fear I may have raised this issue in the wrong repo; this should be for nx not nx console.

Apologies!
