### ISSUE TITLE
[enhancement] Improve UX for file/module selection

### ISSUE THREAD

**Issue by adammedford** [nrwl/nx-console#304]
First off - extraneous pandering. Awesome work guys - another awesome project. I was actually writing something along these lines myself when I discovered this project. Naturally, I had a few ideas for my implementations that  you've not added to your own yet.

The problem:
- Selecting modules as projects grow is tedious and error prone
- The CLI provides tab path completion - the Angular Console is currently restricted to dumb text boxes
- Angular CLI schematic schemas are made for the CLI and shouldn't be modified for GUI problems

The ask:
1.  Assume 'string' fields with names like 'directory', 'module', 'parentModule', should use different inputs (autocomplete + file modal) -  **I don't like this but I'm including for completeness**

2. Add a button next to 'string' fields that opens a dialog window to allow users to select from a list of options with recently used options being pushed to the top. It might be enough just to provide provide a file dialog typed to *.module.ts

I'm sure someone can come up with a better implementation but I'd be happy to offer a PR nonetheless.

**Comment by adammedford** [comment]
So I was working on another project and it looks like there is an autocomplete already - it just isn't always used. For me it works on the vanilla Angular Schematics but I don't see any on the Nrwl schematics.

**Comment by mrmeku** [comment]
@adammedford Could you make a small list of places you would expect to see the autocomplete? If you do that then I'll go through each one and add them :D.

**Comment by adammedford** [comment]
@mrmeku I actually went ahead and made the changes.  I figured if I was going to make a list for you I might as well do it in the code on the off chance my formatting is acceptable. I'll submit a PR later tonight when I'm not blocked by a corporate proxy.

**Comment by adammedford** [comment]
I'm hesitant to close this as this is really an ongoing thing. 

I think if we're going to continue hardcoding details about schematic extensions it'd be a good idea to add a section under the CONTRIBUTING.md providing a checklist of adding a new schematic library and outlining the logic Angular Console uses to interact with them. 

Perhaps if Angular Console continues to grow the schematics extension authors could be coaxed into providing an angular-console.json with the collection.json to provide additional hinting. Would be a lot more durable and up to date than the current approach.

**Comment by Cammisuli** [comment]
We’ll probably come around and look at better autocomplete for additional fields. But I think what we have now is pretty good. We’re not going to force people to put specific json files to work with nx console. We’ll most likely use the nx nrwl/devkit to do more things. 

I’m going to close this because the initial ask was completed.
