### ISSUE TITLE
Angularconsole does not create default apps and libs folder when creating workspace

### ISSUE THREAD

**Issue by vairamsvsjdo** [nrwl/nx-console#442]
Angularconsole does not create default apps and libs folder when creating workspace

Expected Outccome:
https://nrwl.io/nx/guide-nx-workspace
"What you end up with is a Nx Workspace with the following files/folders created."
'''
apps/
libs/
tools/
angular.json
nx.json
tslint.json
tsconfig.json
'''
Instead apps and libs are not created

Reproducing steps:
Open angular console => create a new workspace => choose defaults except create route to true => apps and libs folder are not created.

**Comment by vsavkin** [comment]
@vairamsvsjdo could you provide a repo? Maybe a github repo with the project created by Angular Console.
