### ISSUE TITLE
Context Menu Generator for VS Code Extension

### ISSUE THREAD

**Issue by tayambamwanza** [nrwl/nx-console#650]
I went through the new tutorial on next.angular.io, it takes you through stackblitz and there's a very intuitive feature that I think the angular console vs code extension should adopt.

They allow you to generate components, services etc using the context menu (right click).

I think this would be a better use case for the extension, using the context menu to generate components, I find it's much faster.

Maybe add some buttons to the vs code ui that will allow you to serve and build applications.

Then when something more complex is needed one can open the angular-console desktop app.

![generate-component](https://user-images.githubusercontent.com/11971384/56096401-f1e0ab00-5ee7-11e9-8b1c-6dfaa536ca35.png)

**Comment by mrmeku** [comment]
@tayambamwanza Thanks so much for the screenshot! This is a feature that we've planned to add since making the VSCode plugin. With this UI to use as a prior art that becomes a lot easier :D

So yes, we are TOTALLY doing this very soon

**Comment by fkolar** [comment]
I cant wait to have this feature! 

- Right click on the directory and select which type you want to generate 
- You select a `component` and it will open up angular console window with already prefilled inputs for you. 
   - it will pick the closest module in current directory or on the way up. 
   - I will pre-fill project (it should always pre-fill project(
- Fill in name => generate

**Comment by tayambamwanza** [comment]
@fkolar I think opening up angular console would be unnecessary, I'm using an extension in the meantime called "Angular Schematics" and it just takes you step by step through the options. I'd prefer that because a a change in the ui (new window popping up) can be a bit jarring.

I'd prefer it looks like in the last image that I posted, then add an item at the bottom "angular console" to launch the full ui when desired.

![Screenshot from 2019-04-19 11-29-15](https://user-images.githubusercontent.com/11971384/56418422-2d3bfa80-6297-11e9-82ef-c6a8a4347de1.png)

![Screenshot from 2019-04-19 11-29-35](https://user-images.githubusercontent.com/11971384/56418432-3331db80-6297-11e9-80ca-408cee67065d.png)

![Screenshot from 2019-04-19 11-29-42](https://user-images.githubusercontent.com/11971384/56418450-388f2600-6297-11e9-9553-db949c71174f.png)

![Screenshot from 2019-04-19 11-29-57](https://user-images.githubusercontent.com/11971384/56418461-3d53da00-6297-11e9-94d5-ee37940c26d8.png)

![Screenshot from 2019-04-19 11-30-09](https://user-images.githubusercontent.com/11971384/56418466-42b12480-6297-11e9-8715-3fd6d38618ab.png)

**Comment by tayambamwanza** [comment]
One of the potential ui issues: #https://github.com/Microsoft/vscode/issues/53868

**Comment by fkolar** [comment]
What if part of the process you want to real quick  check something? like “ohh I forgot what should i name the selector?”
so i can open another file... and come come back and finish.

I would prefer less modality. Does this plugin allows to go back?

**Comment by tayambamwanza** [comment]
@fkolar It looks like there isn't but the final step shows the results, which allows you to make any edits, maybe you could add another option

![Screenshot from 2019-04-19 11-30-09](https://user-images.githubusercontent.com/11971384/56437252-f4c00f00-62de-11e9-8144-b9b3018a0585.png)

**Comment by mrmeku** [comment]
@tayambamwanza I really like your vision for how these menus should work. Can we work on the implementation of this together? I'd like to achieve your vision of this should be implemented. If you're open to working with me, let me know. I'll add you to our slack channel

**Comment by tayambamwanza** [comment]
@mrmeku Sure I'd love to help, although I normally work by myself so you may have to be patient with me if I need to contribute code because I'm still getting use to the process of contributing to other projects.

**Comment by tayambamwanza** [comment]
@mrmeku That's fantastic news! As I mentioned before I'd be glad to assist, I might need some guidance though, I'm a solo freelance dev, so not used to contributing to other projects.

I could perhaps just setup the basic project on my own then send you an email when I get stuck? If you're handling it though no problem.

**Comment by mbriggs** [comment]
Unfortunately, this feature can't be implemented the way described due to the limitation of no nested menus in vs.code.

However, we have a feature mostly implemented which will allow you to invoke "Generate" by right clicking the explorer, and will figure out what project you are in. It should ship next major release

**Comment by johnhamm** [comment]
Was this ever released?  I installed 10.0.0 but when I right-click in the Explorer tree, there is no option to create a component.

**Comment by tayambamwanza** [comment]
@johnhamm No no at this stage, which is why the issue is still open :)

**Comment by Cammisuli** [comment]
The feature described here (where we have a generate UI menu item) is in the latest release. I'm going to close this issue now
