### ISSUE TITLE
Karma config reporters are overridden by default

### ISSUE THREAD

**Issue by allan-t** [nrwl/nx-console#681]
When running tests with a custom Karma config the reporters are overidden by default with `--reporters progress`. This means that any custom reporters need to be added every time the tests are run. 

Added to this it will give a misleading running command: `ng test <project-name>` not stating that it is running with a reporters flag under the hood. This makes it very hard to determine why the configured reporters aren't being run.

**Comment by mrmeku** [comment]
Sorry for the delay in fixing this. We will have a release this week which fixes the problem
