### ISSUE TITLE
Feature: find all ngx library and install them (like or include ngxtools)

### ISSUE THREAD

**Issue by manudss** [nrwl/nx-console#688]
Their is a project ngx-tools that can search to angular library : https://ngx.tools 

This could be really usefull to have the same things in Angular Console, and have directly a button to install them. 

This could be done, by including ngx tools, and make a partnership with them, to insert ngx-tools to angular console. 
https://github.com/ngxtools/ngx.tools

or create a similar tools. 

They use algolia search to npm repository.

**Comment by mrmeku** [comment]
That's a very good idea @manudss I'll see if they expose an API we could call

**Comment by mrmeku** [comment]
Here is how they are searching for angular related packages:
https://github.com/ngxtools/ngx.tools/blob/master/src/app/core/algolia/algolia.service.ts

Right now we use a static JSON of packages that we ship along with console. But I believe that their strategy is better. I'll see if their team is interested in making a console extension to get their project in console itself

**Comment by Cammisuli** [comment]
We'll most likely use the nx cli to get the available plugins with the `nx list` command. https://nx.dev/latest/node/core-concepts/plugins#nx-list

This includes officially supported plugins and plugins that are made by the community that would work with both `workspace.json` and `angular.json`
