### ISSUE TITLE
Issue with changing default style from css to scss

### ISSUE THREAD

**Issue by alexljamin** [nrwl/nx-console#778]
The schema in the Angular project I am working on is set to the following:
```
"schematics": {
        "@nrwl/angular:component": {
          "styleext": "scss"
        }
      }
```
When I open Angular Console in VS Code and try to generate, for example, a component, in the optional fields for style I still see css instead of scss. When I manually change the value to scss the Angular Console Terminal Output show the following warning - `Option "styleext" is deprecated: Use "style" instead.`

If I change the schema to 
```
"schematics": {
        "@nrwl/angular:component": {
          "style": "scss"
        }
      }
```
The warning still persists and the default config for styling remains css.

Is there a solution to change the default style config to scss and dismiss the warning message?

**Comment by mrmeku** [comment]
I think there a lot more the UI can do here to make your life easier. First and foremost, we should hide deprecated fields automatically (unless you've already specified an override in angular.json)

The fact that the warning still showed up means that the angular CLI still received it. I'm going to need to do a bit more investigation as to why that might be

**Comment by Maximaximum** [comment]
Seems like nx console should store 
```
"@schematics/angular:component": {
  "style": "scss"
}
```

instead of
```
"@nrwl/angular:component": {
  "style": "scss" 
}
```
into `angular.json`

**Comment by sandikbarr** [comment]
@Maximaximum The workspace default is set to 
```
"@nrwl/angular:component": {
  "style": "scss" 
}
```
because `@nrwl/angular` extends from `@schematics/angular`. With the defaultCollection in the workspace also set to `@nrwl/angular` for example if you run `ng g component` you'll be using `@nrwl/angular`, which is calling the `@schematics/angular:component` under the hood, yes.

However, this isn't exposed in Nx Console, and you also cannot select `@nrwl/angular:component` as a generator because it's not one.  So I can see the issue of how this is not setting `scss` as the default value when you use the Nx Console Generate form for components.

**Comment by joarkm** [comment]
@sandikbarr thanks for the explanation! From what you described I added this under the "schematics" section of workspace.json:
`    "@schematics/angular:component": {
      "style": "scss"
}`
When opening the Nx Console it now default selects scss as style extension in the drop down. I guess this sets scss as default for the entire workspace but this is good enough for me at least.

**Comment by sandikbarr** [comment]
@joarkm Great, yes that will do it for the whole workspace.

But hmm, yeah- We should look into supporting the schematics property at the project level in Nx Console, but it's not supported at this time.

**Comment by MaxKless** [comment]
Hey! We're looking to drop Angular CLI support in the not-too-far future, so I'm closing this issue.

**Comment by joarkm1** [comment]
> Hey! We're looking to drop Angular CLI support in the not-too-far future, so I'm closing this issue.

Can you elaborate? Will the NX Console extension not work with Angular projects in the future?

**Comment by MaxKless** [comment]
Yes that's right.
