### ISSUE TITLE
Custom schematics using collection.json is failing

### ISSUE THREAD

**Issue by Maus3rVonDutch** [nrwl/nx-console#790]
Hi, I have a couple of custom schematics in my workspace. They work fine when using separate folders per schematic and each having it's own _schema.json_ (let's call this **scenario A**). 

However now I'm trying to add more schematics, which I'd like to group per subject (say schematics belong to a group _ngrx_ and a couple of schematics belonging to a group _spectator_). To be able to do that I have added a _collection.json_ file (referencing the custom schematics of course) to the schematics folder (let's call this **scenario B**). Now when I try to run the schematics using scenario B I get an exception (excerpt from angular-errors.log): 

```
[error] Error: Schematic "Workspace" not found in collection "@nrwl/angular".
    at SchematicEngine.createSchematic (A:\Repositories\ncontrol-mijnncontrol\source\node_modules\@angular-devkit\schematics\src\engine\engine.js:232:23)
    at CollectionImpl.createSchematic (A:\Repositories\ncontrol-mijnncontrol\source\node_modules\@angular-devkit\schematics\src\engine\engine.js:69:29)
    at GenerateCommand.getSchematic (A:\Repositories\ncontrol-mijnncontrol\source\node_modules\@angular\cli\models\schematic-command.js:136:27)
    at GenerateCommand.initialize (A:\Repositories\ncontrol-mijnncontrol\source\node_modules\@angular\cli\models\schematic-command.js:46:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

When using scenario A this command is exceuted:
`yarn run workspace-schematic -- mnc-spectator services/test --project=shared-authentication-data-access-authentication --dry-run --no-interactive`

When using scenario B this command is executed:
`ng generate Workspace Schematics:mnc-spectator services/test --project=shared-authentication-data-access-authentication --dry-run --no-interactive`

NB When running scenario B, the schematics are never compiled to the _dist/out-tsc folder_
	
I don't know how to debug this, but I did inspect the source code (file: **read-schematic-collections.ts**) from angular-console. There I'm seeing an if/else condition handling the custom schematics, either using scenario A or B.

For scenario A I'm seeing this implemenation (starting at line 100)

```
const schematics = listFiles(collectionDir)
      .filter(f => path.basename(f) === 'schema.json')
      .map(f => {
        const schemaJson = readJsonFile(f, '');
        return {
          name: schemaJson.json.id,
          collection: collectionName,
          schema: normalizeSchema(schemaJson.json),
          description: '',
          npmClient,
          npmScript: workspaceSchematicsNpmScript
        };
      });
    return { name: collectionName, schematics };
```

For scenario B this is the implementation (starting at line 163)

```
  schematicCollection.schematics.push({
          name: k,
          collection: collectionName,
          schema: normalizeSchema(schematicSchema.json, projectDefaults),
          description: v.description || '',
          npmClient: null,
          npmScript: null
        });
```
		
You can see that scenario B is missing the **nmpScript** implementation, which might be the problem.

I've provided my custom schematics for reference. Again when deleting the _collection.json_ in the provided zip and renaming _ngrx-schema.json_ and _service-schema.json_ in the different folders to just _schema.json_, scenario A is executed and everything works fine. Please let me know if you need more info to replicate this issue. 

[schematics.zip](https://github.com/nrwl/angular-console/files/3471832/schematics.zip)

**Comment by yglin** [comment]
Also met this issue today, +1

**Comment by beamkatana** [comment]
I've got the same problem in my Nx Monorepo Project when adding a collection.json in tools/schematics folder. +1

**Comment by mbriggs** [comment]
@Maus3rVonDutch thanks for the awesome report! we will fix this in the next major release.

**Comment by Maus3rVonDutch** [comment]
@mbriggs great to hear! Thnx a lot for fixing this!

**Comment by jsadowski** [comment]
Any news about supporting collection.json?

**Comment by Cammisuli** [comment]
I'm going to close this here. This is something that the core of Nx doesn't support. So if this is something that's needed, please open a feature request on the https://github.com/nrwl/nx repo
