### ISSUE TITLE
Non-Angular Workspace Not detected by Angular Console

### ISSUE THREAD

**Issue by un33k** [nrwl/nx-console#820]
[ x ] is this a bug?

I think so, or this can be a mismatch of functionalities. 

[ x ] did you search issues before creating new one?

Yes, not found similar issues for what I am reporting

[ x ] can you explain the issue in detail?

Creating a web component non-angular workspace using nx-workspace, but the newly created workspace is not detected by AngularConsole which is looking for angular.json file.

I understand the application is called Angular Console.  But if the command line allows creating a non-angular workspace, it would be great to have the Console application to detect it.

Based on the nature of AngularConsole at the current time, it remains Angular specific.  But it would be great to have it also load non-angular workspaces.  Perhaps a new name may be good to have.  NrwlConsole, maybe. 

[ x ] have steps to reproduce:

npm init nx-workspace common-utils

? What to create in the new workspace web components    [a workspace with a single app built using web components]
? Application name                    Foobar
Creating a sandbox with Nx...
new common-utils --preset=web-components --appName=Foobar --collection=@nrwl/workspace
? Which stylesheet format would you like to use? SASS(.scss)  [ http://sass-lang.com   ]

- Open AngularConsole and point it to the new workspace and it won't be able to recognize it due to the missing angular.json

[ x ] can you include the versions?

node = v12.3.1
├─┬ @nrwl/cli@8.4.3
│ ├─┬ @nrwl/tao@8.4.3
│ ├── UNMET PEER DEPENDENCY @nrwl/workspace@8.4.3
├─┬ @nrwl/schematics@8.4.3
│ ├─┬ @nrwl/angular@8.4.3
│ │ ├─┬ @nrwl/cypress@8.4.3
│ │ ├─┬ @nrwl/jest@8.4.3
│ ├─┬ @nrwl/workspace@8.4.3
│ │ ├─┬ @nrwl/cli@8.4.3
│ │ │ ├─┬ @nrwl/tao@8.4.3
npm│ ├─┬ @nrwl/workspace@8.4.3
│ │ ├─┬ @nrwl/cli@8.4.3
│ │ │ ├─┬ @nrwl/tao@8.4.3

[ x ] can you reproduce this in Electron and VSCode?

Yes, both have difficulties detecting a workspace without angular.json

**Comment by mrmeku** [comment]
@un33k We are considering whether to release a separate extension so that non angular users do not need to have the angular branding to get the functionality the extension provides. I'll update this bug as we solidify our plans to do so so stay tuned

**Comment by Cammisuli** [comment]
This isn't an issue anymore. The extension was rebranded to Nx Console and has support for `workspace.json` and `angular.json`
