### ISSUE TITLE
Missing Option for ESLint when Creating Library

### ISSUE THREAD

**Issue by tthrash** [nrwl/nx-console#920]
When creating a library the option to use ESLint is missing. This was removed in a recent update, and considering that TSLint is now deprecated ([Palantir announcing TSLint deprecation](https://medium.com/palantir/tslint-in-2019-1a144c2317a9)) this is important to have. I understand that Angular doesn't fully support ESLint ([Angular migration to ESLint issue](https://github.com/angular/angular-cli/issues/13732)), but this should still be a feature. 

Also, when applying lint fixes after say generating a component isn't currently working, even with `.eslintrc` file defined. The error I get is `Cannot find module 'tslint'` Though, I assume it's a related issue.

Sidenote: great work on the recent overhaul!

Thanks!

**Comment by Cammisuli** [comment]
The linter option should be available for generators that have the `linter` property defined now.
