### ISSUE TITLE
Build Analyzer?

### ISSUE THREAD

**Issue by tayambamwanza** [nrwl/nx-console#922]
Has this feature been removed from the extension? I'm really struggling to find it and i made frequent use of it.

**Comment by jakehockey10** [comment]
Have you found it?  I can't find it either...

**Comment by ironstine** [comment]
+1

**Comment by Cammisuli** [comment]
I don't remember this feature being here before, but it's definitely something I'd like to have added back.

**Comment by Cammisuli** [comment]
I haven’t been able to find anything related to this. 

If you’re working with a webpack builder, you can put the `statsJson` option in your target/architect options and use an external tool to parse the results. 

Here’s a good guide on how to do it:
https://www.digitalocean.com/community/tutorials/angular-angular-webpack-bundle-analyzer

That being said; we’re probably not going to include this within Nx Console, and I’m going to close this.
