### ISSUE TITLE
ng generate fails with error UnrecognizedToken

### ISSUE THREAD

**Issue by riverstream** [nrwl/nx-console#924]
**Description:**
ng generate fails with error "UnrecognizedToken".

**Click the _Run_ button to reproduce as follows:**

ng generate @schematics/angular:component --name=square --project=MyAppAngular

**Problem;**
The @ is making PowerShell treat @schematics/angular:component as a variable.

**Resolution:**
Add double quotes when executing command:

ng generate "@schematics/angular:component" --name=square --project=MyAppAngular

**Comment by Cammisuli** [comment]
This is unfortunate ☹️ can you try setting your terminal to run in bash instead as a workaround?

**Comment by Cammisuli** [comment]
I just tried to reproduce this on a brand new copy of Windows 10 and the latest version of Nx console, and I cannot reproduce this. 

You can reopen this if you're having issues still.
