### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by vikicoder007** [nrwl/nx-console#925]
- Issue Type: `Performance`
- Extension Name: `angular-console`
- Extension Version: `10.0.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.41.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\vikic\nrwl.angular-console-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by RobertYost** [comment]
I am also experiencing this, and unfortunately had to disable the extension - it added nearly 3 seconds to startup time alone and made all of vscode incredibly laggy.

**Comment by Crocetti** [comment]
I am also experiencing this.
[nrwl.angular-console-unresponsive.cpuprofile.txt](https://github.com/nrwl/nx-console/files/4492548/nrwl.angular-console-unresponsive.cpuprofile.txt)

**Comment by Abdallah-khalil** [comment]
[nrwl.angular-console-unresponsive.cpuprofile.txt](https://github.com/nrwl/nx-console/files/4808552/nrwl.angular-console-unresponsive.cpuprofile.txt)
Having the same when trying to open the generate

**Comment by Cammisuli** [comment]
Thank you for the report! I've definitely noticed a lot of performance issues and I want to fix those up. I'll keep these in mind when I'm going through a performance rundown.
