### ISSUE TITLE
generate ui dont work

### ISSUE THREAD

**Issue by JavikusRod** [nrwl/nx-console#937]
I click in generate in the nx console and do nothing
![generate ui dont work](https://user-images.githubusercontent.com/16100843/75901954-4d23d080-5e0d-11ea-832e-8bfaf1bb6531.png)

**Comment by JavikusRod** [comment]
uninstalled and installed and nothing

**Comment by Sikora00** [comment]
I had the same issue caused by one of my dependencies with incorrect collection.json

**Comment by ctaleck** [comment]
This may be related to issue #923 and others.
