### ISSUE TITLE
New Icons Are not Responsive to Dark/Light themes

### ISSUE THREAD

**Issue by mrmeku** [nrwl/nx-console#941]
<img width="386" alt="Screen Shot 2020-03-19 at 11 15 46 AM" src="https://user-images.githubusercontent.com/8085051/77095120-13d58e00-69d3-11ea-82d8-a120a700871f.png">

The old icons were relatively self contained (no transparency) so were not as reliant on theme color to stand out. With the new icons that's not the case. Consider adding white versions of these icons for dark themed editors

**Comment by Cammisuli** [comment]
We'll work on this with #1023
