### ISSUE TITLE
Running multiple applications at the same time

### ISSUE THREAD

**Issue by rapzo** [nrwl/nx-console#942]
I don't know if this is possible but from pressing the `serve` button for multiple applications, the second will say there's a process running and will ask either to cancel the request or to kill the previous one.
Running via cmd with the flag `--project` works as expected.
If it is an issue, since there were previous issues created with this same context, may i look into it?

**Comment by mackelito** [comment]
I can verify that this is a problem for us as well

**Comment by kdawg1406** [comment]
@rapzo  please see [my comment here](https://github.com/nrwl/nx-console/issues/957#issuecomment-660561416)

Hope this provides some help, best regards, Karl
