### ISSUE TITLE
Terminal shows dry run only one time

### ISSUE THREAD

**Issue by GreatHawkeye** [nrwl/nx-console#944]
Looks like since the [last VSCode update](https://code.visualstudio.com/updates/v1_44), the terminal has some issues displaying the dry run infos.

1) I open NX Console, choose "generate", then choose "library" (or component or anything)
2) I type "foo" in "name", terminal shows the dry run correctly
3) I continue typing, for example "foo-bar" but terminal is just stuck there and nothing display in the dry run preview

**Comment by warrendugan** [comment]
Experiencing the same starting very recently... May be as a result of upgrading to 9.2.1.

**Comment by crissxross** [comment]
I'm also experiencing this issue in VS Code version: 1.44.0 and Angular Cli v.9.1.0

**Comment by RaphyLi** [comment]
Same for me with VS Code version: 1.44.0 and Angular Cli v8.3.26

**Comment by instantgis** [comment]
Just updated VS Code and got this new annoying/show-stopping behavior...

VS Code...

Version: 1.44.1 (system setup)
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:48:12.622Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Angular

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.0
@angular-devkit/build-angular      0.901.0
@angular-devkit/build-ng-packagr   0.901.0
@angular-devkit/build-optimizer    0.901.0
@angular-devkit/build-webpack      0.901.0
@angular-devkit/core               9.1.0
@angular-devkit/schematics         9.1.0
@angular/cdk                       9.2.0
@angular/flex-layout               9.0.0-beta.29
@angular/material                  9.2.0
@angular/service-worker            9.1.1
@angular/youtube-player            9.2.0
@ngtools/webpack                   9.1.0
@schematics/angular                9.1.0
@schematics/update                 0.901.0
ng-packagr                         9.1.0
rxjs                               6.5.4
typescript                         3.8.3
webpack                            4.42.0

**Comment by instantgis** [comment]
It was working with Angular 9.1.0 before so looks like it must be a VS Code newly introduced issue

**Comment by instantgis** [comment]
I turned off VS code updates (none) otherwise it will auto-update (default) to latest - breaking nx console.
I Installed https://code.visualstudio.com/updates/v1_43 **over** v1_44, no need to uninstall.
nx console dry run is working again.

**Comment by ericsnap** [comment]
Experiencing same issue with recent VSCode, Nx Console `11.1.3` and Angular 8 or 9 projects.

```
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

>$ng version

Angular CLI: 8.3.26
Node: 10.20.1
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.26
@angular-devkit/build-angular     0.803.26
@angular-devkit/build-optimizer   0.803.26
@angular-devkit/build-webpack     0.803.26
@angular-devkit/core              8.3.26
@angular-devkit/schematics        8.3.26
@angular/cli                      8.3.26
@ngtools/webpack                  8.3.26
@schematics/angular               8.3.26
@schematics/update                0.803.26
rxjs                              6.5.5
typescript                        3.5.3
webpack                           4.39.2

```

**Comment by z6tanker** [comment]
Same issue. Has this been fixed?

**Comment by RaphyLi** [comment]
Good news with the last version of vscode (1.45.0) it work's.
