### ISSUE TITLE
Standalone download

### ISSUE THREAD

**Issue by americanslon** [nrwl/nx-console#947]
I can't seem to find standalone version anymore. I have been using the software for a long time but haven't had the need to DL it in a while. Did something change? I really have no use for VSCode as of this point and it feels needlessly complex to have to DL VSCode just to get the access to this magnificent tool.

**Comment by jfrazx** [comment]
They [killed](https://blog.nrwl.io/brand-new-ui-custom-vscode-task-support-more-in-angular-console-9-0-5e4d3a109fb9#f5c9) it

**Comment by luizgamabh** [comment]
Do you think about integrating with JetBrains?

**Comment by isaacplmann** [comment]
Nrwl isn't working on a plugin for JetBrains, but there are community efforts.
