### ISSUE TITLE
Serve multiple applications (e.g. back-end and front-end) at the same time

### ISSUE THREAD

**Issue by adams-family** [nrwl/nx-console#957]
Is it possible to to serve two applications at the same time for development purposes:
* backend (api)
* frontend (eshop)

I am able to run the first one with Serve:

<img width="730" alt="image" src="https://user-images.githubusercontent.com/19559733/85222171-6307d200-b3b9-11ea-8753-546ae92619fe.png">

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/19559733/85222063-f7256980-b3b8-11ea-8b5f-bc9a6b0b9034.png">

<img width="618" alt="image" src="https://user-images.githubusercontent.com/19559733/85222070-04daef00-b3b9-11ea-9220-55eadf59cb07.png">

However when attempting to run the second project:

<img width="751" alt="image" src="https://user-images.githubusercontent.com/19559733/85222177-6c913a00-b3b9-11ea-9a20-aff78fd05ce0.png">

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/19559733/85222082-1cb27300-b3b9-11ea-8410-d3f06757ca36.png">

I get the following problem:

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/19559733/85222088-33f16080-b3b9-11ea-8bd3-96fd25cb1055.png">

Is there a solution for this? Is there any better way how to develop back-end & front-end simultaneously? Thanks!

**Comment by kdawg1406** [comment]
@adams-family check out the attached file:
[workspace.zip](https://github.com/nrwl/nx-console/files/4943011/workspace.zip)

Search for this section. You noticed I group it within the main project, the store application.  

Notice I'm running two commands, `nx serve api` which starts the API project and `nx serve store --open` that launches the store application.

Hope this helps you out.  Best regards, Karl

`
        "serve-with-services": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "commands": [
              {
                "command": "nx serve api"
              },
              {
                "command": "nx serve store --open"
              }
            ],
            "parallel": true
          }
        }
`

**Comment by adams-family** [comment]
Ki @kdawg1406 - thanks!

For other people with an Angular project, I put Karl's code into `angular.json` instead of `workspace.json` and replaced `nx` with `ng`:

```
        "serve-with-services": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "commands": [
              {
                "command": "ng serve api"
              },
              {
                "command": "ng serve store --open"
              }
            ],
            "parallel": true
          }
        }
```

The I use this command to run it:

`ng serve store:serve-with-services`

It's working - thanks!

I have one question however: is it possible to keep the colorized output of the two ng serve commands?

**Comment by kdawg1406** [comment]
@adams-family I don't know about this question, "is it possible to keep the colorized output of the two ng serve commands?"

I did find this blog post explaining how to log the output to disk when using the command line.  
[https://www.windowscentral.com/how-save-command-output-file-using-command-prompt-or-powershell](https://www.windowscentral.com/how-save-command-output-file-using-command-prompt-or-powershell)

Since the Angular CLI is executing the command, reaching out to them may be your best route to success.

**Comment by adams-family** [comment]
For completeness sake I'm adding some of my findings.

It's interesting, I found an attribute called `color` in the documentation of nrwl/run-commands which is by default set to `false`:

```
color
Default: false
Type: boolean
Use colors when showing output of command
```

https://nx.dev/angular/plugins/workspace/builders/run-commands#color

However setting it to `true` didn't help. It's not a huge things but colors help to figure out that there is an error more quickly.

**Comment by isaacplmann** [comment]
Closing this, since you've found a solution

**Comment by cgatian** [comment]
What's the best way to do this in 2023? This is the top result on google.
