### ISSUE TITLE
VSCode nx console schematics not updating options/flags

### ISSUE THREAD

**Issue by webberwang** [nrwl/nx-console#963]
The generate schematic UI is correctly picking up the `schema.json`, but when I edit the json schema, the UI doesn't update the options until I restart VSCode. 

I've closed the generate tab, and re-select the generate option, but doesn't work as well.

VSCode: 1.47.0
Nx Console 12.0.0

**Comment by isaacplmann** [comment]
Yes, Nx console parses all your available schematics at load time.  You can use the `Reload Window` command from the VS Code command palette to easily restart your window.
