### ISSUE TITLE
Include .vsix to github releases

### ISSUE THREAD

**Issue by adrian-ub** [nrwl/nx-console#968]
Hello folks!

I am using code-server which can't use Marketplace due to the legal reasons. So they have their own "marketplace" where they are trying to publish extensions.

The simplest way for them to automatically update their own marketplace is by observing github releases of related extensions.

It would be really helpful if you could include .vsix files into your github releases.

Currently it seems that they are building extension from source which is less reliable option. So sometimes extension version falls behind.

**Comment by isaacplmann** [comment]
I added the latest release to the github releases section.
