### ISSUE TITLE
Fields are unreadable in latest insiders builds

### ISSUE THREAD

**Issue by smlombardi** [nrwl/nx-console#969]
I've been using the console for a while without issue.  I noticed earlier this week that suddenly all the fields are white with white text, making typing into them unusable.

![CleanShot 2020-08-21 at 11 08 35](https://user-images.githubusercontent.com/835148/90905995-f9974600-e39e-11ea-8353-231fb8067b34.jpg)

Extension version 13.0.0.  Insiders Version: 1.49.0-insider.  I have tried the default VSCode themes, same thing.

**Comment by isaacplmann** [comment]
Fixed by #972

**Comment by smlombardi** [comment]
This was fixed but has returned. NX console 13.0.0, Version: 1.50.0-insider

**Comment by isaacplmann** [comment]
Should be fixed in Nx Console 14.0.0
