### ISSUE TITLE
Windows 10 "ng serve" error 

### ISSUE THREAD

**Issue by quentinmayo** [nrwl/nx-console#973]
When I try to serve my ng project, I get the following error below, I couldn't figure how to override the & signed. I tried changing the console but I think the script defaults to powershell for windows. 

> Executing task: ng serve projectname <

At line:1 char:17
+ & {e:\Projects` &` Automation\projectname\node_modules\.bin\ng.cmd ser ...
+                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed
 
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Sta -NoLogo -NonInteractive -C "& {e:\Projects` &` Automation\projectname\node_modules\.bin\ng.cmd serve projectname}" ng serve projectname" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

**Comment by isaacplmann** [comment]
Try setting this setting: https://code.visualstudio.com/docs/editor/integrated-terminal#_changing-shell-for-tasks-and-debug

**Comment by Cammisuli** [comment]
I tried this out on a brand new copy of Windows 10, with powershell and everything appears to be working. You can reopen this if you're still having issues.
