### ISSUE TITLE
Nx console not using project flag

### ISSUE THREAD

**Issue by nickroberts** [nrwl/nx-console#978]
I'm trying to create an Angular component with the console, and no matter what project I select, it does not use the project when running the schematic.

In the dry-run step, you can see that the `--project` flag is not set.

Nx console version: `v14.0.0`

Some of my dependencies:
```json
{
  "dependencies": {
    "@angular/core": "10.1.4"
  },
  "devDependencies": {
    "@angular/cli": "10.1.4",
    "@nrwl/workspace": "10.2.1"
  }
}
```

**Comment by insta-code1** [comment]
![Screenshot 2020-10-04 at 11 18 36](https://user-images.githubusercontent.com/16502828/95012805-5a1ed180-0633-11eb-953b-d10c435c5846.png)

I got it working again by rolling back to v13.0.0

**Comment by kasius** [comment]
Same problem, solution was to go back to version 13 and restart VSCODE.

**Comment by mrscrott** [comment]
Yeah, I also have this probelm, I have to roll back to previous version, it took me a while to notice this and thank for the fix version in advance.

**Comment by isaacplmann** [comment]
obviously, this affecting a lot of people, but I can't reproduce it myself.  Are all of you on windows?

I'm running on a mac with the version numbers specified by @nickroberts .

**Comment by kasius** [comment]
> obviamente, esto afecta a mucha gente, pero no puedo reproducirlo yo mismo. ¿Están todos en Windows?
> 
> Estoy ejecutando una Mac con los números de versión especificados por @nickroberts .

MAC, version 14.0.0 throws that problem, when returning to version 13.0.0 everything works fine

**Comment by isaacplmann** [comment]
I figured it out.  If there are less than 10 projects in the workspace, a select field is used and the schematic works correctly.  With more than 10 projects, an autocomplete field is used and is breaking things.  I'll work on a fix.
