### ISSUE TITLE
Cannot select --all option with run-many command

### ISSUE THREAD

**Issue by vivekmore** [nrwl/nx-console#979]
Due to the option type `Boolean` of `--all`, the value `true` is added which causes the command to fail.
I'd be happy to submit a fix. Looking for some guidance/direction.

![nx-error](https://user-images.githubusercontent.com/2099329/95036371-badef600-0695-11eb-9f87-82b05bf38efc.gif)

**Comment by isaacplmann** [comment]
What version of nx are you using?

`nx run-many --target=test --all=true`

works in nx version 10.1

**Comment by isaacplmann** [comment]
Please reopen if it isn't working with the latest nx.

**Comment by vivekmore** [comment]
```
❯ nx --version
10.2.1-beta.1
```

**Comment by vivekmore** [comment]
@isaacplmann - is there anything else you'd like me to provide?

**Comment by isaacplmann** [comment]
That should be enough, I just need to find time to reproduce and try to find a fix.

**Comment by vivekmore** [comment]
@isaacplmann I'd be happy to submit a fix. Looking for some guidance/direction.

Meanwhile - I'd appreciate if you could re-open this issue.

**Comment by isaacplmann** [comment]
It looks like this worked in nx 10.1.x and was broken in 10.2.x.  Still broken in 10.3.0.  I'm trying to track down why.

**Comment by Cammisuli** [comment]
Looks like this is fixed with the latest version of Nx. This also looked like it was an issue with Nx CLI, and it was fixed on that side.
