### ISSUE TITLE
Empty Projects page after importing a newly created nx workspace project

### ISSUE THREAD

**Issue by Yonet** [nrwl/nx-console#98]
Repro: 
- Create an nx workspace.
- Navigate to import and select newly created workspace.
- Automatic navigation to Project page renders empty page.

Suggestion:
- Have a message on Project tab for empty project and link to generate code tab.
- Or navigate to generate code tab if the project is empty.
<img width="814" alt="screen shot 2018-08-08 at 6 36 36 pm" src="https://user-images.githubusercontent.com/3523671/43873249-b789a0a4-9b3a-11e8-9591-e16236505c34.png">

**Comment by mrmeku** [comment]
For whomever tackles this bug, here’s a template to basically copy from for how we represent empty states right now: https://github.com/nrwl/angular-console/blob/master/libs/feature-workspaces/src/lib/workspaces/workspaces.component.html#L46

**Comment by manekinekko** [comment]
Looking at this one.

**Comment by manekinekko** [comment]
Got the initial dialog in place.Ready to send my PR. Here are few questions though: 

1. Should we have a different icon for empty projects?
2. The `create a new application` button redirects to the `../generate` tab and we let the user choose the schematic they want to use to create a new app. That's the easiest solution for now. 
3. Currenty we have 2 schematic collections `@nrwl/schematics` and `@schematics/angular`, both provide the `application` command. Is there a way to extract this `application` commands from a schematic without having to hardcode anything? Assuming that the user could include a 3rd party schematic (company internal?!) which also provides a `command`.

![image](https://user-images.githubusercontent.com/1699357/47304920-45a0c480-d628-11e8-9542-1375f05f967a.png)

**Comment by jaysoo** [comment]
@manekinekko 

1. I think this is fine for now, but in the future it would be good to make this empty state more distinguishable from the empty workspaces one.

2 & 3. It's possible to query for collections and schematics and filter by `name === 'application`. I'm not sure how robust this approach is, but it is better than what we have now.
