### ISSUE TITLE
Feature: use x-prompt details in nx-console-field

### ISSUE THREAD

**Issue by srlee309** [nrwl/nx-console#981]
Angular cli has [schematic prompts](https://github.com/angular/angular-cli/blob/master/docs/specifications/schematic-prompts.md) and Nx console currently doesn't do anything with this information. This means that the Nx console provides less information than the angular cli and makes you need to use a text-field in the scenario when multiple items need to be selected. The experience using the cli is much better for this scenario, for example:
![image](https://user-images.githubusercontent.com/13536934/97096875-2e38be00-16be-11eb-8714-d278caa333b6.png)

I think if the Nx console used the x-prompt details it would provide a better experience that is more aligned with the angular cli. What do you think about:

- When an x-prompt message is used, adding a tooltip to the field name that displays the message after hover and a delay period of 1 second.

- When the x-prompt type is list and multiselect is true, using a new multi-select mat-select component that allows the user to select multiple options. The below is an example schema that would use the multi-select component. It would also by default have all the options selected due to the provided default value.

```
"libraries": {
    "description": "The library types that will be generated",
    "type": "array",
    "items": {
        "type": "string"
    },
    "uniqueItems": true,
    "alias": "l",
    "minItems": 1,
    "default": ["data-access", "feature", "shell", "ui", "util"],
    "x-prompt": {
        "message": "Which library types do you want to generate?",
        "type": "list",
        "multi-select": true,
        "items": [
            {
            "value": "data-access",
            "label": "data-access - for state management and services"
            },
            {
            "value": "feature",
            "label": "feature - for smart components (containers)"
            },
            {
            "value": "shell",
            "label": "shell - for wrapping different libraries and exposing them as a single library. Also, for routing."
            },
            {
            "value": "ui",
            "label": "ui - for dumb components"
            },
            {
            "value": "util",
            "label": "util - for model files, constants, validators, pipes and any other miscellaneous items, e.g. shared functions."
            }
        ]
    }
}
```
- When it provides items in the x-prompt that have labels, display a tooltip on the relevant auto-complete or select options after hover and a delay period of 1 second.

---

Adding the x-prompt details to the field should be fairly easy. It can be done by updating the below function to also get the x-prompt details.
https://github.com/nrwl/nx-console/blob/ec66c8f052464f0f2c5cf34038b4b3dafcabc1a5/libs/server/src/lib/utils/utils.ts#L152

For each option, add the x-prompt details if they are there.
```
if (s.properties[option.name]['x-prompt']) {
    option['x-prompt'] = s.properties[option.name]['x-prompt'];
}
```
Update the type from Option to something like OptionWithXPrompt 
```
import { Option } from '@angular/cli/models/interface';

export interface OptionWithXPrompt extends Option {
  ['x-prompt']?: string | LongFormXPrompt;
}

interface LongFormXPrompt {
  message: string;
  type: 'confirmation' | 'input' | 'list';
  items?: (string | { label: string; value: string })[];
}
```

If the above all sounds good, I can look into creating PRs for these changes.

**Comment by isaacplmann** [comment]
Thanks for putting so much thought into this!

I think this is definitely worth adding to nx-console.

What would the behavior be for the `confirmation` type?

**Comment by srlee309** [comment]
@isaacplmann for the first PR the only change would be that it would have a tooltip based on the message. 

Based on the current behavior if you have the below field, it will ask in the terminal for a selection if you haven't chosen for it to be true.
```
 "addJestJunitReporter": {
    "description": "Add jest junit reporter setup",
    "type": "boolean",
    "default": false,
    "x-prompt": {
        "message": "Configure jest junit reporter?",
        "type": "confirmation",
    }
},
```

If you want that confirmation in nx-console, the following changes would be needed:

- the commands that are run would include the schema properties when they are false or have a default value. For example, "--addJestJunitReporter false".  Currently these are not included in the command and this leads to the angular cli asking for values when you run the command.
 - the confirmation field would need to be changed from a checkbox to a select field with the options: blank, Yes, No. The field would be required, so dry run would fail and the run button would be disabled until you selected "Yes" or "No" on all the required fields.  Based on the default (true or false) value the field will be set to "Yes" or "No".

**Comment by isaacplmann** [comment]
I think its fine to have the `confirmation` type just show a tooltip.  I think having the option shown in the form makes it visible for people to choose what they want.

**Comment by srlee309** [comment]
I have raised the PR #986

**Comment by Cammisuli** [comment]
Added with #986
