### ISSUE TITLE
Where's the "Add" command gone?

### ISSUE THREAD

**Issue by MonsieurLeSuisse** [nrwl/nx-console#982]
In previous versions of Angular Console there was an Add option to add support for external libraries to a project.
Sure one can still use the native ng add command (https://angular.io/cli/add), but why was it removed from nrwl/ng-console?

**Comment by isaacplmann** [comment]
Nx now supports many different frameworks.  `ng add` doesn't mean anything for React, Nest, Next or Node.  To get the same behavior you can install the library `npm i some-library` and then run the `ng-add` schematic for that library under the generate command (`nx g some-library:ng-add`).
