### ISSUE TITLE
`nx generate` doesn't work in Girhub Codespaces

### ISSUE THREAD

**Issue by IKatsuba** [nrwl/nx-console#983]
I try to generate a library in Github Codespaces. There is an error:
```
> Executing task: nx generate @nrwl/node:library --name=http --importPath=@rxnode/http --publishable --testEnvironment=node <

/usr/bin/env: ‘node’: No such file or directory
The terminal process "/bin/bash '-l', '-c', '/home/codespace/workspace/rxnode/node_modules/.bin/nx generate @nrwl/node:library --name=http --importPath=@rxnode/http --publishable --testEnvironment=node', 'nx generate @nrwl/node:library --name=http --importPath=@rxnode/http --publishable --testEnvironment=node'" failed to launch (exit code: 127).

Terminal will be reused by tasks, press any key to close it.
```
I'm so want to use Nx Console in Github Codespaces. Any thoughts?

**Comment by Cammisuli** [comment]
I just created a new Github Codespace and it looks like Node is available by default now. I recommend that you try rebuilding the container or configuring the container with these instructions:
https://docs.github.com/en/github/developing-online-with-codespaces/configuring-codespaces-for-your-project
