### ISSUE TITLE
Autocomplete options cutoff and require window scroll when it is the last control

### ISSUE THREAD

**Issue by srleecode** [nrwl/nx-console#985]
When the autocomplete is the last control, the options are cutoff with only one option shown. The window then needs to be scrolled in order to see more than one options at a time.
![autocomplete requires window scroll](https://user-images.githubusercontent.com/13536934/97984935-95c3db80-1e2b-11eb-90a4-ae9e6429c242.gif)

**Comment by Cammisuli** [comment]
There's nothing we can do about this unfortunately ☹️ 

Usually with these types of UI we can attach the popup/menu/dropdown to the root of the document, and it will make it self contained and not relative to the parent. 

With VSCode, the whole view is contained in an iframe, and we can't really go outside the iframe without using native vscode components (which we do when the items are less than a certain amount). 

For now we'll close this a limitation with vscode. We'll look into other ways to solve this in the future.

**Comment by MaxKless** [comment]
Hey! Sorry this hasn't been handled until now.
We're going to completely rewrite the generate ui from scratch soon-ish so I will close this issue. 

Thanks for the report :)
