### ISSUE TITLE
Feature: add field as argument even when it is the default value

### ISSUE THREAD

**Issue by srlee309** [nrwl/nx-console#987]
At the moment, if you don't change a field from the default value it needs to be confirmed in the angular cli when running the command.
https://github.com/nrwl/nx-console/blob/master/libs/vscode-ui/feature-task-execution-form/src/lib/task-execution-form.component.ts#L345

Can it be changed so that it adds the field as an argument even when it is the default value. This would stop the angular cli asking you to confirm that you want to use the default value. If you want to keep this confirmation request, can be restricted so that it only happens for the required fields. This would mean that if the field is the default value and not a required field it would be added as an argument in the command and the user would not need to confirm it.

**Comment by sandikbarr** [comment]
Fixed in #1008 and deployed today in v17.0.0
