### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ajaysankard07** [nrwl/nx-console#990]
- Issue Type: `Bug`
- Extension Name: `angular-console`
- Extension Version: `15.0.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.51.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by ajaysankard07** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 9189,
		"activateCallTime": 161,
		"activateResolvedTime": 11,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "nrwl.angular-console",
				"_lower": "nrwl.angular-console"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by Cammisuli** [comment]
I'm sorry, but what exactly is the issue?

**Comment by Cammisuli** [comment]
I'm gonna close this issue. There hasn't been any feedback.
