### ISSUE TITLE
NX Console doesn't appear to work with nx 11 project

### ISSUE THREAD

**Issue by mwarger** [nrwl/nx-console#991]
When using the extension, there are no options available when clicking the 'Run' command in the nx console pane.

Attempting to run something like `serve` also doesn't work (running the serve command in the CLI works for me):
![image](https://user-images.githubusercontent.com/686823/102516407-6b815280-4054-11eb-8eb2-35fa00ca4eed.png)

I'm curious if there's something about the project config that changed?  I'm new to NX so I'm not sure what that would be - something about an `architect` object not being in the config anymore?

**Comment by Julien76** [comment]
I am running into the same problem.
The `serve` command does not work on Win10 + nx 11 + VS code 1.52.1.

**Comment by Sauermann** [comment]
I ran into the same problem after setting up a nx-11 workspace with the option

`empty             [an empty workspace with a layout that works best for building apps]`

My workaround was to set up the workspace with the option:

`angular-nest      [a workspace with a full stack application (Angular + Nest)]`

With this setting the VSCode-Nx-Console worked without problems.

**Comment by bartlettpsj** [comment]
Same problem.  I'm assuming they changed structure of workspace.json in v11 and nx console hasn't been updated yet?
My "workaround" is to use latest v10 --- i.e. npx create-nx-workspace@10.4
Perhaps there is a new version of nx console?  I'll take a look.

**Comment by sandikbarr** [comment]
Oh hi @mwarger 👋 
The workspace structure did change with Nx11. Sorry about the delay; I have updated Nx Console with #993 to add support for the new configuration. We also deployed a fix with #999 yesterday for using workspace generators. You should all be able to update to v16.0.1 from the Marketplace. Let us know if you have further issues.
