### ISSUE TITLE
The task 'nx-console: ng serve api (myOrg)' is already active.

### ISSUE THREAD

**Issue by mackelito** [nrwl/nx-console#992]
I was trying out this https://blog.nrwl.io/using-apollo-graphql-with-angular-in-an-nx-workspace-9ad0155c1914
and when I started the api and then want to start the client I get an error `The task 'nx-console: ng serve api (myOrg)' is already active.`

Yes "api".. not client (the one I'm trying to start as "api" is already running..

**Comment by mackelito** [comment]
Edit: Running `nx run client:serve ` works fine :)

**Comment by Cammisuli** [comment]
I suspect it's because we try to use the same terminal name behind the scene.

**Comment by ringodotnl** [comment]
Same issue here on a new project
