### ISSUE TITLE
Publish to the open-vsx registry

### ISSUE THREAD

**Issue by etienne-bc** [nrwl/nx-console#995]
Can this extension be published to the Open VSX registry as well?

Open VSX registry: https://open-vsx.org/
How to Publish an Extension: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

This would allow users from VSCodium, Gitpod, Theia, etc. to also use it.

vscode-jest issue discussing the same thing: jest-community/vscode-jest#602

**Comment by Cammisuli** [comment]
I have this marked down when we eventually automate the publishing from a CI.

**Comment by Cammisuli** [comment]
We now automate our release process, so I can take a closer look at this.

**Comment by vymarkov** [comment]
@Cammisuli any updates on that ?

**Comment by Cammisuli** [comment]
@vymarkov no, not really. 🙁 

We want to change the id from `nrwl.angular-console` to `nrwl.nx-console`, and we don't want to publish to a new registry and then have to change it again there. 

So we're thinking of a plan to best attack this. We'll get there eventually 😅

**Comment by ghuntley** [comment]
👋 Geoff from Gitpod here. ICMYI folks have been asking about this over at https://old.reddit.com/r/vscode/comments/ox0am2/experiences_with_gitpodio/h7nor3v/. I

**Comment by Cammisuli** [comment]
Published on openvsix now 
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/4332460/129370589-307a4842-4959-48a4-be3c-3bcd3175c58c.png">
