### ISSUE TITLE
VSCode Extension doesn't prefilled directory for @nwrl/nest:controller 

### ISSUE THREAD

**Issue by hugoblanc** [nrwl/nx-console#997]
When I right click on a directory in VSCode explorer, select Nx generate (UI) and then  @nwrl/nest controller, the "Directory" field stay empty. 

The controller is then generated in the src folder, not inside the inital clicked folder.

For exemple, on a right click on  .apps/api/src/app/domain, the controller will be, at src level.

**Comment by hugoblanc** [comment]
After cheking on webstorm, I reproduce exactly the same issue.

**Comment by BobBDE** [comment]
Same for me

**Comment by Cammisuli** [comment]
If this issue is happening with the plugin on Webstorm, it could be a issue for the Nx repo. I can double check.

**Comment by Cammisuli** [comment]
Looking at the console logs, it looks like there's some exceptions happening with the nest schematics.
